### ISSUE TITLE
Type mismatch: inferred type is Canvas? but Canvas was expected

### ISSUE THREAD

**Issue by sunel-pyt** [software-mansion/react-native-screens#1787] opened 2023-06-11 03:00 UTC
### Description

node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt:300:25 Type mismatch: inferred type is Canvas? but Canvas was expected

### Steps to reproduce

1. Open Project in Android Studio
2. Run Build Project 

### Snack or a link to a repository

Default

### Screens version

3.20.0

### React Native version

0.69.11

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by sunel-pyt** [comment] 2023-06-11 06:19
working on the repo will share in a while

**Comment by numsu** [comment] 2023-06-12 18:52
I had this issue and it was because I used compileSdkVersion 34. Works with 33.

**Comment by jsimmons12** [comment] 2023-06-15 09:38
I'm getting the same issue when trying to build against sdkVersion 34. The issue persists after updating to the latest version (3.21.0).

**Comment by kkafar** [comment] 2023-06-19 10:21
Hi, thanks for reporting!

Can anyone confirm for me that the issue is resolved with these changes:

* https://github.com/software-mansion/react-native-screens/pull/1795

To try it out you can install `react-native-screens` directly from the branch by putting this in your `package.json`:

```json
"react-native-screens": "software-mansion/react-native-screens/@kkafar/fix-canvas-nullability-android-sdk34-1787"
```

(writing from memory, 🤞🏻 it works)

**Closed** 2023-06-20 15:25 UTC
Labels: Platform: Android, MIssing repro

**Comment by abdullahIsa** [comment] 2023-06-22 00:54
> Hi, thanks for reporting!
> 
> Can anyone confirm for me that the issue is resolved with these changes:
> 
> * [fix: canvas nullability in ScreenStack for Android SDK 34 #1795](https://github.com/software-mansion/react-native-screens/pull/1795)
> 
> To try it out you can install `react-native-screens` directly from the branch by putting this in your `package.json`:
> 
> ```json
> "react-native-screens": "software-mansion/react-native-screens/@kkafar/fix-canvas-nullability-android-sdk34-1787"
> ```
> 
> (writing from memory, 🤞🏻 it works)
> 
> cc @sunel-pyt @numsu @jsimmons12

Hello it says does not exist, the fix branch

**Comment by kkafar** [comment] 2023-06-22 07:32
These changes were not released it & the branch does not exist because I've merged it to main (sorry for no update here).

You can try it out by using 

```
"react-native-screens": "software-mansion/react-native-screens/main"
```

**Comment by nikitadubyk** [comment] 2023-06-22 07:42
@kkafar Hi! I try to update lib like `"react-native-screens": "software-mansion/react-native-screens/main"`, but it didn't help.
![image](https://github.com/software-mansion/react-native-screens/assets/73419198/c315eea3-6d2e-47a6-802e-450ab0c16964)

**Comment by kkafar** [comment] 2023-06-22 07:45
@nikitadubyk please try out `rm -fr node_modules && yarn install`, most likely native code didn't get downloaded. 

Let me know whether this helped

**Comment by nikitadubyk** [comment] 2023-06-22 07:53
@kkafar the build went well, but another error occurred
![image](https://github.com/software-mansion/react-native-screens/assets/73419198/0166a1b7-863c-415d-baf8-cf4dd038dc7c)

**Comment by kkafar** [comment] 2023-06-22 08:02
Oh I see. There were some changes in metro with simlinks handling and some more setup is now required.
Ok, I'll release new version ASAP.

**Comment by kkafar** [comment] 2023-06-22 08:06
version 3.22.0 is on npm ready to test-out.

**Comment by harrymamba** [comment] 2023-06-22 08:15
> @kkafar the build went well, but another error occurred

What is the kotlinVersion you are using @nikitadubyk? Im getting the same `react-native-screens:compileDebugKotlin` error while the main branch of react-native-screens.

**Comment by NilayPorwal** [comment] 2023-06-23 05:33
> version 3.22.0 is on npm ready to test-out.

No matching version found for react-native-screens@3.22.0

**Comment by elStranger** [comment] 2023-06-24 06:27
> Hi, thanks for reporting!
> 
> Can anyone confirm for me that the issue is resolved with these changes:
> 
> * [fix: canvas nullability in ScreenStack for Android SDK 34 #1795](https://github.com/software-mansion/react-native-screens/pull/1795)
> 
> To try it out you can install `react-native-screens` directly from the branch by putting this in your `package.json`:
> 
> ```json
> "react-native-screens": "software-mansion/react-native-screens/@kkafar/fix-canvas-nullability-android-sdk34-1787"
> ```
> 
> (writing from memory, 🤞🏻 it works)
> 
> cc @sunel-pyt @numsu @jsimmons12

`Running "npm install" in /home/expo/workingdir/build directory
[stderr] 
npm ERR! code ERESOLVE
[stderr] 
npm ERR!
[stderr] 
ERESOLVE could not resolve
[stderr] 
npm ERR! 
[stderr] 
npm
[stderr] 
ERR! While resolving: @react-navigation/bottom-tabs@6.5.8
[stderr] 
npm ERR! Found: react-native-screens@undefined
[stderr] 
npm
[stderr] 
ERR! node_modules/react-native-screens
[stderr] 
npm ERR!   react-native-screens@"software-mansion/react-native-screens/@kkafar/fix-canvas-nullability-android-sdk34-1787" from the root project
[stderr] 
npm ERR! 
[stderr] 
npm ERR! Could not resolve dependency:
[stderr] 
npm
[stderr] 
ERR! peer react-native-screens@">= 3.0.0" from @react-navigation/bottom-tabs@6.5.8
[stderr] 
npm ERR! node_modules/@react-navigation/bottom-tabs
[stderr] 
npm ERR!   @react-navigation/bottom-tabs@"^6.3.2" from the root project
[stderr] 
npm ERR! 
[stderr] 
npm ERR! Conflicting peer dependency: react-native-screens@3.22.0
[stderr] 
npm ERR! node_modules/react-native-screens
[stderr] 
npm ERR!   peer react-native-screens@">= 3.0.0" from @react-navigation/bottom-tabs@6.5.8
[stderr] 
npm ERR!   node_modules/@react-navigation/bottom-tabs
[stderr] 
npm ERR!     @react-navigation/bottom-tabs@"^6.3.2" from the root project
[stderr] 
npm ERR! 
[stderr] 
npm ERR! Fix the upstream dependency conflict, or retry
[stderr] 
npm ERR! this command with --force, or --legacy-peer-deps
[stderr] 
npm ERR!
[stderr] 
to accept an incorrect (and potentially broken) dependency resolution.
[stderr] 
npm ERR! 
[stderr] 
npm ERR! See /home/expo/.npm/eresolve-report.txt for a full report.
[stderr] 
[stderr] 
npm ERR! A complete log of this run can be found in:
[stderr] 
npm ERR!     /home/expo/.npm/_logs/2023-06-24T06_26_26_801Z-debug-0.log
npm exited with non-zero code: 1`

no it's not working

**Comment by elStranger** [comment] 2023-06-24 06:31
> @nikitadubyk please try out `rm -fr node_modules && yarn install`, most likely native code didn't get downloaded.
> 
> Let me know whether this helped


after cleaning node_modules and npm install over again with "react-native-screens": "software-mansion/react-native-screens/main"....

` 
CommandError: "react-native-screens" is added as a dependency in your project's package.json but it doesn't seem to be installed. Please run "yarn" or "npm install" to fix this issue.`

**Comment by elStranger** [comment] 2023-06-24 15:26
> version 3.22.0 is on npm ready to test-out.

fixed it
