### ISSUE TITLE
Implement iOS 11 searchbar in header

### ISSUE THREAD

**Issue by tobiaslins** [software-mansion/react-native-screens#194] opened 2019-10-23 06:24 UTC
First of all - thank you so much for your hard work in all these amazing RN libraries! Without them react native just wouldn't be as good as it's now!

Do you think it's a lot of work to implement the iOS11 Header Searchbar?
https://developer.apple.com/design/human-interface-guidelines/ios/bars/search-bars/

Maybe I'll take a look into it if I find the time!

**Comment by WoLewicki** [comment] 2020-04-01 12:51
Thanks for your contribution! Feel free to open a PR about the Header Searchbar whenever you have time. I will close this one but comment here if you need anything regarding this topic.

**Comment by arjndr** [comment] 2020-05-28 08:57
@WoLewicki I managed to get the native search controller inside the header, I'm not sure how to send the events to the JS side tho, I'm not experienced with Objective-C, having a bit of problem with delegation of UISearchBar, can you check it out on [my fork](https://github.com/arjndr/react-native-screens)?

**Comment by WoLewicki** [comment] 2020-05-28 12:16
Maybe this could help you https://github.com/umhan35/react-native-search-bar?

**Comment by nandorojo** [comment] 2020-09-21 18:08
Hey all, just echoing the gratitude for this library. It's been the greatest noticeable change in making my app feel smooth.

Did you end up making a search bar for the header?

**Comment by WoLewicki** [comment] 2020-09-22 10:01
It is not implemented yet and I am afraid I do not have time for this now. I would love to merge a PR with it though!

**Comment by WoLewicki** [comment] 2020-11-03 10:09
I investigated it a bit more and I tried to add the `SearchBar` component (e.g. the one from this comment: https://github.com/software-mansion/react-native-screens/issues/194#issuecomment-635302265) to the header on the native side on iOS. The problem is that this component cannot be used as is, it can be only delegated to use the given methods, it means that it won't apply any of the properties like `placeholder` by itself. It could possibly be done in a way that each of the component's properties is copied one-by-one on the native side, but it doesn't seem like the best solution. It can still be done though, maybe by choosing only some most crucial options from the `SearchBar` component.

Also, cannot `SearchBar` component be implemented as e.g. the first item of `ScrollView` and replicate the native behavior by properly manipulating it?

Can you elaborate on it @nandorojo, @tobiaslins, @arjndr, and others? I can also submit a PR that shows the most simple example of usage without any modifications available.

**Comment by grahammendick** [comment] 2020-11-03 10:22
@WoLewicki Just thought I'd let you know that I've wrapped the [native iOS search bar](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/src/ios/NVSearchBarView.m) in [my Navigation router](https://grahammendick.github.io/navigation/documentation/native/navigation-bar.html).

**Comment by WoLewicki** [comment] 2020-11-03 10:31
@grahammendick I thought of maybe doing something like that. The second option is to take props from the passed `SearchBar` component instead of passing so many props from the JS side. I don't know if any of them is good enough though.

**Comment by grahammendick** [comment] 2020-11-03 10:38
@WoLewicki There aren't that many props. Here's the [typescript def for my SearchBar component](https://github.com/grahammendick/navigation/blob/e4036e40fc39322ea3321e29987d89f2a817ee9b/build/npm/navigation-react-native/navigation.react.native.d.ts#L220)

**Comment by a-eid** [comment] 2020-12-10 03:36
wondering if there's any progress on this ?

**Comment by WoLewicki** [comment] 2020-12-21 12:30
@a-eid I added a first look at it in #758. Can you check if the most basic version with `placeholder` and events option work?

**Comment by FrankFundel** [comment] 2020-12-26 11:35
@WoLewicki I tested it and I couldn't get it to work. I tried:
`static navigationOptions = ({ navigation }) => {
    const {params = {}} = navigation.state;
    return {
      title: translate('Search'),
      searchBar: () => <NativeSearchBar
        placeholder="Placeholder"
        onChangeText={() => alert('changetext')}
        onSearchButtonPress={() => alert('button press')}
        onCancelButtonPress={() => alert('button cancel')}
      />
    }
  };`

But it is not showing.

**Comment by FrankFundel** [comment] 2020-12-26 15:42
I cannot get it to work. I looked through all your changes, they seem to be fine. But somehow `case RNSScreenStackHeaderSubviewTypeSearchBar: {` does not get called in RNSScreenStackHeaderConfig.m line 478. I thought maybe add `export const ScreenStackHeaderSearchBarView = View;` in src/index.js or `if (options.searchBar)...` in src/createNativeStackNavigator.js but no effects.

**Comment by FrankFundel** [comment] 2020-12-27 17:17
Plus: How to unFocus after searchButton has pressed? And when scrolling down, the title disappears.

**Comment by WoLewicki** [comment] 2020-12-28 14:52
@FrankFundel can you provide the reproduction of your problems? It would be easier to work on them then.

**Comment by FrankFundel** [comment] 2020-12-28 15:12
@WoLewicki it is in a bigger private project, I dont have the time to set up a new project. Maybe I can add you to the rep?

**Comment by WoLewicki** [comment] 2020-12-29 09:20
Adding is not a good option because it doesn't make reproduction available for all of the users. Making an easy reproduction should not take too much time, you can just fork the `react-native-screens` repository, and add a simple test case in [TestExample](https://github.com/software-mansion/react-native-screens/tree/master/TestsExample) project.

**Comment by FrankFundel** [comment] 2021-01-10 14:07
My stuff is exatly like you have it, except I'm using it like:
`export default class SearchScreen extends React.Component {
  static navigationOptions = ({ navigation }) => {
    const {params = {}} = navigation.state;
    
    return {
      title: translate('Search'),
      searchBar: () => <SearchBar
        placeholder={translate("Search")}
        onChangeText={params.search}
        onSubmitEditing={params.fullSearch}
        header
      />
    }
  };`
With class components and:
`
import createNativeStackNavigator from 'react-native-screens/createNativeStackNavigator';
const SearchStack = createNativeStackNavigator({
  Search: SearchScreen,
},
{
  initialRouteName: 'Search',
});`

**Comment by WoLewicki** [comment] 2021-01-11 15:11
@FrankFundel you are using v4 `native-stack`, yes? I haven't added the new prop there, it's my mistake. Can you check if it works now?

**Comment by FrankFundel** [comment] 2021-01-22 11:59
Works now, but still: How to unFocus after searchButton has pressed? And when scrolling down, the title disappears.

**Comment by dioncodes** [comment] 2021-01-22 12:19
When the searchfield is focused, a gray half transparent view is visible above the screen content. How is it possible to display the search results there, so the user can tap on a result while the keyboard is visible? In my case it was always required to tap and close it before being able to select something. Also in that case the value of the textfield is gone as soon as its unfocused.

**Comment by WoLewicki** [comment] 2021-02-09 17:47
I added a second attempt on implementing the `SearchBar` on iOS. It now uses the native component provided by `react-native-screens` and accepts only it. You can see the example of usage here: https://github.com/software-mansion/react-native-screens/blob/@wolewicki/add-search-bar/TestsExample/src/Test758.tsx. Please test it and comment if you see any bugs or weird behavior. This component is based on @grahammendick and @umhan35 work :tada:.

As for your question @dioncodes, I think it should be possible with `obscureBackground` prop set to `false`.

**Comment by dioncodes** [comment] 2021-02-12 00:03
@WoLewicki This is awesome, thank you!! Works like a charm, haven't discovered any problem so far. Of course I will let you know, in case anything comes up...

**Comment by elie-chaaban** [comment] 2021-02-13 10:53
The search bar is not showing, I m using react navigation 5 with expo and react native screens is already installed, what should i add???

**Comment by WoLewicki** [comment] 2021-02-15 10:11
If you use Expo managed workflow, you will not be able to use it since it changes the native code, which is already compiled in Expo managed workflow. You would have to use bare workflow or wait for SDK 41 which hopefully has this change if you want to test it with Expo.

**Comment by WoLewicki** [comment] 2021-02-16 11:20
Could you elaborate on what kind of `SearchBar` would you expect on Android? Is it built-in the header one like in this article: https://www.tutorialspoint.com/how-to-use-searchview-in-toolbar-android (also used in @grahammendick implementation)? Or should it rather be under the header, with a look similar to the one provided by [`react-native-search-bar`](https://github.com/umhan35/react-native-search-bar)?

**Comment by elie-chaaban** [comment] 2021-02-16 11:22
No, like the link you have sent

**Comment by dhanushm360** [comment] 2021-04-14 01:39
any update for expo users?

**Comment by WoLewicki** [comment] 2021-04-19 10:47
@dhanushm360 what do you mean by expo users? If you mean Expo managed workflow, then it will not be available before the next SDK for sure since you cannot change the native code in there.

**Comment by pouyarezvani** [comment] 2021-05-01 21:48
@WoLewicki you mentioned we cant use this iOS feature on Expo 41 managed workflow.  Will the iOS search feature be available for when Expo SDK 42 will be released (managed workflow)?
And I'm guessing until then, there is no other way to implement it?

**Comment by WoLewicki** [comment] 2021-05-04 10:32
@pouyarezvani it should be available in SDK 42. As for implementing it, if you want the native behavior, you need to use native APIs, so yeah, there is no way of doing this.

**Closed** 2021-05-06 14:18 UTC
Labels: enhancement, good first issue, iOS

**Comment by nandorojo** [comment] 2021-05-11 23:00
Thanks for the new update @WoLewicki, this is awesome!

**Comment by dhanushm360** [comment] 2021-07-05 20:50
SDK 42 finally came out! Is this behavior available in this release?

**Comment by 10000multiplier** [comment] 2021-09-03 18:44
> SDK 42 finally came out! Is this behavior available in this release?

Yep, all you need to do is, instead of using ```screenOptions```, use ```navigation.setOptions```in your component like this:

```jsx
React.useEffect(() => {
    navigation.setOptions({
	headerSearchBarOptions: {
		onChangeText: (event) => event.nativeEvent.text,
		hideWhenScrolling: false,
		obscureBackground: false,
		onFocus: () => ...,
		onCancelButtonPress: () => ...,
		placeholder: 'Search',
	}
    });
}, [navigation]);
```
@WoLewicki Can we implement an ```autoFocus``` prop for the search bar?

**Comment by oleg-moseyko** [comment] 2022-02-21 04:51
How can to implement autoFocus in iOS?

**Comment by michaelkremenetsky** [comment] 2024-01-28 10:17
Anyone know how to implement autoFocus on iOS in 2024?

**Comment by a-eid** [comment] 2024-01-28 18:37
there is an `autoFocus` option, I have not tested it my self, but I would assume it's working. 

<img width="474" alt="Screenshot 2024-01-28 at 8 36 57 PM" src="https://github.com/software-mansion/react-native-screens/assets/19273413/8e1ab9ff-fe35-4453-88cd-b3bde6fb00a5">

**Comment by michaelkremenetsky** [comment] 2024-01-29 01:28
> @michaelkremenetsky 
> 
> 
> 
> there is an `autoFocus` option, I have not tested it my self, but I would assume it's working. 
> 
> 
> 
> <img width="474" alt="Screenshot 2024-01-28 at 8 36 57 PM" src="https://github.com/software-mansion/react-native-screens/assets/19273413/8e1ab9ff-fe35-4453-88cd-b3bde6fb00a5">
> 
> 

Ya I know about the autoFocus option the issue is that it only works on android if you read the docs
