### ISSUE TITLE
unable to find plugin with id com.facebook.react

### ISSUE THREAD

**Issue by aleluiah** [software-mansion/react-native-screens#1361] opened 2022-03-17 00:00 UTC
## Steps To Reproduce

1.

## Platform

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [ ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |         |
| @react-navigation/native               |         |
| @react-navigation/native-stack         |         |
| react-native-screens                   |         |
| react-native-safe-area-context         |         |
| react-native-gesture-handler           |         |
| react-native-reanimated                |         |
| expo                                   |         |

**Comment by WoLewicki** [comment] 2022-04-26 11:24
Closing due to no reproduction provided in 30 days. Feel free to comment to reopen.

**Closed by WoLewicki** 2022-04-26 11:24 UTC
Labels: needs-more-info, 🧰needs-repro, needs-review
