### ISSUE TITLE
Sliding back animation is offset

### ISSUE THREAD

**Issue by JonnyBurger** [software-mansion/react-native-screens#229] opened 2019-11-21 20:15 UTC
I found a rare bug in my navigation which I think happened after upgrading to the react-native-screen beta.

Versions:
react-native-screens: 2.0.0-alpha.11
react-navigation: 3.13.0
react-native: 0.61.4

Repro:
- Start an app with a stack navigator (iOS)
- Navigate to a different view
- Suspend the app into the background
- Open the app again
- Slide back

Here is a video that shows the issue:
https://streamable.com/6poie

I'm trying to downgrade to fix the problem. If I am able to isolate the issue I will report it here.

**Comment by JonnyBurger** [comment] 2019-11-21 20:47
I resolved the issue in my app by downgrading to v1.0.0-alpha.23.

**Comment by seekcx** [comment] 2019-11-22 06:45
+1

**Comment by gamingumar** [comment] 2019-11-25 19:11
For me this also happens on device orientation change and going back to previous screen. The issue seems to be iOS only. Android is working fine for me. 

I am using 2.0.0-alpha.11

**Comment by dapicester** [comment] 2019-12-16 01:57
It happened to me too on en Expo app right after upgrading to SDK 36. If I background the expo client and then reopen it, then the layout gets fixed.

**Comment by CapitanRedBeard** [comment] 2019-12-20 17:27
> I resolved the issue in my app by downgrading to v1.0.0-alpha.23.

Jeez that's like 100 commits behind. Is that the earliest this is fixed?

**Comment by JonnyBurger** [comment] 2019-12-21 12:50
@CapitanRedBeard 

No, I have not tried all the versions to find the newest one that is working yet.
Just chose the one I had before.

**Comment by gamingumar** [comment] 2019-12-24 15:19
The issue started to appear from v2 release. v1 worked fine.

**Comment by pepf** [comment] 2020-01-09 12:59
Duplicate of #220

**Comment by gamingumar** [comment] 2020-01-10 15:02
The issue seems to be fixed in "2.0.0-alpha.23"

**Comment by mbryk** [comment] 2020-01-16 03:14
I still had the issue in alpha.23. I had to remove `enableScreens()` as suggested in many of the other issues. (Removing it actually sped up my app as well.)

**Comment by WoLewicki** [comment] 2020-04-01 11:24
It indeed looks like a duplicate of #220 so I am closing it. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2020-04-01 11:24 UTC
