### ISSUE TITLE
Navbar BG Color Does Not Change When Appearance Changes

### ISSUE THREAD

**Issue by zachgibson** [software-mansion/react-native-screens#677] opened 2020-10-21 22:09 UTC
If you change the system appearance in iOS while a modal is open the previous screen's navbar background color does not update.

**Comment by WoLewicki** [comment] 2020-10-22 09:44
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by zachgibson** [comment] 2020-10-22 14:04
Yeah here's a public repo with an Expo repro app. I couldn't import to snack. https://github.com/zachgibson/rndarkmode

**Comment by zachgibson** [comment] 2020-10-22 14:06
If you start in light mode, then open modal, then change to dark mode, the home navbar bg color is still light colored.

**Comment by WoLewicki** [comment] 2020-10-28 14:06
Can you try and use `PlatformColor('systemBackgroundColor')` as a `backgroundColor` of your header? You can check this comment: https://github.com/software-mansion/react-native-screens/issues/596#issuecomment-676270650.
Btw, the problem with navigation bar color seems like some kind of native bug: https://developer.apple.com/forums/thread/119413, it is written there that it is fixed in iOS 13.3, but it doesn't look like it is fixed :/

**Comment by zachgibson** [comment] 2020-11-16 22:12
I will try your suggestion and report back.

**Comment by WoLewicki** [comment] 2021-04-26 09:30
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Closed by WoLewicki** 2021-04-26 09:30 UTC
Labels: iOS, native-stack

**Comment by JoniVR** [comment] 2021-12-02 09:54
@WoLewicki I'm running into this exact issue (on iOS15 still), if the fix you mentioned were to work, where would I have to apply it? 

I'd be happy to submit a PR for it but I don't really know where to look (and if you'd accept it). I'm guessing inside the implementation of `RNScreensNavigationController`?

**Comment by JoniVR** [comment] 2021-12-02 13:35
I found a solution to this problem, which can probably be fixed quite easily (still needs actual proper logic, but shows where to fix it).

In the file `RNSSCreenStackHeaderConfig.m`, if we move the `updateController` call outside of the condition, the background update happens correctly.

```patch
  // if nav is nil, it means we can be in a fullScreen modal, so there is no nextVC, but we still want to update
  if (vc != nil && (nextVC == vc || isInFullScreenModal)) {
-    [RNSScreenStackHeaderConfig updateViewController:self.screenView.controller withConfig:self animated:YES];
  }
+    [RNSScreenStackHeaderConfig updateViewController:self.screenView.controller withConfig:self animated:YES];
}
```
[Specific line](https://github.com/software-mansion/react-native-screens/blob/ea6d02ccb8f6bf8e36a2b351361b8d0446e26419/ios/RNSScreenStackHeaderConfig.m#L158)

Before
https://user-images.githubusercontent.com/7591717/144431557-e1ddfcc5-490f-4245-8990-3156a31905ba.mov


After
https://user-images.githubusercontent.com/7591717/144430417-d5f9788c-ebd9-454c-b296-d4c939d9d9a3.mov
