### ISSUE TITLE
Color flash between large and small title screen

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-screens#520] opened 2020-05-22 08:10 UTC
"react-native-screens": "^2.7.0",
    "react-native": "0.62.2",

<img src="http://g.recordit.co/ps9wNfqwp4.gif"/>

I can't seem to transition between a large and small title screen without colours flashing. 
Screen A
```
 largeTitle
 largeTitleBackgroundColor="red"
backgroundColor="red"
largeTitleHideShadow
title="Status"
```

Screen B

```
largeTitleBackgroundColor="red"
backgroundColor="red"
backTitle="Back"
title="Privacy"
```

Edit: It seems like I have to force translucent={false} on both screens for this issue to go away.

**Comment by kyle-ssg** [comment] 2020-05-22 08:13
Ah progress on this, It seems like I have to force translucent={false} on both screens for this issue to go away.

**Comment by WoLewicki** [comment] 2020-05-25 09:37
Can you provide a repo with minimal configuration needed to reproduce the issue?

**Comment by kyle-ssg** [comment] 2020-06-17 19:48
@WoLewicki https://snack.expo.io/@kyle-ssg/color-flash-between-large-and-small-title-screen 

Similarly to the issue with expo not showing translucent screens properly (mentioned here https://github.com/software-mansion/react-native-screens/issues/524) I think the code will need to be ran on a vanilla react-native app in the simulator / on a phone to replicate as expo seems to do weird things with the headers.

**Comment by sercanov** [comment] 2020-06-23 13:03
It's more visible on black background

![Screen-Recording-2020-06-23-at-15 58 18](https://user-images.githubusercontent.com/10291644/85406843-0cda9080-b56b-11ea-8927-8dc1ebae9fc9.gif)

**Comment by WoLewicki** [comment] 2020-06-24 14:06
@sercanov where is the flashing color in your gif?

**Comment by kyle-ssg** [comment] 2020-06-24 14:20
I believe this is a slightly different issue which I've also seen, I'd imagine he's talking about the glitchy looking background colour here 

![image](https://user-images.githubusercontent.com/8608314/85573932-37d9e880-b62e-11ea-9f88-75f7e232b690.png)

**Comment by sercanov** [comment] 2020-06-24 14:58
yes, @kyle-ssg is right. I thought it's the same issue, if not I can open a new one

**Comment by WoLewicki** [comment] 2020-06-24 15:46
@sercanov would be nice if you could open another issue with this and attach a repro. @kyle-ssg I debugged it and there appears to be quite the same issue as https://stackoverflow.com/questions/39571613/tabbar-navigation-bar-became-dark-after-updating-to-xcode-8. There is UIVisualEffectBackdropView applied during the transition and I am not sure why it is there. Can you repro this behavior in native-stack? I will try to look more at it tomorrow.
![image](https://user-images.githubusercontent.com/32481228/85587952-872a1400-b642-11ea-85fe-bee68d160418.png)

**Comment by WoLewicki** [comment] 2020-06-25 14:45
I think I know why this happened. If not setting the `translucent={false}` explicitly, the `UIVisualEffectBackdropView` becomes opaque and with dark color, as it is written in the SO thread I linked. It happens due to `configureWithDefaultBackground` prop set on appearance here: https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreenStackHeaderConfig.m#L271 which applies `systemChromeMaterial` blur effect. I updated my PR #512 to remove that `configureWithDefaultBackground` with the translucent header. If you want a quick workaround, you can apply `appearance.backgroundEffect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleRegular];` in native code under the line I mentioned.

**Comment by kyle-ssg** [comment] 2020-06-26 17:41
@WoLewicki tried out the PR, can confirm it solves this issue, brilliant!

**Comment by WoLewicki** [comment] 2020-07-29 10:37
Closing since #512 was merged. Feel free to comment if something is wrong.

**Closed by WoLewicki** 2020-07-29 10:37 UTC
