### ISSUE TITLE
Rerendering parent view causes incorrect swipe animation offset

### ISSUE THREAD

**Issue by ouabing** [software-mansion/react-native-screens#220] opened 2019-11-13 04:39 UTC
I'm using [react-native-appearance](https://github.com/expo/react-native-appearance) to listen to the system appearance change event. When the system appearance changes, all the mounted screens will rerender. With `enableScreens` called, the parent screen will animate incorrectly on iOS, as the screenshot below.

![11573619380_ pic_hd](https://user-images.githubusercontent.com/1430376/68733545-f69e4680-0611-11ea-8588-f032cd698ddc.jpg)

react-navigation: 4.0.10
react-navigation-stack: 1.10.3
react-navigation-tabs: 2.5.6
react-native-screens:  2.0.0-alpha.8
react-native: 0.61.4
system: iOS 13.2

**Comment by cmmartin** [comment] 2019-11-13 21:18
I have possibly the same issue. I can only seem to reproduce it in Release mode. Basically I can swipe the screen to the right, creating the gap on the left side that you see in the above screenshot. Almost like a drawer that should not exist.

```
"react-native": "0.60.5",
 "react-native-screens": "^2.0.0-alpha.8",
iOS: 13.1.3
```

**Comment by bwoodlt** [comment] 2019-11-14 17:40
Having similar issue

**Comment by luutruong** [comment] 2019-11-16 23:11
Same for me :(

**Comment by peterkuiper** [comment] 2019-11-19 09:48
Still having this problem with the latest `2.0.0-alpha.11`.

**Comment by Mlobaievskyi** [comment] 2019-11-20 14:46
You just need to replace your `import { createStackNavigator } from 'react-navigation-stack'` with `import createNativeStackNavigator from 'react-native-screens/createNativeStackNavigator';`. It should resolve your issues (refer to docs https://github.com/kmagiera/react-native-screens#using-native-stack-navigator)

**Comment by luutruong** [comment] 2019-11-20 14:48
@Mlobaievskyi 
`There are some technical limitations for implementing some of the stack header options.`

I have tried that and break my layouts. More worst :D

**Comment by ouabing** [comment] 2019-11-21 03:19
@Mlobaievskyi  Native stack navigator doesn't support some stack navigation options, I think it's still an experimental feature.

**Comment by ajanauskas** [comment] 2019-12-13 17:23
Same issue with new version of screens. Not using native stack navigator.

Reproduced with steps described in issue, had to downgrade screens as well

**Comment by mizinin** [comment] 2019-12-17 20:03
@kmagiera @janicduplessis @osdnk Any solution for this? It's very relevant problem

**Comment by cmmartin** [comment] 2019-12-28 22:56
@mizinin Are you using `import createNativeStackNavigator from 'react-native-screens/createNativeStackNavigator'`? Solved the issue for me

**Comment by ajanauskas** [comment] 2019-12-30 08:00
Using `createNativeStackNavigator` is not suitable for all cases, since its API is much more restrictive compared to `@react-navigation/stack` library

**Comment by gamingumar** [comment] 2020-01-10 15:02
The issue seems to be fixed in "2.0.0-alpha.23"

**Comment by ouabing** [comment] 2020-01-13 03:39
I'm still using react-navigation-stack 1.10.3, the 2.0.0-alpha.23 version seems not solving this issue for me.

I currently can't upgrade react-navigation-stack to 2.0.13 version 'cause it breaks my screen animations and need some rework. I'll check if 2.0.0-alpha.23 works with 2.0.13 once I upgrade it.

**Comment by pepf** [comment] 2020-01-16 09:21
Issue seems to be fixed for me as well, using these versions:

```
   "react-native-screens": "^2.0.0-alpha.23",
    "react-native": "0.61.5",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.15",
```

**Comment by WoLewicki** [comment] 2020-04-01 11:27
Does the issue still exist in the newest version? @ouabing @pepf ? Or can I close it?

**Comment by pepf** [comment] 2020-04-01 11:46
The issue seemed to be solved using this config :)

**Comment by WoLewicki** [comment] 2020-04-01 12:40
Ok, so I am closing it. Feel free to comment if the issue still persists for someone.

**Closed by WoLewicki** 2020-04-01 12:40 UTC

**Comment by ouabing** [comment] 2020-04-02 02:13
I've already migrated to react-navigation v5 and react-navigation-stack v2, no more this issue so far.

**Comment by mayankkumawat** [comment] 2023-10-05 16:22
![Simulator Screen Shot - iPhone 14 Pro - 2023-10-05 at 20 41 56](https://github.com/software-mansion/react-native-screens/assets/80257573/f4aee89e-3046-4ef6-8f40-e2f188d66d8f)

I am facing the same issue. Drawer is not properly closing.
` "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/drawer": "^6.3.0",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/stack": "^6.3.10",
     "react-native-screens": "^3.23.0",
    "react-native-reanimated": "^3.5.1",`
