### ISSUE TITLE
topInsetEnabled only android

### ISSUE THREAD

**Issue by maystrenkoYurii** [software-mansion/react-native-screens#604] opened 2020-08-14 15:56 UTC
But i have disable inset for ios, end add custom top padding. Style root container props need add
![Снимок экрана 2020-08-14 в 18 55 53](https://user-images.githubusercontent.com/23016311/90268510-cc5b0d00-de5f-11ea-90b6-f7bb0fccc0a9.png)

**Comment by WoLewicki** [comment] 2020-08-17 10:09
I don't understand what is the problem? Could you describe it more clearly? `topInsetEnabled` is a prop only for Android since on iOS the status bar is translucent by default.

**Comment by WoLewicki** [comment] 2020-08-24 07:21
Can you provide a repo that shows the problem? If you mean that there should be a prop for padding on iOS, then I think there should not be one since the height of the header is provided by the iOS and changing it is not recommended by Apple's HIG for sure.

**Comment by WoLewicki** [comment] 2020-09-15 13:17
Closing due to no reproduction provided in 30 days.

**Closed by WoLewicki** 2020-09-15 13:17 UTC
Labels: needs more info, needs repro
