### ISSUE TITLE
error comes out when running :prepareKotlinBuildScriptModel in Android Project

### ISSUE THREAD

**Issue by CHOIMINSEOK** [software-mansion/react-native-screens#2279] opened 2024-08-02 10:52 UTC
### Description

I'm trying to embed pure react native (without expo) into Android Project. Because of project structure, I can not use auto link(I make react native module as submodule of android project). so, I manually add code for link in `settings.gradle` like this: 
```gradle

include ':react-native-screens'
project(':react-native-screens').projectDir = new File(rootProject.projectDir, '***-react-native/node_modules/react-native-screens/android')
```

After this, when I trigger gradle sync, following cmake error is thrown. It seems that this doesn't trigger build fail, but I want to know root cause of this so that I could guess the impact of this error. Can anyone know why this error occur? 

**This is error message during build:** 

```
[CXX1429] error when building with cmake using /Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/CMakeLists.txt: -- The C compiler identification is Clang 17.0.2
-- The CXX compiler identification is Clang 17.0.2
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/cms3718/Library/Android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/cms3718/Library/Android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/.cxx/Debug/3o5u2t2d/x86/CMakeFiles/CMakeOutput.log".

C++ build system [configure] failed while executing:
    /Users/cms3718/Library/Android/sdk/cmake/3.22.1/bin/cmake \
      -H/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android \
      -DCMAKE_SYSTEM_NAME=Android \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_SYSTEM_VERSION=21 \
      -DANDROID_PLATFORM=android-21 \
      -DANDROID_ABI=x86 \
      -DCMAKE_ANDROID_ARCH_ABI=x86 \
      -DANDROID_NDK=/Users/cms3718/Library/Android/sdk/ndk/26.1.10909125 \
      -DCMAKE_ANDROID_NDK=/Users/cms3718/Library/Android/sdk/ndk/26.1.10909125 \
      -DCMAKE_TOOLCHAIN_FILE=/Users/cms3718/Library/Android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake \
      -DCMAKE_MAKE_PROGRAM=/Users/cms3718/Library/Android/sdk/cmake/3.22.1/bin/ninja \
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/build/intermediates/cxx/Debug/3o5u2t2d/obj/x86 \
      -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/build/intermediates/cxx/Debug/3o5u2t2d/obj/x86 \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_FIND_ROOT_PATH=/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/.cxx/Debug/3o5u2t2d/prefab/x86/prefab \
      -B/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/.cxx/Debug/3o5u2t2d/x86 \
      -GNinja \
      -DANDROID_STL=c++_shared \
      -DRNS_NEW_ARCH_ENABLED=false
  from /Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android
CMake Error at CMakeLists.txt:39 (find_package):
  Could not find a package configuration file provided by "ReactAndroid" with
  any of the following names:

    ReactAndroidConfig.cmake
    reactandroid-config.cmake

  Add the installation prefix of "ReactAndroid" to CMAKE_PREFIX_PATH or set
  "ReactAndroid_DIR" to a directory containing one of the above files.  If
  "ReactAndroid" provides a separate development package or SDK, be sure it
  has been installed. : com.android.ide.common.process.ProcessException: -- The C compiler identification is Clang 17.0.2
-- The CXX compiler identification is Clang 17.0.2
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/cms3718/Library/Android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/cms3718/Library/Android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/.cxx/Debug/3o5u2t2d/x86/CMakeFiles/CMakeOutput.log".

C++ build system [configure] failed while executing:
    /Users/cms3718/Library/Android/sdk/cmake/3.22.1/bin/cmake \
      -H/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android \
      -DCMAKE_SYSTEM_NAME=Android \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_SYSTEM_VERSION=21 \
      -DANDROID_PLATFORM=android-21 \
      -DANDROID_ABI=x86 \
      -DCMAKE_ANDROID_ARCH_ABI=x86 \
      -DANDROID_NDK=/Users/cms3718/Library/Android/sdk/ndk/26.1.10909125 \
      -DCMAKE_ANDROID_NDK=/Users/cms3718/Library/Android/sdk/ndk/26.1.10909125 \
      -DCMAKE_TOOLCHAIN_FILE=/Users/cms3718/Library/Android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake \
      -DCMAKE_MAKE_PROGRAM=/Users/cms3718/Library/Android/sdk/cmake/3.22.1/bin/ninja \
      -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/build/intermediates/cxx/Debug/3o5u2t2d/obj/x86 \
      -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/build/intermediates/cxx/Debug/3o5u2t2d/obj/x86 \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_FIND_ROOT_PATH=/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/.cxx/Debug/3o5u2t2d/prefab/x86/prefab \
      -B/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/.cxx/Debug/3o5u2t2d/x86 \
      -GNinja \
      -DANDROID_STL=c++_shared \
      -DRNS_NEW_ARCH_ENABLED=false
  from /Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android
CMake Error at CMakeLists.txt:39 (find_package):
  Could not find a package configuration file provided by "ReactAndroid" with
  any of the following names:

    ReactAndroidConfig.cmake
    reactandroid-config.cmake

  Add the installation prefix of "ReactAndroid" to CMAKE_PREFIX_PATH or set
  "ReactAndroid_DIR" to a directory containing one of the above files.  If
  "ReactAndroid" provides a separate development package or SDK, be sure it
  has been installed.
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.execute(ExecuteProcess.kt:288)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt$executeProcess$1.invoke(ExecuteProcess.kt:108)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt$executeProcess$1.invoke(ExecuteProcess.kt:106)
	at com.android.build.gradle.internal.cxx.timing.TimingEnvironmentKt.time(TimingEnvironment.kt:32)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.executeProcess(ExecuteProcess.kt:106)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.executeProcess$default(ExecuteProcess.kt:85)
	at com.android.build.gradle.tasks.CmakeQueryMetadataGenerator.executeProcess(CmakeFileApiMetadataGenerator.kt:59)
	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator$configureOneAbi$1$1$3.invoke(ExternalNativeJsonGenerator.kt:247)
	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator$configureOneAbi$1$1$3.invoke(ExternalNativeJsonGenerator.kt:247)
	at com.android.build.gradle.internal.cxx.timing.TimingEnvironmentKt.time(TimingEnvironment.kt:32)
	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.configureOneAbi(ExternalNativeJsonGenerator.kt:247)
	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.configure(ExternalNativeJsonGenerator.kt:113)
	at com.android.build.gradle.internal.ide.v2.NativeModelBuilder.generateBuildFilesAndCompileCommandsJson(NativeModelBuilder.kt:209)
	at com.android.build.gradle.internal.ide.v2.NativeModelBuilder.buildAll(NativeModelBuilder.kt:174)
	at com.android.build.gradle.internal.ide.v2.NativeModelBuilder.buildAll(NativeModelBuilder.kt:58)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuilderWithParameter.build(DefaultToolingModelBuilderRegistry.java:289)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$UserCodeAssigningBuilder.lambda$build$0(DefaultToolingModelBuilderRegistry.java:374)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication.reapply(DefaultUserCodeApplicationContext.java:108)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$UserCodeAssigningBuilder.build(DefaultToolingModelBuilderRegistry.java:374)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$LockSingleProjectBuilder.lambda$build$0(DefaultToolingModelBuilderRegistry.java:304)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$fromMutableState$2(DefaultProjectStateRegistry.java:430)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withReplacedLocks(DefaultWorkerLeaseService.java:360)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:430)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$LockSingleProjectBuilder.build(DefaultToolingModelBuilderRegistry.java:304)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuildOperationWrappingBuilder$1.call(DefaultToolingModelBuilderRegistry.java:337)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuildOperationWrappingBuilder.build(DefaultToolingModelBuilderRegistry.java:334)
	at org.gradle.internal.build.DefaultBuildToolingModelController$AbstractToolingScope.getModel(DefaultBuildToolingModelController.java:87)
	at org.gradle.tooling.internal.provider.runner.DefaultBuildController.getModel(DefaultBuildController.java:114)
	at org.gradle.tooling.internal.consumer.connection.ParameterAwareBuildControllerAdapter.getModel(ParameterAwareBuildControllerAdapter.java:39)
	at org.gradle.tooling.internal.consumer.connection.UnparameterizedBuildController.getModel(UnparameterizedBuildController.java:113)
	at org.gradle.tooling.internal.consumer.connection.NestedActionAwareBuildControllerAdapter.getModel(NestedActionAwareBuildControllerAdapter.java:31)
	at org.gradle.tooling.internal.consumer.connection.UnparameterizedBuildController.findModel(UnparameterizedBuildController.java:97)
	at org.gradle.tooling.internal.consumer.connection.NestedActionAwareBuildControllerAdapter.findModel(NestedActionAwareBuildControllerAdapter.java:31)
	at com.android.tools.idea.gradle.project.sync.SyncActionRunnerKt$toMeasuringController$1$findModel$4.invoke(SyncActionRunner.kt:289)
	at com.android.tools.idea.projectsystem.gradle.sync.Counter.invoke(PerformanceMeasurementUtil.kt:108)
	at com.android.tools.idea.gradle.project.sync.SyncActionRunnerKt.measure(SyncActionRunner.kt:330)
	at com.android.tools.idea.gradle.project.sync.SyncActionRunnerKt.access$measure(SyncActionRunner.kt:1)
	at com.android.tools.idea.gradle.project.sync.SyncActionRunnerKt$toMeasuringController$1.findModel(SyncActionRunner.kt:289)
	at com.android.tools.idea.gradle.project.sync.ActionToRun$toSafeController$1.findModel(SyncActionRunner.kt:160)
	at com.android.tools.idea.gradle.project.sync.ModelFetchersKt.findNativeVariantAbiModel(ModelFetchers.kt:141)
	at com.android.tools.idea.gradle.project.sync.VariantDiscovery$toFetchVariantDependenciesAction$1$1.invoke(VariantDiscovery.kt:210)
	at com.android.tools.idea.gradle.project.sync.VariantDiscovery$toFetchVariantDependenciesAction$1$1.invoke(VariantDiscovery.kt:199)
	at com.android.tools.idea.gradle.project.sync.ModelResult$Companion.create(ModelResult.kt:32)
	at com.android.tools.idea.gradle.project.sync.VariantDiscovery$toFetchVariantDependenciesAction$1.invoke(VariantDiscovery.kt:199)
	at com.android.tools.idea.gradle.project.sync.VariantDiscovery$toFetchVariantDependenciesAction$1.invoke(VariantDiscovery.kt:194)
	at com.android.tools.idea.gradle.project.sync.ActionToRun$map$1.invoke(SyncActionRunner.kt:66)
	at com.android.tools.idea.gradle.project.sync.ActionToRun$map$1.invoke(SyncActionRunner.kt:66)
	at com.android.tools.idea.gradle.project.sync.ActionToRun.run$intellij_android_projectSystem_gradle_sync(SyncActionRunner.kt:77)
	at com.android.tools.idea.gradle.project.sync.SyncActionRunner$runActions$executionResults$1$1.execute(SyncActionRunner.kt:234)
	at org.gradle.tooling.internal.consumer.connection.NestedActionAwareBuildControllerAdapter$1.get(NestedActionAwareBuildControllerAdapter.java:51)
	at org.gradle.internal.buildtree.IntermediateBuildActionRunner$NestedAction.run(IntermediateBuildActionRunner.java:119)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$QueueWorker.execute(DefaultBuildOperationExecutor.java:238)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:272)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.doRunBatch(DefaultBuildOperationQueue.java:253)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$1(DefaultBuildOperationQueue.java:226)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:264)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:128)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:224)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:192)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.android.ide.common.process.ProcessException: Error while executing process /Users/cms3718/Library/Android/sdk/cmake/3.22.1/bin/cmake with arguments {-H/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=21 -DANDROID_PLATFORM=android-21 -DANDROID_ABI=x86 -DCMAKE_ANDROID_ARCH_ABI=x86 -DANDROID_NDK=/Users/cms3718/Library/Android/sdk/ndk/26.1.10909125 -DCMAKE_ANDROID_NDK=/Users/cms3718/Library/Android/sdk/ndk/26.1.10909125 -DCMAKE_TOOLCHAIN_FILE=/Users/cms3718/Library/Android/sdk/ndk/26.1.10909125/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/cms3718/Library/Android/sdk/cmake/3.22.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/build/intermediates/cxx/Debug/3o5u2t2d/obj/x86 -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/build/intermediates/cxx/Debug/3o5u2t2d/obj/x86 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_FIND_ROOT_PATH=/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/.cxx/Debug/3o5u2t2d/prefab/x86/prefab -B/Users/cms3718/***-android/***-react-native/node_modules/react-native-screens/android/.cxx/Debug/3o5u2t2d/x86 -GNinja -DANDROID_STL=c++_shared -DRNS_NEW_ARCH_ENABLED=false}
	at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:73)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:48)
	at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.execute(ExecuteProcess.kt:277)
	... 75 more
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Users/cms3718/Library/Android/sdk/cmake/3.22.1/bin/cmake'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:431)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:46)
	... 76 more

```

### Steps to reproduce

1. add dependency of react-native-screens on react native project
2. try to link android module on android project
3. gradle sync 

### Snack or a link to a repository

https://github.com/software-mansion/react-native-screens

### Screens version

3.32.0

### React Native version

0.74.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2024-08-02 13:15
Hey @CHOIMINSEOK, I think that the error is quite self-explanatory:

```
CMake Error at CMakeLists.txt:39 (find_package):
  Could not find a package configuration file provided by "ReactAndroid" with
  any of the following names:

    ReactAndroidConfig.cmake
    reactandroid-config.cmake

  Add the installation prefix of "ReactAndroid" to CMAKE_PREFIX_PATH or set
  "ReactAndroid_DIR" to a directory containing one of the above files.  If
  "ReactAndroid" provides a separate development package or SDK, be sure it
  has been installed.
```

It will be useful to research to how CMake looks for configuration files to understand the error, however it should be enough to literally apply the provided suggestion.

This is not something we'll patch on the library level, because it affects only your non-usual, custom & specific setup, while at the same time I'm sure you can setup this library to work out of the box in brownfield applications (I know of projects who do this), however I don't have knowledge how it is done. Thus I'm closing the issue, however not locking the conversation, so that we can freely discuss & find a solution.

**Closed by kkafar** 2024-08-02 13:15 UTC
Labels: Platform: Android, Missing repro

**Comment by kkafar** [comment] 2024-08-02 13:52
I've also come to knowledge that too low `minSdk` version might be the cause of this error. try out bumping `minSdk` to more recent one & see whether it works. 

This error was also seen in case of improper migration from RN version (w/o applying proper updates).

**Comment by CHOIMINSEOK** [comment] 2024-08-02 15:40
Hi @kkafar  thank you for reply.

actually, I already read that error message you attached above, and tried to research about that, but honestly I can't understand what's going on about that. Maybe because of lack of my background knowledges. All I figured out is for some reason, one of my third party library fail to run CMake because of ReactAndroidConfig.cmake dependecy. 

I have no idea even what ReactAndroidConfig.cmake is, where this come out from, and how I can add this cmake file. would you please explain more about this so that I could guess more?

**Comment by Neeraj-WebNeuron** [comment] 2024-08-14 12:09
Same issue..2 Days lost

**Comment by spyshower** [comment] 2024-08-16 14:54
3.34.0 was supposed to fix this but it didn't.

Dear SM, are you going to help or are you following Expo and their advertising company?

**Comment by kkafar** [comment] 2024-08-27 08:58
Hey :wave:

1. There is still no reproduction for this issue,
2. it seems to happen only in specific / custom setups, which we can not test for before a release. 

If you manage to provide us with reproduction we might be able to look into this.

**Comment by socialsuiteDavid** [comment] 2024-09-02 07:17
https://github.com/software-mansion/react-native-screens/issues/2082#issuecomment-2019263554

This (downgrading to 3.29.0) solved it for me, hope it helps
