### ISSUE TITLE
[native-stack] [iOS] usage of UIAlertController created some strange crashes

### ISSUE THREAD

**Issue by jarvisluong** [software-mansion/react-native-screens#694] opened 2020-11-05 14:51 UTC
## Description

Usage of UIAlertController (from react-native's Alert) does result in some strange crashes. I cannot reproduce the issue myself but I can present the crash traces from Sentry:

https://sentry.io/share/issue/88d7772d5b434794a83ec57ee55fbed9/

(UIAlertController is a subclass of UIPresentationController I believe)

### Screenshots

The link above does not show the breadcrumbs of the crashes so here it is:

https://imgur.com/a/U25L5h9

## Package versions

- React: 16.11.0
- React Native: 0.62.2
- React Native Screens: 2.9.0
- React-navigation: 5.7.2

**Comment by WoLewicki** [comment] 2020-11-09 10:26
I made a simple example of using `native-stack` and `Alert` but I cannot reproduce this crash in any configuration. I am afraid that I cannot help you if you don't provide a reproduction I could work on.

**Comment by jarvisluong** [comment] 2020-11-09 10:31
Hi, Thanks for looking at this. I also understand that this is hard to fix, so I tried to provide as much information as I can (I'm also trying to reproduce this in my end too). I will definitely update this when I have more information

**Comment by WoLewicki** [comment] 2021-02-24 11:37
Closing due to no reproduction provided in 30 days. Feel free to comment to reopen.

**Closed by WoLewicki** 2021-02-24 11:37 UTC
Labels: iOS, needs repro
