### ISSUE TITLE
Native stack header resizes on navigation

### ISSUE THREAD

**Issue by kickbk** [software-mansion/react-native-screens#1720] opened 2023-02-18 16:52 UTC
### Description

I posted about this issue here: https://github.com/react-navigation/react-navigation/issues/11232 and was told to post here.

My code: https://snack.expo.dev/@kickbk/navigation
When app loads and when navigating to `Account` screen, the header resizes and causes the content to move around, and on very weak Android devices, the content even gets stuck below the bottom tabs.

It looks like this header adjusting height behavior happens with `@react-navigation/native-stack`. When switching to importing stack from @react-navigation/stack, and then navigating to Account, the glitch doesn't happen.

However, when launching the app, even when the stacks get imported from `@react-navigation/stack`, the header gets adjusted once. I am guessing it's because the entire JS implementation of stacks sits inside a native component which causes this behavior when loaded once. Maybe because NavigationContainer is imported from '@react-navigation/native'?

I ran the snack I shared with a very weak Android phone so I can share the issue frame by frame with images:

Frame 1
![1](https://user-images.githubusercontent.com/31323376/219877655-7959bd60-9886-4b05-a3d3-2b9df0bd0c0c.png)

Frame 2
![2](https://user-images.githubusercontent.com/31323376/219877658-691c98f9-8663-42fc-bd4a-2fb20f012a54.png)

Frame 3
![3](https://user-images.githubusercontent.com/31323376/219877659-cc3bc7cf-d2b0-4563-8744-3ddc4a0c1251.png)

Frame 4
![4](https://user-images.githubusercontent.com/31323376/219877660-798dc0ea-cc4a-4263-8418-74670d77f0ca.png)

### Steps to reproduce

1. Open the snack with an Android phone. Best an old one.
2. Click on "Account"
3. See how the header changes height and the content jumps around

### Snack or a link to a repository

https://snack.expo.dev/@kickbk/navigation

### Screens version

~3.18.0

### React Native version

0.70.5

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

Real device

### Device model

This happens on all devices to various degrees

### Acknowledgements

Yes

**Comment by kickbk** [comment] 2023-03-07 15:23
Any update on this?

**Comment by cam-shaw** [comment] 2023-04-06 04:53
@kickbk I've had an interesting discovery. When I run my expo project above in "managed" mode, I get the issue. If I run the command `npx expo prebuild -p android` I no longer get the issue. Any chance you can confirm this on a project for yourself?

Haven't worked out root cause yet, and I still have this in my non-expo project. I wonder what Expo might be doing when we run prebuild that is preventing this issue from happening. If I could replicate that, that might be where the solution is.

**Comment by RickardZrinski** [comment] 2023-05-05 15:49
Same issue reported here I believe: https://github.com/software-mansion/react-native-screens/issues/1504

**Comment by dylancom** [comment] 2023-06-06 18:37
I experience the same on iOS(https://github.com/software-mansion/react-native-screens/issues/1779). Sometimes you don't notice it as the rendering is really fast. But if you log the onLayout callback, you'll notice that the height of the container view is larger upon first render and then corrected after.

I think this bug was introduced by: #184

**Comment by cam-shaw** [comment] 2023-08-23 06:28
@kmagiera is this an issue the team are aware of?

**Comment by kkafar** [comment] 2024-07-03 09:06
I was recently improving fixing this for Fabric here https://github.com/software-mansion/react-native-screens/pull/2169 and here https://github.com/react-navigation/react-navigation/pull/12014. Right now it is crucial that you manually set `statusBarTranslucent` correctly (either on whole navigator or per-screen).

If you're on Paper, from my testing, it looks like setting `statusBarTranslucent` to appropriate value is sufficient to workaround the issue. I'm was looking into setting this to appropriate value automatically, but it is quite problematic to detect whether the status bar is translucent or not programatically due to how Android's inset system works. 

The fix for Fabric is not released yet, it landed after `3.32.0`, you can test with installing `main`. 

The changes for `statusBarTranslucent` prop to fix this behaviour that I added to react-navigation are also unreleased, but you can apply the patch: https://patch-diff.githubusercontent.com/raw/react-navigation/react-navigation/pull/12014.patch & try it out. 

You should be fine with navigation v6 & v7, I have not backported the change to v5. 

See the recordings:

| `statusBarTranslucent: false` | `statusBarTranslucent: undefined` |
|--------|--------|
| <video width="320" height="240" controls src="https://github.com/software-mansion/react-native-screens/assets/50801299/b0ffbf6f-1cd7-43a6-bf8f-282b39cead0b"></video> | <video width="320" height="240" controls src="https://github.com/software-mansion/react-native-screens/assets/50801299/e212c125-33b1-4407-9352-c79b7589af39"></video> |

Let me know once you have tested this & how it works for you.

Note that on iOS it is not handled yet, but we're aware of it.

**Comment by kkafar** [comment] 2024-07-03 09:12
I'll close this issue as the situation on Android can be considered handled (I'll reopen if you test & report that this is not the case) & there is separate issue for iOS case by @dylancom https://github.com/software-mansion/react-native-screens/issues/1779

Oh, and I've just checked that [`react-navigation@6.10`](https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fnative-stack%406.10.0) was released with the changes, so together with installing recent screens you should be able to test this on Paper (for Fabric you will need to use `react-native-screens@main`

**Closed** 2024-07-03 09:13 UTC
Labels: Platform: iOS, Platform: Android, Repro provided
