### ISSUE TITLE
Modal header is smaller after update to iOS 14.5+

### ISSUE THREAD

**Issue by JB1905** [software-mansion/react-native-screens#932] opened 2021-05-11 18:32 UTC
## Description

Modal header is smaller (height) on iOS 14.5+ than on previous versions.

### Screenshots

<table>
<tr>
	<td>Older iOS 14.x
	<td>iOS 14.5+
<tr>
	<td><img src="https://user-images.githubusercontent.com/28870390/117866187-24139100-b297-11eb-8c31-be6777e3423a.png"/>
	<td><img src="https://user-images.githubusercontent.com/28870390/117866220-2d9cf900-b297-11eb-843e-90a7749d77a0.PNG"/>
</table>

## Package versions

- React: 16.13.1
- Expo: 41.0.1
- React Native Screens: 3.0.0, 3.2.0

**Comment by Hirbod** [comment] 2021-05-11 22:04
That is most likely an OS change and not a bug. Have you checked other native modal displays, like in the app store for example or inside the settings app? If the headerBar shrinked there too, you know it was in purpose

**Comment by JB1905** [comment] 2021-05-12 06:16
Theme is no change in native modals e.g. in App Store, Music, Mail etc.

**Comment by JB1905** [comment] 2021-05-12 06:19
Clock from iOS 14.5/14.6 beta.

![image](https://user-images.githubusercontent.com/28870390/117927657-c9138580-b2fa-11eb-95ee-f4ba7de8635f.png)

**Comment by JB1905** [comment] 2021-05-12 06:34
<table>
<tr>
	<td>Older iOS 14.x
	<td>iOS 14.5+
<tr>
	<td><img src="https://user-images.githubusercontent.com/28870390/117929119-b437f180-b2fc-11eb-9ae1-53f07402370e.png"/>
	<td><img src="https://user-images.githubusercontent.com/28870390/117928973-92d70580-b2fc-11eb-9988-d8f5005514f7.PNG"/>
</table>

**Comment by kacperkapusciak** [comment] 2021-05-12 10:35
I've tested this issue in-depth and it occurs only in Expo managed workflow on iOS 14.5. In the bare workflow, it works perfectly fine no matter the version of `screens` or iOS. The issue doesn't seem to be connected to `react-native-screens` but rather to Expo itself and I'm clueless why it occurs.

**Comment by Hirbod** [comment] 2021-05-13 16:47
I can confirm this issue too. Also happens on my expo standalone build

**Comment by nguyenbathanh** [comment] 2021-07-22 14:15
I have experienced this issue too. However, if I open an other app on my Iphone and return back my app, it resizes to correct size.

![image](https://user-images.githubusercontent.com/4046112/126654048-183178a3-0d80-4a38-af34-2efd2a8ae452.png)

![image](https://user-images.githubusercontent.com/4046112/126654100-a0be2018-b7d3-4ba3-ba4b-e13207fca2f1.png)

**Comment by lucatk** [comment] 2021-09-04 10:11
Experiencing this issue too in an Expo managed project.

Dragging the header bar further to the top and letting it bounce back down also resets the header height to it's desired height for me.

**Comment by Hirbod** [comment] 2021-11-10 11:03
This issue got worse on iOS 15. If you drag the modal up a little bit, it will reset the header to its desired height, looking weird but not too weird.
(Running with EXPO SDK 40-41)
https://streamable.com/3ou3ye

Going forward with the new react-native-screens and Expo SDK 43, we get something really weird now.
https://streamable.com/oukllx

The height gets HUGE @WoLewicki 

The only thing I am doing is to drag the modal up a little bit using my finger. This will also happen if I minimize the app and open another app and returning back to the app.

React-Navigation v6 (newest version)

**Comment by WoLewicki** [comment] 2021-11-17 08:38
@Hirbod can you reproduce the new behavior with huge header without expo?

**Comment by Hirbod** [comment] 2021-11-17 10:59
@WoLewicki I haven’t tested this outside of Expo, but I am currently working on one with a custom dev client and I will try it there. I might be able to eject this test project in order to reproduce it.

**Comment by lucasmotta** [comment] 2021-12-02 23:00
I'm experiencing the same issue as @Hirbod. I will try to test this outside of Expo later this week.

**Comment by samwatkinson1** [comment] 2021-12-06 16:44
This also affects appearance of stacked modals once closed, the modal behind the previously closed modal becomes full screen and loses its shadow background. Also seem to be experiencing this whilst running inside Expo Go, haven't yet tested native in the simulator.

**Comment by samwatkinson1** [comment] 2021-12-06 19:41
> This also affects appearance of stacked modals once closed, the modal behind the previously closed modal becomes full screen and loses its shadow background. Also seem to be experiencing this whilst running inside Expo Go, haven't yet tested native in the simulator.

Tested with an ejected Expo app in simulator and cannot reproduce, seems like expo may be a contributing factor.

**Comment by Hirbod** [comment] 2021-12-06 19:45
@WoLewicki it does not happen outside of Expo.

**Comment by lucasmotta** [comment] 2021-12-08 22:09
To give some more information, I've tested a couple issues that were happening inside Expo go and then with an ejected app. All issues are fixed after the eject, pointing that it could be an issue within Expo go client app? 😨 

### Modal Header issue
**Expo go (bug)**

https://user-images.githubusercontent.com/76673/145291952-54fc2a8f-0346-4f8c-993b-d074414e02b0.mp4

**Ejected (works)**

https://user-images.githubusercontent.com/76673/145292097-333613da-845e-4013-b5af-0b61974989cc.mp4


### Modal Stacking issue
**Expo go (bug)**

https://user-images.githubusercontent.com/76673/145292198-4754418b-e4e7-4f62-ab53-f7ace8a92a9e.mp4

**Ejected (works)**

https://user-images.githubusercontent.com/76673/145292237-c15f5512-b94c-4e40-91db-90a8a80a0f6a.mp4


I will open an issue on Expo's GitHub with this extra information. But if you know anything solution for the meantime @WoLewicki, let us know and we were not planning to eject from Expo just yet!

**Comment by brentvatne** [comment] 2021-12-10 21:36
@lucasmotta - if you build with EAS Build it will have the same result as building an "ejected" project (we've renamed this to "prebuild" because it basically just generates native projects from your source/config), so it shouldn't be blocking for you for now.

**Comment by lucasmotta** [comment] 2021-12-10 22:23
@brentvatne I am aware of that, but for our current setup we are relying on the Expo Go client and the channel features for fast previews and iterations with our client. In the future, when we are past the MVP we will build our own app using EAS build, but for now the experience is slightly broken because of this modal issue.

**Comment by brentvatne** [comment] 2021-12-11 00:04
@lucasmotta - gotcha. you could use [expo-dev-client](https://docs.expo.dev/development/introduction/) also

**Comment by Hirbod** [comment] 2021-12-11 00:14
Is is not possible to fix the issue?

**Comment by brentvatne** [comment] 2021-12-11 00:15
@Hirbod - https://github.com/expo/expo/issues/15482#issuecomment-991352592

**Comment by WoLewicki** [comment] 2021-12-20 13:17
I tried to debug it with @lukmccall, but the problems seem to come from layout calculations in platform methods, which are not available for us. I'd risk a guess that it is a problem of some `UIViewController` or maybe `UINavigationBar` extension (maybe for analytics) present in Expo Go app, but we couldn't find the exact one. I am afraid we cannot do much more on the side of `react-native-screens`, so maybe it would be best to close this issue here in order to keep the discussion in one place - `expo` repo?

**Closed** 2022-08-14 09:13 UTC
