### ISSUE TITLE
Screen is inactive after force refresh when screen with stackPresentation modal is opened

### ISSUE THREAD

**Issue by JB1905** [software-mansion/react-native-screens#401] opened 2020-02-29 11:39 UTC
Screen is inactive after refresh app in Expo Client when native-stack screen with `stackPresentation: 'modal'` is opened (it seems that the modal layer is still visible over main screen).

**Platform:**
- XCode Simulator 11.3.1 / iOS 13.4 b3
- Expo Client: 2.14.1
- Expo SDK: 36.0.2
- react-native-screens: 2.0.0-alpha.12 / 2.2.0

**Comment by emroot** [comment] 2020-03-19 22:54
I'm experiencing this as well. 
The bug doesn't happen when there's only one modal open (or at least I couldn't reproduce), on force refresh I can still interact with the UI. 
However when I open 1 modal, then open another one on top, and force refresh, I can't interact with the UI. The modal layer seems to be on top of my view. 
A workaround is to close all my modals first and then force refresh. Not ideal.

**Comment by kmagiera** [comment] 2020-03-25 14:26
Apparently upgrading screens to 2.3.0 in expo won't help here as the client with SDK 36 uses native code from alpha-12. I believe this problem should've been addressed already and if you have time I'd appreciate if you could test your app on a clean react-native project with latest version of screens installed.

**Comment by Hirbod** [comment] 2020-04-22 22:34
This is fixed in SDK 37

**Comment by JB1905** [comment] 2020-04-23 10:07
In the new Expo Client with SDK 37 the Dev Menu opens under the modal, but you can still refresh the app using the keyboard shortcut – `command` + `r` (iOS Simulator)

**Comment by Hirbod** [comment] 2020-04-23 10:09
Thats true, the dev menu and element inspector always attaches under the modal. There is already an open issue I've posted couple of months ago.

**Comment by Hirbod** [comment] 2020-05-12 14:19
No, its not. The dev menu opens on top of the modal now, which is great, but when you select force refresh, the app will reload but you can't use the app after that. No touches. Expo SDK 37.0.9 with the new interface fix.

**Comment by bedevgirl-com** [comment] 2020-05-24 13:55
How to use Expo SDK to version 37.0.9 in project? npm i -g expo-cli does't upgade version in my project.

**Comment by Hirbod** [comment] 2020-05-24 14:34
just increase it manually. It will bring some few js based optimizations.

**Comment by WoLewicki** [comment] 2020-08-13 11:53
About the inactivity of the screen under the modal, there is already an issue: #233. I will close this issue to keep the discussion in one place. If you have any questions, feel free to comment.

**Closed by WoLewicki** 2020-08-13 11:53 UTC
Labels: bug, native-stack
