### ISSUE TITLE
'useReanimatedHeaderHeight' doesn't respond to changes in search bar focus

### ISSUE THREAD

**Issue by ha3** [software-mansion/react-native-screens#1951] opened 2023-10-29 16:14 UTC
### Description

On iOS, when the search bar is focused, the upper section of the header is collapsed. But it seems that the reanimated value from `useReanimatedHeaderHeight` doesn't get updated during focus/blur.

Also on the simulator (iPhone 13 - iOS 15.5) I tested, `useReanimatedHeaderHeight` returns the value '91' but when I used the visual inspector I found it should be '96' (44 for the upper part, 52 for the search bar). I haven't tested this with other simulators–but as far as I know, they should have the same search bar height.

### Steps to reproduce

1. Add a screen with a search bar
2. Wrap `NavigationContainer ` with `ReanimatedScreenProvider`.
3. Use `useReanimatedHeaderHeight` inside the screen
4. Log header height value inside a worklet
5. Click on the search bar and observe that the header height has been changed
6. Observe that the change in the header height is not reflected in the logs

### Snack or a link to a repository

https://snack.expo.dev/@hozdemir/delicious-red-marshmallows

### Screens version

3.27.0

### React Native version

0.72.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 13 (iOS 15.5)

### Acknowledgements

Yes

**Comment by tboba** [comment] 2023-11-02 14:17
hi @ha3, thanks for reporting this issue!
I can confirm this problem is reproducible for me and I'm looking for the solution - will come to you with more updates shortly.

**Comment by tboba** [comment] 2023-11-02 14:41
Hi @ha3, thanks for reporting this issue!
Unfortunately I cannot reproduce this problem. On my side `useReanimatedHeaderHeight` hook returns correct values when I'm trying to swipe the search bar.

On the large header:

https://github.com/software-mansion/react-native-screens/assets/23281839/d3cba485-0cef-4588-8385-88017c133f59

On small header:

https://github.com/software-mansion/react-native-screens/assets/23281839/60eaf226-c581-447b-b91c-f5bac88cd9fc

Here's my code that reproduces this problem. Can you try to compare if you're using the shared value correctly?
Cheers!

```tsx
import { ScrollView, StyleSheet, Text } from 'react-native';

import { NavigationContainer } from '@react-navigation/native';
import {
  useReanimatedHeaderHeight,
  ReanimatedScreenProvider,
} from 'react-native-screens/reanimated';
import Animated, { useAnimatedStyle } from 'react-native-reanimated';
import { createNativeStackNavigator } from 'react-native-screens/native-stack';
import { FullWindowOverlay } from 'react-native-screens';
import React from 'react';

const Stack = createNativeStackNavigator();

function ExampleScreen() {
  // const headerHeight = useAnimatedHeaderHeight();
  const headerHeight = useReanimatedHeaderHeight();

  const animatedStyles = useAnimatedStyle(() => ({
    transform: [{ translateY: headerHeight.value }],
  }));

  return (
    <FullWindowOverlay>
      <Animated.View
        style={[
          {
            display: 'flex',
            justifyContent: 'flex-end',
            alignItems: 'center',

            backgroundColor: 'red',
            width: '100%',
            opacity: 0.5,
            height: 60,
            zIndex: 1,
            // transform: [
            //   {
            //     translateY: headerHeight.value,
            //   },
            // ],
          },
          animatedStyles,
        ]}>
        <Text>I'm a header!</Text>
      </Animated.View>
    </FullWindowOverlay>
  );
}

const Screen = () => {
  return (
    <>
      <ScrollView
        style={styles.screen}
        contentContainerStyle={{
          flexGrow: 1,
          justifyContent: 'center',
          alignItems: 'center',
        }}
        contentInsetAdjustmentBehavior="automatic">
        <Text>Screen</Text>
      </ScrollView>
      <ExampleScreen />
    </>
  );
};

export default function App() {
  return (
    <ReanimatedScreenProvider>
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen
            name="screen"
            component={Screen}
            options={{
              searchBar: {
                placeholder: 'Search',
              },
              headerTitle: 'Custom header title',
            }}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </ReanimatedScreenProvider>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
});
```

**Comment by tboba** [comment] 2023-11-02 14:46
Actually, when I'm trying to use native stack v6 from React Navigation I'm facing the same issue 💡
Let me investigate that further, I'll try to come back with a solution shortly.

**Comment by tboba** [comment] 2023-11-02 16:14
@ha3 I've tried to test `useReanimatedHeaderHeight` on example app from React Navigation and it seems that I've managed to make it work. My first assumption is that react navigation needs to have react-native-screens version set to 3.27.0 (which currently is 3.22.1, as Expo Go has that version of rn-screens by default).

https://github.com/software-mansion/react-native-screens/assets/23281839/13833947-a2d7-496f-9a20-fdc813ceac29

Could you check if patching react-native-screens version to 3.27.0 inside whole @react-navigation monorepo is sufficient in your case?

**Comment by ha3** [comment] 2023-11-21 19:53
@tboba sorry for responding so late! Unfortunately, I couldn't run the example app in `react-navigation` repo.

Also, I don't understand one thing. Since `react-native-screens` is a peer dependency for `react-navigation`, its code uses the version installed in the app. So how does changing the version inside the monorepo affects the outcome?

**Comment by tboba** [comment] 2023-11-22 09:56
@ha3 I think that you should be right right about your meaning of screens as a peer dependency, but to be honest I don't know how peerDependencies work with different versions of packages between defined version of peerDependency and the actual dependency installed in a project. 
While I was testing screens inside a react navigation example, changing the version of react-native-screens somehow worked for me 🤔

**Comment by tboba** [comment] 2024-05-15 13:01
Hi @ha3, sorry for pretty late update about this issue, but I finally found the time to check it again 😄 
Right now useReanimatedHeaderHeight should work correctly with search bar (and other stuff, like large title mode), but it seems that native-stack v7 is required to make it work (at this moment you need to install alpha version of 7.0). That's because on native-stack v6, implementation of adding useAnimatedHeaderHeight hasn't been merged yet.

However, I'll try to push forward with creating a PR for adding `useAnimatedHeaderHeight` also there! 💪
Because there's a way to make this hook working, I'll close this issue for now, but don't hesitate to ask any questions, if you have any.

Cheers! 👋 

https://github.com/software-mansion/react-native-screens/assets/23281839/8218d3f2-0d0d-4c34-a5e3-da4fc99a6627

**Closed by tboba** 2024-05-15 13:01 UTC
Labels: Platform: iOS, Repro provided

**Comment by ugoi** [comment] 2025-12-09 22:17
@tboba I see that you probably have flexGrow: 1 in your ScrollView? My question is how can I get rid of the additional space because it seems to me that the flexGrow makes the ScrollView grow beyond the free space, resulting in unnecessary scrolling.

https://github.com/user-attachments/assets/485f0b1d-ef82-4289-8de0-dc1272fa0e6f
