### ISSUE TITLE
Use transparent fragment by default

### ISSUE THREAD

**Issue by tychota** [software-mansion/react-native-screens#32] opened 2018-10-17 14:00 UTC
On my react native App, I have a section that have look like this:

![image](https://user-images.githubusercontent.com/13785185/47091543-5cf54180-d225-11e8-824c-8e58b37dfc8e.png)

When you go to the next page, the blue image background remains fixed while the page go over.

We achieved this by doing something like that:

```tsx
const ChapterWrapper = createStackNavigator(
  {
    "A": {
      screen: Question,
    },
    "B": {
      screen: Question,
    },
  },
  {
    cardStyle: {
      backgroundColor: 'transparent',
    },
    transitionConfig: () => ({
      // some custom animation, simplified because not impacting the issue
      containerStyle: {
        backgroundColor: 'transparent',
      },
    }),
  }
);

class QuestionsWrapper extends Component<
  IProps & IProfileCaptureContainerProps
> {
  public render() {
    return (
      <Fragment>
        <BackgroundContainer>
          <BackgroundImage chapter={this.getBackgroundChapterImage()} />
        </BackgroundContainer>
        <PageContainer>
          <ChapterWrapper navigation={this.props.navigation} />
        </PageContainer>
      </Fragment>
    );
  }
  private getBackgroundChapterImage = () => {
    const chapterLabel = this.props.navigation.getParam('chapterLabel');
  };
}
```

When installing react-native screen the Screen container have the default light grey android background that looks like this:

![image](https://user-images.githubusercontent.com/13785185/47091771-cecd8b00-d225-11e8-8dd2-b1967ebd062d.png)

The explanation is that there is then this view hierarchie:

![image](https://user-images.githubusercontent.com/13785185/47090995-50bcb480-d224-11e8-8020-ea4f95d3588d.png)

in this image, the background (in green) is between the first and the second view container (red).
Since the background of them are not transparent (they have android default), the image is not shown. (my hypothesis, maybe I'm completely wrong).

I fixed this using patch package:

```patch
patch-package
--- a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java
+++ b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java
@@ -2,6 +2,7 @@ package com.swmansion.rnscreens;
 
 import android.annotation.SuppressLint;
 import android.content.Context;
+import android.graphics.Color;
 import android.os.Bundle;
 import android.support.annotation.Nullable;
 import android.support.v4.app.Fragment;
@@ -29,6 +30,7 @@ public class Screen extends ViewGroup {
     public View onCreateView(LayoutInflater inflater,
                              @Nullable ViewGroup container,
                              @Nullable Bundle savedInstanceState) {
+      mScreenView.setBackgroundColor(Color.TRANSPARENT);
       return mScreenView;
     }
   }
```

*I'm happy to contribute to this repo but I will first discuss the solution*

- are transparent fragment hacky ? 
- should it be configurable somehow ?

**Comment by brentvatne** [comment] 2018-10-17 17:37
this is interesting.. maybe we want to make this a prop in screens, then we could toggle that within react-navigation

**Comment by tychota** [comment] 2018-10-17 17:48
(note, by default in iOS, it works, probably because the présentation mode is UIModalPresentationOverCurrentContext)

**Comment by brentvatne** [comment] 2018-10-17 18:18
in that case this may make sense!

**Comment by kmagiera** [comment] 2018-10-18 14:43
have you tried setting a background prop on <Screen> component?

**Comment by tychota** [comment] 2018-10-18 15:40
No! shall I modify react-navigation (or react-navigation-stack) directly to test this ?

**Comment by kmagiera** [comment] 2018-10-18 17:01
I think you'll have to do it here -> https://github.com/kmagiera/react-native-screens/blob/master/src/screens.native.js#L65

This could actually be the root cause, we seem to only pass styles to the wrapped `Animated.View`  there and so the background isn't set on the `AnimatedNativeScreen` component.

If you are on RN 0.57 you could try removing the whole wrapping bit and just do:
```
return <AnimatedNativeScreen {...this.props} />;
```
The whole wrapping code is workaround for one issue in react-native core that's been fixed in 0.57 already with this change https://github.com/facebook/react-native/commit/75505993f0523ebf5f1ad68ee30e91e6879b28a3

**Comment by tychota** [comment] 2018-10-22 08:54
Interesting. I will try this afternoon.

**Comment by miblanchard** [comment] 2018-11-09 20:38
@tychota Any luck with this approach?  I found this in our app today while updating and would also love a way to use screens without the flash of grey.

**Comment by brentvatne** [comment] 2018-11-09 20:59
@miblanchard - can you try the suggestion from @kmagiera above and let us know how it goes?

**Comment by miblanchard** [comment] 2018-11-09 22:57
@brentvatne I replaced https://github.com/kmagiera/react-native-screens/blob/master/src/screens.native.js#L61-L75 with 

`return <AnimatedNativeScreen {...this.props} />;` 

per @kmagiera and also updated the stack properties as follows per @tychota:

    cardStyle: {
      backgroundColor: 'transparent',
    },
    transitionConfig: () => ({
      // some custom animation, simplified because not impacting the issue
      containerStyle: {
        backgroundColor: 'transparent',
      },
    }),

With both of these changes, I still see the grey flash when switching between stacks.

**Comment by tychota** [comment] 2018-11-09 23:08
Sorry for not giving any news, last weeks were hard with production issue and so. It is kinda long to reproduce in my app (due to the structure) so I didn't prioritize:

Have you tried:

```tsx
<AnimatedNativeScreen style={[this.props.style, {backgroundColor: "transparent"]} {...this.props} />
```
Will be interested to know if above fixes..

@miblanchard if you need quick fix, this patch package works:

```patch
patch-package
--- a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java
+++ b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java
@@ -2,6 +2,7 @@ package com.swmansion.rnscreens;
 
 import android.annotation.SuppressLint;
 import android.content.Context;
+import android.graphics.Color;
 import android.os.Bundle;
 import android.support.annotation.Nullable;
 import android.support.v4.app.Fragment;
@@ -29,6 +30,7 @@ public class Screen extends ViewGroup {
     public View onCreateView(LayoutInflater inflater,
                              @Nullable ViewGroup container,
                              @Nullable Bundle savedInstanceState) {
+      mScreenView.setBackgroundColor(Color.TRANSPARENT);
       return mScreenView;
     }
   }
```

How to generate it ?

you should:
- install https://www.npmjs.com/package/patch-package (see readme)
- edit the java code in `node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java` 
- run `yarn patch-package react-native-screen`

**Comment by andresesfm** [comment] 2018-11-13 07:10
@tychota: setting the background to transparent still shows the issue. Actually setting it to red makes it more apparent. I think @miblanchard is seeing to this issue: https://github.com/kmagiera/react-native-screens/issues/35 instead of the background problem discussed on this thread. Any thoughts on that one?

**Comment by tychota** [comment] 2018-11-13 08:14
@andresesfm you mean setting it in native (modifying java source code) or setting it in rn-screens as @kmagiera suggested.

**Comment by andresesfm** [comment] 2018-11-13 15:14
@tychota I meant the Java change. Any infights are appreciated.

**Comment by andresesfm** [comment] 2018-11-13 15:14
*insights

**Comment by rogerkerse** [comment] 2019-03-23 18:56
On iOS i can't get transparent modal as well

**Comment by WoLewicki** [comment] 2020-04-02 11:59
Can someone tell if the issue still exists?

**Comment by WoLewicki** [comment] 2020-05-29 11:43
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Closed by WoLewicki** 2020-05-29 11:43 UTC
