### ISSUE TITLE
 [RNScreens] Failed to initialise dummy layout in onHostResume. This is not expected. Android

### ISSUE THREAD

**Issue by Kabeer-Haseja** [software-mansion/react-native-screens#2324] opened 2024-08-29 07:01 UTC
### Description

when we run app we are getting this 
versions that i am using 
 "react-native": "0.75.2",
      "react-native-safe-area-context": "^4.10.9",
    "react-native-screens": "^3.34.0",
 
and kotlin version
  kotlinVersion = "1.9.24"
![Screenshot_20240829_115709](https://github.com/user-attachments/assets/c43a34af-ff73-456e-acc2-1e91c76903b1)

### Steps to reproduce

just update the react native screen 

### Snack or a link to a repository

..

### Screens version

3.34.0

### React Native version

0.75.2

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2024-08-29 07:53
@Kabeer-Haseja can you provide us with reproduction / stack trace at least? You might also want to try out `3.35.0-rc.1` version of the library

**Comment by Kabeer-Haseja** [comment] 2024-08-29 09:13
@kkafar when i enable new architecture `newArchEnabled=true` and run the app  it come up with the that screen that i already showed to you

**Comment by kkafar** [comment] 2024-08-29 18:42
@Kabeer-Haseja Thats understandable, but it does not happen for me.
Have you tried out 3.35.0-rc.1?

**Comment by Kabeer-Haseja** [comment] 2024-08-30 09:31
Hi @kkafar,

I encountered an issue while trying to install react-native-screens@3.35.0-rc.1. The other packages, such as:

	•	@react-navigation/bottom-tabs: ^6.6.1
	•	@react-navigation/native: ^6.1.18
	•	@react-navigation/native-stack: ^6.11.0
	•	@react-navigation/stack: ^6.4.1

are not supported after the installation.

Here’s what I did to install react-native-screens@3.35.0-rc.1 (though it’s not an ideal approach):

	1.	Removed react-native-screens package: I started by removing the existing react-native-screens package.
	2.	Ran npm install: After removing the package, I ran npm install to install all the remaining dependencies.
	3.	Reinstalled react-native-screens: Finally, I installed react-native-screens@3.35.0-rc.1.

However, when I tried to add all the packages back together and ran npm install, I encountered errors with the packages mentioned above.

**Comment by LinhLM23496** [comment] 2024-09-06 15:58
+1

**Comment by sanchezzzs** [comment] 2024-09-06 19:07
same problem on armv8 with newArchEnabled=true, armv7 works fine.
`"react-native-screens": "^3.34.0"`

**Comment by abrah4mr** [comment] 2024-09-18 18:41
@kkafar Seems to work with 3.35.0-rc.1 version.

I have RN 0.75 with the flag enabled, and once I installed the rc version it work.

**Comment by kkafar** [comment] 2024-09-25 17:59
I'll close the issue, since the fix is already merged & released with rc version.

**Closed by kkafar** 2024-09-25 17:59 UTC
Labels: Missing info, Platform: Android, Missing repro
