### ISSUE TITLE
Crash when closing the app while the rn activity is not on top

### ISSUE THREAD

**Issue by janicduplessis** [software-mansion/react-native-screens#33] opened 2018-10-20 00:42 UTC
When an app opens a new activity and then is backgrounded it crashes because getCurrentActivity returns another activity.

In my case it happens when using facebook sign in and then backgrounding the app.

EDIT: Can't seem to repro consistently but I think my theory about getCurrentActivity is still valid.

```
IllegalStateException
In order to use RNScreen components your app's activity need to extend ReactFragmentActivity or ReactCompatActivity
com.swmansion.rnscreens.ScreenContainer in <init> at line 44
com.swmansion.rnscreens.ScreenContainerViewManager in createViewInstance at line 21
com.swmansion.rnscreens.ScreenContainerViewManager in createViewInstance at line 9
com.facebook.react.uimanager.ViewManager in createView at line 44
com.facebook.react.uimanager.NativeViewHierarchyManager in createView at line 260
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation in execute at line 200
com.facebook.react.uimanager.UIViewOperationQueue$1 in run at line 908
com.facebook.react.uimanager.UIViewOperationQueue in flushPendingBatches at line 1021
com.facebook.react.uimanager.UIViewOperationQueue in access$2500 at line 46
com.facebook.react.uimanager.UIViewOperationQueue$2 in runGuarded at line 979
com.facebook.react.bridge.GuardedRunnable in run at line 24
android.os.Handler in handleCallback at line 739
android.os.Handler in dispatchMessage at line 95
android.os.Looper in loop at line 145
android.app.ActivityThread in main at line 5942
java.lang.reflect.Method in invoke
java.lang.reflect.Method in invoke at line 372
com.android.internal.os.ZygoteInit$MethodAndArgsCaller in run at line 1399
com.android.internal.os.ZygoteInit in main at line 1194
```

**Comment by Chubacca** [comment] 2018-11-13 21:29
We have a Hybrid app and this is easily reproducible. All we have to do is put another activity on top of our ReactActivity, minimize, and reopen the app

**Comment by tgensol** [comment] 2018-11-16 19:20
I am also getting that error. I can say, but I am not 100%sure, that it happens when the app is put in background, for a certain time (minutes).If we want to open it, the app crashed with that error.

Any idea ?

Best

**Comment by K-Leon** [comment] 2018-11-28 12:44
It‘s also the single biggest crash in my app. Any workaround available?

**Comment by jeongsd** [comment] 2018-12-07 02:02
I have same issue

**Comment by javiercr** [comment] 2018-12-15 17:36
Same problem :/ (react-navigation v3.0.7 & react-native-screens v1.0.0-alpha.16)

**Comment by javiercr** [comment] 2018-12-28 10:54
@kmagiera I'm afraid we're still seeing this error with `^1.0.0-alpha.19` (we rolled up a production release yesterday with `^1.0.0-alpha.19` and got the first errors today):

```
java.lang.IllegalStateException In order to use RNScreens components your app's activity need to extend ReactFragmentActivity or ReactCompatActivity 
    ScreenContainer.java:88 com.swmansion.rnscreens.ScreenContainer.getOrCreateTransaction
    ScreenContainer.java:103 com.swmansion.rnscreens.ScreenContainer.attachScreen
    ScreenContainer.java:175 com.swmansion.rnscreens.ScreenContainer.updateIfNeeded
    ScreenContainer.java:127 com.swmansion.rnscreens.ScreenContainer.onAttachedToWindow
    View.java:17449 android.view.View.dispatchAttachedToWindow
    ViewGroup.java:3326 android.view.ViewGroup.dispatchAttachedToWindow
    ViewGroup.java:3333 android.view.ViewGroup.dispatchAttachedToWindow
    ViewGroup.java:3333 android.view.ViewGroup.dispatchAttachedToWindow
    ViewGroup.java:4977 android.view.ViewGroup.addViewInner
    ViewGroup.java:4768 android.view.ViewGroup.addView
    ViewGroup.java:4708 android.view.ViewGroup.addView
    ViewGroupManager.java:39 com.facebook.react.uimanager.ViewGroupManager.addView
    NativeViewHierarchyManager.java:438 com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren
    UIViewOperationQueue.java:227 com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute
    UIViewOperationQueue.java:894 com.facebook.react.uimanager.UIViewOperationQueue$1.run
    UIViewOperationQueue.java:1001 com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches
    UIViewOperationQueue.java:46 com.facebook.react.uimanager.UIViewOperationQueue.access$2400
    UIViewOperationQueue.java:959 com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded
    GuardedRunnable.java:24 com.facebook.react.bridge.GuardedRunnable.run
    Handler.java:790 android.os.Handler.handleCallback
    Handler.java:99 android.os.Handler.dispatchMessage
    Looper.java:172 android.os.Looper.loop
    ActivityThread.java:6590 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:438 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:807 com.android.internal.os.ZygoteInit.main
```

In the mean time we're gonna rollback and disable react-native-screens for Android :/

**Comment by K-Leon** [comment] 2018-12-29 08:54
Same happening on our end - even though the frequency seems to be a little lower.

**Comment by kmagiera** [comment] 2019-01-04 10:00
Thanks for the updates @javiercr @K-Leon and @janicduplessis – Sorry that the fix hasn't resolved your issue.

Could any of you be able to provide some more details on how this problem can actually be reproduced? As per following @janicduplessis original description I tried:
1) Having my app use react-navigation library with screens enabled
2) From the initial screen I opened an external (non RN) activity via intent that launched in the same app process
3) pressed home button to place the app into background

Following these steps I wasn't able to repro the issue. Is there anything that I'm missing?

**Comment by kmagiera** [comment] 2019-01-04 15:48
I still cannot reproduce this problem but as it's been mentioned earlier the problem might be that `ReactContext.getCurrentActivity` does not return the correct react activity but some other activity that has covered the current one. I believe this is most likely the root cause of the problem and therefore I figured out a solution that'd allow us to avoid using that method.

I merged it into master here c0b73545ffba5eb3310451c368ec6cbcac429a59 and published alpha.20 with it included. If any of you is willing to give it a shot and see if the problem still persist I would be grateful

**Comment by javiercr** [comment] 2019-01-08 14:48
@kmagiera
> I still cannot reproduce this problem but as it's been mentioned earlier the problem might be that ReactContext.getCurrentActivity does not return the correct react activity but some other activity that has covered the current one. I

We're using [Intercom Android SK](https://github.com/intercom/intercom-android) through [react-native-intercom](https://github.com/tinycreative/react-native-intercom). We use it as our in-app support chat. Is it possible that is the activity which is covering the current one as you mentioned?

Anyways, we'll give a shot to alpha.20, thank you very much!

**Comment by WoLewicki** [comment] 2020-04-02 11:55
Can someone tell if the issue still exists or was it solved with the commit? @janicduplessis @javiercr

**Comment by janicduplessis** [comment] 2020-04-02 16:58
@WoLewicki I'm not seeing this crash anymore, no idea what fixed it though.

**Comment by WoLewicki** [comment] 2020-04-03 08:08
Ok, so I am closing it. Looks like it was https://github.com/software-mansion/react-native-screens/commit/c0b73545ffba5eb3310451c368ec6cbcac429a59 which @kmagiera linked since no more activity on the issue since then.

**Closed by WoLewicki** 2020-04-03 08:08 UTC
