### ISSUE TITLE
SVGs disappear on Android when the screen transition animation starts

### ISSUE THREAD

**Issue by SimpleCreations** [software-mansion/react-native-screens#1547] opened 2022-07-27 15:53 UTC
## Description

As the title says. This issue is similar to the one I created previously, but I've decided to make a separate one, because this one is more straightforward to reproduce (doesn't require seemingly unrelated things like a tab navigator, `screenOptions` or a `FlatList`).

### Screenshots

Notice how the circle disappears right as the back button is pressed.

https://user-images.githubusercontent.com/12449725/181292779-3fada3d9-c387-4810-8c2d-d5bd57c3d845.mp4

## Steps To Reproduce

See the code sample.

## Reproduction

```javascript
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {Button, Text} from 'react-native';
import React from 'react';
import {Circle, Svg} from 'react-native-svg';

const Stack = createNativeStackNavigator();

const Parent = ({navigation}) => (
  <Button title="Press me" onPress={() => navigation.navigate('Child')} />
);

const Child = () => (
  <>
    <Svg
      width={200}
      height={200}
      viewBox="0 0 100 100"
      xmlns="http://www.w3.org/2000/svg">
      <Circle cx="50" cy="50" r="50" fill="#000" />
    </Svg>
    <Text>This text will stay, but the circle above will disappear!</Text>
  </>
);

const App = () => (
  <NavigationContainer>
    <Stack.Navigator>
      <Stack.Screen name="Parent" component={Parent} />
      <Stack.Screen name="Child" component={Child} />
    </Stack.Navigator>
  </NavigationContainer>
);

export default App;

```

## Platform

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Architecture

- [x] Paper
- [ ] Fabric

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

```json
  {
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "react": "18.0.0",
    "react-native": "0.69.3",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.15.0",
    "react-native-svg": "^12.4.3"
  }
```

**Comment by WoLewicki** [comment] 2022-07-29 10:20
I believe it is a duplicate of #773 (check https://github.com/software-mansion/react-native-screens/issues/773#issuecomment-783469792 for solution). I will close it then. Feel free to comment if I am wrong and we can always reopen it then.

**Closed by WoLewicki** 2022-07-29 10:20 UTC
Labels: 🤖android, repro-provided, needs-review

**Comment by SimpleCreations** [comment] 2022-07-29 10:26
Thank you! And I should've looked for the existing issue better, sorry 😬
