### ISSUE TITLE
[3.30.0] Installation fails after new release. `/bin/sh: 1: cd: can't cd to react-navigation`

### ISSUE THREAD

**Issue by kuzkokov** [software-mansion/react-native-screens#2078] opened 2024-03-25 16:33 UTC
### Description

Hey guys. Just got this error from the CI/CD that was working fine previously:

```
error /project/node_modules/react-native-screens: Command failed.
Exit code: 2
Command: git submodule update --init --recursive && (cd react-navigation && yarn)
Arguments: 
Directory: /project/node_modules/react-native-screens
Output:
/bin/sh: 1: cd: can't cd to react-navigation
```

I guess it's because of the newest release and [this PR](https://github.com/software-mansion/react-native-screens/pull/1993)?
Didn't really made much research and reproducing, but it seems quite clear what this is about

### Steps to reproduce

1. `yarn install react-native-screens`
2. enjoy

### Snack or a link to a repository

N/A

### Screens version

3.30.0

### React Native version

0.73.6

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by donutdonate** [comment] 2024-03-25 16:33
faced with the same issue

**Comment by tboba** [comment] 2024-03-25 16:37
Hi @kuzkokov, @donutdonate - thanks for reporting this. Yeah, looks like we didn't cover `.gitmodules` file we've added recently 😓 We'll take care of this in upcoming days. For now, you can stay with the `3.29.0` version to build Screens on CI. Thank you for your patience 🙏

**Comment by cubancodepath** [comment] 2024-03-25 16:47
Same issues in React Native (witheout expo)

# Step to reproduce 
`npm i react-native-screens`

![image](https://github.com/software-mansion/react-native-screens/assets/41394649/2dc21dfa-ee12-4361-a599-0de90609ef11)

**Comment by efstathiosntonas** [comment] 2024-03-25 16:59
same here

**Comment by tboba** [comment] 2024-03-25 17:17
@efstathiosntonas okay, let me quickly check this change with `npm pack` 🙏 

About the offtopic - that's because this nightly has been made for the purposes of making `goBackGesture` work before the PR with implementing the functionalities on reanimated has been merged 😄

**Comment by efstathiosntonas** [comment] 2024-03-25 17:19
@tboba it seems yarn 4.1.1 wants it like this:     "react-native-screens": "https://github.com/software-mansion/react-native-screens.git", will test now.

**Comment by Lump01** [comment] 2024-03-25 17:33
> @efstathiosntonas @cubancodepath @kuzkokov @short-dsb @Alexandre-Cornillon @donutdonate @kuzkokov @akeva001 @Lump01
> 
> Could you please check whether the newest commit in `3.30.0` branch resolves the issue with builds and that your app works correctly while using the version from branch?
> 
> Please change in `package.json` version of react-native-screens to:
> 
> ```json
> "react-native-screens": "software-mansion/react-native-screens#3.30.0"
> ```
Still getting the issue with the submodule. 
```
npm ERR! command sh -c git submodule update --init --recursive && (cd react-navigation && yarn)
npm ERR! npm ERR! fatal: not a git repository (or any of the parent directories): .git
```
Could it be that the pipeline failed for the branch of react-navigation y'all are pulling in as a submodule?

[react-navigation 523fa4f](https://github.com/react-navigation/react-navigation/tree/523fa4f3afb7c428a8370bfd83933c0163224e66)

**Comment by tboba** [comment] 2024-03-25 17:34
@Lump01 that's strange 🤔 but this is not caused from react-navigation for sure.

**Comment by tboba** [comment] 2024-03-25 17:36
The patch has been released! Could you check whether this issue is fixed in `3.30.1`?

cc @kuzkokov @donutdonate @short-dsb @Alexandre-Cornillon @akeva001 @Lump01 @efstathiosntonas @twokilohertz @cubancodepath @mohd-ramzan-1

**Comment by tboba** [comment] 2024-03-25 17:37
cc @aditya063 @FraserKemp (I see you've also reacted to the issue)

**Comment by FraserKemp** [comment] 2024-03-25 17:41
@tboba Just tested this now on 3.30.1 and it all seemed to work for me! Thanks for the speedy fix !

**Comment by tboba** [comment] 2024-03-25 17:47
Great @FraserKemp, thanks for letting me know! I'll wait for the opinion from others before closing this issue. Can anyone also confirm this error doesn't happen anymore?

**Comment by Lump01** [comment] 2024-03-25 17:48
I was able to install 3.30.1 successfully!

**Comment by Lump01** [comment] 2024-03-25 17:49
Thanks for the speedy fix @tboba

**Comment by efstathiosntonas** [comment] 2024-03-25 17:50
`3.30.1` worked as a charm, thank you @tboba for the really quick fix.

**Comment by tboba** [comment] 2024-03-25 17:51
That's great to hear! Now I can sleep well 😄 🚀 
I'll assume this issue can be closed for now, but if anyone is still impacted of this error, feel free to comment your scenario below.

Cheers 🙏

**Closed by tboba** 2024-03-25 17:51 UTC
Labels: Bug, Platform: iOS, Platform: Android

**Comment by Alexandre-Cornillon** [comment] 2024-03-26 13:10
3.30.1 worked nice for me too :) Big thanks 👍
