### ISSUE TITLE
Screen freeze after update FlatList data and go back

### ISSUE THREAD

**Issue by totodot** [software-mansion/react-native-screens#1297] opened 2022-02-01 23:14 UTC
## Description

Screen freeze after updating FlatList data and return to the previous screen

App does not freeze when:
1. Used ScrollView instead FlastList
or
2. Downgrade react-native-screens to 2.18.0
or
3. Add `detachInactiveScreens={false}` for Stack Navigator

### Screenshots

https://user-images.githubusercontent.com/14233750/152067342-08ee546b-dd1c-462f-9c28-d0ebebc0d954.mp4

## Steps To Reproduce

1. Create 2 Stack Screens
2. Go to Second Screen which display FlastList
3. Add new item to FlatList
4. Go back to First Screen

### Expected behavior
First Screen not freeze

### Actual behavior
First screen freeze, and cannot click on button

## Reproduction

```
const First = ({ navigation }) => {
  return (
    <View>
      <Button title="click" onPress={() => navigation.navigate('Second')} />
    </View>
  );
};
const Second = ({ navigation }) => {
  const [numbers, setNumbers] = useState([1, 2, 3]);
  return (
    <View>
      <FlatList data={numbers} renderItem={({ item }) => <Text>{item}</Text>} />
      <Button title="add" onPress={() => setNumbers((a) => [...a, 1])} />
      <Button title="back" onPress={() => navigation.goBack()} />
    </View>
  );
};

const RootNavigation: React.FC = () => {
  const RootStack = createStackNavigator();

  return (
    <NavigationContainer>
      <RootStack.Navigator>
        <RootStack.Screen name="First" component={First} />
        <RootStack.Screen name="Second" component={Second} />
      </RootStack.Navigator>
    </NavigationContainer>
  );
};

export default RootNavigation;
```

## Platform

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## 3.

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           | 0.66.3         |
| @react-navigation/native               |  6.0.6       |
| @react-navigation/stack         | 6.0.11        |
| react-native-screens                   | 3.10.2        |
| react-native-safe-area-context         | 3.3.2        |
| react-native-gesture-handler           |   1.10.3      |
| react-native-reanimated                |   2.3.0-beta.3      |

**Comment by WoLewicki** [comment] 2022-02-15 13:59
I checked the code you provided locally and could not spot the freeze. The video you attached also does not show any freeze, or am I missing something? Could you provide a repository so we can reproduce it with the exact packages etc?

**Comment by rubanraj54** [comment] 2022-02-16 09:13
We're also having the same issue.

**Comment by camcnz** [comment] 2022-02-16 09:18
We are experiencing the same problem. It seems to be easier to reproduce when the app is newly installed.

Platform
 iOS


package | version
-- | --
react-native | 0.67.1
@react-navigation/native | 6.0.6
@react-navigation/stack | 6.1.1
react-native-screens | 3.11.1
react-native-safe-area-context | 3.3.2
react-native-gesture-handler | 2.1.1
react-native-reanimated | 2.3.0-beta.3

**Comment by WoLewicki** [comment] 2022-02-16 09:20
What exactly is the issue? The application stops responding? Or is it a laggy behavior? Could you provide a more detailed description of this?

**Comment by rubanraj54** [comment] 2022-02-16 09:30
After the screen freeze, we cannot interact with the screen anymore.

We can't click or scroll.

**Comment by WoLewicki** [comment] 2022-02-16 09:32
Ok, thanks for the clarification. Could you provide a repository where we can recreate this behavior in an isolated way so everyone can test it? It will greatly help with debugging the problem.

**Comment by totodot** [comment] 2022-02-16 14:10
Update react-native-reanimated to 2.4.1 resolved the problem

**Comment by WoLewicki** [comment] 2022-02-17 11:26
Great to hear that! I will close this issue then, feel free to comment here if something is wrong and we can reopen it then.

**Closed by WoLewicki** 2022-02-17 11:26 UTC
Labels: 🍎iOS, repro-provided

**Comment by anhnch** [comment] 2022-12-06 14:58
I confirm tododot's info
2. Downgrade react-native-screens to 2.18.0
3. Add detachInactiveScreens={false} for Stack Navigator

This is definitely a bug or the 3 points should be written in the official documents. I hope someone can fix it.

**Comment by diegods-ferreira** [comment] 2024-07-07 00:43
I'm facing a similar problem to this one. It's not the entire app that freezes to me though, it's just the first screen's FlatList.

I described the issue on a [post](https://www.reddit.com/r/reactnative/comments/1ds4fcm/flatlist_freezes_on_ios/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) on Reddit's r/reactnative subreddit.

**Comment by guihendias** [comment] 2024-08-21 18:40
I have a similar problem using native-stack. But we don't have access to `detachInactiveScreens` there. I wonder what's the alternative.
