### ISSUE TITLE
android bug latest version

### ISSUE THREAD

**Issue by maystrenkoYurii** [software-mansion/react-native-screens#744] opened 2020-12-10 12:18 UTC
<img width="1095" alt="Снимок экрана 2020-12-10 в 14 17 33" src="https://user-images.githubusercontent.com/23016311/101771400-8acb2d80-3af2-11eb-9eb2-9327adeaca06.png">

After update from "react-native-screens": "2.15.0" to "react-native-screens": "2.16.0", android not bundled

**Comment by JaapWeijland** [comment] 2020-12-10 12:25
Same!

**Comment by JaapWeijland** [comment] 2020-12-10 12:26
![Schermafbeelding 2020-12-10 om 13 26 39](https://user-images.githubusercontent.com/7115712/101772206-57d16b80-3aeb-11eb-822a-484f73b1ac0a.png)

Same!

**Comment by GuentonBrooks** [comment] 2020-12-10 12:37
I have this problem too:

`..\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStack.java:189: error: cannot find symbol
            getOrCreateTransaction().setCustomAnimations(R.anim.rns_slide_in_from_right, R.anim.rns_slide_out_to_left);   
                                                               ^
  symbol:   variable rns_slide_in_from_right
  location: class anim`

**Comment by kaunghtethein977** [comment] 2020-12-10 12:58
Same Here. Happened in the latest version `"react-native-screens": "^2.15.0",`

**Comment by kaunghtethein977** [comment] 2020-12-10 12:59
Same Here. Happened in the latest version "react-native-screens": "^2.16.0",

**Comment by MaixEqu** [comment] 2020-12-10 13:00
The same problem in 2 diffrent projects.
2 solutions work:
1 - back to 2.15.0.
2 - (rude) comment in Java in 2 places where the vars are.

**Comment by MaixEqu** [comment] 2020-12-10 13:05
> The same problem in 2 diffrent projects (both - react native cli).
> 2 solutions work:
> 1 - back to 2.15.0.
> 2 - (rude) comment in Java in 2 places where the vars are.

/home/maick/xMx/aaViewers/aAviewC/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStack.java:190: error: cannot find symbol
            getOrCreateTransaction().setCustomAnimations(R.anim.rns_slide_in_from_right, R.anim.rns_slide_out_to_left);
                                                               ^
  symbol:   variable rns_slide_in_from_right
  location: class anim

**Comment by WoLewicki** [comment] 2020-12-10 13:08
Can you check if this regression is fixed in `2.16.1`?

**Comment by GuentonBrooks** [comment] 2020-12-10 13:09
> Can you check if this regression is fixed in `2.16.1`?

Hang on, I'll check right away

**Comment by GuentonBrooks** [comment] 2020-12-10 13:15
> Can you check if this regression is fixed in `2.16.1`?

Steps:
`yarn upgrade react-native-screens --latest
cd android
./gradlew clean
cd ..
yarn android`

Confirmed working using react-native-cli
`"react": "17.0.1",
"react-native": "0.63.4",`

Thank you so much for your quick action @WoLewicki you're the MVP for the day!

**Comment by MaixEqu** [comment] 2020-12-10 13:18
Yes. The 2.16.1 solves the problem in my both projects.

**Comment by WoLewicki** [comment] 2020-12-10 13:19
Thanks for finding the bug so quick 💪  Since this is fixed now, I am closing this issue.

**Comment by MaixEqu** [comment] 2020-12-10 13:20
And very quick correction. Thanx!

**Closed by WoLewicki** 2020-12-10 13:19 UTC

**Comment by kyle-ssg** [comment] 2020-12-10 13:44
Haha this caught me out for 15 minutes, cheers for the quick work!
