### ISSUE TITLE
Tried to register two views with the same name RNSScreen

### ISSUE THREAD

**Issue by raphaelrk** [software-mansion/react-native-screens#15] opened 2018-09-20 19:26 UTC
Getting the following issue when I add `import { useScreens } from 'react-native-screens';` in my App.js

![simulator screen shot - iphone se - 2018-09-20 at 15 25 00](https://user-images.githubusercontent.com/3377845/45841983-67392400-bce9-11e8-88da-80e73dd4a847.png)

![simulator screen shot - iphone se - 2018-09-20 at 15 25 02](https://user-images.githubusercontent.com/3377845/45841982-67392400-bce9-11e8-8f60-a5abf11ef065.png)

## react-native info
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.10.0
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

## Etc
  "expo": "^30.0.0",
  "react-native-screens": "^1.0.0-alpha.12",

Happens in both dev and production mode
Was not able to reproduce in a [simple snack](https://snack.expo.io/@raphaelrk/rnsscreen-bug)

**Comment by kantorm** [comment] 2018-09-21 07:43
I had the same issue but with the app  created with `react-native init`

**Comment by jaydenwindle** [comment] 2018-09-23 00:36
I'm also running into this issue using in an ejected CRNA app. 

The app I'm working on uses multiple types of nested navigators (stack, switch, drawer, tab) and has multiple stack navigators. I wonder if having multiple navigators setup is part of the issue here?

**Comment by kmagiera** [comment] 2018-09-24 06:49
The issue is related to the fact `react-native-screens` package is installed several times under `node_modules` in different versions. I am investigating a possible cause of this but one hint that I have for the time being is to try upgrading `yarn` and performing a clean install with `yarn` instead of `npm`

**Comment by MaxInMoon** [comment] 2018-10-13 11:10
@kmagiera what do you mean by "`installed several times under node_modules`"?

**Comment by AkilLis** [comment] 2018-10-16 23:57
@kmagiera any solution for that?

**Comment by AkilLis** [comment] 2018-10-17 04:30
error appears when upgrading react-navigation to v2.16.0. Since react navigation uses react-native-screens.

**Comment by kelset** [comment] 2018-10-22 09:13
So, related to this:
* the latest released version of 2.x of `react-navigation` still requires alpha.11 https://github.com/react-navigation/react-navigation/blob/2.x/package.json
* even when enforcing the latest version via yarn resolutions, the issue still occurs

can't really investigate it more atm, but yeah there is probably something with a clash.

**Comment by lanceharper** [comment] 2018-10-22 21:48
^ Bumping `react-native-screens` for 2.x in a fork of `react-navigation` addressed this issue for me: https://github.com/lanceharper/react-navigation/commit/1df42a41c17769a87c5532d2dc8afa7847162cce

I can submit this back to the main repo if there is no preferred alternative.

**Comment by brentvatne** [comment] 2018-10-23 20:19
2.x of react-navigation depends on ^1.0.0-alpha.11 which should match 1.0.0-alpha.15. *however*, another package has installed react-native-screens with a more strict dependency that doesn't match this range, for example if your package.json explicitly includes react-native-screens@1.0.0-alpha.5, then you will end up with 2 copies of react-native-screens. i'd check your yarn.lock to see what package is installing which version of it.

useful reference:
https://semver.npmjs.com/
<img width="1163" alt="screen shot 2018-10-23 at 1 18 07 pm" src="https://user-images.githubusercontent.com/90494/47388109-31aba000-d6c6-11e8-9651-f416dfc4f36f.png">

**Comment by kelset** [comment] 2018-11-02 14:21
(update: with ReactNav v3 the issue disappears 👌)

**Comment by hufkens** [comment] 2019-02-08 12:51
Is there a way to solve this error when using reac-native-screens as a local_module?

I'm currently trying to fix this library for tvOS but because it is a dependency now of `@react-navigation/native` I always get this error now. Probably because it gets loaded twice (once from local_module and once for as a dependency for react-navigation)

Any tips for that?

**Comment by ranjitatwal30** [comment] 2019-03-16 17:04
I deleted the react-native-gesture-handler from node_modules/expo/ and it worked for me. It took me so much time to figure it.

**Comment by oussamaAbdelwahed** [comment] 2019-03-30 18:02
@ranjitatwal30 , thanks a lot man , it saves e a lot of time :+1:

**Comment by altab** [comment] 2019-04-01 21:22
@ranjitatwal30 it works for me too !!! thank you !!!

**Comment by asimonv** [comment] 2019-04-10 12:59
> I deleted the react-native-gesture-handler from node_modules/expo/ and it worked for me. It took me so much time to figure it.

it works!

**Comment by sebastian-yabiku** [comment] 2019-05-26 21:24
> I deleted the react-native-gesture-handler from node_modules/expo/ and it worked for me. It took me so much time to figure it.

thank u.

**Comment by Pandazaur** [comment] 2019-05-28 15:28
For people not using Expo:

I had the problem with `react-navigation`. I checked in *yarn.lock* what was the exact version of ` react-native-screens`used by the `react-navigation` package and installed EXACTLY the same version and now it works !

My yarn.lock was:
```
react-native-screens@^1.0.0-alpha.11:
  version "1.0.0-alpha.15"
  resolved "https://registry.yarnpkg.com/react-native-screens/-/react-native-screens-1.0.0-alpha.15.tgz#5b5a0041310b46f12048fda1908d52e7290ec18f"
```

So i installed`yarn add react-native-screens@^1.0.0-alpha.11`

**Comment by WoLewicki** [comment] 2020-04-02 12:07
Can someone tell if the issue still exists in the newer versions of Expo and Screens?

**Comment by WoLewicki** [comment] 2020-05-29 11:38
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Closed by WoLewicki** 2020-05-29 11:38 UTC
