### ISSUE TITLE
updateDisplayListIfDirty error

### ISSUE THREAD

**Issue by invyctus92** [software-mansion/react-native-screens#1315] opened 2022-02-14 11:16 UTC
I receive from Bugsnags several reports of the following error, can you give me some help?

## Description

java.lang.IllegalStateException: Recording currently in progress - missing #endRecording() call?
        at android.graphics.RenderNode.beginRecording(RenderNode.java:372)
        at android.view.View.updateDisplayListIfDirty(View.java:20454)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.swmansion.rnscreens.ScreenStack.performDraw(ScreenStack.kt:304)
        at com.swmansion.rnscreens.ScreenStack.access$performDraw(ScreenStack.kt:14)
        at com.swmansion.rnscreens.ScreenStack$DrawingOp.draw(ScreenStack.kt:325)
        at com.swmansion.rnscreens.ScreenStack.drawAndRelease(ScreenStack.kt:278)
        at com.swmansion.rnscreens.ScreenStack.dispatchDraw(ScreenStack.kt:295)
        at android.view.View.draw(View.java:21490)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:21490)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:21490)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:226)
        at android.view.View.draw(View.java:21490)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.draw(View.java:21621)
        at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:122)
        at eightbitlab.com.blurview.BlockingBlurController.draw(BlockingBlurController.java:164)
        at eightbitlab.com.blurview.BlurView.draw(BlurView.java:51)
        at android.view.View.updateDisplayListIfDirty(View.java:20483)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:21621)
        at android.view.View.updateDisplayListIfDirty(View.java:20483)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.swmansion.rnscreens.ScreenStack.performDraw(ScreenStack.kt:304)
        at com.swmansion.rnscreens.ScreenStack.access$performDraw(ScreenStack.kt:14)
        at com.swmansion.rnscreens.ScreenStack$DrawingOp.draw(ScreenStack.kt:325)
        at com.swmansion.rnscreens.ScreenStack.drawAndRelease(ScreenStack.kt:278)
        at com.swmansion.rnscreens.ScreenStack.dispatchDraw(ScreenStack.kt:295)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:21621)
        at android.view.View.updateDisplayListIfDirty(View.java:20483)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:21621)
        at android.view.View.updateDisplayListIfDirty(View.java:20483)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:21621)
        at android.view.View.updateDisplayListIfDirty(View.java:20483)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.swmansion.rnscreens.ScreenStack.performDraw(ScreenStack.kt:304)
        at com.swmansion.rnscreens.ScreenStack.access$performDraw(ScreenStack.kt:14)
        at com.swmansion.rnscreens.ScreenStack$DrawingOp.draw(ScreenStack.kt:325)
        at com.swmansion.rnscreens.ScreenStack.drawAndRelease(ScreenStack.kt:278)
        at com.swmansion.rnscreens.ScreenStack.dispatchDraw(ScreenStack.kt:295)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:226)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21350)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
        at android.view.View.draw(View.java:21621)
        at com.android.internal.policy.DecorView.draw(DecorView.java:964)
        at android.view.View.updateDisplayListIfDirty(View.java:20483)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3837)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3645)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2951)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1854)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8086)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
        at android.view.Choreographer.doCallbacks(Choreographer.java:875)
        at android.view.Choreographer.doFrame(Choreographer.java:776)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

## Platform

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.67.2       | 
| @react-navigation/native               | 6.0.8        |
| @react-navigation/native-stack         |  6.5.0       |
| react-native-screens                   |  3.11.0       |
| react-native-safe-area-context         | 3.3.2        |
| react-native-gesture-handler           | 2.2.0        |
| react-native-reanimated                | 2.4.1        |

**Comment by WoLewicki** [comment] 2022-02-16 10:59
Looks like a duplicate of https://github.com/software-mansion/react-native-screens/issues/1287 so I will close it. Feel free to comment here if I am wrong and we can reopen it then.

**Closed by WoLewicki** 2022-02-16 10:59 UTC
Labels: needs-more-info, 🤖android, 🧰needs-repro, needs-review
