### ISSUE TITLE
Modal + keyboard autoFocus (native stack) issues on iOS 14+

### ISSUE THREAD

**Issue by ferrannp** [software-mansion/react-native-screens#703] opened 2020-11-11 15:03 UTC
### Native modal stack + keyboard autoFocus. iOS 13 vs iOS 14

A native modal stack with a TextInput using `autoFocus`. 

Smooth in iOS 13 (no jumping) + handle keyboard when sliding:

![ios13-modal-keyboard](https://user-images.githubusercontent.com/774577/98827449-2eafb380-2437-11eb-91f2-a1c4e84b11c6.gif)

Not smooth on iOS 14 (jumping) + does not handle keyboard when sliding:

![ios14-modal-keyboard](https://user-images.githubusercontent.com/774577/98827461-31aaa400-2437-11eb-8a27-47cb72993298.gif)

### Bottom tabs - iOS 13 vs iOS 14

**SOLVED** (see comments)

On iOS 13 is respecting the bottom safe area:

![ios13-tabs](https://user-images.githubusercontent.com/774577/98827467-353e2b00-2437-11eb-9374-d2ed255527ca.png)

On iOS 14 is not:

![ios14-tabs](https://user-images.githubusercontent.com/774577/98827485-396a4880-2437-11eb-8667-46809732ec7c.png)

Not sure if the tabs issue is screens related.

## Package versions

```
"react": "^16.13.1",
"react-native": "0.63.3",
"react-native-screens": "2.14.0",
"@react-navigation/material-bottom-tabs": "^5.3.9",
"@react-navigation/native": "^5.8.9",
"@react-navigation/stack": "^5.12.6",
```

**Comment by Hirbod** [comment] 2020-11-15 05:36
Weird, I also have the same Issue with my bottom bar, but only in production mode

**Comment by Hirbod** [comment] 2020-11-15 08:34
I had the same issue, but it's not related to native-stack, its related to material-bottom-tabs.

Fix is easy

```
expo install react-native-safe-area-view@next react-native-safe-area-context@next
```
If you're not on expo, just make sure that you install them with yarn/npm and make sure to have v2 and not 1.1.1 of react-native-safe-area-view.

And add this to your package.json (below devDependencies on root level)

```
  "resolutions": {
    "react-native-safe-area-view": "^2.0.0"
  },
```

Restart your app, enjoy fixed app :)

**Comment by WoLewicki** [comment] 2020-11-16 09:10
@ferrannp can you check if @Hirbod's solution works? And if not, can you or @Hirbod provide a simple repo where I can test it?

**Comment by ferrannp** [comment] 2020-11-19 14:28
@Hirbod thanks for the hint! Yes, that solves the bottom tabs issue @WoLewicki. Looks like `react-native-paper` is using an old version of `react-native-safe-area-view`. I'll send a PR there.

So we can rename this issue just to be the modal one.

**Comment by Hirbod** [comment] 2020-11-22 20:33
I think you prob. should use a setTimeout and manually focus your input for now as a workaround. But indeed, this issue persists and my fix was only for the tab bar

**Comment by WoLewicki** [comment] 2021-01-27 10:59
Closing since after trying to reproduce the modal issue, it seems that it does not appear in isolation and may be caused by some misconfiguration. Feel free to comment here if you spot any issues regarding this.

**Closed by WoLewicki** 2021-01-27 10:59 UTC
Labels: iOS, native-stack, needs repro

**Comment by maxzinovev** [comment] 2021-08-21 00:20
@ferrannp i faced the same. Have you solved this problem?
