### ISSUE TITLE
xcode build failed

### ISSUE THREAD

**Issue by Staryixing** [software-mansion/react-native-screens#769] opened 2021-01-07 09:25 UTC
'React/RCTImageLoader.h' file not found

## Steps To Reproduce

1. npm install react-native-screens
2. cd ios pod install
3.  import { enableScreens } from 'react-native-screens'; enableScreens();

## Package versions

- React:16.8.6
- React Native: 0.60.5
- React Native Screens: 2.16.1

**Comment by WoLewicki** [comment] 2021-01-11 13:24
It is most probably duplicate of #415. I will close this issue then. Feel free to comment here if I am wrong.

**Closed by WoLewicki** 2021-01-11 13:24 UTC
