### ISSUE TITLE
Tablet orientation issue with createNativeStackNavigator 

### ISSUE THREAD

**Issue by xjuni0r87** [software-mansion/react-native-screens#1110] opened 2021-09-07 07:59 UTC
## Description

i use  createNativeStackNavigator from '@react-navigation/native-stack'
i force fix portrait orientation in orientation prop.
on Android emulator works fine, but on Android tablet emulator (Nexus 9 API 30) orientation is not locked

if i fix landscape orientation on a second screen
on Android emulator works fine, but on Android tablet emulator (Nexus 9 API 30) doesn't rotate automatically

```
const Stack = createNativeStackNavigator()

const LoginStack = () => (
  <Stack.Navigator>
    <Stack.Screen
      name="Login"
      component={LoginScreen}
      options={{
        orientation: 'portrait',
      }}
    />
    <Stack.Screen
      name="Second"
      component={SecondScreen}
      options={{
        orientation: 'landscape',
      }}
    />
  </Stack.Navigator>
)
```

- React: 17.0.1
- React Native: 0.64.2
- React Native Screens: 3.6.0

**Comment by WoLewicki** [comment] 2021-09-07 08:34
It is probably caused by how different orientations are interpreted by the system depending on what device you are using. You can check other `landscape` options from here: https://developer.android.com/reference/android/R.attr#screenOrientation and apply them there: https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/Screen.kt#L176. You can also check if https://docs.expo.dev/versions/latest/sdk/screen-orientation/ works correctly and report back. If these work the same, I am afraid there is nothing we can do about it.

**Comment by xjuni0r87** [comment] 2021-09-07 19:42
i've added all options from here: https://developer.android.com/reference/android/R.attr#screenOrientation in this file
https://github.com/software-mansion/react-native-screens/blob/2622254f9229b0a163f6c436ef206b1f85613d75/android/src/main/java/com/swmansion/rnscreens/Screen.kt#L176
and test them without success.
I also tried to install react-native-orientation-locker but it doesn't work.
Is it possible is only an android issue? i will try on other android tablets.

**Comment by WoLewicki** [comment] 2021-09-08 08:55
It might be a bug specific to this one device. Can we close this issue then? I am not sure if there is anything we can do in the library to help it unfortunately.

**Closed** 2021-09-08 10:01 UTC
