### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.

### ISSUE THREAD

**Issue by ganeshsek** [software-mansion/react-native-screens#2365] opened 2024-10-01 07:38 UTC
### Description

 ERROR  Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.

This error is located at:
    in RNSScreenStackHeaderConfig (created by HeaderConfig)
    in HeaderConfig (created by SceneView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous) (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes

### Steps to reproduce

I have tried to run this command for android in development 
Command : npx expo start

### Snack or a link to a repository

https://github.com/software-mansion/react-native-screens/discussions/2364

### Screens version

3.31.1

### React Native version

0.74.5

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2024-10-01 09:51
Hey @ganeshsek, this issue does not contain reproduction and is a duplicate of:

* https://github.com/software-mansion/react-native-screens/issues/2157
* https://github.com/software-mansion/react-native-screens/issues/1986
* https://github.com/software-mansion/react-native-screens/issues/1845

Usually fixing this boils down to removing node_modules, gradle caches and running `yarn install --force` again. 

I'll close this issue, since it is known and this report does not contain reproduction.

**Closed by kkafar** 2024-10-01 09:51 UTC
Labels: Platform: Android, Missing repro
