### ISSUE TITLE
Android Crash at com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow (prod only)

### ISSUE THREAD

**Issue by MelColmant** [software-mansion/react-native-screens#1241] opened 2021-12-20 13:54 UTC
## Description

The app crashes in production (can't reproduce in debug mode):

java.lang.IllegalArgumentException: 
  at androidx.fragment.app.FragmentStateManager.createView (FragmentStateManager.java:513)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:282)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:2189)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:2106)
  at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:2002)
  at androidx.fragment.app.FragmentManager.executePendingTransactions (FragmentManager.java:600)
  at com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow (ScreenContainer.java:289)
  at android.view.View.dispatchDetachedFromWindow (View.java:22071)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4755)
  at android.view.ViewGroup.removeAllViewsInLayout (ViewGroup.java:6606)
  at android.view.ViewGroup.removeAllViews (ViewGroup.java:6552)
  at com.facebook.react.views.view.ReactClippingViewManager.removeAllViews (ReactClippingViewManager.java:86)
  at com.facebook.react.views.view.ReactClippingViewManager.removeAllViews (ReactClippingViewManager.java:19)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView (NativeViewHierarchyManager.java:657)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView (NativeViewHierarchyManager.java:654)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView (NativeViewHierarchyManager.java:654)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView (NativeViewHierarchyManager.java:654)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView (NativeViewHierarchyManager.java:654)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren (NativeViewHierarchyManager.java:507)
  at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute (UIViewOperationQueue.java:211)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:908)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1019)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:47)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1079)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1008)
  at android.view.Choreographer.doCallbacks (Choreographer.java:809)
  at android.view.Choreographer.doFrame (Choreographer.java:740)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:995)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8633)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

90% of crashes occur in Android 11 (SDK30) 

## Platform

- [ ] iOS
- [ x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.64.2  |
| @react-navigation/native               |  6.0.2  |
| @react-navigation/stack         |  6.0.7  |
| react-native-screens                   |  3.5.0  |
| react-native-safe-area-context         |  3.3.0  |
| react-native-gesture-handler           |  1.10.1  |
| react-native-reanimated                |  2.2.3 |
| expo                                   |         |

**Comment by WoLewicki** [comment] 2021-12-20 14:11
Could you provide a minimal reproducible code example? Could be as an Expo Snack or just a code-snippet. It would be very helpful.

**Comment by MelColmant** [comment] 2021-12-20 15:34
Hi,

Thanks for the quick answer. As I said I am unable to reproduce the crash in debug mode but can with an apk build.

Here is where I believe the issue is in our code:
`
const content = useMemo(() => {
    const pairingFailed = error?.key === "pairingCheckFailed";

    if (isDemo && hasAppDashboardAccess)
      return <RootStack.Screen name="app" component={AppNavigator} />;
    if (
      (isDevicePaired == null && !pairingFailed) ||
      getTCDocumentStatus === "loading" ||
      customerLoading
    )
      // As we log the user out (state reset), we call the getIsPaired endpoint again (init calls)
      // the isDevicePaired is thus updated from null to boolean.
      // We use this state update to display the loading page and renew the navigation state.
      return <RootStack.Screen name="Init" component={Init} />;
    if (profile.status === "error")
      return (
        <RootStack.Screen name="Error">
          {() => <Error type="profileError" />}
        </RootStack.Screen>
      );
    if (tcDocument && termsAndConditionsDocumentValidationStatus !== "loaded")
      return (
        <RootStack.Screen
          name="TermsAndConditions"
          component={TermsAndConditions}
        />
      );
    if (hasAppDashboardAccess)
      return <RootStack.Screen name="app" component={AppNavigator} />;
    return <RootStack.Screen name="auth" component={AuthNavigator} />;
  }, [
    hasAppDashboardAccess,
    profile,
    termsAndConditionsDocumentValidationStatus,
    tcDocument,
    isDevicePaired,
    isDemo,
    getTCDocumentStatus,
    error,
    customerLoading,
  ]);

  return (
    <NavigationContainer ref={navigationRef}>
      <RootStack.Navigator
        initialRouteName="auth"
        screenOptions={{ animationEnabled: false, headerShown: false }}
      >
        {content}
      </RootStack.Navigator>
    </NavigationContainer>
  );
`

Moving from one RootStack.Screen to another is what I believe making the app crash.

**Comment by WoLewicki** [comment] 2021-12-20 16:22
We would need a simple repo with the simplified code in order to be able to reproduce the issue. Such snippet is not applicable anywhere unfortunately. Also, can you check if this happens with the newest version of `react-native-screens`?

**Comment by MelColmant** [comment] 2021-12-21 08:15
Hi,

I understand. For now updating to the newest version seems to have solved the issue. Thanks for suggesting it, I shall have thought about it.

I'll come back to you if the issue does persist. Again, thank you very much for the swift answers and suggestions.

Mel

**Comment by WoLewicki** [comment] 2021-12-21 11:58
Ok, so I will close this issue since it looks like the problem has been resolved. Feel free to comment here if it comes back and we can always reopen it then.

**Closed by WoLewicki** 2021-12-21 11:58 UTC
Labels: 🐞 Bug, 🧰needs-repro

**Comment by wcastand** [comment] 2023-10-16 12:40
getting this error since my last deployment on android on sentry.

will try to get as much info as i can:
seems to be all version of android and any kind of devices so probably not related.


only started happening since the last deployment.

this is the package.json changes:
react-native-screens went from `"~3.22.0",` to `"~3.22.1",`

If you need any other package version let me know happy to provide those (wanted to avoid a big screen of package.json diff)

this is the sentry error report: 

![Screenshot 2023-10-16 at 14 36 53](https://github.com/software-mansion/react-native-screens/assets/2178244/18eb9be5-4347-4c1d-9d44-6857f6e015c5)

from what i can see on almost all the error report, the crash seem to be reported after the user relaunch the app after a long time being asleep or when the phone have a OS wide change. screen on/off, low memory, NETWORK_CAPABILITIES_CHANGED, etc

not 100% sure it's linked to this but only reference i've seen of the same error.

**Comment by zeabdelkhalek** [comment] 2023-11-17 22:51
Same crash report as @wcastand in BugSnag. And I confirm that it happens when the user quit the app and come back after long time as the attached screenshot shows. react-native-screens version used is 3.18.2

![Uploading Screenshot 2023-11-17 at 11.50.43 PM.png…]()

**Comment by zeabdelkhalek** [comment] 2023-11-17 22:54
@wcastand were you be able to find any workaround about this?

**Comment by wcastand** [comment] 2023-11-18 01:36
No 😅 I just rebuilt my app for a new release and it looks like it's not there anymore or we don't catch it or we fixed it without realising it 😅

I'll try to ask my team about it just in case (in holiday right now )

**Comment by zeabdelkhalek** [comment] 2023-12-14 23:53
@wcastand Any update from your team about this one?

**Comment by wcastand** [comment] 2023-12-15 09:49
Hi, sorry forgot to update you, i asked and no idea either, i tried to check between the 2 release but can't pinpoint any reason why it stopped happening or why it was happening in the first place :/

sorry i can't help more :/
