### ISSUE TITLE
Large title: The navbar gets stuck when using the refresh control.

### ISSUE THREAD

**Issue by maxencehenneron** [software-mansion/react-native-screens#1034] opened 2021-08-03 13:16 UTC
## Description

When using a refreshcontrol, large titles and a scrollview, the navbar gets stuck when refreshing.

This seems to be related to this: https://stackoverflow.com/questions/50708081/prefer-large-titles-and-refreshcontrol-not-working-well.

It seems like the scrollview needs to be at the top of the main view for this to work correctly, which is currently not possible with this library

Other bugs I found:

- The large title initially appears in "collapsed" mode (maybe related to #649)
- The refresh control disappears

### Screenshots

https://user-images.githubusercontent.com/377682/128021240-d5f07c16-70ac-4640-8860-a999bcce3297.mp4

## Steps To Reproduce

1. Add a native stack container
2. Set "headerLargeTitle" to true in the screenOptions
3. Add a refresh control
4. Run the app, refresh.

### Expected behavior

It should snap back to its initial position

### Actual behavior

It gets stuck when refreshing stops.

## Snack or minimal code example

https://github.com/maxencehenneron/RefreshControlBug/blob/main/App.js
(You can pull the repository to test)

## Package versions

- React: 17.0.1
- React Native: 0.64.2
- React Native Screens: 3.4.0

**Comment by maxencehenneron** [comment] 2021-08-03 14:08
I found a fix for this but it's dirty: 

In RNScreen.m, add the following in the viewDidLayoutSubviews function:

```objective-c
UIViewController *parentVC = [self parentViewController];
if ([parentVC isKindOfClass:[UINavigationController class]]) {
  [((UINavigationController *)parentVC).navigationBar sizeToFit];
}
```

This ensures the navigation bar re-renders when the screen updates... Any thoughts?
Final result:

https://user-images.githubusercontent.com/377682/128029826-b0cc9ba1-958f-49c3-9484-c5cebcf38d15.mp4

**Comment by WoLewicki** [comment] 2021-08-04 09:23
Is it a duplicate of https://github.com/software-mansion/react-native-screens/issues/395 ?

**Comment by WoLewicki** [comment] 2021-08-09 08:26
In your repro you did not provide `contentInsetAdjustmentBehavior=“automatic”` on the `ScrollView`, but on the `RefreshControl` and there is no `headerTranslucent: true` option on the stack. These settings are necessary for this to work with the `ScrollView` as mentioned in https://github.com/software-mansion/react-native-screens/issues/395#issuecomment-674043236. After applying them, the repro seems to work correctly. Can you confirm that?

**Comment by maxencehenneron** [comment] 2021-08-17 08:40
Hi @WoLewicki, sorry I was on vacation last week. It does seem to work when setting the header to translucent. However it makes the header, well, translucent. I can set the header color to white to fix it, but maybe it's worth investigating why this is happening?

**Comment by WoLewicki** [comment] 2021-08-17 09:31
I think since the `translucent` header is the default option in native apps, maybe we should make the header `translucent` by default on iOS. I am also not sure what you would want to achieve. If you want the `refreshControl` to appear in the area of the header, it seems reasonable that this area is available for laying anything underneath it. Can you elaborate more on it?

**Comment by maxencehenneron** [comment] 2021-08-17 11:44
Yes, I agree, translucent should be set to TRUE by default, especially when using large titles. 
I'm able to achieve what I want to do by setting translucent to true and the header background color to white.

My comment was about these lines in the library source code:

https://github.com/software-mansion/react-native-screens/blob/e02172a08b694bd9a8baf7e94c21124b195bd268/ios/RNSScreenStackHeaderConfig.m#L436-L443

I was wondering if we could make it work without needing to set translucent to true

**Comment by WoLewicki** [comment] 2021-08-17 15:30
I think it might be good to change it to be set `vc.edgesForExtendedLayout = UIRectEdgeAll;` by default when you have large title, and change it to `UIRectEdgeNone` when `headerTranslucent` is explicitly set to `false`. We are always open to PRs if you would like to do it.

**Comment by WoLewicki** [comment] 2021-09-10 09:45
I will close this issue since I think there is nothing to be added here. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2021-09-10 09:45 UTC
