### ISSUE TITLE
iOS back button/menu title always is "back" when headerShown is false

### ISSUE THREAD

**Issue by h-five-e** [software-mansion/react-native-screens#1864] opened 2023-08-09 10:08 UTC
### Description

If you have a stack of screens, the back button and the back button menu show the title of the previous screen, except when the header of the previous screen is not shown, in which case the shown title will revert to "back" (or localised equivalent).

For example:
```
<Stack.Navigator>
  <Stack.Screen name="screenA" component={ScreenA} options={{headerTitle: 'screen a title', headerShown: false}}/>
  <Stack.Screen name="screenB" component={ScreenB} options={{headerTitle: 'screen b title'}}/>
  <Stack.Screen name="screenC" component={ScreenC} options={{headerTitle: 'screen c title', headerShown: false}} />
  <Stack.Screen name="screenD" component={ScreenD} options={{headerTitle: 'screen d title'}} />
  <Stack.Screen name="screenE" component={ScreenE} options={{headerTitle: 'screen e title'}} />
</Stack.Navigator>
```
The names of `screenA` and `screenC` will be `back` where as the others will show `screen x title`. I expect this to be `screen x title` for all screens, regardless of whether or not the header has been shown.

<img width="300" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/9553994/bcdec3d5-c31a-4ab4-8d79-a54151fde7ea"> <img width="300" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/9553994/ba962ec4-38b5-4685-b362-ba699cbcf582">

I have provided a snack. I am not quite familiar with Expo and Snacks and the versions differ a little from my app (for example I am using react native 0.71.7 and react-native-screens 3.24 locally, which are newer) but it has the same issue on the newer versions.

### Steps to reproduce

1. Create a navigator with a screen where the option `headerShown` is `false` and another screen to navigate to from there
2. Navigate to the second screen, note the back button/menu

### Snack or a link to a repository

https://snack.expo.dev/@hanneke/navigation-ios-back-name-not-properly-set-repro

### Screens version

3.20.0

### React Native version

0.71.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

iPhone 11 16.5.1

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2023-08-09 15:45
Thanks for reporting, I can confirm the issue, will look into it.

**Comment by kkafar** [comment] 2023-08-09 16:41
Hey @h-five-e,

would you mind trying fix from #1866?
I haven't tested it exhaustively yet, but it looks like it should work fine.

To test the fix you can install screens directly from branch in your `package.json`:

```json
"react-native-screens": "software-mansion/react-native-screens#@kkafar/bad-text-on-back-button"
```

**Comment by h-five-e** [comment] 2023-08-10 10:31
Oh wow, that's really quick! That does indeed fix it 🙏🏻  thank you!

I do run into a semi-related issue. If, say, screen C uses a `headerBackTitle` that is also what gets pushed onto the menu as the name for screen B, instead of screen B's `headerTitle`. A cursory scan does not reveal related issues, should I create one (if there indeed isn't one) or is this expected behaviour?

**Comment by kkafar** [comment] 2023-08-10 10:54
> I do run into a semi-related issue. If, say, screen C uses a headerBackTitle that is also what gets pushed onto the menu as the name for screen B, instead of screen B's headerTitle. A cursory scan does not reveal related issues, should I create one (if there indeed isn't one) or is this expected behaviour?

I do not consider it a bug. IIRC `headerBackTitle` defaults to header / route title. When it is set it overrides it & IMO the name next to back button & name in the back button context menu should be consistent.

**Comment by h-five-e** [comment] 2023-08-10 11:17
Cool, thanks for the feedback. We use it to provide a "back" text in cases where the title is a bit long (related to https://github.com/software-mansion/react-native-screens/issues/1589), so we're keeping our fingers crossed on a fix there although that seems a little more involved 😅.

Anyway this particular issue seems to be resolved, thank you ☺️.

**Comment by kkafar** [comment] 2023-08-10 12:15
It looks like #1589 was already fixed in native stack v6 `@react-navigation/native-stack` here:

* https://github.com/react-navigation/react-navigation/pull/10844

Does this still happen there? 

My follow up question would be: do you import `createNativeStackNavigator` from `@react-navigation/native-stack` or `react-native-screens/native-stack`?

**Comment by h-five-e** [comment] 2023-08-10 14:15
I did a quick check, I'm using `"@react-navigation/native-stack": "6.9.13"`, from which I import `createNativeStackNavigator`.

I cannot check back in until Monday, if necessary I can work on a repro then/Tuesday (and open a new report).

I hope you have an enjoyable weekend!
-H

**Comment by kkafar** [comment] 2023-08-11 06:32
So according to react-navigation/react-navigation#10844 that issue should be fixed. In case it is still present - let me know.

**Closed** 2023-08-11 10:57 UTC
Labels: Bug, Platform: iOS, Repro provided

**Comment by h-five-e** [comment] 2023-08-15 09:49
It seems to be a regression in `react-native-screens` at least in our production app; it's fine in 3.20 but not in 3.22/3.24. I'll provide a repro later (and stop discussing it here).
