### ISSUE TITLE
Crash on Android when setting route params

### ISSUE THREAD

**Issue by tboerc** [software-mansion/react-native-screens#428] opened 2020-03-20 14:20 UTC
I'm using the last version avaliable of **react-native-screens** (2.3.0) with **react-navigation** (5.0.3), and in one of my screens, I set it params after refreshing the data from database, and if the database returns an empty array, which is a normal behavior, the app just crash. This only happens on newer versions of Android (tested on 6.0, 8.1 and only 9.0 is crashing). Somehow, if I disable react-native-screens the problem goes away, so the problem is with this package.

The params that I set when the refresh is done is just a boolean variable, so don't know why this would make the app crash. And the crash just closes the app, so it doesn't give any information, I could try to see the logcat to give more info about.

**Comment by kmagiera** [comment] 2020-03-25 14:21
Thanks @tboerc for reporting but I am afraid that this description is hardly actionable for us. Happy to look more into the crash but would need to get a small reproducable demo. It appears like you can reproduce the crash locally so maybe try to comment out fragments of the app that are not relevant for the crash to happen and build up that small example this way. Thanks!

**Comment by luizfonseca** [comment] 2020-03-31 07:57
I am having a similar issue with Android; I cannot use the native stack to open any screens when setting params or the format `{ screen: 'ScreenName', params: { something... } }`

I will setup a example app to showcase the issue

**Comment by Hirbod** [comment] 2020-04-03 16:32
> I am having a similar issue with Android; I cannot use the native stack to open any screens when setting params/ using the format `{ screen: 'ScreenName', params: { something... } }`
> 
> I will setup a example app to showcase the issue.
> 
> PS.: The app doesn't "crash" for me, it just doesn't open the screen. It tries to open it and immediately closes.

That screen params only works when you try to open a Screen which is nested inside another stack.

**Comment by WoLewicki** [comment] 2020-05-29 11:35
@luizfonseca were you able to reproduce the issue? Or can I close it?

**Comment by WoLewicki** [comment] 2020-06-29 15:24
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Closed by WoLewicki** 2020-06-29 15:24 UTC
Labels: bug, needs more info
