### ISSUE TITLE
Build fails on iOS - Undefined symbols for architecture

### ISSUE THREAD

**Issue by alexisbronchart** [software-mansion/react-native-screens#887] opened 2021-04-12 13:45 UTC
## Description
After I upgraded to version 3.1.0 I started having this build error (I was on 2.17.1 before):
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTImageLoader", referenced from:
      objc-class-ref in RNSScreenStackHeaderConfig.o
```
This happens when I build for the simulator. The same error for architecture arm64 happens when I build for a device /  in release mode. I'm only using react-native-screens as a dependency of react-navigation.
The issue goes away if I downgrade to 2.17.1 without changing anything else. However it comes back as from version **2.18.0**

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Screens: 3.1.0

**Comment by WoLewicki** [comment] 2021-04-13 10:40
I believe it is duplicate of #842 so I will close it. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2021-04-13 10:40 UTC
