### ISSUE TITLE
[native-stack] Large title scrolls completely wrong

### ISSUE THREAD

**Issue by iDuuck** [software-mansion/react-native-screens#320] opened 2020-02-11 05:58 UTC
Hey guys, I wanted to implement React-Navigation v5 into my project, but now found an issue, which is very huge. I also found some bugs regarding this one.

**Referenced here:**
- https://stackoverflow.com/questions/48039046/ios-11-large-title-navigation-bar-snaps-instead-of-smooth-transition
- https://stackoverflow.com/questions/47649375/ios-11-large-navigation-bar-title-unexpected-velocity

I think both questions on SO have described the issue properly, so I don't need to redescribe here, but yeah. I have this issue right now.

**Comment by iDuuck** [comment] 2020-02-11 05:58
Related: https://github.com/react-navigation/react-navigation/issues/6754

**Comment by iDuuck** [comment] 2020-03-06 13:56
Wow, still no update?

**Comment by WoLewicki** [comment] 2020-08-07 11:23
You should use `headerTranslucent: true` and `contentInsetAdjustmentBehavior` prop set to "automatic" on your `ScrollView` component. Setting it should make the `ScrollView` with `largeHeader` behave the way it was designed by Apple. Does it solve your issue?

**Comment by WoLewicki** [comment] 2020-08-20 12:42
I am closing this issue since it should be resolved. Feel free to comment if something is wrong.

**Closed by WoLewicki** 2020-08-20 12:42 UTC
Labels: bug, iOS, native-stack, scrollView

**Comment by zachgibson** [comment] 2020-10-28 22:27
https://github.com/software-mansion/react-native-screens/issues/320#issuecomment-670469660 fixed it for me.

**Comment by Evan-Younan** [comment] 2021-06-21 00:22
@WoLewicki Does this actually work properly with a FlatList? It works fine with a ScrollView but as soon as I introduce a FlatList, it does not scroll to the top properly.

**Comment by WoLewicki** [comment] 2021-06-21 09:25
@Evan-Younan provide a reproduction where it does not work for you so we can elaborate on it.

**Comment by guiccbr** [comment] 2021-08-20 13:52
Did anyone notice that if `bounces={false}` the large header never gets back after being collapsed for the first time? This should be easy to reproduce in the latest versions of the libs.
