### ISSUE TITLE
ANR in rns

### ISSUE THREAD

**Issue by heroic** [software-mansion/react-native-screens#935] opened 2021-05-12 11:35 UTC
## Description

App is throwing an ANR due to React Native Screens

```
ANR:  Input dispatching timed out (in.galaxycard.android/in.galaxycard.android.MainActivity, Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 1.)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:179)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:184)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:184)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:184)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:184)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:184)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:184)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:184)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:184)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:184)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:184)
        at com.swmansion.rnscreens.Screen.hasWebView(Screen.java:184)
        at com.swmansion.rnscreens.Screen.setTransitioning(Screen.java:171)
        at com.swmansion.rnscreens.ScreenContainer.performUpdate(ScreenContainer.java:382)
        at com.swmansion.rnscreens.ScreenContainer.onUpdate(ScreenContainer.java:339)
        at com.swmansion.rnscreens.ScreenContainer.updateIfNeeded(ScreenContainer.java:325)
        at com.swmansion.rnscreens.ScreenContainer.access$000(ScreenContainer.java:24)
        at com.swmansion.rnscreens.ScreenContainer$1.doFrame(ScreenContainer.java:40)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:688)
        at android.view.Choreographer.doFrame(Choreographer.java:620)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

### Expected behavior

Should not cause ANR

### Actual behavior

Causes ANR

## Package versions

- React: 16.13.1
- React Native:0.63.4
- React Native Screens:3.1.0

**Comment by kacperkapusciak** [comment] 2021-05-12 12:35
Can you please provide a reproducible code sample in which this error occurs?

**Comment by heroic** [comment] 2021-05-12 14:03
@kacperkapusciak This occurred in production, we haven't been able to replicate this on our dev instance yet.

**Comment by jsamr** [comment] 2021-05-19 11:43
We've also experienced Android ANR on a regular basis in production after re-enabling screens (`enableScreens(true)`).

**Comment by kacperkapusciak** [comment] 2021-05-25 12:13
@jsamr 
Are your call stacks the same as in the issue?
We need all the information we can get because [this method](https://github.com/software-mansion/react-native-screens/blob/3.1.0/android/src/main/java/com/swmansion/rnscreens/Screen.java#L178) literally just traverses the children so it shouldn't trigger an ANR on its own.

**Comment by Sebastian-Jedrocha** [comment] 2021-06-21 20:10
We experience the same issue. Any ideas on how to solve it?

**Comment by WoLewicki** [comment] 2021-06-23 08:59
@Sebastian-Jedrocha provide a minimal reproduction of the crash so we can work on it. Otherwise we cannot say much.

**Comment by kacperkapusciak** [comment] 2021-08-03 08:38
Closing due to not providing a reproduction in more than 30 days.

**Closed by kacperkapusciak** 2021-08-03 08:38 UTC
