### ISSUE TITLE
Should initialRouteName preserve stack?

### ISSUE THREAD

**Issue by spacesuitdiver** [software-mansion/react-native-screens#659] opened 2020-10-07 20:36 UTC
```
        <Stack.Navigator
            screenOptions={{
                headerShown: false,
                intialRouteName: 'HomeScreen',
            }}
        >
            <Stack.Screen name="HomeScreen" component={HomeScreen} />
            <Stack.Screen name="AuthenticationScreen" component={AuthenticationScreen} />
        </Stack.Navigator>
```

I am noticing that popping `AuthenticationScreen` off in this style stack leads to the transition presenting `HomeScreen` despite it's ordering in the component tree. I assume this is just because it's not explicitly pushed onto the stack and maybe is expected behavior?

**Comment by WoLewicki** [comment] 2020-10-12 08:54
Can you be more precise about what is the issue? Is it something specific to `native-stack`?

**Comment by WoLewicki** [comment] 2020-10-20 07:53
You can read about `initialRouteName` here: https://reactnavigation.org/docs/stack-navigator/#initialroutename. If you want the `initialRouteName` screen to be always loaded when going to a navigator, you can use `initial: false` (see https://reactnavigation.org/docs/nesting-navigators#rendering-initial-route-defined-in-the-navigator). 
It seems that the issue is not connected specifically to the library, but rather to how React Navigation works, I am closing this issue then. Feel free to comment if I am wrong and I can reopen it then.

**Closed by WoLewicki** 2020-10-20 07:53 UTC
Labels: needs more info
