### ISSUE TITLE
App is getting very slow and crashes on iPhone 12, 12 ProMax

### ISSUE THREAD

**Issue by Achilles0509** [software-mansion/react-native-screens#897] opened 2021-04-21 09:24 UTC
Recently I updated react-native-screens version from 2.10.1 to 2.18.1
After update App is getting very slow and crashes on iPhone X+ i.e iPhone XR, 12, 12 ProMax etc.
Especially but appeared well in production mode.

I didn't make test on Android.

I use react-native-screens with react-navigation v5.
I'm not sure the reason.

**Comment by kacperkapusciak** [comment] 2021-04-21 09:47
Hi @Achilles0509,
1. Please don't ignore the issue template. It serves its purpose.
2. Your description is very vague and we have no way of knowing what your app consists of. Please provide a reproduction example - see [this guide](https://stackoverflow.com/help/minimal-reproducible-example).
3. If it crashes, please provide us with crash messages and exact steps on how to reproduce them (see point 2).

We would love to help you but first, you need to help us to understand what exactly is wrong.

**Comment by Achilles0509** [comment] 2021-04-21 12:49
There is not any crash message.
I tried to catch crash using Sentry, but crash is not cached with Sentry, it's strange.

**Comment by kacperkapusciak** [comment] 2021-04-22 07:28
Higher CPU usage during transition is something you rather expect to happen.
I'll close the issue for now because the provided description doesn't provide any information other than your application is slow and you don't know why. If you have any useful information from an engineering point of view feel free to comment down below and I'll reopen the issue.
Cheers

**Closed by kacperkapusciak** 2021-04-22 07:28 UTC
Labels: needs more info, needs repro
