### ISSUE TITLE
Issue with reanimated Transition on Android

### ISSUE THREAD

**Issue by Freddy03h** [software-mansion/react-native-screens#203] opened 2019-10-25 18:13 UTC
Regarding https://github.com/kmagiera/react-native-reanimated/issues/304 there is an issue about using a Reanimated `<Transition>` on Android, inside a `react-navigation-stack` while using `useScreens()`.

Reproductible demo with Expo v35 : https://snack.expo.io/@freddy03h/issue-transition-inside-navigation

I experiencing the issue also on a normal react-native project with those dependencies :
```
   "react-native": "0.61.2",
    "react-native-gesture-handler": "1.4.1",
    "react-native-reanimated": "1.3.0",
    "react-native-screens": "2.0.0-alpha.6",
    "react-navigation": "4.0.10",
```

**Comment by brunocrpontes** [comment] 2019-10-25 18:37
Screens v2 isn't implemented in Expo yet! Use v1 instead.

**Comment by Freddy03h** [comment] 2019-10-26 10:16
So it mean the issue exist with Screens v1 (in expo) and Screens v2 (in a normal react-native updated project)

**Comment by brunocrpontes** [comment] 2019-10-26 12:49
Did you follow fully native setup? Editing app/build.gradle?

**Comment by Freddy03h** [comment] 2019-10-26 13:06
I answered you in this comment: https://github.com/kmagiera/react-native-reanimated/issues/304#issuecomment-546600631

Maybe it's an issue from configuration, I don't know, but the issue only appear inside a StackNavigator with `useScreens`/`enableScreens`. Otherwise it work well!

But I don't think it's an issue from setup configuration because I can reproduce it on an Expo application (So, even if it's not the same dependencies list, because the issue is exactly the same, can be reproduced exactly the same way, I think it's the same issue)

**Comment by James-E-Adams** [comment] 2019-10-28 03:42
I'm experiencing something similar within a `stackNavigator` - calling `useScreens` causes a button not to work on Android (I think it's within a Transition). I haven't worked out the exact root cause but commenting out the call to `useScreens()` fixes it.

**Comment by WoLewicki** [comment] 2020-04-01 11:55
Does the issue still exist in the newest versions of the libraries? @Freddy03h

**Comment by Freddy03h** [comment] 2020-04-01 12:09
I need to re-test it! I removed `enableScreens()` on my production app due to too much crash reported by Android vitals on google play console at this time and haven't re-enable it since.

Thank you for the follow up of the issue!

**Comment by WoLewicki** [comment] 2020-06-08 18:04
Did you manage to do it @Freddy03h ?

**Comment by Freddy03h** [comment] 2020-06-08 22:21
Hi! Sorry for the delay, I tried the example from my snack example with this config on a new initiated react-native project and now everything work fine :
```
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/native": "5.5.1",
    "@react-navigation/stack": "5.5.1",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "1.6.1",
    "react-native-reanimated": "1.9.0",
    "react-native-safe-area-context": "3.0.2",
    "react-native-screens": "2.8.0"
```

**Comment by WoLewicki** [comment] 2020-06-09 07:19
Ok so I am closing this issue. Feel free to comment if there is something wrong.

**Closed by WoLewicki** 2020-06-09 07:19 UTC

**Comment by Sin-** [comment] 2020-09-24 13:31
Hello! 
This issue is still present, no transitions working on Android.
Config:
```
"@react-navigation/bottom-tabs": "^5.8.0",
"@react-navigation/native": "^5.7.2",
"@react-navigation/stack": "^5.8.0",
"react-native-safe-area-context": "^3.1.1",
"react-native-screens": "^2.9.0",
"@react-native-community/masked-view": "^0.1.10",
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-gesture-handler": "^1.7.0",
"react-native-reanimated": "^1.10.1",
```

**Comment by WoLewicki** [comment] 2020-09-29 14:54
I am afraid I cannot help you much with this issue. Can you provide a repo that shows the problem though? Maybe someone will be able to help you with this.
