### ISSUE TITLE
Scrollview not working when fullScreenSwipeEnabled is enabled (ios)

### ISSUE THREAD

**Issue by chazzaoui** [software-mansion/react-native-screens#1511] opened 2022-07-04 23:17 UTC
### Screenshots

https://user-images.githubusercontent.com/22476835/177224391-ab70208f-bab4-4397-a4e2-45af9e986f65.mov

## Steps To Reproduce
Somehow in my latest development build, I cannot scroll anymore within a screen where full-screen gesture is enabled. Scroll only works when this is false. Not sure what is causing this
1.

### Expected behavior
Being able to scroll in a screen where fullscreengesture is enabled

### Actual behavior
Not being able to scroll when fullscreengesture is enabled.
## Platform

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Architecture

- [X] Paper
- [ ] Fabric

## Workflow

- [ ] Managed workflow
- [X] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |   0.68.2      |
| @react-navigation/native               |   5.7.1      |
| react-native-screens                   |     3.14.1    |
| react-native-safe-area-context         |   3.1.1      |
| react-native-gesture-handler           |   1.6.1      |
| react-native-reanimated                |   2.2.3      |

**Comment by kkafar** [comment] 2022-07-05 06:36
Closing this issue as it is duplicate of https://github.com/software-mansion/react-native-screens/issues/1510. Thank you for reporting. Diving onto the problem.

**Closed by kkafar** 2022-07-05 06:36 UTC
Labels: needs-more-info, 🍎iOS, 🧰needs-repro, needs-review
