### ISSUE TITLE
Display any view on top of native-stack's modal

### ISSUE THREAD

**Issue by Strate** [software-mansion/react-native-screens#525] opened 2020-05-26 08:58 UTC
Hello, thank you for this awesome library.

Is there any possible solution to display any view on top of visible stack's modal?

I realized, that react-native-modal is not visible over stack's modal, and also there is no way to display any view on top of screen. For example, I need to display in-app-notification on top of all content, or sometime display modal loader spinner - both of them are not appears when stack's modal is visible.

This is related to ios only, android works fine.

**Comment by friedolinfoerder** [comment] 2020-05-26 12:27
Same issue here. iOS issue only.

**Comment by arberK** [comment] 2020-05-26 14:29
same issue

**Comment by Hirbod** [comment] 2020-05-27 01:51
This issue is known and also reported by me. You can't even toggle the element inspector on the modal. They managed to get EXPOs Dev Menu finally to overlay the modal, but not sure about any other view. The modal is currently the most top element that nothing can overlap. I also had issues with in-app-notifications and worked around displaying them inside the modal when modal was open - but yeah, there should be another method for it. Maybe we need to wrap a provider for that modal and let it mount there or something - dunno if thats even possible, just thinking

**Comment by Strate** [comment] 2020-05-27 09:40
@Hirbod how Modal from react-native can overlap? I've tested it for a while, but modal just invisible and dismisses almost right after mounted.

**Comment by Hirbod** [comment] 2020-05-27 09:45
@Strate https://streamable.com/mtsbmh here, from my app

**Comment by Strate** [comment] 2020-05-27 09:48
@Hirbod wow, awesome! This is looks like Shared Element Transition, but with Modal?

**Comment by Hirbod** [comment] 2020-05-27 09:49
Yes, tooked me a crazy amount of time and is not smooth on android :D
But it works mit react-native modal in a react-native-screens modal :D

**Comment by Strate** [comment] 2020-05-27 13:18
@Hirbod could you please share some code for Modal from react-native? Which presentation used for display over screen's modal? Because my modal still invisible :(

**Comment by Hirbod** [comment] 2020-06-02 15:01
@Strate its nothing special.

```tsx
      <Modal
        transparent
        visible={fullscreen}
        onShow={this.handleModalShow}
        onRequestClose={this.close}
      />
```

**Comment by a-eid** [comment] 2020-08-03 12:15
I've the same issue, I'm trying to display a loader but can't draw over the 'formsheet' modal.

```jsx
<>
  <NavigationContainer>
    <Stack.Navigator screenOptions={{ stackPresentation: 'formSheet' }} .... >
  </NavigationContainer> 
  <View style={{
   ...Stylesheet.absoluteFillObject,
   zIndex: 1000, 
   backgroundColor: 'rgba(0,0,0,0.4)'
  }}/> /* <<< */
</>
```

**Comment by WoLewicki** [comment] 2020-08-26 15:12
Can you provide a repo with the thing you want to achieve so I could work on it?

**Comment by a-eid** [comment] 2020-08-26 15:54
Hi @WoLewicki 
this repo explains the issue ( at least the one I'm having.) 

https://github.com/a-eid/react-native-native-stack-global-loader

you can see that when we have a `formSheet` screen the loader is behind the screen unlike the normal screen. please let me know if you need more context.

I wan't to do another example for toast but it basically is the same idea.

thank you.

**Comment by a-eid** [comment] 2020-08-26 23:04
it's also worth noting that this happens also with other modals.

**Comment by Abhishek12345679** [comment] 2020-08-27 01:59
also a modal screen (using stackPresentation:modal) does not pop up over a [react-native-modal](https://github.com/react-native-community/react-native-modal)'s modal component.

**Comment by WoLewicki** [comment] 2020-08-27 11:55
@a-eid regarding your example: the loader will not load above the modal this way since all the views displayed under the root view of the application will be displayed also under the modal screens. You can spot the same thing while using `Modal` component from `react-native`. It is like so because of the native view hierarchy of iOS. Roots of the modals are above the react's root view, so the only way to display something above the modal is to either display it in that modal, or display another modal on the previous modal. In particular, for your example, the flow can be changed somehow like that: 
```js
<Stack.Screen
            name="modal-screen"
            options={{
              stackPresentation: 'formSheet',
            }}>
            {() => (
              <GlobalLoader>
                <ModalScreen />
              </GlobalLoader>
            )}
</Stack.Screen>
```
Then the `GlobalLoader` component is under the modal screen in the view hierarchy and is displayed on the modal component.

Another option, maybe even better, is to make the `GlobalLoader` a `Screen` of the stack and call navigation to it when triggered and `goBack` when removing it. In order for it to be displayed on the whole screen, you can use `stackPresentation: 'transparentModal'` which will give you an option to make the component semi-transparent. Does it solve your issue?

@Abhishek12345679 yes, because it messes with the modal stack of `native-stack` and is not permitted in `react-native-screens` since they both use view controllers.

**Comment by a-eid** [comment] 2020-08-27 13:32
@WoLewicki thank you for the reply.

I'm wondering how would you display toasts on a 'formSheet' screens ?

**Comment by WoLewicki** [comment] 2020-08-27 14:20
About the first question, what is the difference of having `formSheet` screens for displaying toasts? I think the approach should be the same, the `Toast` should be a child of the `Screen` component in order to be visible over the modal screen. You probably cannot use `transparentModal` then because it disables touches on the screens under it.

About the second question, I am not sure what you mean. If you mean to control the transition of the modal appearing then no, since it is controlled by a native `UINavigationController`.

**Comment by a-eid** [comment] 2020-08-27 14:26
global toasts are great when you have a background task ( socket connection or even an api request ). and you wanna notify the user when the task is finish ( success | error ). there is no way to find out where the user is on the app. 

global toasts & loaders have a single mount point which is really great for those cases and convenient for almost all other cases.

I'm not really that familiar with IOS but do u think there is a way to do that on ios Natively ?

**Comment by WoLewicki** [comment] 2020-08-31 12:58
You can read more about how certain interactions with user on iOS should be implemented in Apple's HIG. You can look at e.g. [Alert Views](https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/) and then look for libraries in react-native that implement those things. Also, I think it is just not possible to have the listener for such events in one place only when trying to use native iOS modal views since they simply aren't children of `RCTRootView`. Can I help you more with it?

**Comment by a-eid** [comment] 2020-08-31 13:26
@WoLewicki thank you very much, I'll be reading more about it.

**Comment by WoLewicki** [comment] 2020-09-01 12:10
Can I close this issue then? @Strate do you any more information?

**Comment by Strate** [comment] 2020-09-02 07:09
@WoLewicki looks like there is still no solution to display *any* view on top of modal ^(

**Comment by WoLewicki** [comment] 2020-09-02 13:56
@Strate you can do it as long as you are displaying it in the `Screen`, in which the modal is located or use another modal screen to display it.

**Comment by Strate** [comment] 2020-09-03 07:43
@WoLewicki thats okay for alerts, for example, but not great for toasts :(

This is how toasts looks like when rendered inside Screen which displayed in modal:
![image](https://user-images.githubusercontent.com/392644/92086008-42ed8980-edd2-11ea-99bb-9070e81ea96c.png)

**Comment by a-eid** [comment] 2020-10-15 08:59
@WoLewicki I'm wondering how RN `perf monitor` works, could we display a `toast` the same way that the `perf monitor` is being displayed ?

**Comment by WoLewicki** [comment] 2020-10-19 10:47
@a-eid I think it is just a `View` that shows on the screen. You can see that enabling it on one screen and then going to a modal screen makes it stay on the background screen.

**Comment by a-eid** [comment] 2020-10-19 11:49
@WoLewicki yes, however if you enable it on a `formsheet modal` and then dismiss it it stays in place as if it's not part of that screen. ( somehow mounted at the top of the tree . ).

**Comment by WoLewicki** [comment] 2020-10-19 12:14
Yes, it is directly under the `UIWindow`. But the modal is on the same level in the view hierarchy. That's why it is visible after dismissing the modal but goes under after going to another modal since that modal is displayed as the most visible subview of the window. You can use your own component that will add a subview to the `UIWindow` and I think it will behave the same. You can check it by displaying View Hierarchy in Xcode.

**Comment by sslash** [comment] 2020-12-09 15:03
I'm having the same issue. I can append my view to UIWindow on the native side, and it will appear on top. But the problem is that I have a ViewController with IBActions etc, and afaik you can't append a ViewController to UIWindow (?). Or do you know if there's another way to natively append a ViewController to the `UINavigationController` (ie the modal) ?

**Comment by Strate** [comment] 2020-12-10 09:13
@WoLewicki thank you for suggestion!
Do you have any idea how to implement this thing: "You can use your own component that will add a subview to the UIWindow"? Sounds very easy, but very hard for non-iOS developer :(

**Comment by WoLewicki** [comment] 2021-04-26 14:29
Here is the code which adds the monitor to the `UIWindow`: https://github.com/facebook/react-native/blob/dc80b2dcb52fadec6a573a9dd1824393f8c29fdc/React/CoreModules/RCTPerfMonitor.mm#L336. I think you can make your own native module, which will make a native view and add it straight under the `UIWindow`. I may add such thing in a free moment and I will post it here then.

**Comment by a-eid** [comment] 2021-04-26 14:33
@WoLewicki that would be awesome, thank you.

**Comment by WoLewicki** [comment] 2021-04-27 15:07
I added a PoC package where you can render a `View` under the `UIWindow`. You can try and play with it: https://github.com/WoLewicki/react-native-window-view.

**Comment by a-eid** [comment] 2021-04-27 18:54
@WoLewicki I'm testing it rn, do you think you'll keep it as a seperate package or will you be adding it to `react-native-screens` ?

**Comment by a-eid** [comment] 2021-04-27 22:37
![overlay ](https://user-images.githubusercontent.com/19273413/116321197-e5230d00-a7b9-11eb-9379-64b7aaec9ba4.gif)

**Comment by WoLewicki** [comment] 2021-04-28 10:05
> do you think you'll keep it as a separate package or will you be adding it to react-native-screens ?

I think it will now be a separate package since `react-native-screens` is library connected to navigation and this component has nothing to do with it. It may change in the future though.

> it's only draggable, it doesn't allow touches, do u think I can try and fix it ?

I fixed it in `0.3.0`. I also added option to make it non-draggable with `draggable` prop.

> The modal does display on top of `RNWindowView`.
> if the `RNWindowView` is displayed last it always comes on top thou

Yes, because the modal and `RNNWindowView` are both attached to the `UIWindow`, so their visibility is determined by their attaching order, just like you saw here: https://github.com/software-mansion/react-native-screens/issues/525#issuecomment-712102972. For now what you can do is detect when the modal is being pushed and do a hide-show sequence when it comes up, something similar to what you posted above. I also added another option to make the view always visible by subscribing to subview updates of the `UIWindow` in your `AppDelegate.m` (see changes here: https://github.com/WoLewicki/react-native-window-view/commit/1cf924eec9c41354bf76345247373c42a168eb6b#diff-572a1fa43eaec8dc052d345a050635916f8bdeb379f1ab00367368dffa947e45R14)

**Comment by a-eid** [comment] 2021-04-28 21:04
@WoLewicki touchables work inside of the `windowView` now, great work thank you.

**Comment by nandorojo** [comment] 2021-05-23 15:51
I'm a bit new to this thread, and I'm not exactly sure how the iOS Window works. 

@WoLewicki does the package you linked to solve the problem of rendering toasts on top of any modal? I have some UI providers (bottom sheet menu, toast notifications) at the root of my app, and I'd like them to render on top of any content.

**Comment by a-eid** [comment] 2021-05-23 16:23
@nandorojo the package work similar to `Perf Monitor` window, which does display in front on any modal as long as it was displayed last. it goes behind the modal if the modal is displayed after it.

**Comment by nandorojo** [comment] 2021-05-23 18:05
I see, you mean last in the component tree, right? As in, if I render this after my native stack, it should be fine.

Can treat this component as a sort of a Portal for components at the root of the app that need to render on top of everything?

**Comment by a-eid** [comment] 2021-05-23 18:31
> I see, you mean last in the component tree, right? As in, if I render this after my native stack, it should be fine.

 yes and no. 
 
 you see if you render this component then trigger a modal, the modal will display on top of the component.

**Comment by nandorojo** [comment] 2021-05-23 18:33
Oh, so it's based on the time of rendering? As if it were attached to the window imperatively?

**Comment by WoLewicki** [comment] 2021-05-24 08:38
I added an option for the toast to stay on top even after pushing modals after it was rendered (see https://github.com/WoLewicki/react-native-window-view/issues/2#issuecomment-832863462). This library is kind of a PoC still, so if you see any bugs/inconsistencies, please report them there.

**Comment by a-eid** [comment] 2021-05-24 08:41
@WoLewicki thank you so much, I will be testing this lib extensively in a couple of apps that we have, will report and if possible contribute.

**Comment by nandorojo** [comment] 2021-05-24 23:03
> I added an option for the toast to stay on top even after pushing modals after it was rendered (see https://github.com/WoLewicki/react-native-window-view/issues/2#issuecomment-832863462). This library is kind of a PoC still, so if you see any bugs/inconsistencies, please report them there.

@WoLewicki thanks! Is this a prop on the JS side? I don't know my way around native code so I'm not sure exactly what I should be doing.

Also, are pointed events configurable? I'd like to set it to box-none, not sure what the default behavior is. Thanks again.

**Comment by WoLewicki** [comment] 2021-05-25 08:40
It requires adding code in your app's `AppDelegate.m` as shown in the code of example app. As for pointer events, I have not changed anything about it, so I assume it should work in a default RN way. If not, please submit issues in the repo.

**Comment by a-eid** [comment] 2021-06-17 15:23
@WoLewicki `pointerEvents` & `style` do no work consistently between android & ios. 

positional style do work but not all styles, for example `backgroundColor` does not work. 

also pointerEvents doesn't seem to be working.

**Comment by a-eid** [comment] 2021-06-24 12:41
<img width="416" alt="Screen Shot 2021-06-24 at 14 40 13" src="https://user-images.githubusercontent.com/19273413/123264203-1722c800-d4fa-11eb-8e95-df9b8c764499.png">


does having `RNViewContainer` & `RNWindowView` means that we have 2 views ?

is that necessary and could that be the issue why `pointerEvents` is not working properly ?

**Comment by WoLewicki** [comment] 2021-06-25 08:38
@a-eid I think I answered the questions in your issue in the repo, and I think we should keep the discussion there since it is connected to it.

**Comment by pouyarezvani** [comment] 2021-07-07 23:47
@Strate Which toast component are you using may I ask?

**Comment by WoLewicki** [comment] 2021-09-01 12:33
After some discussion, we decided to move `WindowView` to `react-native-screens` package. You can check #1096 and test if it is what you need.

**Closed** 2021-09-08 13:10 UTC
Labels: modal
