### ISSUE TITLE
react-native-screens RTL  back arrow icon is not visible in ios

### ISSUE THREAD

**Issue by TheEhsanSarshar** [software-mansion/react-native-screens#654] opened 2020-09-30 17:22 UTC
the problem only exist with the release build in real device

**Comment by WoLewicki** [comment] 2020-10-01 08:42
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by WoLewicki** [comment] 2020-10-14 12:24
@EhsanSarshar can you tell if this bug appeared in iOS 14 or was it present in iOS 13 already?

**Comment by EhsanSarshar** [comment] 2020-10-14 16:00
@WoLewicki yes the issue exist in iOS 14 and I don't test it in iOS 13. and one thing more the header also don't have the shadow.

**Comment by WoLewicki** [comment] 2020-11-24 14:32
@EhsanSarshar can you check if applying #722 fixes the issue?

**Comment by ajpaulingalls** [comment] 2020-12-15 00:17
@WoLewicki I have applied the patch and verified that it fixes the issue.

**Comment by WoLewicki** [comment] 2021-02-24 13:19
@EhsanSarshar @ajpaulingalls I checked a simple code example:

<details>
<summary>Code snippet</summary>

```tsx
import * as React from 'react';
import {Button} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from 'react-native-screens/native-stack';

const Stack = createNativeStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={{direction: 'rtl'}}>
        <Stack.Screen name="First" component={First} />
        <Stack.Screen
          name="Second"
          component={Second}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

function First({navigation}) {
  return (
    <Button title="Tap me for second screen" onPress={() => navigation.navigate('Second')} />

  );
}

function Second({navigation}) {
  return (
    <Button title="Tap me for second screen" onPress={() => navigation.navigate('First')} />
  );
}
```

</details>

and it looks like on iOS 14.4 this issue is gone. Can someone confirm it?

**Comment by ajpaulingalls** [comment] 2021-06-03 23:53
@WoLewicki it does appear to work now

**Comment by WoLewicki** [comment] 2021-06-07 09:22
Ok, so I will close this issue now and the linked PR too. Feel free to comment if something is wrong.

**Closed by WoLewicki** 2021-06-07 09:22 UTC
Labels: iOS, native-stack
