### ISSUE TITLE
Android Build Fails With "NoSuchFileException: /{mypath}/node_modules/react-native-screens/android/build/intermediates/res/symbol-table-with-package/debug/package-aware-r.txt"

### ISSUE THREAD

**Issue by johndanek** [software-mansion/react-native-screens#169] opened 2019-10-02 20:42 UTC
I am unable to build my React Native app for Android. iOS is working fine. I wonder if this is an AndroidX issue, as I used Android Studio's migration and Jetify.

I also tried manually looking for the file "package-aware-r.txt" but I can't find it anywhere in node_modules/react-native-screens. I wonder why processDebugResources is looking for this non-existent file?

Here are my relevant packages; let me know what other info I can provide.

"react": "16.8.6",
"react-native": "0.60.5",
"react-native-screens": "^2.0.0-alpha.3",
"react-navigation": "^4.0.10",

Full error:

    info Installing the app...
    > Task :app:processDebugResources FAILED

    Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
    Use '--warning-mode all' to show the individual deprecation warnings.
    See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
    71 actionable tasks: 3 executed, 68 up-to-date

    FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':app:processDebugResources'.
    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
    > java.nio.file.NoSuchFileException: /{mypath}/node_modules/react-native-screens/android/build/intermediates/res/symbol-table-with-package/debug/package-aware-r.txt

**Comment by necipallef** [comment] 2019-12-18 22:09
I had the same problem after upgrading gradle. I changed followings back:

# android/gradle/wrapper/gradle-wrapper.properties file
# below was distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
# changed to this
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip

and 

# android/build.gradle
# inside buildscript/dependencies below was classpath 'com.android.tools.build:gradle:3.5.3'
# changed to this
classpath 'com.android.tools.build:gradle:3.4.2'

I don't know why, but this fixed it. My co-worker didn't have this problem though. I guess my PC has some incorrect setup

**Comment by anastely** [comment] 2020-01-24 18:18
are you solve it?

**Comment by KaelLuo** [comment] 2020-03-31 10:16
I met the same issue when I trying to launch other library and solved it by remove few dependencies, in y case is `compile 'com.library.name'`.  
The author made a mistake and compile the library itself in it's dependencies, and the library was built in old gradle version.
Hope this could help you or others

**Comment by WoLewicki** [comment] 2020-04-02 12:40
It looks like the issue is solved. Can I close it @johndanek ?

**Comment by johndanek** [comment] 2020-04-02 16:07
@WoLewicki I'm no longer working on this Android app, so I can't verify. Feel free to close. Thanks.

**Comment by WoLewicki** [comment] 2020-04-22 10:50
Ok so I am closing this issue. Feel free to comment if there is something wrong.

**Closed by WoLewicki** 2020-04-22 10:50 UTC
