### ISSUE TITLE
RN 60.x ReactFragmentActivity deprecated

### ISSUE THREAD

**Issue by IntelliJAbhishek** [software-mansion/react-native-screens#129] opened 2019-07-15 06:49 UTC
As per the RN60.x changelog ReactFragmentActivity is deprecated.

https://github.com/facebook/react-native/commit/8ea8dd6d48bc3db0b8255f320537e662e8fa2a09

**Comment by ChrisEelmaa** [comment] 2019-07-15 13:46
duplicate of https://github.com/kmagiera/react-native-screens/issues/7

**Comment by jhoanborges** [comment] 2019-07-16 16:12
Just use ReactActivity. Fragment activity is already included on the react core

**Comment by WoLewicki** [comment] 2020-04-01 15:36
Looks like this issue is outdated, so I am closing it. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2020-04-01 15:36 UTC
