### ISSUE TITLE
Content overlapping on screen transitions [createNativeStackNavigator]

### ISSUE THREAD

**Issue by Abhishek12345679** [software-mansion/react-native-screens#610] opened 2020-08-21 10:55 UTC
react native :  0.62
react navigation v5 : 
react-navigation/native : ^5.7.3
react-navigation/stack : ^5.9.0
expo - 38.0.8

![glitch](https://media.giphy.com/media/dz0r9IAANO17GIjaxj/giphy.gif)

I am using `createNativeStackNavigator` and i have headerLargeTitle enabled .
This glitch usually happens for longer lists but , does happen on shorter lists too.

Repro-

You can reproduce this error on iOS (i am not sure if this error occurs on android) by putting two screens in a createNativeStackNavigator and setting the `headerLargeTitle` to true

**Comment by WoLewicki** [comment] 2020-08-24 09:34
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by Abhishek12345679** [comment] 2020-08-25 18:42
> Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

[Link to github repo for the repro](https://github.com/Abhishek12345679/GlitchRepro)

It is an expo init app

**Comment by WoLewicki** [comment] 2020-08-26 07:14
I think it is not a glitch. You provided `headerStyle: { backgroundColor: "#ffffff00" }` which means it has 0 alpha value, so it is transparent. At the beginning of the transition, the content of the below screen appears under that header and it is fully visible due to that 0 alpha value. After the transition, it stops to be transparent since you didn't provide `headerTranslucent: true` which would enable the content to go under the screen, so now it is opaque. Am I right or am I not seeing something?

**Comment by Abhishek12345679** [comment] 2020-08-26 09:41
yeah removing the headerStyle did the trick , don't know why i put it there in the first place.

**Comment by WoLewicki** [comment] 2020-08-26 09:44
Great! Can I close this issue then?

**Closed** 2020-08-26 10:20 UTC
