### ISSUE TITLE
Bug in react-native-screens latest beta release 

### ISSUE THREAD

**Issue by vishaalsaravanan** [software-mansion/react-native-screens#381] opened 2020-02-25 05:57 UTC
App Crashes when I try to render the component in the stack .Please fix it !..
Platform :Android
Version :2.0.0 beta 13
Error:Doesnt show any error message it simply crashes..
While looking into my package.json file i found out that the package react-native-screen  was in beta mode.Just downgraded the package's version to the one in my previous build which i had used before 2.0.0-alpha.27 and it works perfectly fine

**Comment by billouboq** [comment] 2020-02-25 08:11
> App Crashes when i try to load the App .Please fix it !..

maybe you should be more specific : 
  - iOS android ?
  - Which version ?
  - What is the error ?

Please fix your message !..

**Comment by cryptedx** [comment] 2020-02-26 09:30
I have the same problem, directly after app start. I can just can see a white screen for a short time. 
Platform :Android
Version :2.0.0 beta 13

beta 4 was working fine.
iOS is also working fine.

**Comment by fernandoavf7** [comment] 2020-02-27 04:48
same problem here, I tried with 2.0.1, 2.0.0, 2.0.0 beta 13, 2.0.0 beta 4 and doesnt work app crush at start with a white screen and show this message
https://imgur.com/ir2r8HP
if I delete the module from package.json, delete node_modules and install all again the app works

**Comment by kmagiera** [comment] 2020-02-27 08:40
Thank you all for your reports. However I'd like to point out that the level of details provided on this report is not actionable. Would be great to get at least the stack trace of the crash and at best a reproducible simple app I can use to see the problem for myself.

**Comment by i-suraj007** [comment] 2020-02-27 10:13
``
2020-02-27 15:33:52.167 31172-31172/com.epsumthings E/HAL: PATH3 /odm/lib64/hw/gralloc.qcom.so
2020-02-27 15:33:52.167 31172-31172/com.epsumthings E/HAL: PATH2 /vendor/lib64/hw/gralloc.qcom.so
2020-02-27 15:33:52.167 31172-31172/com.epsumthings E/HAL: PATH1 /system/lib64/hw/gralloc.qcom.so
2020-02-27 15:33:52.167 31172-31172/com.epsumthings E/HAL: PATH3 /odm/lib64/hw/gralloc.msm8953.so
2020-02-27 15:33:52.167 31172-31172/com.epsumthings E/HAL: PATH2 /vendor/lib64/hw/gralloc.msm8953.so
2020-02-27 15:33:52.167 31172-31172/com.epsumthings E/HAL: PATH1 /system/lib64/hw/gralloc.msm8953.so
2020-02-27 15:33:52.632 31172-31213/com.epsumthings E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.epsumthings, PID: 31172
    java.lang.NoClassDefFoundError: com.facebook.react.views.swiperefresh.ReactSwipeRefreshLayout
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:2551)
        at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169)
        at java.lang.reflect.Method.getParameterTypes(Method.java:193)
        at java.lang.Class.getDeclaredMethods(Class.java:1812)
        at com.facebook.react.uimanager.ViewManagersPropertyCache.extractPropSettersFromViewManagerClassDefinition(ViewManagersPropertyCache.java:446)
        at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:341)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:127)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:121)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findManagerSetter(ViewManagerPropertyUpdater.java:84)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:71)
        at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:272)
        at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:142)
        at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:93)
        at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:275)
        at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:182)
        at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:143)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
        at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:165)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: java.lang.ClassNotFoundException: com.facebook.react.views.swiperefresh.ReactSwipeRefreshLayout
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
        at java.lang.Class.getDexCacheType(Class.java:2551) 
        at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169) 
        at java.lang.reflect.Method.getParameterTypes(Method.java:193) 
        at java.lang.Class.getDeclaredMethods(Class.java:1812) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache.extractPropSettersFromViewManagerClassDefinition(ViewManagersPropertyCache.java:446) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:341) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:127) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:121) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findManagerSetter(ViewManagerPropertyUpdater.java:84) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:71) 
        at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:272) 
        at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:142) 
        at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:93) 
        at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:275) 
        at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:182) 
        at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:143) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184) 
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110) 
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188) 
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153) 
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466) 
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31) 
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054) 
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012) 
        at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972) 
        at android.os.Handler.handleCallback(Handler.java:754) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26) 
        at android.os.Looper.loop(Looper.java:165) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225) 
        at java.lang.Thread.run(Thread.java:760) 
2020-02-27 15:33:52.632 31172-31213/com.epsumthings E/AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
        at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:185)
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:782)
        	... 20 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.SwipeRefreshLayout" on path: DexPathList[[zip file "/data/app/com.epsumthings-1/base.apk"],nativeLibraryDirectories=[/data/app/com.epsumthings-1/lib/arm64, /data/app/com.epsumthings-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:74)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 22 more
2020-02-27 15:33:53.045 21321-21321/? E/Launcher: changeViewByFsGestureState,  view=FitSystemWindowView,  alpha=1.0,  scale=1.0
2020-02-27 15:33:53.045 21321-21321/? E/Launcher: changeViewByFsGestureState,  view=ShortcutMenuLayer,  alpha=1.0,  scale=1.0
2020-02-27 15:33:57.539 8619-9813/? E/libc: Access denied finding property "persist.radio.meid"
2020-02-27 15:33:57.539 8619-9813/? E/libc: Access denied finding property "ro.ril.oem.meid"
2020-02-27 15:34:00.671 2663-2705/? E/octvm_klo: Not get wanted event from the watchset in 8000ms for 2
2020-02-27 15:34:08.438 30694-30734/? E/FirebaseInstanceId: Topic sync failed: TOO_MANY_SUBSCRIBERS
2020-02-27 15:34:37.083 3417-3417/? E/SystemPropertiesUtils: SystemPropertiesUtils getInt: 
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.miui.support.c.e.bPb()
        at com.miui.common.c.c.getBoolean()
        at com.miui.networkassistant.utils.TelephonyUtil.getDataRoamingName()
        at com.miui.networkassistant.utils.TelephonyUtil.getDataRoamingEnabled()
        at com.miui.networkassistant.service.tm.TrafficManageService.initInternationalRoaming()
        at com.miui.networkassistant.service.tm.TrafficManageService.updateRoamingStateChanged()
        at com.miui.networkassistant.service.tm.TrafficManageService.-wrap17()
        at com.miui.networkassistant.service.tm.TrafficManageService$9.onSubscriptionsChanged()
        at miui.securitycenter.DualSim.DualSimInfoManagerWrapper.broadcastSubscriptionsChanged(DualSimInfoManagerWrapper.java:36)
        at miui.securitycenter.DualSim.DualSimInfoManagerWrapper.-wrap0(DualSimInfoManagerWrapper.java)
        at miui.securitycenter.DualSim.DualSimInfoManagerWrapper$SimInfoChangeImpl.onSubscriptionsChanged(DualSimInfoManagerWrapper.java:53)
        at miui.telephony.SubscriptionManager.notifyOnSubscriptionsChangedListeners(SourceFile:284)
        at miui.telephony.SubscriptionManager.onSubscriptionInfoChanged(SourceFile:262)
        at miui.telephony.SubscriptionManagerEx$2.onSubscriptionsChanged(SubscriptionManagerEx.java:141)
        at android.telephony.SubscriptionManager$OnSubscriptionsChangedListener$1.handleMessage(SubscriptionManager.java:378)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
     Caused by: java.lang.IllegalArgumentException: key.length > 31
        at android.os.SystemProperties.getBoolean(SystemProperties.java:112)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.miui.support.c.e.bPb() 
        at com.miui.common.c.c.getBoolean() 
        at com.miui.networkassistant.utils.TelephonyUtil.getDataRoamingName() 
        at com.miui.networkassistant.utils.TelephonyUtil.getDataRoamingEnabled() 
        at com.miui.networkassistant.service.tm.TrafficManageService.initInternationalRoaming() 
        at com.miui.networkassistant.service.tm.TrafficManageService.updateRoamingStateChanged() 
        at com.miui.networkassistant.service.tm.TrafficManageService.-wrap17() 
        at com.miui.networkassistant.service.tm.TrafficManageService$9.onSubscriptionsChanged() 
        at miui.securitycenter.DualSim.DualSimInfoManagerWrapper.broadcastSubscriptionsChanged(DualSimInfoManagerWrapper.java:36) 
        at miui.securitycenter.DualSim.DualSimInfoManagerWrapper.-wrap0(DualSimInfoManagerWrapper.java) 
        at miui.securitycenter.DualSim.DualSimInfoManagerWrapper$SimInfoChangeImpl.onSubscriptionsChanged(DualSimInfoManagerWrapper.java:53) 
        at miui.telephony.SubscriptionManager.notifyOnSubscriptionsChangedListeners(SourceFile:284) 
        at miui.telephony.SubscriptionManager.onSubscriptionInfoChanged(SourceFile:262) 
        at miui.telephony.SubscriptionManagerEx$2.onSubscriptionsChanged(SubscriptionManagerEx.java:141) 
        at android.telephony.SubscriptionManager$OnSubscriptionsChangedListener$1.handleMessage(SubscriptionManager.java:378) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6375) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802) 
2020-02-27 15:34:37.960 1666-3229/? E/BatteryStatsService: no controller energy info supplied
2020-02-27 15:34:37.960 1666-3229/? E/BatteryStatsService: no controller energy info supplied
2020-02-27 15:34:37.983 31324-31324/? E/ACRA: Initializing ANR detector for process: com.facebook.katana
2020-02-27 15:34:38.141 31324-31347/? E/art: No implementation found for int com.facebook.soloader.MergedSoMapping$Invoke_JNI_OnLoad.libaborthooks_so() (tried Java_com_facebook_soloader_MergedSoMapping_00024Invoke_1JNI_1OnLoad_libaborthooks_1so and Java_com_facebook_soloader_MergedSoMapping_00024Invoke_1JNI_1OnLoad_libaborthooks_1so__)
2020-02-27 15:34:38.143 31324-31347/? E/FacebookApplication: Unable to install abort hooks
    java.lang.UnsatisfiedLinkError: No implementation found for int com.facebook.soloader.MergedSoMapping$Invoke_JNI_OnLoad.libaborthooks_so() (tried Java_com_facebook_soloader_MergedSoMapping_00024Invoke_1JNI_1OnLoad_libaborthooks_1so and Java_com_facebook_soloader_MergedSoMapping_00024Invoke_1JNI_1OnLoad_libaborthooks_1so__)
        at com.facebook.soloader.MergedSoMapping$Invoke_JNI_OnLoad.libaborthooks_so(Native Method)
        at X.02E.A0A(:3257)
        at X.02E.A09(:3146)
        at X.02E.A08(:1)
        at com.facebook.aborthooks.AbortHooks.<clinit>(:2)
        at com.facebook.aborthooks.AbortHooks.install(Native Method)
        at com.facebook.katana.app.FacebookApplication.A0E(:308)
        at X.002.A0A(:5)
        at X.04W.run(:2)``


I got this log 

I tried the latest release 2.1.0 and still i face this app crash issue

**Comment by kmagiera** [comment] 2020-02-27 11:26
As one of the causes of the crash I can see the following record:

`ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.SwipeRefreshLayout"`

The above error means that Android app tries to load a class that is not included in the application bundle.

I presume there is something wrong with your project setup as that class should no longer be needed in screens 2.1.0.

**Comment by kmagiera** [comment] 2020-02-27 11:34
I was actually wrong about the above comment and that dependency is needed by another dependency screens use (however androidx does not list it as dependency despite loading some of the classes). 

You should follow the steps in the readme and add swipetorefresh dependency to your gradle project. See step 4 here https://github.com/software-mansion/react-native-screens#usage-with-react-navigation-without-expo

**Closed by kmagiera** 2020-02-27 11:34 UTC

**Comment by cryptedx** [comment] 2020-02-27 20:58
OK, I have fixed my startup crash problem with your help. Thank you very much!
