### ISSUE TITLE
react-native-screens/native-stack BUG ORIENTATION 

### ISSUE THREAD

**Issue by misaku** [software-mansion/react-native-screens#836] opened 2021-02-28 05:36 UTC
i use  createNativeStackNavigator  from 'react-native-screens/native-stack';

i have one problem in two cases:
first is when i fixed orientation: dont work.
secont when i use wonday/react-native-orientation-locker has the same problem orientation dont fixed.
if i donte use react native screens the orientation fixed was ok.
i force fix orientation with calling react native locker  every page with timeout 100ms and ok but, i would like no need use this pratice.

**Comment by kacperkapusciak** [comment] 2021-03-01 07:07
Could you provide a simple example that we could reproduce this issue?

**Comment by jp928** [comment] 2021-03-04 06:24
@kacperkapusciak Same here. Just simply create a createNativeStackNavigator with two screens with 
```
android:screenOrientation="portrait"
```
in AndroidManifest.xml wouldn't work to fix the orientation.

**Comment by jp928** [comment] 2021-03-04 06:46
@misaku 
The issue is in ScreenStackHeaderConfig.java line 47
, change it to:
```
private int mScreenOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
```
works for me.

**Comment by WoLewicki** [comment] 2021-03-04 10:01
Can you check if changing this line: https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java#L176 to `if ((getScreenFragment() == null || !getScreenFragment().hasChildScreenWithConfig(getScreen())) && mScreenOrientation != ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED) {` fixes your issue?

**Comment by tankers746** [comment] 2021-03-09 17:23
@WoLewicki The one line `ScreenStackHeaderConfig.java` fixed my problem, orientation is now locked again. Cheers!

**Comment by kamui545** [comment] 2021-03-09 19:06
@WoLewicki Your patch fixed the issue on my end as well.

**Comment by misaku** [comment] 2021-03-15 23:44
> @kacperkapusciak Same here. Just simply create a createNativeStackNavigator with two screens with
> 
> ```
> android:screenOrientation="portrait"
> ```
> 
> in AndroidManifest.xml wouldn't work to fix the orientation.

i try this but not work

**Comment by misaku** [comment] 2021-03-15 23:46
> @misaku
> The issue is in ScreenStackHeaderConfig.java line 47
> , change it to:
> 
> ```
> private int mScreenOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
> ```
> 
> works for me.
I will try to do this, but I would like to change the orientation at a specific time, for example, when I open the camera,

**Comment by misaku** [comment] 2021-03-15 23:52
@kacperkapusciak thx to help to fix, i will try to do and i will provide porject case to simulate this case.

**Comment by WoLewicki** [comment] 2021-03-18 15:48
Can you check if adding changes from https://github.com/software-mansion/react-native-screens/pull/860 also resolves the issue? It should prevent setting the orientation if it was not done explicitly by the user via a prop.

**Comment by misaku** [comment] 2021-03-21 20:47
hi @WoLewicki  i test withe the change, and this solution fix the problem, thx to help

**Comment by misaku** [comment] 2021-04-05 13:19
i will close when fix merge  =)

**Comment by misaku** [comment] 2021-04-18 18:36
any idea when it is merge fix solution?

**Comment by WoLewicki** [comment] 2021-04-19 10:46
It will be merged after the PR is thoroughly tested. You can always use [patch-package](https://www.npmjs.com/package/patch-package) to apply the changes in your project before they are merged and released.

**Comment by gp3gp3gp3** [comment] 2021-05-12 04:01
I am running into a similar but different issue.  On android the `default` orientation is not being respected, meaning the orientation is not rotating depending on the user's system settings when set to default (or not set), and vice versa if set to `all`.  I'm looking to not force the orientation to lock or `all`, but only respect what the device settings are.  This behaves fine on iOS.  The patch in the `ScreenStackHeaderConfig` doesn't address it unfortunately.

**Comment by WoLewicki** [comment] 2021-05-12 08:38
After this PR: https://github.com/software-mansion/react-native-screens/pull/863 is released, it should work in the way that until you don't set the orientation on any screen, the system settings should be used. Although if you set the orientation by using a prop, then `react-native-screens` will be the one managing it. You can try and [patch-package](https://www.npmjs.com/package/patch-package) that PR to see if it is what you need. It is a big one though cause it makes the status bar and orientation props usable in all navigators of `react-navigation`.

**Comment by Aryk** [comment] 2021-05-12 11:12
> Hi @WoLewicki,
> 
> On my side I was able to reproduce a similar issue:
> 
> * my app also has `android:screenOrientation="portrait"` but since we upgraded `react-native-screens`, on Android the orientation isn't fixed anymore.
> * we're using https://github.com/yamill/react-native-orientation to change the orientation on the fly
> 
> adding what you mentioned in
> 
> * https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java#L176
> * **but also in** https://github.com/software-mansion/react-native-screens/pull/679/files#diff-aeb4ca9ea647dc7e00b8260659b6632108daedb013772dee25853f06f361329fR71
>   fixed the issue
> 
> No issues on iOS.

@Almouro - I'm trying to get this fix into my app. I'm using Expo Managed.

I tried making the two changes you outlined, a pushed the changes, then changed the package.json to point to my branch.

However it didn't lock the orientation on Android.

What am I missing in the project? Is there some branch that I can point to that has these fixes?

**Comment by Aryk** [comment] 2021-05-12 17:56
@WoLewicki - You mentioned:

> Although if you set the orientation by using a prop

How do you set the orientation using a prop? Cannot find any documentation on this option in the README or anywhere on the internet.

-----

I also tried just explicitly setting: `private int mScreenOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;`

Do I need to build this library or run any commands before I check in my changes to my fork?

Any help would be greatly appreciated.

**Comment by Aryk** [comment] 2021-05-13 00:16
@jp928 - How did you actually implement this fix?

Did you fork, make the change, then just point to it from package.json...or did you need to run some build step?

> @kacperkapusciak Same here. Just simply create a createNativeStackNavigator with two screens with
> 
> ```
> android:screenOrientation="portrait"
> ```
> 
> in AndroidManifest.xml wouldn't work to fix the orientation.

**Comment by Aryk** [comment] 2021-05-13 02:24
I can't for the life of me get this fixed for Android, I've tried:

1. Using a fork with `private int mScreenOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;`
2. Passing through `screenOrientation: "portrait_up"` in screenOptions on the top most navigator
3. I've tried pointing my react-native-screens to this [commit](https://github.com/software-mansion/react-native-screens/pull/849/commits/b06674aa6a7f6059fdae1fa29c98fb69992112ff) and running "yarn" to install it. I see that the code in node_modules is updated, but the screen is still rotating.

Nothing works. I'm on Expo SDK 41 Managed.

**Comment by WoLewicki** [comment] 2021-05-13 08:27
@Aryk if you are using Expo managed workflow, you cannot change the native code since it is compiled into your Expo Go application. That is why any of the changes in the native code won't be applied in your app.

**Comment by Aryk** [comment] 2021-05-13 16:18
@WoLewicki - What options do I have here to lock my orientation. Even passing through the `screenOrientation` is getting completely ignored. 

Or do you happen to know when this fix will be out so I can use it on expo managed?

It's blocking my deploy so this is code-red for me.

According to Brent...seems like EAS Builds might be the only way...but I really don't want to venture into that if I don't have to.

thoughts?

**Comment by Aryk** [comment] 2021-05-13 23:36
@WoLewicki - FYI I was trying to get it working through EAS builds.

While I was doing it I had to `yarn clear cache` and then `rm yarn.lock` and then `yarn`

Somehow...that caused the "screenOrientation" param to start working again, so I can use that fix without complicating my workflow.

**Comment by rpander93** [comment] 2021-05-18 10:26
Only updating ScreenStackHeaderConfig didnt work for me. I also had to do the 2nd change mentioned by @Almouro to get it to work.

**Closed** 2021-05-19 13:20 UTC
Labels: needs more info, needs repro

**Comment by Paduado** [comment] 2021-05-26 21:58
I'm having this issue on iOS, I'm changing the orientation of a screen when mounting:
```js
useEffect(() => {
  Orientation.lockToPortrait();
},[])
```

Sometimes it works, sometimes it doesn't. 
If I add a delay it works consistently, so a wild guess is that it has something to do with the navigation transition?

Any ideas on how can I debug this?

**Comment by WoLewicki** [comment] 2021-05-27 10:06
@Paduado I think it is not in scope of this issue since this one is about Android. If you want help with this, please submit a new issue with a reproduction.

**Comment by DevineDecrypter** [comment] 2023-11-18 18:12
im having this issue with "react-native-screens": "^3.27.0", the files are now in kotlin and not java, how can i fix this?

**Comment by tboba** [comment] 2023-11-20 09:34
Hi @DevineDecrypter, since this issue has been created 2 years ago, could you create a new issue that describes your problem?
