### ISSUE TITLE
Android build is failing. 502 Bad Gateway

### ISSUE THREAD

**Issue by Manouli** [software-mansion/react-native-screens#1269] opened 2022-01-12 17:34 UTC
## Description
I am trying to build an android release in AppCenter and I am getting the following error: 

```
* What went wrong:
Execution failed for task ':app:lintVitalStagingRelease'.
> Could not resolve all artifacts for configuration ':react-native-screens:releaseRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-screens
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```
I think its related to jcenter but I am unsure of how I need to sort this out. I saw a PR [here](https://github.com/software-mansion/react-native-screens/pull/1245) which possibly sort this issue out and I am wondering if there is any other solution here.

## Platform

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |0.66.3|
| @react-navigation/native               |6.0.6|
| @react-navigation/native-stack         |6.2.5|
| react-native-screens                   |3.10.1|
| react-native-safe-area-context         |3.3.2|

**Comment by Manouli** [comment] 2022-01-12 17:44
> Hey! 👋
> 
> The issue doesn't seem to contain a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
> 
> Could you provide a snippet of code, a [snack](https://snack.expo.dev/) or a link to a GitHub repository that reproduces the problem?

A reproduction step or snack is not needed in this case.

**Comment by Manouli** [comment] 2022-01-12 17:46
> Hey! 👋
> 
> It looks like you've omitted a few important sections from the issue template.
> 
> Please complete **Steps To Reproduce** and **Reproduction** sections.

I believe I have supplied the info required for the issue. Let me know if you need any more info.

**Comment by Manouli** [comment] 2022-01-12 18:43
I have for now resolved this issue by adding the following code into root build.gradle of the android app. Turns out the + was causing the issue so by specifying a version the problem got resolved and I was able to build. I am going to leave this issue open to get some thoughts from other people too. 

```
       configurations.all {
          resolutionStrategy {
            force 'com.facebook.react:react-native:0.66.3'
          }
        }
```

**Comment by osliver** [comment] 2022-01-12 20:06
> I have for now resolved this issue by adding the following code into root build.gradle of the android app. Turns out the + was causing the issue so by specifying a version the problem got resolved and I was able to build. I am going to leave this issue open to get some thoughts from other people too.

didn't help

**Comment by trantus** [comment] 2022-01-12 20:48
same issue

**Comment by numboDumbo** [comment] 2022-01-12 20:51
It is failing for me also with
"@react-navigation/bottom-tabs": "^6.0.9",
"@react-navigation/native": "^6.0.6",
"react": "17.0.2",
"react-native": "0.66.4",
"react-native-safe-area-context": "^3.3.2",
"react-native-screens": "^3.10.1",
"react-redux": "^7.2.6",
"redux": "^4.1.2"

**Comment by gax97** [comment] 2022-01-12 22:07
I made a PR that removes jcenter: [1270](https://github.com/software-mansion/react-native-screens/pull/1270)

**Comment by kacperkapusciak** [comment] 2022-01-13 08:29
It was a global JCenter outage: https://status.gradle.com/incidents/nv93msj8q658

The repositories are now operational and the issue is resolved.

**Comment by trantus** [comment] 2022-01-13 09:13
> 

still occurring

**Comment by kacperkapusciak** [comment] 2022-01-13 11:19
I can't seem to reproduce this error 😞 

Nevertheless, I've merged the PR removing `jcenter()` in https://github.com/software-mansion/react-native-screens/pull/1245. 

We were hesitant to remove `jcenter` for so long because last time we removed it users couldn't build the app - https://github.com/software-mansion/react-native-screens/pull/1101.

Now it seems that every package that `screens` depends on is now moved to `mavenCentral`, which was not the case a few months ago when the `jcenter` deprecation warning first appeared.

@Manouli could you confirm that this issue still occurs?

**Comment by Manouli** [comment] 2022-01-13 13:29
@kacperkapusciak Nope its not happening anymore. If it does I will get back to you again. From my point of view we can close this issue. I only left it open for brainstorming ideas mostly. Thank you all for your comments

**Closed** 2022-01-13 13:31 UTC
Labels: needs-more-info, 🤖android, repro-provided
