### ISSUE TITLE
Using custom font in navigation header?

### ISSUE THREAD

**Issue by beaur** [software-mansion/react-native-screens#319] opened 2020-02-10 23:19 UTC
I'm using expo and have loaded a custom font using the expo-font package https://docs.expo.io/versions/v36.0.0/sdk/font/.  I am also using the new react-navigation 5 library and the Native Stack Navigator which uses react-native-screens.

I want to use this custom font in my navigation header however is seems setting `titleFontFamily` to this custom loaded font is not working.  I can set the font family successfully to any of the UIFont font families (https://github.com/lionhylra/iOS-UIFont-Names) but not my custom loaded font.  Is this a known limitation or should this be working?

**Comment by WoLewicki** [comment] 2020-03-16 15:39
It seems like a duplicate of #371 . I am closing it then, please inform me if it is not the same issue.

**Closed by WoLewicki** 2020-03-16 15:39 UTC
Labels: native-stack

**Comment by beaur** [comment] 2020-03-16 23:31
Yes this seems to have been since duplicated.  I will continue monitoring #371 .
