### ISSUE TITLE
Android Unresolved reference: ReactTypefaceUtils

### ISSUE THREAD

**Issue by hoangtrungit** [software-mansion/react-native-screens#1271] opened 2022-01-13 05:28 UTC
I'm buidling android application using "react-native-screens": "^3.10.1", but I'm getting error 
![image](https://user-images.githubusercontent.com/8652255/149271186-fca6f7fa-513e-481f-8d17-d24783b47341.png)

**Comment by kacperkapusciak** [comment] 2022-01-13 08:36
Hi @hoangtrungit,

Your problem looks like a duplicate of https://github.com/software-mansion/react-native-screens/issues/1230

You are probably using `react-native` in version older than `0.62.x`. `react-native-screens` `3.x.x` require `react-native` `>=0.62.x`. This information can be found [here in the README](https://github.com/software-mansion/react-native-screens#supported-react-native-version).

Try downgrading `react-native-screens` to version `2.18.1` or upgrade your `react-native` project.

I would know that for sure if you filled out the issue template and provided the necessary package versions. 

Cheers

**Closed by kacperkapusciak** 2022-01-13 08:36 UTC
Labels: needs-more-info, 🧰needs-repro, needs-review

**Comment by zvs001** [comment] 2022-01-31 13:39
@kacperkapusciak
I reproduced same error with current latest versions:
```
"react-native-screens": "~3.10.2"
"react-native": "^0.67.1"
```
