### ISSUE TITLE
[native-stack] Header is out of the safe area on Android

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-screens#360] opened 2020-02-22 18:16 UTC
_Moved from [react-navigation/react-navigation#6797](https://github.com/react-navigation/react-navigation/issues/6797). Originally opened by @enheit_
___

**Current Behavior**

The header navigation is rendered beyond safe area on Android devices.

![image](https://user-images.githubusercontent.com/8645216/74091933-4f249900-4ac6-11ea-9ce6-bded773c13a7.png)

**Expected Behavior**

The header should be rendered in 'safe area'.

![image](https://user-images.githubusercontent.com/8645216/74091967-b2aec680-4ac6-11ea-97a8-6d03cc8be951.png)

(this is how `@react-navigation/stack` works)

**How to reproduce**

Create a screen by using `Screen.Stack` from `@react-navigation/native-stack`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android (v9)
| @react-navigation/native       | ^5.0.0-alpha.33
| @react-navigation/native-stack | ^5.0.0
| react-native-screens           | ^2.0.0-beta.2
| react-native                   | ~0.61.4
| expo                           | ~36.0.0
| node                           | v12.14.1
| npm or yarn                    | 6.13.4

**Comment by WoLewicki** [comment] 2020-03-31 09:14
@enheit can you repro the issue in v. 2.4.0?

**Comment by Erc93** [comment] 2020-04-02 05:23
Hi. I am getting the same issue and it looks like it still occurs in v2.4.0

**Comment by enheit** [comment] 2020-04-02 07:08
@WoLewicki  Issue is no reproduced on Android 9

![image](https://user-images.githubusercontent.com/8645216/78220142-a55ff800-74c9-11ea-994f-455ec236b0b6.png)

I would recommend to verify on other Android versions & devices if it possible

**Comment by WoLewicki** [comment] 2020-04-02 12:47
@Erc93 can you provide a reproduction with a minimal needed configuration that would show the issue?

**Comment by Erc93** [comment] 2020-04-03 01:03
@WoLewicki 
I just realised that I might be running into a separate but similar issue. I seem to be getting the problem when using `import { createNativeStackNavigator } from "react-native-screens/native-stack";` to create my stack. Using the stack navigator from react-navigation seems to fix my issue.

Here is an example:
https://snack.expo.io/HqDtTeyzQ

**Comment by WoLewicki** [comment] 2020-04-03 09:15
![image](https://user-images.githubusercontent.com/32481228/78344142-3ef7da00-759c-11ea-8178-3578218e4b97.png)
@Erc93 I cannot repro your issue with this configuration. It looks like the safe area is correctly applied on Android. Can you be more specific on how to reproduce the bug?

**Comment by Erc93** [comment] 2020-04-05 23:59
<img width="274" alt="Screen Shot 2020-04-06 at 9 42 02 am" src="https://user-images.githubusercontent.com/10914349/78512843-174a8100-77eb-11ea-8ab7-ef610d685ae8.png">
<img width="379" alt="Screen Shot 2020-04-06 at 9 43 08 am" src="https://user-images.githubusercontent.com/10914349/78512844-19144480-77eb-11ea-8e99-dcc5e4d29317.png">

@WoLewicki I'm not sure why you cannot reproduce the issue. The issue seems to occur on both the Android device on the snack and on the Android Simulator for me.

The issue specifically happens when using `createNativeStackNavigator` from "react-native-screens/native-stack" to create the stack. If I replace this with `createStackNavigator` from "@react-navigation/stack", then the issue no longer happens.

I'm not quite sure if I am missing anything else to be able to reproduce the issue. I have tested the problem from Android 8.1 until 10 and it seems to happen on all of them. I'm also quite new to React Native so I apologise if I am being confusing.

**Comment by WoLewicki** [comment] 2020-04-06 07:45
I think the problem might be that you are trying to do it in Expo Client, which has an older version of `react-native-screens`, where the bug still exists. Could you try making a bare RN project with newest `react-native-screens` and check if the issue exists there?

**Comment by Erc93** [comment] 2020-04-07 01:44
@WoLewicki Yup you are right. I was using the Expo client the whole time. I created a bare project as you advised and the issue does not occur. Thanks for all the assistance!

**Comment by WoLewicki** [comment] 2020-04-07 09:19
Ok so sadly all you can do with Expo client is to wait for the next release where the newer native code will be added. I am closing the issue since it is resolved.

**Closed by WoLewicki** 2020-04-07 09:19 UTC
Labels: Android, bug, native-stack

**Comment by dougg0k** [comment] 2020-06-15 14:16
I found a temp solution for Android while using Expo. In the `Screen` `options`, when declaring your header (left, center and right), you can add `height` and `marginTop` to it and that can help, maybe not in all cases though.

```
headerCenter: (props) => (
    <Text
      style={{
        color: "white",
        fontSize: 18,
        height: 40,
        marginTop: 30,
      }}
    >
      Title
    </Text>
  ),
```
