### ISSUE TITLE
[Android] Could not get unknown property 'javaCompileProvider' for object of type 

### ISSUE THREAD

**Issue by lorenzo-crowd** [software-mansion/react-native-screens#124] opened 2019-07-09 15:49 UTC
Hi,

I followed all Installation steps but when I try to build the app for Android I get the following error.

React native version 0.58.4
React Navigation Version ^3.1.5

* Where:
Build file '/Library/WebServer/Documents/offf-app/node_modules/react-native-screens/android/build.gradle' line: 103

* What went wrong:
A problem occurred configuring project ':react-native-screens'.
> Could not get unknown property 'javaCompileProvider' for object of type com.android.build.gradle.internal.api.LibraryVariantImpl.

**Comment by JustinKasad** [comment] 2019-07-10 18:26
I'm having the same issue.  I temporarily fixed it with this:
https://github.com/kmagiera/react-native-reanimated/issues/315#issuecomment-503916860

**Comment by se-bastiaan** [comment] 2019-07-10 19:42
What version of gradle and the android build plugin are you using?

**Comment by lorenzo-crowd** [comment] 2019-07-11 08:15
From my build.gradle file:

```
buildToolsVersion = "28.0.2"

classpath 'com.android.tools.build:gradle:3.2.1'

gradleVersion = '4.7'
```

**Comment by se-bastiaan** [comment] 2019-07-11 09:41
According to the [PR that created this change](https://github.com/kmagiera/react-native-screens/pull/60) you need Gradle 4.10+. So if you update it should work again.

**Comment by WoLewicki** [comment] 2020-04-01 15:44
It looks like the issue is outdated, so I am closing it then. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2020-04-01 15:44 UTC

**Comment by imamarham10** [comment] 2020-08-12 13:53
you are wrong,any issue can never be outdated, there are unnumerable beginners coming to dev world

**Comment by 1-aminadab** [comment] 2023-12-18 13:55
I got this error all the time I start my react-native app. I'm about to lose my job. pleace help 
A problem occurred configuring project ':react-native-screens'.
> Could not determine the dependencies of null.    
   > Could not resolve all dependencies for configuration ':react-native-screens:classpath'.

**Comment by tboba** [comment] 2023-12-18 14:12
Hi @1-aminadab, I'm sorry that's happening for you. Could you provide us more information about your project? What's your Java/Kotlin, Gradle and React Native version and which version of react-native-screens are you trying to install? Also if it's possible for you, could you provide any steps to reproduce, so we could also test that? If not, could you at least send us your configuration (what dependencies are you using, how does your gradle configuration look like, etc.)?

**Comment by easyecom-manu** [comment] 2024-04-30 18:57
same problem with `"react-native-screens": "^3.31.1",`

`BUILD FAILED in 6s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: A
 problem occurred configuring project ':react-native-screens'. > com.android.builder.errors.EvalIssueException: [CXX1101] NDK at C:\Users\manu\AppData\Local\Android\Sdk\ndk\26.1.10909125 d
id not have a source.properties file * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full
 insights. > Get more help at https://help.gradle.org. BUILD FAILED in 6s.
info Run CLI with --verbose flag for more details.
`

why this happening even it is recommended in react native official page
https://reactnative.dev/docs/navigation

**Comment by tboba** [comment] 2024-05-06 08:15
Hi @easyecom-manu, I believe this has been already reported before. Please check out if solution from [this](https://github.com/software-mansion/react-native-screens/issues/2114#issuecomment-2081113357) comment resolves your issue.
