### ISSUE TITLE
[Android] NativeStackNavigator lose state when switching between tabs in BottomTabNavigator

### ISSUE THREAD

**Issue by enheit** [software-mansion/react-native-screens#450] opened 2020-04-02 07:55 UTC
### Implementation

1) Create `bottomStackNavigator` with 2 tabs
2) Create `createNativeStackNavigator` in the first tab of `bottomStackNavigator`
2) Create `createNativeStackNavigator` in the second tab of `bottomStackNavigator`

Now you have 2 tabs with each unique `nativeStackNavigator` 

4) Provide few `Stack.Screen` to the `createNativeStackNavigator` in the second screen.

### Step to reproduce

1) Open app
2) Navigate to the second page of `bottomTabNavigator`
3) Open some screen (which will be pushed to the `createNativeStackNavigator`)
4) Navigate to the first page of `bottomTabNavigator`
5) Navigate to the second page of `bottomTabNavigator`

### Actual result:
The second tab lose internal state and open the first screen in the stack

### Expected result:
The second tab should preserve internal state of the stack

### Environemnt
os: Android
version: 9

P.S. iOS 13.4 has no the issue
P.S.S. Defect is not reproducible on the `2.0.0-beta.2` version

#### Gif

![issue](https://user-images.githubusercontent.com/8645216/78223894-48b40b80-74d0-11ea-8389-e27620f23a6e.gif)

As you can see after switching the tab (Pages < - > Menu), the Menu stack navigator lose state and show first page (with menu) instead of second page (with settings)

#### Video
[nativeStack-lose-state.zip](https://github.com/software-mansion/react-native-screens/files/4419543/nativeStack-lose-state.zip)

**Comment by WoLewicki** [comment] 2020-04-02 15:38
It is probably duplicate of #402 so I am closing it. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2020-04-02 15:38 UTC

**Comment by Hirbod** [comment] 2020-04-23 07:42
@enheit did you also use "materialBottomTabs" by any chance? Because for me, its only happening with that navigator, it works with the other tab navigators.
