### ISSUE TITLE
headerLargeTitle & headerSearchBarOptions Doesn't Support RTL

### ISSUE THREAD

**Issue by Wahsner** [software-mansion/react-native-screens#1884] opened 2023-09-07 12:39 UTC
### Description

When RTL is enabled, the headerLargeTitle & headerSearchBarOptions don't honour the text direction. Instead they remain LTR as shown in the below screen cuttings. 
- Restarting the app between changing text direction makes no difference. 
- The fact the text itself isn't a RTL language makes no difference. 
- Having the device in a RTL language makes no difference.
- Doesn't matter if you're using Paper or Fabric or the new/old arch.
- Doesn't matter if you're running in debug or release.
- Doesn't matter if you're running on a real or sim device.

**headerLargeTitle**
![image](https://github.com/software-mansion/react-native-screens/assets/47725355/b63c3133-eae0-491b-82cf-a57573a6bd07)
**headerSearchBarOptions(focused)**
![image](https://github.com/software-mansion/react-native-screens/assets/47725355/9c9d0085-3092-463b-9be5-468517503bb4)

I would expect them to be positioned right as shown below (taken from the contacts app)

**Large Title**
![image](https://github.com/software-mansion/react-native-screens/assets/47725355/441fb407-25db-43f2-8bf0-92c34e52416b)
**Search bar(focused)**
![image](https://github.com/software-mansion/react-native-screens/assets/47725355/87402b27-9ef1-41fb-ade0-6bf4f56763d0)

### Steps to reproduce

1. Set the options direction: 'rtl'
2. Not sure if required, but Set I18nManager.forceRTL(true); in the App.js too
3. Restart the app by closing it completely from background and re-launching

Expected
- For text direction to be RTL for headerLargeTitle & headerSearchBarOptions

Actual
- headerLargeTitle & headerSearchBarOptions are still LTR

### Snack or a link to a repository

https://github.com/0xRenshaw/react-native-screens/tree/main/FabricExample

### Screens version

3.25.0

### React Native version

0.72.4

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Acknowledgements

Yes

**Comment by tboba** [comment] 2023-09-20 08:14
Hi @0xRenshaw, thank you for reporting this issue!
I've managed to reproduce this problem - I'll open a PR that solves it shortly.

<img width="378" alt="Screenshot 2023-09-20 at 10 12 25" src="https://github.com/software-mansion/react-native-screens/assets/23281839/fac7b593-7a55-43fd-9762-2a3ef3e0c1bc">

**Comment by moedeveloper** [comment] 2023-10-12 20:59
what is the fix, i am still having the same issue ?

**Comment by 0xRenshaw** [comment] 2023-10-12 21:05
> what is the fix, i am still having the same issue ? 

It has been merged to master. There hasn't yet been a release.

**Comment by tboba** [comment] 2023-10-17 16:47
Hi @0xRenshaw @moedeveloper, there's a new version of react-native-screens: 3.26.0 which has this change included. Check it out! If you find something wrong related to the newest version (this change is still buggy or doesn't work for you) let us know 🎉

**Comment by STonkoshkur** [comment] 2024-02-16 10:39
@tboba the back button direction is still incorrect in RTL for iOS. I'm running the example application from `Example` directory using Xcode 15.2

<img width="459" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/6708783/3c85cfa7-68f4-41fa-ad9c-09c82df5c79c">

**Comment by tboba** [comment] 2024-02-16 10:42
@STonkoshkur interesting, do you have some native apps that have RTL mode enabled? I just wanted to see how the back button should look like. In my case, I have the same back button as you, but if I unhide the default navigation bar of the navigation controller, it looks completely the same 🤔 

<img width="337" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/23281839/e4b6557f-3530-4ec6-b2ff-b9be4b197bda">

**Comment by tboba** [comment] 2024-02-16 10:46
Reopening the issue, since something has broke in iOS 17.2 that has broke the back button in RTL mode.

Expected behavior:
![image](https://github.com/software-mansion/react-native-screens/assets/23281839/e12c81b0-5973-4b19-96d8-ce3494cee2f5)

**Comment by tboba** [comment] 2024-02-16 11:50
I believe that potentially the bug with back button might occur also in iOS native apps. I've found on Apple forums that someone has the same problem - https://developer.apple.com/forums/thread/737855.
@STonkoshkur could you check if on the non-system native apps the issue with back button is the same?

**Comment by alduzy** [comment] 2024-06-12 10:51
I can confirm the back arrow faces correct direction after changing the application's CFBundleDevelopmentRegion.
Looks as if the `I18nManager.forceRTL(true)` does not force the change.
It's worth noticing that the Text element's alignment is not changing properly - only flexDirection of View element changes:
![Screenshot 2024-06-12 at 12 33 10](https://github.com/software-mansion/react-native-screens/assets/91994767/e36bbd8d-9627-4e11-9825-237a548ca59f)

| `developmentRegion = ar` | `developmentRegion = en` |
|--------|--------|
| ![Screenshot 2024-06-12 at 12 41 14](https://github.com/software-mansion/react-native-screens
![Screenshot 2024-06-12 at 12 41 27](https://github.com/software-mansion/react-native-screens/assets/91994767/49463b15-a653-4800-807b-55f028042911)
/assets/91994767/e26483bd-233a-48ed-abb2-821c1d5cbce8) | ![Screenshot 2024-06-12 at 12 42 33](https://github.com/software-mansion/react-native-screens/assets/91994767/23b98847-214f-46b7-bc77-3b0935d18291)
![Screenshot 2024-06-12 at 12 42 46](https://github.com/software-mansion/react-native-screens/assets/91994767/e5595101-8065-46a9-ae39-c5506e46b63f) |

**Closed** 2024-06-27 07:53 UTC
Labels: Platform: iOS, Missing repro
