### ISSUE TITLE
Android RN 0.75.3, app crashes when returning to the previous screen

### ISSUE THREAD

**Issue by DinhHoangNgoc** [software-mansion/react-native-screens#2341] opened 2024-09-16 04:31 UTC
### Description

When I return to the previous screen, the app crashes. I am using version RN 0.75.3. I have tested with other RN versions, and this issue occurs from version RN 0.75 onwards.

https://github.com/user-attachments/assets/97f32a60-3a97-4b37-af4e-388d4db08553

![7a0f880c8e5c2802714d](https://github.com/user-attachments/assets/865d1fb4-55de-4080-9c88-1cc4a8813668)

### Steps to reproduce

app crashes when returning to the previous screen

### Snack or a link to a repository

https://github.com/Ngoca1k15PT/AppNew

### Screens version

3.34.0

### React Native version

0.75.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Device model

Xiaomi

### Acknowledgements

Yes

**Comment by hosseinmd** [comment] 2024-09-16 14:34
I have the same issue.

**Comment by tamacroft** [comment] 2024-09-17 02:17
same issue here

**Comment by DorianMazur** [comment] 2024-09-17 11:52
@tamacroft @hosseinmd @DinhHoangNgoc 
```
diff --git a/android/src/main/java/com/swmansion/rnscreens/Screen.kt b/android/src/main/java/com/swmansion/rnscreens/Screen.kt
index 1ab8594ef35bf43821a46c97ca77292c87190850..8e9d712718f385638d0d58a1f3ef144e3de6eb55 100644
--- a/android/src/main/java/com/swmansion/rnscreens/Screen.kt
+++ b/android/src/main/java/com/swmansion/rnscreens/Screen.kt
@@ -10,13 +10,16 @@ import android.view.View
 import android.view.ViewGroup
 import android.view.WindowManager
 import android.webkit.WebView
+import android.widget.ImageView
 import androidx.core.view.children
 import androidx.fragment.app.Fragment
+import androidx.swiperefreshlayout.widget.SwipeRefreshLayout
 import com.facebook.react.bridge.GuardedRunnable
 import com.facebook.react.bridge.ReactContext
 import com.facebook.react.uimanager.PixelUtil
 import com.facebook.react.uimanager.UIManagerHelper
 import com.facebook.react.uimanager.UIManagerModule
+import com.facebook.react.views.scroll.ReactScrollView
 import com.swmansion.rnscreens.events.HeaderHeightChangeEvent
 
 @SuppressLint("ViewConstructor") // Only we construct this view, it is never inflated.
@@ -295,7 +298,7 @@ class Screen(
         parent?.let {
             for (i in 0 until it.childCount) {
                 val child = it.getChildAt(i)
-                if (child.javaClass.simpleName.equals("CircleImageView")) {
+                if (parent is SwipeRefreshLayout && child is ImageView) {
                     // SwipeRefreshLayout class which has CircleImageView as a child,
                     // does not handle `startViewTransition` properly.
                     // It has a custom `getChildDrawingOrder` method which returns
@@ -312,6 +315,11 @@ class Screen(
                     startTransitionRecursive(child.toolbar)
                 }
                 if (child is ViewGroup) {
+                    if (it is ReactScrollView && it.removeClippedSubviews) {
+                        for (j in 0 until child.childCount) {
+                            child.addView(View(context))
+                        }
+                    }
                     startTransitionRecursive(child)
                 }
             }
diff --git a/common/cpp/react/renderer/components/rnscreens/RNSScreenComponentDescriptor.h b/common/cpp/react/renderer/components/rnscreens/RNSScreenComponentDescriptor.h
index 37aac4e1aca18f5dd537b3599c408abac114d4be..53415e9a8cc663d62373e3e432b4b1ed88e976e5 100644
--- a/common/cpp/react/renderer/components/rnscreens/RNSScreenComponentDescriptor.h
+++ b/common/cpp/react/renderer/components/rnscreens/RNSScreenComponentDescriptor.h
@@ -5,9 +5,9 @@
 #endif
 #include <react/debug/react_native_assert.h>
 #include <react/renderer/components/rnscreens/Props.h>
+#include <react/renderer/components/rnscreens/utils/RectUtil.h>
 #include <react/renderer/core/ConcreteComponentDescriptor.h>
 #include "RNSScreenShadowNode.h"
-#include "utils/RectUtil.h"
 
 namespace facebook {
 namespace react {

```

**Comment by DinhHoangNgoc** [comment] 2024-09-18 04:57
@DorianMazur  It works well, thank you for the help.

**Comment by DorianMazur** [comment] 2024-09-18 09:28
FYI: For some reason, in my project this patch is not always working 🤷 
That's why I decided to disable removeClippedSubviews globally in the index.js file, like this:
```
FlatList.defaultProps = FlatList.defaultProps || {}
FlatList.defaultProps.removeClippedSubviews = false
ScrollView.defaultProps = ScrollView.defaultProps || {}
ScrollView.defaultProps.removeClippedSubviews = false
SectionList.defaultProps = SectionList.defaultProps || {}
SectionList.defaultProps.removeClippedSubviews = false
```

**Comment by mrenann** [comment] 2024-09-18 13:05
@DorianMazur I also put it and it worked but with a bottomtabnavigation, when switching between tabs it gives the error No view found for id 0x6fe for fragment ScreentStackFragment

**Comment by abrah4mr** [comment] 2024-09-18 21:52
@mrenann If you add `detachInactiveScreens={false}` fix the error for now.

I already opened an issue for this error.

**Comment by hosseinmd** [comment] 2024-09-22 11:12
@DorianMazur your solution work but doesn't work in all situation, in my app some page still crashing when going back.

**Comment by NiuGuohui** [comment] 2024-09-24 06:46
Does anyone have a complete solution?

**Comment by DorianMazur** [comment] 2024-09-24 15:06
It worked for me
```
FlatList.defaultProps = FlatList.defaultProps || {}
FlatList.defaultProps.removeClippedSubviews = false
ScrollView.defaultProps = ScrollView.defaultProps || {}
ScrollView.defaultProps.removeClippedSubviews = false
SectionList.defaultProps = SectionList.defaultProps || {}
SectionList.defaultProps.removeClippedSubviews = false
```

**Comment by NiuGuohui** [comment] 2024-09-25 01:31
> It worked for me
> 
> ```
> FlatList.defaultProps = FlatList.defaultProps || {}
> FlatList.defaultProps.removeClippedSubviews = false
> ScrollView.defaultProps = ScrollView.defaultProps || {}
> ScrollView.defaultProps.removeClippedSubviews = false
> SectionList.defaultProps = SectionList.defaultProps || {}
> SectionList.defaultProps.removeClippedSubviews = false
> ```

I don't think this is a good solution because this problem can be encountered in many scenarios. For example, when using dynamic content in the Drawer of react native drawer layout.

**Comment by b0iq** [comment] 2024-09-29 08:24
its still happening `3.35.0-rc.1`

**Comment by hosseinmd** [comment] 2024-09-29 10:46
i commented entire of `startTransitionRecursive` and it works for me.
https://github.com/software-mansion/react-native-screens/blob/bc95fa466b3a115682db6b74ef5e2b73d830e6cc/android/src/main/java/com/swmansion/rnscreens/Screen.kt#L365

**Comment by kkafar** [comment] 2024-09-29 10:53
What architecture is that? Are you all using Fabric or is that Paper?

**Comment by NiuGuohui** [comment] 2024-09-30 01:30
> What architecture is that? Are you all using Fabric or is that Paper?

Fabric and disable bridgeless.

**Comment by alduzy** [comment] 2024-09-30 14:56
I believe it's a duplicate of https://github.com/software-mansion/react-native-screens/issues/2282 and should be resolved by https://github.com/software-mansion/react-native-screens/pull/2307

As a workaround for now you can try setting the [removeClippedSubviews](https://reactnative.dev/docs/flatlist#removeclippedsubviews) option in the FlatList to false or applying the patch pasted by @DorianMazur

**Comment by hosseinmd** [comment] 2024-09-30 16:44
Is it possible to have an option to disable transition?

**Comment by hosseinmd** [comment] 2024-09-30 16:55
https://github.com/software-mansion/react-native-screens/pull/2307 this is not fixed for all situations. I had to remove transition.

**Comment by alduzy** [comment] 2024-09-30 17:04
@hosseinmd Could you attach a minimal reproduction?

**Comment by DorianMazur** [comment] 2024-09-30 19:26
@alduzy We should reopen this issue. It's not fixed by #2307

**Comment by hosseinmd** [comment] 2024-09-30 19:27
Sorry, it is not happening in a regular app. I don't know what is the exact problem, but when I remove transition, it work.

**Comment by alduzy** [comment] 2024-10-01 06:32
Ok let's reopen it. Some reproduction snack would be necessary to find out what's broken though. 🙏 
I tried the one provided by @DinhHoangNgoc and it works just fine with the fix.

**Comment by hosseinmd** [comment] 2024-10-03 11:20
I reproduced the issue with latest version 4.0.0-beta.3
https://github.com/hosseinmd/react-native-screens-new-arch-crash-example 
the root cause is related to render an image in Flatlist which is rendered in another Flatlist.

**Comment by alduzy** [comment] 2024-10-03 12:57
@hosseinmd I can't open it (404). Make sure the example is public

**Comment by hosseinmd** [comment] 2024-10-03 13:07
sorry, i make it public now.

**Comment by alduzy** [comment] 2024-10-03 14:56
@hosseinmd Thanks! I was able to reproduce the issue and found out that it's caused by the nested flatlist.

As a workaround for now try setting the [removeClippedSubviews](https://reactnative.dev/docs/flatlist#removeclippedsubviews) option in the **nested** FlatList to false.

**Comment by sankar-gp** [comment] 2024-10-08 03:20
any update?

**Comment by spyshower** [comment] 2024-10-12 10:18
@alduzy still not fixed.

**Comment by WKampel** [comment] 2024-10-12 21:05
Happens not only when navigating back for me, but also TO screens. I'm on 4.0.0-beta.9.

**Comment by alduzy** [comment] 2024-10-14 07:30
@spyshower @WKampel Under what circumstances does it fail, can you attach a reproduction?

**Comment by spyshower** [comment] 2024-10-14 10:18
2 lists in the same screen, one of them being horizontal, it crashes.

```
import { View, Text, Pressable, FlatList } from 'react-native';
import s from './styles';

export const Settings = () => {
    // const renderItem = (item, isLast) => {
    const renderItem = ({}) => {
        return <Text style={s.settings_item_label}></Text>;
    };

    const settings = [{}, {}, {}];

    return (
        <>

            <FlatList data={settings} renderItem={renderItem} />

            <FlatList data={settings} renderItem={renderItem} horizontal />
        </>
    );
};
```

**Comment by joarkosberg** [comment] 2024-10-14 11:14
@alduzy Will the fix be back ported to v3 also, or is upgrade to v4 required?

**Comment by alduzy** [comment] 2024-10-14 11:16
@spyshower Thanks for the repro, as you pointed out, the horizontal lists aren't handled properly. https://github.com/software-mansion/react-native-screens/pull/2383 fixes it.

**Comment by spyshower** [comment] 2024-10-14 11:18
@alduzy not really, I am on `^4.0.0-beta.9`

**Comment by alduzy** [comment] 2024-10-14 11:36
@joarkosberg We're going to backport it to v3 after we release a stable v4.

**Comment by alduzy** [comment] 2024-10-14 12:59
@spyshower You're right, the current change only considers **nested** horizontal lists. Thanks for noticing it!
I opened a PR that fixes the issue https://github.com/software-mansion/react-native-screens/pull/2403

**Closed** 2024-10-14 14:52 UTC
Labels: Platform: Android, Repro provided, NewArch

**Comment by spyshower** [comment] 2024-10-20 07:45
@alduzy I know this is closed but I have noticed an issue with animating a nested list using `reanimated 3.16.0`. I get something like this error https://stackoverflow.com/questions/58584676/react-native-filter-flatlist-error-index-10-count-0. Do you think it's related to this one or should I open an issue there?

**Comment by alduzy** [comment] 2024-10-21 09:08
@spyshower It's hard for me to tell given the information provided. Please open a new issue with some in-depth description and a reproduction code.

**Comment by talaikis** [comment] 2024-10-21 09:13
Latest beta works fine w. RN 0.75.5

**Comment by r0b0t3d** [comment] 2024-10-29 04:31
I'm using react native 0.76 with fabric. Here is my observation
1. Using 4.0.0-beta.16
--> Works, but I got issue blank screen when going back ( #1685). 
2. Using 3.35.0
--> Not working, but don't have issue blank screen when going back

**Comment by alduzy** [comment] 2024-10-29 11:19
@r0b0t3d I am unable to replicate the issues you mentioned on either `4.0.0-beta.16` or `3.35.0`. Could you provide some more details? Ideally, having a code snippet for reproduction would be helpful.

**Comment by dppo** [comment] 2024-11-16 14:38
This error still exists when using `react-native-drawer-layout`, similar to [12248](https://github.com/react-navigation/react-navigation/pull/12248). Are there any other fixes?

**Comment by tajinder-06** [comment] 2024-11-25 09:43
same issue

**Comment by kkafar** [comment] 2024-11-25 10:47
It might be that it certain scenarios this will still fail, however to patch this behaviour completely it must be handled in the upstream.

You can watch the progress here: https://github.com/facebook/react-native/pull/47634
