### ISSUE TITLE
headerCenter not working on Android

### ISSUE THREAD

**Issue by fmarquin** [software-mansion/react-native-screens#582] opened 2020-07-31 11:22 UTC
I am trying to include a custom component as a header. Just need to set a image and title in the center. The only one that works is headerRight. **Both headerCenter and headerLeft are not working.**
**Also I'm using typescript and in shows that screenOptions, headerCenter/left/right are not a valid option but headerLeft is working, so..**
I've tried using options and screenOptions.
Could you help me with this?
Thanks in advance.

```
<Stack.Screen
        name="ItemList"
        component={ItemListScreen}
        options={{
          headerStyle: { backgroundColor: '#f6f6f6' },      
          headerCenter: () => (
            <View>
              <Text>TESTING</Text>
            </View>
          ),
        }}
        screenOptions={{
          headerCenter: () => (
            <View>
              <Text>TESTING</Text>
            </View>
          ),
        }}
      />
```

**Comment by WoLewicki** [comment] 2020-07-31 13:36
It should work when put in `options` for the `Screen`. Can you provide a snack/repo which shows that it does not work correctly?

**Comment by fmarquin** [comment] 2020-08-01 17:40
Hi, I wanted to create a snack but I couldn't due to a dependency issue. I've created a branch named 'screen-issue' and granted Guest permissions on gitLab, the project name is mobius-app. Just need to clone and npm install. It's an expo project. StackNavigatior.tsx is the file where I've set the header stuff. You will be able to check two things:
-headerCenter is not working, both in options and in screenOptions.
-some properties are missing, because typescript indicates errors with properties that work ok.

Thanks in advance.

**Comment by WoLewicki** [comment] 2020-08-03 07:36
Could you please make a GitHub repository with the code needed to reproduce the issue rather than granting me any permissions to private repositories? The issues should be available for everyone to reproduce/work on it.

**Comment by emilisb** [comment] 2020-08-09 09:25
Same issue on iOS. `headerCenter` and `headerLeft` are not working, `headerRight` works.

**Comment by WoLewicki** [comment] 2020-08-10 07:45
@emilisb could you give me a link to the outdated docs?

**Comment by WoLewicki** [comment] 2020-08-11 11:00
I am closing this issue as it seems to be resolved. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2020-08-11 11:00 UTC
