### ISSUE TITLE
cannot access NestedScrollingParent3

### ISSUE THREAD

**Issue by Sume-Ishtiaq** [software-mansion/react-native-screens#630] opened 2020-09-11 20:15 UTC
The project runs fine on iOS without any issue, but gives the error mentioned below while compiling android project.

/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java:26: error: cannot access NestedScrollingParent3
  private static class NotifyingCoordinatorLayout extends CoordinatorLayout {
                 ^
  class file for androidx.core.view.NestedScrollingParent3 not found

**Comment by WoLewicki** [comment] 2020-09-14 08:38
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by WoLewicki** [comment] 2020-10-12 09:06
Closing due to no reproduction provided in 30 days. Feel free to comment to reopen.

**Closed by WoLewicki** 2020-10-12 09:06 UTC
Labels: Android, needs repro

**Comment by JakyChen** [comment] 2021-01-04 18:46
I ran into a similar issue and I wanted to share a solution in case anyone else was also facing a similar problem.

I upgraded my project build.gradle dependency from 3.2.0 to 3.6.2 and androidx.core version to 1.3.2 (I'm guessing NestedScrollingParent3 is a module in this newest androidx version)
dependencies {
    classpath('com.android.tools.build:gradle:3.6.2')
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.core' &&
                !details.requested.name.contains('androidx')) {
                details.useVersion "1.3.2"
            }
        }
    }
}

Try building it on Android Studio. I hope this helps!
