### ISSUE TITLE
Library Conflict with libfbjni.so

### ISSUE THREAD

**Issue by gianni-gulino-eleva** [software-mansion/react-native-screens#2463] opened 2024-10-29 10:44 UTC
### Description

I encountered an issue while building my React Native project (version 0.76.0) after installing the @react-navigation/native package.
After installing react-native-screens, as per @react-navigation/native documentation, when I attempt to build the project with "Make Project", I receive the following error:

Execution failed for task ':react-native-screens:mergeDebugAndroidTestNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libfbjni.so' from inputs:
      - /Users/name_user/Desktop/GitHub/test-farmer-app/testfarmer/node_modules/react-native-screens/android/build/intermediates/library_jni/debug/copyDebugJniLibsProjectOnly/jni/arm64-v8a/libfbjni.so
      - /Users/name_user/.gradle/caches/8.10.2/transforms/2fa3c78e855de2c4ef8aa6911c4216a0/transformed/react-android-0.76.0-debug/jni/arm64-v8a/libfbjni.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

I tried excluding on "android/app/build.gradle" with

android {
    packagingOptions {
        // Escludi le librerie specifiche nella cache di Gradle
        exclude "/Users/giannigulino/.gradle/caches/**/lib/arm64-v8a/libfbjni.so"
        exclude "/Users/giannigulino/.gradle/caches/**/lib/x86_64/libfbjni.so"
    }
} 

But I didn't solve it.

### Steps to reproduce

1. Install React Native 0.76.0
2. Install with "yarn add @react-navigation/native"
3. Install with "yarn add react-native-screens react-native-safe-area-context"
4. From Android Studio, "Make Project"

### Snack or a link to a repository

./

### Screens version

3.35.0

### React Native version

0.76.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2024-10-29 11:48
Hey @gianni-gulino-eleva, thanks for reporting the issue!
However I've just checked the 3.35.0 version of the library on fresh app & it seems that everything works properly, thus most likely the issue is down to some local specific configuration.

I would start with removing all the caches, including gradle `~/.gradle/caches`, `node_modules`, `android/app/build android/app/.cxx android/build`

I doubt we will be able to help more w/o problem reproduction. If you re able to reproduce this problem on fresh app, please create a repo & let us know. For now I'm closing this issue as I believe it is not related to the library setup, however I'm not limiting conversation. 

In case you manage to create reproduction or new circumstances /information arise tag me & I'll reopen.

**Closed by kkafar** 2024-10-29 11:48 UTC
Labels: Missing info, Platform: Android, Missing repro

**Comment by erie-e9** [comment] 2024-10-30 06:37
Android Studio: Hey guys, after run `~/.gradle/caches, node_modules, android/app/build android/app/.cxx android/build` I sync gradle and click on `Rebuild project` but I'm getting this error. Any idea?

Note: App is correctly installed on device using `Run app` but this only happens  on `Rebuild project`.

<img width="786" alt="Captura de pantalla 2024-10-30 a la(s) 12 26 59 a m" src="https://github.com/user-attachments/assets/f6bc69e8-73d0-462f-864f-2d6df0fe7737">

**Comment by kkafar** [comment] 2024-10-30 08:13
Hey @erie-e9, since you're second person who reports similar issue maybe we have a situation here. Are you able to reproduce this behaviour on fresh app?

**Comment by gianni-gulino-eleva** [comment] 2024-11-20 17:08
Hi @kkafar
I'm sorry for the delay in getting back to you. 
Tomorrow, I should be able to reproduce the issue in a repo and share it with you. In the meantime, thank you for your response—I really appreciate it!

**Comment by gianni-gulino-eleva** [comment] 2024-11-21 11:06
Hi! @kkafar ,
Here's the example repo that you can reproduce the issue:
https://github.com/gianni-gulino-eleva/react-native-screens-issue-2463

I updated this dependencies, the problem occurs again while Make Project from Android Studio:

    "@react-navigation/bottom-tabs": "^7.0.6",
    "@react-navigation/native": "^7.0.3",
    "@react-navigation/native-stack": "^7.1.0",
    "react-native-safe-area-context": "^4.14.0",
    "react-native-screens": "^4.2.0"

**Comment by kkafar** [comment] 2024-11-21 11:40
@gianni-gulino-eleva hey, I've taken a very quick look at the reproducer (only the code, haven't run it yet). It looks like you've created new app, added dependencies & some JS screens, right? If you haven't made any additional android-related setup then IMO this indicates that the problem is scoped to your local environment.

I doubt it's due to apple chip, I'm also using it and I do not encounter any such problems.

Have you tried following the steps I've recommended above? Citing them here:

>I would start with removing all the caches, including gradle: `~/.gradle/caches`, `node_modules`, `android/app/build` `android/app/.cxx` `android/build`.

While the fact that this happens in fresh project to you indicates that cleaning gradle caches makes most sense. Let me know, if purging the caches won't work I'll try to debug your repro

**Comment by gianni-gulino-eleva** [comment] 2024-11-22 16:23
Hi @kkafar, it seems that clearing the cache/build has made some progress:

> I would start with removing all the caches, including gradle: ~/.gradle/caches, node_modules, android/app/build android/app/.cxx android/build.

Now, i obtain this error:

FAILURE: Build failed with an exception.

* What went wrong:
Cannot locate tasks that match ':react-native-screens:testClasses' as task 'testClasses' not found in project ':react-native-screens'.

P.S: In addition to the above attempts, I have updated the version of react-native-screens to 4.3.0.

**Comment by Omnicpie** [comment] 2024-11-25 10:55
I had the above issue while running Detox and was able to fix it by adding the following patch:

```
diff --git a/node_modules/react-native-screens/android/build.gradle b/node_modules/react-native-screens/android/build.gradle
index 9b4a263..fe3c95a 100644
--- a/node_modules/react-native-screens/android/build.gradle
+++ b/node_modules/react-native-screens/android/build.gradle
@@ -119,7 +119,9 @@ android {
                 "**/libc++_shared.so",
                 "**/libreact_render*.so",
                 "**/libreactnativejni.so",
-                "**/libreact_performance_timeline.so"
+                "**/libreact_performance_timeline.so",
+                "**/libfbjni.so",
+                "**/libreactnative.so"
         ]
     }
     sourceSets.main {
```

Im running RN 0.76.2 and react-native-screens 3.35.0

**Comment by saeid-elio** [comment] 2024-12-11 09:41
I updated to react-native-screen 4.3.0 and even in RN's default AwesomeProject I'm getting same error in Android Stuiod and I went through all cleaning steps mentioned above and that didn't help:

> What went wrong:
> Execution failed for task ':react-native-screens:mergeDebugAndroidTestNativeLibs'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
>    > 2 files found with path 'lib/arm64-v8a/libfbjni.so' from inputs:
>       - /Users/sm/Apps/AwesomeProject/node_modules/react-native-screens/android/build/intermediates/library_jni/debug/copyDebugJniLibsProjectOnly/jni/arm64-v8a/libfbjni.so
>       - /Users/sm/.gradle/caches/8.10.2/transforms/53ca3ec166779873078450fc2e43b919/transformed/react-android-0.76.1-debug/jni/arm64-v8a/libfbjni.so
>      If you are using jniLibs and CMake IMPORTED targets, see
>      https://developer.android.com/r/tools/jniLibs-vs-imported-targets

sm@Mac AwesomeProject % npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 15.1.1
  CPU: (12) arm64 Apple M3 Pro
  Memory: 100.50 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.22
    path: /usr/local/bin/yarn
  npm:
    version: 10.8.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.09.23.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12550806
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.5
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

**Comment by saeid-elio** [comment] 2024-12-11 09:50
@kkafar Why did you close this issue? Obviously the problem still exists.

**Comment by alexandrumogic** [comment] 2024-12-17 14:34
Hi!

I am getting the same error, with latest version 4.3.0 , RN 0.76.5

* What went wrong:
Execution failed for task ':react-native-screens:mergeDebugAndroidTestNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libfbjni.so' from inputs:
   
  Any fix for this?

**Comment by saeid-elio** [comment] 2024-12-17 15:53
@alexandrumogic For me the problem got resolved after half a day of fighting with Android Studio, restarting it, cleaning builds and caches, syncing gradle, hopelessly changing stuff in settings, and so on. I have no idea what fixed it, but I just to let you know. See if you can report back what fixed the error for you. 

And while trying to fix it I ran into another issue in Android Studio which is reported [here](https://github.com/gradle/gradle/issues/25747) and which luckily someone has already posted a solution for it.

**Comment by vadzimk** [comment] 2025-01-06 18:02
The solution is to patch
node_modules/react-native-screens/android/build.gradle
```
    packagingOptions {
        // For some reason gradle only complains about the duplicated version of libreact_render libraries
        // while there are more libraries copied in intermediates folder of the lib build directory, we exclude
        // only the ones that make the build fail (ideally we should only include librnscreens_modules but we
        // are only allowed to specify exclude patterns)
        excludes = [
                "META-INF",
                "META-INF/**",
                "**/libjsi.so",
                "**/libc++_shared.so",
                "**/libreact_render*.so",
                "**/libreactnativejni.so",
                "**/libreact_performance_timeline.so",
                "**/libfbjni.so",  // <--- New (solution for this particular file)
                "**/libreactnative.so" // <--- New (also conflicts, and build succeeds when it is excluded)
        ]
    }
```
@kkafar could we see the fix for it in the next release?
