### ISSUE TITLE
RNSScreen crash with NSRangeException in iOS

### ISSUE THREAD

**Issue by Aung-Myint-Thein** [software-mansion/react-native-screens#633] opened 2020-09-13 09:15 UTC
Hello, 

I am using RNScreen with React-Navigation v5 in our app. I think sometimes when a user is using our app for a while, the app crashed with 

```
OS Version: iOS 13.6.1 (17G80)
Report Version: 104

Exception Type: EXC_CRASH (SIGABRT)
Crashed Thread: 22

Application Specific Information:
*** NSRunStorage (0x28360f480), _replaceElements(): replaced range {165, 96} extends beyond current run storage size 258.
```

Any recommendations for this issue? Will provide more info if need more. Thanks.

**Comment by WoLewicki** [comment] 2020-09-14 08:43
Can you provide more info? I haven't seen such a crash before. Is there an easy reproduction of this issue?

**Comment by Aung-Myint-Thein** [comment] 2020-09-14 10:28
This is the first time I see this crash in our app too. However, just 2 versions ago (1 month), we started using RNScreens. So, at this point, I am afraid wouldn't be able to get an easy reproduction of this issue yet. I am just wondering if anyone who uses this library with React-Navigation faced this problem before.

In my current set up, most of my screens are using `navigate()` on `nativeStack` and I am guessing after a user is using our app for a few mins, the screens on the stack is way too many for memory to handle. Then, when a screen with `replace()` is routed, maybe the app crashed.. Is it possible?

**Comment by WoLewicki** [comment] 2020-09-14 10:39
Are you stacking many screens one on another? Maybe there is some kind of limit on the native side. I can just leave this open, but I don't think I can help you anyhow without a reproduction.

**Comment by Aung-Myint-Thein** [comment] 2020-09-14 12:40
I have a stack but user can keep on navigating from a screen to another screen by tapping items on the page and maybe it got to the limit. I was thinking it is what this message `replaced range {165, 96} extends beyond current run storage size 258` mean :D .. what is the best approach or best practices for apps which can get many screens stacked? Is it better for performance to use `replace()` than simple `navigate()`

**Comment by WoLewicki** [comment] 2020-09-15 08:23
It is better for sure to use `replace` for memory consumption since you remove the screens that way. The drawback is that you cannot go back to a previous screen after that action.

**Comment by MiguelGrability** [comment] 2020-09-21 23:42
Hi, We are facing with crashes similars as this issue describes

![Screen Shot 2020-09-21 at 6 34 35 PM](https://user-images.githubusercontent.com/38761943/93831725-1bebe000-fc39-11ea-9183-2756b65c39f9.png)

Our app has been under test for months and now in production, we have been seeing these reports in our Sentry in both platforms ios and android

![Screen Shot 2020-09-21 at 6 38 01 PM](https://user-images.githubusercontent.com/38761943/93831901-a3d1ea00-fc39-11ea-9da9-03db8ef4fd7c.png)

We haven't reproduced and figured out how these issues occur and at this moment we are planning to turn react-native-screen off

**Comment by WoLewicki** [comment] 2020-09-29 13:11
@MiguelGrability why do you think it is the same issue? Please provide a repo with a reproduction of this problem so I could work on it.

**Comment by MiguelGrability** [comment] 2020-09-29 14:05
> @MiguelGrability why do you think it is the same issue? Please provide a repo with a reproduction of this problem so I could work on it.

I am not sure if this is the same issue but is the only issue that I found something similar, for months we have been testing our app with differents QA teams and beta testers, and we never receive this reports until we launch the app to stores

And the other problem is that we've never been able to reproduce that crashes, but they still reporting in our sentry

**Comment by WoLewicki** [comment] 2020-09-29 14:18
Unfortunately, I don't think I can help you anyhow without the reproduction of the crash since I also see it for the first time.

**Comment by WoLewicki** [comment] 2020-11-04 14:07
Closing due to no reproduction provided in 30 days, I cannot do much without it. Feel free to comment to reopen.

**Closed by WoLewicki** 2020-11-04 14:07 UTC
Labels: iOS, needs more info, needs repro
