### ISSUE TITLE
RNSScreens was not found in the UIManager.

### ISSUE THREAD

**Issue by nikhilmaurya-21** [software-mansion/react-native-screens#2291] opened 2024-08-08 07:44 UTC
### Description

I already install the react native screens library. but give me  this error.
**Invariant Violation: requireNativeComponent: "RNSScreen" was not found in the UIManager.**.
i also try to use latest version and old version but worked.
This package.json

"dependencies": {
    "@codler/react-native-keyboard-aware-scroll-view": "^2.0.1",
    "@react-native-async-storage/async-storage": "^1.19.0",
    "@react-native-community/datetimepicker": "^7.4.1",
    "@react-native-community/push-notification-ios": "^1.11.0",
    "@react-native-community/slider": "^4.5.0",
    "@react-native-firebase/app": "^18.7.3",
    "@react-native-firebase/messaging": "^18.7.3",
    "@react-navigation/drawer": "^6.7.2",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@react-navigation/stack": "^6.3.16",
    "axios": "^1.4.0",
    "formik": "^2.4.3",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-calendar-strip": "^2.2.6",
    "react-native-check-box": "^2.1.7",
    "react-native-flash-message": "^0.4.2",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-image-crop-picker": "^0.40.0",
    "react-native-linear-gradient": "^2.7.3",
    "react-native-modal-datetime-picker": "^17.1.0",
    "react-native-pager-view": "^6.2.3",
    "react-native-pell-rich-editor": "^1.9.0",
    "react-native-popup-menu": "^0.16.1",
    "react-native-push-notification": "^8.1.1",
    "react-native-raw-bottom-sheet": "^3.0.0",
    "react-native-reanimated": "^3.4.1",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^4.10.8",
    "react-native-screens": "^3.29.0",
    "react-native-searchable-dropdown-kj": "^1.9.3",
    "react-native-sectioned-multi-select": "^0.10.0",
    "react-native-signature-capture": "^0.4.12",
    "react-native-simple-toast": "^3.0.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-tab-view": "^3.5.2",
    "react-native-table-component": "^1.2.2",
    "react-native-vector-icons": "^10.0.0",
    "react-native-webview": "^13.6.0",
    "react-native-wheel-color-picker": "^1.2.0",
    "yup": "^1.2.0"
  },

### Steps to reproduce

none

### Snack or a link to a repository

none

### Screens version

3.29.0

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2024-08-08 09:31
Hey @nikhilmaurya-21, this issue often happens when there are multiple instances of `react-native` running in the project or simply because of some invalid dependency cache. 

Running `rm -fr node_modules android/build android/app/build && yarn install` and then rebuilding the native code either via Android studio or simply by `yarn run android` usually helps, if there are no other misconfigurations in user project. 

I'm closing this issue, because it pops up quite often due to reasons described above. If this does not help, please provide a reproduction so that we can investigate the issue.

**Closed by kkafar** 2024-08-08 09:31 UTC
Labels: Platform: Android, Missing repro
