### ISSUE TITLE
Conditional rendering of a screen shows a blank screen (new arch)

### ISSUE THREAD

**Issue by SpaghettiC0des** [software-mansion/react-native-screens#1628] opened 2022-11-02 17:49 UTC
### Description

Related to #690

I'm playing around with new architecture and the native stack navigator, and I encountered this issue. It's working properly when using  the JS based stack navigator. 

I have a simple redux state `isLoggedIn` which is just a simple `boolean` flag to simulate an authenticated user. I have a button to toggle the state to replace `AuthStack` with the `MainStack`. You know, the classic architecture for auth flow with react-navigation. More info on the [official docs.](https://reactnavigation.org/docs/auth-flow/#define-our-screens)

### Steps to reproduce

Just follow the example here https://reactnavigation.org/docs/auth-flow/#define-our-screens

### Snack or a link to a repository

https://github.com/karlmarxlopez/rn-navigation-native-stack-new-arch-issue

### Screens version

3.18.2

### React Native version

0.70.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2022-11-24 11:25
Hi @karlmarxlopez, the [link to reproduction you provided](https://github.com/karlmarxlopez/rn-navigation-native-stack-new-arch-issue) seems to be outdated / invalid (or maybe the repository is private?). Would you mind updating this?

**Comment by martinraveglia** [comment] 2023-01-02 17:06
I'm having exactly the same issue here! We are using the New Architecture and for now just 4 screens with a basic auth flow as follows,

```
import React from 'react';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import useIsSignedIn from '../../hooks/isSignIn';
import {appNavOptions, mainStackNavOption} from '../../helpers';
import {Routes, StackParamList} from '../../interfaces';
import TabNavigator from '../tabNavigator';
import {CreateAccount, Login, SelectPlayers} from '../../screens';

export const Stack = createNativeStackNavigator<StackParamList>();

const MainStack = () => {
  const isSignedIn = useIsSignedIn();
  return (
    <Stack.Navigator screenOptions={mainStackNavOption}>
      {isSignedIn ? (
        <>
          <Stack.Screen
            name={Routes.HOME}
            component={TabNavigator}
            options={appNavOptions[Routes.HOME]}
          />
          <Stack.Screen
            name={Routes.SELECT_PLAYERS}
            component={SelectPlayers}
            options={appNavOptions[Routes.SELECT_PLAYERS]}
          />
        </>
      ) : (
        <>
          <Stack.Screen
            name={Routes.LOG_IN}
            component={Login}
            options={appNavOptions[Routes.LOG_IN]}
          />
          <Stack.Screen
            name={Routes.CREATE_ACCOUNT}
            component={CreateAccount}
            options={appNavOptions[Routes.CREATE_ACCOUNT]}
          />
        </>
      )}
    </Stack.Navigator>
  );
};

export default MainStack;
```

When the `isSignedIn` state changes, I get a completely blank screen.

For example, if we are logged out, I can see the LogIn screen fully interactive and shown correctly. After we log in, the `isSignedIn` state changes for the first time, from false to true, a blank screen is shown

**Comment by aldiazveGlobant** [comment] 2023-01-03 21:53
I'm having the same issue :'c

**Comment by aldiazveGlobant** [comment] 2023-01-04 03:44
@kkafar Hi! I just create a repo reproducing the error: https://github.com/aldiazveGlobant/react-native-screens-stack-error

Is an app using the new architecture, just run it and press de button at the bottom; Android works just fine, but iOS renders an empty view and never recovers. 

Let me know if I can help on anything else!

**Comment by Onedayago** [comment] 2023-01-11 05:56
RNSScreenStack.mm 代码更改如下

注释下面的代码
<img width="833" alt="截屏2023-01-11 13 55 31" src="https://user-images.githubusercontent.com/28590738/211728545-42eb5e02-7c71-424d-8b5a-b7d8bb86b8c9.png">
// when there is no change we return immediately
//   if ([_controller.viewControllers isEqualToArray:controllers]) {
//     return;
//   }

下面的代码增加
auto screenController = (RNSScreen *)top;
   [screenController resetViewToScreen];

<img width="833" alt="截屏2023-01-11 13 55 52" src="https://user-images.githubusercontent.com/28590738/211728596-bba121d1-83b4-4581-be23-8a11ab7514a3.png">

上面的更改对我有些，希望作者看下是否有用

**Comment by cospin** [comment] 2023-01-11 19:39
@kkafar can you check this please? It's currently unusable in iOS projects that use conditional rendering on new arch.

**Comment by karlmarxlopez** [comment] 2023-02-22 04:53
@kkafar can we remove the missing repro label now? It's already provided by @martinraveglia

**Comment by AamirHafiez** [comment] 2023-02-23 06:45
@Onedayago node module fix worked for me. Thanks.
https://github.com/software-mansion/react-native-screens/issues/1628#issuecomment-1378273906

**Comment by batuhansahan** [comment] 2023-04-19 14:50
has anyone on android in here, i have same issue with android, it just show empty page but i can see the logs from new screen.

**Comment by notmarinho** [comment] 2023-04-27 20:18
A **partial solution** to this issue: 

1. Locate the file`node_modules/react-native-screens/ios/RNSScreenStack.mm.`
2. Open the file and find the function `setPushViewControllers`.
3. **Comment** out the following block of code within the function:
```
// when there is no change we return immediately
if ([_controller.viewControllers isEqualToArray:controllers]) {
  return;
}
````

4. **Add the following** lines of code at the bottom of the else statement within the function:
```
else {
    // change wasn't on the top of the stack. We don't need animation.
    auto screenController = (RNSScreen *)top;  // Add this line
    [screenController resetViewToScreen];   // Add this line
    [_controller setViewControllers:controllers animated:NO];
  }
 ```

**Comment by affansk** [comment] 2023-06-23 10:37
@notmarinho  this is not working after release of 0.72 and react native screens new version

**Comment by khanakia** [comment] 2023-08-17 04:03
Thanks to @notmarinho his solution worked for now 😄 .

But is there any official fix yet? 

This I have Protected Routes and Auth Routes and when switching Stack with isSignedIn() conditionally it breaks and shows the Blank Screen.

```tsx
 <NavigationContainer>
      {isAuthenticated() ? <AppStack /> : <AuthStackNavigator />}
 </NavigationContainer>
```

**Comment by Onedayago** [comment] 2023-08-22 06:31
My solution is also a bit problematic. I hope the official can fix it as soon as possible

**Comment by Tracht** [comment] 2023-09-22 10:06
We are also having the same issues on iOS. @Onedayago your solution worked for us, I haven't run into any issues yet.

**Comment by Tracht** [comment] 2023-09-22 10:09
@kkafar will an official fix come out soon?

**Comment by awmoreira** [comment] 2023-09-26 21:39
+1

**Comment by MaxWesley** [comment] 2023-09-26 21:39
+1

**Comment by jokerhp6789** [comment] 2023-10-04 04:56
Today I encountered the same issue with my app update to the newest version of react native 0.72.4 and the New Architecture is enabled. The app is working fine in the Old Architecture. 
Thanks to the solution of @Onedayago  it help resolve the issue, and I haven't got any other issues related to this one so far. 
Hope this bug will be fixed soon in the future update of the package

**Comment by ganselu** [comment] 2023-10-23 12:08
+1

**Comment by tboba** [comment] 2023-11-20 10:16
Hi guys! Do you know if this problem still appears in react-native-screens 3.27.0? I just tested the reproduction provided by @aldiazveGlobant and unfortunately I cannot achieve blank screen, even if given components are being rendered conditionally 😕 

https://github.com/software-mansion/react-native-screens/assets/23281839/1a27158c-d7a0-4289-9b8c-60057f1c023b

**Comment by aldiazve** [comment] 2023-11-20 15:04
Hi @tboba! Let me double check and i'll get back to you! Thanks for the reply btw.

**Comment by samuelBenh** [comment] 2023-11-20 15:36
I updated react-native-screens to  3.27.0 to and still have the problem :(

**Comment by tboba** [comment] 2023-11-20 15:49
@samuelBenh thank you for providing the info! On which device and OS are you testing your application? Maybe I've got wrong / too newest environment (or the repro does not reflect actual bug) 🤔

**Comment by samuelBenh** [comment] 2023-11-20 15:52
> @samuelBenh thank you for providing the info! On which device and OS are you testing your application? Maybe I've got wrong / too newest environment (or the repro does not reflect actual bug) 🤔

I tested it on my personal device. I also tested before in my Emulator (Iphone 14 pro, IOS 16.2)

Here are the OS version and model of my personal device i tested with:

![image](https://github.com/software-mansion/react-native-screens/assets/57507399/107c23dc-04a5-47a2-bd65-eb76ff1c47e2)

**Comment by Onedayago** [comment] 2023-11-20 15:54
may be you do not enable fabric



---Original---
From: "Samuel ***@***.***&gt;
Date: Mon, Nov 20, 2023 23:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [software-mansion/react-native-screens] Conditional rendering ofa screen shows a blank screen (new arch) (Issue #1628)




  
@samuelBenh thank you for providing the info! On which device and OS are you testing your application? Maybe I've got wrong / too newest environment (or the repro does not reflect actual bug) 🤔
  
I tested it on my personal device. I also tested before in my Emulator (Iphone 14 pro, IOS 16.2)
 
Here are the OS version and model of my personal device i tested with:

**Comment by tboba** [comment] 2023-11-20 16:19
@Onedayago ...yeah 😅 Thanks for pointing that out!
That may sound easy, but I just double-checked if I've got fabric enabled on that project and while I was testing it I just did `pod install` on iOS directory instead of `yarn pod-install` which should build the fabric version of the app.
As I'm testing this app right now the repro seems to be correct (I can see the white screen!). Sorry for my mistake! 🙈

**Comment by samuelBenh** [comment] 2023-11-21 16:33
Update: I realised that my screen that changed the login condition was a 'fullscreenModal'

When i remove it the transition works well and i don't have the blank screen !

<img width="396" alt="Capture d’écran 2023-11-21 à 17 29 30" src="https://github.com/software-mansion/react-native-screens/assets/57507399/5df6c3b1-a39a-4709-9a82-48e6e2cbbc1b">

**Comment by tboba** [comment] 2023-11-21 16:37
@samuelBenh in my case I'm still getting blank screen, even on the normal screen 😕 
However, I believe that I've found the starting point of the bug! I'm still thinking what are the conditions that shouldn't pass by the if statement, but I am close 👀 Modals are still waiting to test them though.

**Comment by tboba** [comment] 2023-11-27 11:03
Hi guys, I believe I've found the solution for this issue! Could you test whether this change works correctly on your environment?
You can test those changes by changing `react-native-screens` dependency in your package.json to:

```json
"react-native-screens": "software-mansion/react-native-screens#@tboba/fix-conditional-rendering"
```

**Comment by samuelBenh** [comment] 2023-11-27 15:00
I changed the package as you mentionned installed my app again. My case was to add back the parameter

`presentation: 'fullScreenModal',`

When i added it back it is still not doing the transition and brings me to a white screen. :(

**Comment by tboba** [comment] 2023-11-27 15:21
@samuelBenh That's strange 🤔 could you describe how does your scenario like? How does your hierarchy of screens inside navigator look like? Do you have some nested views in modal?
If it's possible, could you create a minimal repro of your case?

**Comment by samuelBenh** [comment] 2023-11-27 15:27
My app navigation look like this

```
return (
    <Stack.Navigator
      screenOptions={{
        contentStyle: tailwind('bg-white'),
        headerShown: false,
        animation: 'slide_from_right',
      }}>
      {startedFirstTraining ? (
        <Stack.Screen name="Main" component={HomeStackNavigation} />
      ) : (
        <Stack.Screen name="AuthNavigation" component={AuthNavigation} />
      )}
    </Stack.Navigator>
```

Inside my Authnavigation i have a screen that have the parameter `presentation: 'fullScreenModal'`

This modal screen toggle the value that make the transition from the AuthNavigation to the HomeStackNavigation.
The transition is working when i remove the `presentation: 'fullScreenModal'`. Otherwise the transition is not working and lead me to a white screen

**Comment by tboba** [comment] 2023-11-27 15:44
@samuelBenh I assume that AuthNavigation is another nested stack that manages to open fullscreen modal, right? If so, could you also show how that navigation looks like?

**Comment by samuelBenh** [comment] 2023-11-28 16:00
Yess. I removed other stack screen but it looks like this

```
<Stack.Navigator
      screenOptions={{
        headerShown: false,
        contentStyle: tailwind('bg-white'),
        animation: 'slide_from_right',
      }}>
      <Stack.Screen
        name="AdModal"
        options={{
          animation: 'slide_from_bottom',
        }}
        component={AdModal}
      />
    </Stack.Navigator>
```

**Comment by tboba** [comment] 2023-11-28 16:25
@samuelBenh Great! Thanks for that. I'll try to check that tomorrow and will come with what I've observed soon.

**Comment by samuelBenh** [comment] 2023-11-30 15:18
> @samuelBenh I've tried the steps you have provided and I still cannot get working scenario with the blank screen 😕 I'm trying to switch between states and I have no luck with it, unfortunately. Can you correct me if I'm doing something wrong?
> 
>  Screen.Recording.2023-11-30.at.16.05.07.mov 
> My repro:
> 
> ```tsx
> const Home = () => (
>   <View style={styles.view}>
>     <Text>This is the initial View</Text>
>   </View>
> );
> 
> const NestedHome = () => (
>   <View style={styles.view}>
>     <Text>This is nested view!</Text>
>   </View>
> );
> 
> const NestedStack = createNativeStackNavigator();
> 
> const AuthNavigation = () => (
>   <NestedStack.Navigator
>     screenOptions={{ headerShown: false, animation: 'slide_from_right' }}>
>     <NestedStack.Screen
>       name="NestedScreen"
>       component={NestedHome}
>       options={{
>         animation: 'slide_from_bottom',
>         presentation: 'fullScreenModal',
>       }}
>     />
>   </NestedStack.Navigator>
> );
> 
> const Stack = createNativeStackNavigator();
> 
> const Test1978 = () => {
>   const [hasChangedState, setHasChangedState] = useState(true);
> 
>   return (
>     <NavigationContainer>
>       <Stack.Navigator
>         screenOptions={{ headerShown: false, animation: 'slide_from_right' }}>
>         {hasChangedState ? (
>           <Stack.Screen name="Home" component={Home} />
>         ) : (
>           <Stack.Screen
>             name="AuthNavigation"
>             component={AuthNavigation}
>           />
>         )}
>       </Stack.Navigator>
>       <TouchableOpacity
>         style={styles.button}
>         onPress={() => setHasChangedState(old => !old)}>
>         <Text>Change state</Text>
>       </TouchableOpacity>
>     </NavigationContainer>
>   );
> };
> 
> const styles = StyleSheet.create({
>   button: {
>     justifyContent: 'center',
>     alignItems: 'center',
>     height: 100,
>   },
>   view: {
>     alignItems: 'center',
>     backgroundColor: '#b7c4bb',
>     flex: 1,
>     justifyContent: 'center',
>     padding: 12,
>   },
> });
> 
> export default Test1978;
> ```

Thanks ! You have almost the same setup as me. The only change i notice is maybe that my home navigation is also a nested stack like the AuthNavigation.

**Comment by tboba** [comment] 2023-11-30 16:39
@samuelBenh I tried to make your case more tricky and change the logic of opening the fullscreen modal (somehow I cannot open the fullscreen modal while opening AuthNavigation). Unfortunately even if I'm opening the modal I'm still managing to change the views conditionally 🤔 

https://github.com/software-mansion/react-native-screens/assets/23281839/3cd12416-1e0b-4fc6-b03b-0bacd6491b3b

I did the same thing with classic modals and changing the condition still works there.

https://github.com/software-mansion/react-native-screens/assets/23281839/d1c2d8ca-9815-42ca-bd62-3353ccac85c1

```tsx
type StackParamList = {
  Home: undefined;
  AuthNavigation: undefined;
  Start: undefined;
  ConditionalScreen: undefined;
};

interface MainScreenProps {
  navigation: NativeStackNavigationProp<StackParamList>;
}

const Home = () => (
  <View style={styles.view}>
    <Text>This is the initial View</Text>
  </View>
);

const NestedHome = () => (
  <View style={styles.view}>
    <Text>This is nested view!</Text>
  </View>
);

const NestedStack = createNativeStackNavigator();
const OmegaNestedStack = createNativeStackNavigator();

const HomeNavigation = () => (
  <OmegaNestedStack.Navigator
    screenOptions={{ headerShown: false, animation: 'slide_from_right' }}>
    <OmegaNestedStack.Screen
      name="NestedScreen"
      component={Home}
      options={{
        animation: 'slide_from_bottom',
      }}
    />
  </OmegaNestedStack.Navigator>
);

const AuthNavigation = () => (
  <NestedStack.Navigator
    screenOptions={{ headerShown: false, animation: 'slide_from_right' }}>
    <NestedStack.Screen
      name="NestedScreen"
      component={NestedHome}
      options={{
        animation: 'slide_from_bottom',
      }}
    />
  </NestedStack.Navigator>
);

const Stack = createNativeStackNavigator();
const StartStack = createNativeStackNavigator();

const AppView = ({ navigation }: MainScreenProps) => (
  <View>
    <TouchableOpacity onPress={() => navigation.navigate('ConditionalScreen')}>
      <Text>Open me!</Text>
    </TouchableOpacity>
  </View>
);

const App = () => {
  return (
    <NavigationContainer>
      <StartStack.Navigator>
        <Stack.Screen name="Start" component={AppView} />
        <Stack.Screen
          name="ConditionalScreen"
          component={RealTestScenario}
          options={{ presentation: 'modal', headerShown: false }}
        />
      </StartStack.Navigator>
    </NavigationContainer>
  );
};

const RealTestScenario = () => {
  const [hasChangedState, setHasChangedState] = useState(true);

  return (
    <>
      <Stack.Navigator
        screenOptions={{
          headerShown: false,
          animation: 'slide_from_right',
        }}>
        {hasChangedState ? (
          <Stack.Screen name="Home" component={HomeNavigation} />
        ) : (
          <Stack.Screen name="AuthNavigation" component={AuthNavigation} />
        )}
      </Stack.Navigator>
      <TouchableOpacity
        style={styles.button}
        onPress={() => setHasChangedState(old => !old)}>
        <Text>Change state</Text>
      </TouchableOpacity>
    </>
  );
};

const styles = StyleSheet.create({
  button: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 100,
  },
  view: {
    alignItems: 'center',
    backgroundColor: '#b7c4bb',
    flex: 1,
    justifyContent: 'center',
    padding: 12,
  },
});

export default App;
```

**Comment by rzckztman** [comment] 2023-12-12 13:12
@tboba Thank you - I tried your fix and can confirm that it works in my app.

There is a remaining issue where the screens switch over immediately and don't respect the `animationTypeForReplace` option.

If we use this example from the react-navigation documentation:
https://reactnavigation.org/docs/7.x/auth-flow#define-our-screens

```
<Stack.Navigator>
  {state.userToken == null ? (
    // No token found, user isn't signed in
    <Stack.Screen
      name="SignIn"
      component={SignInScreen}
      options={{
        title: 'Sign in',
        // When logging out, a pop animation feels intuitive
        // You can remove this if you want the default 'push' animation
        animationTypeForReplace: state.isSignout ? 'pop' : 'push',
      }}
    />
  ) : (
    // User is signed in
    <Stack.Screen name="Home" component={HomeScreen} />
  )}
</Stack.Navigator>
```

The pop/push animation is not applied in this case.

**Comment by tboba** [comment] 2023-12-12 13:28
@rzckztman thanks for confirming this works for you!
I already know about missing animation when screen is replaced conditionally but I believe there's no solution that resolves this problem for now. Because Fabric uses a new method of screen mounting that recycles the view under the hood we would need to mount the conditional screen as a new screen which is not that easy to do. Maybe after merging @WoLewicki PR in React Native ([#35378](https://github.com/facebook/react-native/pull/35378)) it would be easier to do, but so far no luck 😕

**Closed** 2024-03-20 18:16 UTC
Labels: Platform: iOS, Missing repro

**Comment by nvbach91** [comment] 2024-05-27 21:05
Hi @tboba, I'm having this conditional rendering blank screen issue only on iOS when using `@react-navigation/material-top-tabs`

Here is a [minimal reproduction snack](https://snack.expo.dev/@nvbach91/bug---conditionally-rendering-screens-in-react-navigation---material-top-tab-navigator?platform=ios). This happens on both Expo SDK 50, Expo SDK 51, in Expo Go and also as ipa production build.

Strangely enough, the blank screen starts to render right after I navigate to a second screen (by clicking on the tab nav at the bottom or by calling `navigation.navigate('...')`) and it seems to always affect the first screen in a conditional stack of screens. 

![screen-capture1-ezgif com-video-to-gif-converter](https://github.com/software-mansion/react-native-screens/assets/20724910/32737f80-6b5c-4cb7-a0c0-d090118becf4)

I have just posted a stackoverflow [here](https://stackoverflow.com/questions/78541065/react-navigation-material-top-tabs-navigator-conditional-rendering-blank-screen)

Would you mind have a look at it? Thank you very much

**Comment by tboba** [comment] 2024-05-28 09:10
Hi @nvbach91, that looks strange 🤔
I see that on your snack, you have react-native-screens with 3.29.0 version installed. Have you tried using 3.31.1 version and checking if you can still spot that issue?

**Comment by nvbach91** [comment] 2024-05-28 11:13
Hi @tboba, Expo Snack doesn't allow `react-native-screens@3.31.1` but I have it on my local dev. I have tried to `yarn clean cache` and `npm clean cache` to make sure the newer (also tried older) versions of `react-native-screens` are installed but it didn't help.

I have created a minimal git repo for you [here](https://github.com/nvbach91/react-navigation-test) in case you want to test it your self locally.

Since this only happens with Material Top Tabs (where I primarily want the swipe between screens behavior) I think the issue is in one of these packages:
- `@react-navigation/material-top-tabs`
- `react-native-reanimated`
- `react-native-screens`
- `react-native-pager-view`

What do you think?

**Comment by lvlupharshit** [comment] 2024-11-14 00:54
My SAME problem was solved when I added backgroundColor to outer container

```
<GestureHandlerRootView
        style={{ flex: 1, backgroundColor: Colors.blackTheme.backgroundPrimary }}
      >
        <BottomSheetModalProvider>
          <NavigationContainer linking={linkingObject}>
            <Stack.Navigator
              initialRouteName="MainAppScreen"
              screenOptions={{ headerShown: false, animation: "none" }}
            >
              {/* TODO => Improve Flickering of Going Back Down Animation */}
              {/* Rendering Screens */}
              {Object.entries(screens).map(([name, component]) => (
                <Stack.Screen key={name} name={name} component={component} />
              ))}

              {/* Animation Slide From Bottom Screens */}
              <Stack.Group screenOptions={{ animation: "slide_from_bottom" }}>
                {Object.entries(bottomSlideScreens).map(([name, component]) => (
                  <Stack.Screen key={name} name={name} component={component} />
                ))}
              </Stack.Group>
            </Stack.Navigator>
          </NavigationContainer>
        </BottomSheetModalProvider>
      </GestureHandlerRootView>
 ```

**Comment by rocketraman** [comment] 2025-05-22 18:35
I had this problem as well, with react-native-screens 4.10.0. Interestingly, @lvlupharshit 's solution of adding a background color to the outer container does indeed resolve the problem.
