### ISSUE TITLE
Wrong icon color when push modal on iOS

### ISSUE THREAD

**Issue by blueberry6401** [software-mansion/react-native-screens#767] opened 2021-01-05 19:44 UTC
## Description

When form sheet or page sheet modal is pushed, info icon on status bar should change color to white as shown

### Screenshots

| RNC      | Right |
| ----------- | ----------- |
|![ezgif-6-a1f17d5dd8c6](https://user-images.githubusercontent.com/7337535/103691468-cc070e00-4fc8-11eb-9344-c474fbed47be.gif)|![ezgif-6-dfd7927aed0c](https://user-images.githubusercontent.com/7337535/103691489-d3c6b280-4fc8-11eb-8a50-da1433fc6dbb.gif) |

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Screens: 2.16.1

**Comment by WoLewicki** [comment] 2021-01-11 14:35
You can control the the color of the status bar icons with a prop: [`statusBarStyle`](https://github.com/software-mansion/react-native-screens/tree/master/native-stack#statusbarstyle). Does it solve your issue?

**Comment by MoOx** [comment] 2021-01-29 10:49
I would  have expected this to work out of the box. That's weird for a DX point of view.
I started to use native-screens to have a more native experience and have less to worry about and would have expected to have this handled as this seems trivial (formSheet on iOS => status bar light when there is more than one screen, am I right?).

I guess if that's not handled, it's because iOS doesn't handle this built-in? Can we add this in this library to have this built-in?

**Comment by MoOx** [comment] 2021-01-29 10:50
Because how can we know what color to use? If I have a screen that's white and pushed first, I need dark status bar. But what if this screen is pushed after? I will need light and I cannot really no, or am I missing something?
react-navigation stack (js implementation) handle this if I am correct.

**Comment by MoOx** [comment] 2021-01-29 10:55
Also we don't know (or don't want to make the test manually) the version of iOS we runs on, and so we don't know if formSheet exist (ex: I am testing on an iPhone 5c and there is no "formSheet" effect, so I don't really want to have a very complexe `statusBarStyle` value based on OS and position in the stack, when it could be done in this library.

I can help with the right pointers :)

**Comment by WoLewicki** [comment] 2021-02-03 16:50
Can you check if #798 fixes all of the problems and does not introduce any new bugs?

**Comment by MoOx** [comment] 2021-02-03 17:13
Sorry I don't have any bandwidth for this until next week, meanwhile I used js implementation because I got too much bugs with this native one (mostly `navigate()` call that were doing nothing and no error)

**Comment by WoLewicki** [comment] 2021-02-03 17:16
@MoOx could you submit issues with all of the other bugs that you spotted? It would for sure help with resolving them.

**Comment by MoOx** [comment] 2021-02-03 17:18
I kept my work in a branch and want to be sure to reproduce before opening issues, I will try that next friday as I really would like to have use this native module :)

**Closed** 2021-02-10 15:46 UTC
Labels: iOS, native-stack

**Comment by MoOx** [comment] 2021-02-12 18:28
@WoLewicki I am currently trying master with your included fix, it seems great!

That said, I have some custom headers that didn't use safe area in the past (because formSheet was on all platform, since I used the JS implementation) but now that formSheet is only on iPhone X+ devices, how can I know if I should add my safe area padding?
This will be clear with images :) 

![IMG_E4975](https://user-images.githubusercontent.com/157534/107807394-5aa94080-6d68-11eb-90d8-7cdd77a82f24.jpeg)

![IMG_E4974](https://user-images.githubusercontent.com/157534/107807389-57ae5000-6d68-11eb-9e23-0fbb3046b6be.jpeg)

I guess, could we have a static method to know if formSheet is supported?

**Comment by WoLewicki** [comment] 2021-02-15 10:20
IIRC, the new presentation style is available since iOS 13, so I believe you can just use methods provided by `react-native` to check the current version: https://reactnative.dev/docs/platform-specific-code#detecting-the-ios-version. But adding a method in `react-native-screens` that does the same under the hood can be a good option too. I am open to merge a PR with this for sure.

**Comment by MoOx** [comment] 2021-02-15 17:41
@WoLewicki it's iOS 13 + notch? Because I don't think and iPhone 6s/7/8 will have this even if they run on iOS 14.

**Comment by WoLewicki** [comment] 2021-02-16 09:17
I think it is only the matter of the iOS version. Here you have an iPhone 6s simulator with iOS 14.4: 
![image](https://user-images.githubusercontent.com/32481228/108042518-2ff90980-7040-11eb-87a0-4c5677c8a63e.png)

**Comment by MoOx** [comment] 2021-02-16 18:27
I guess you are right :) Sorry for the bad information. I will try to do a PR for this method.

I have currently a simple thing like this (rescript): 

```rescript
let isFormSheetSupported = Platform.os === Platform.ios && versionIos > "13"
```

(I can do that in JS very easily, don't worry haha)

Will this be ok for you?

Also I have this too

```rescript
let formSheetStatusBarStyle = (theme, barStyle) =>
  isFormSheetSupported ? #lightContent : statusBarStyle(theme, barStyle)

let formSheetSafeArea = isFormSheetSupported ? false : true
```

But I guess this can stick to user land.

**Comment by WoLewicki** [comment] 2021-02-17 16:45
I think you can make a PR with both of these things and we can move the discussion there to keep it in one place.
