### ISSUE TITLE
[Android] headerTitleStyle is ignored

### ISSUE THREAD

**Issue by mlecoq** [software-mansion/react-native-screens#1132] opened 2021-09-15 08:06 UTC
## Description

With react-navigation (native-stack), I try to customize header user `headerTitleStyle` prop. I see that those prop are well passed to `ScreenStackHeaderConfig` but it has no effect (works fine on Web and iOS)

Even if I hardcode a value 

```
  <ScreenStackHeaderConfig
      backButtonInCustomView={backButtonInCustomView}
      backgroundColor={
        headerStyleFlattened.backgroundColor ??
        (headerTransparent ? 'transparent' : colors.card)
      }
      backTitle={headerBackTitleVisible ? headerBackTitle : ' '}
      backTitleFontFamily={backTitleFontFamily}
      backTitleFontSize={headerBackTitleStyleFlattened.fontSize}
      blurEffect={headerBlurEffect}
      color={tintColor}
      direction={I18nManager.isRTL ? 'rtl' : 'ltr'}
      hidden={headerShown === false}
      hideBackButton={headerBackVisible === false}
      hideShadow={headerShadowVisible === false}
      largeTitle={headerLargeTitle}
      largeTitleBackgroundColor={headerLargeStyleFlattened.backgroundColor}
      largeTitleColor={headerLargeTitleStyleFlattened.color}
      largeTitleFontFamily={largeTitleFontFamily}
      largeTitleFontSize={headerLargeTitleStyleFlattened.fontSize}
      largeTitleFontWeight={headerLargeTitleStyleFlattened.fontWeight}
      largeTitleHideShadow={headerLargeTitleShadowVisible === false}
      title={typeof headerTitle === 'string' ? headerTitle : titleText}
      titleColor={
        headerTitleStyleFlattened.color ?? headerTintColor ?? colors.text
      }
      titleFontFamily={titleFontFamily}
      titleFontSize={8}
      titleFontWeight={headerTitleStyleFlattened.fontWeight}
      topInsetEnabled={insets.top !== 0}
      translucent={
        // This defaults to `true`, so we can't pass `undefined`
        headerTransparent === true
      }
    >
```

in HeaderConfig file of react-navigation/native-stack 

### Screenshots

![screenshot-1631692378270](https://user-images.githubusercontent.com/3649784/133393228-97de1424-3d16-4478-a132-012170bebee5.png)

## Steps To Reproduce

1. Configure header title style in your screen options 

```
 <Stack.Navigator
      screenOptions={{
        headerTitleAlign: 'center',
        headerTitleStyle: {
          fontSize: 2,
          fontFamily: 'SFProDisplay-Medium',
          fontWeight: '500',
        },
      }}>
```

### Expected behavior

Title is displayed according to `headerTitleSTyle`prop

### Actual behavior

`headerTitleStyle` has no effect

## Snack or minimal code example

https://snack.expo.dev/@mlecoq/react-native-screen---header-style-issue

## Package versions

- React: 17.0.2
- React Native: 0.65.1
- React Native Screens: 3.7.2

**Comment by kacperkapusciak** [comment] 2021-09-15 08:28
Duplicate of https://github.com/react-navigation/react-navigation/issues/9885
Issue should be fixed in the next release of `@react-navigation/native-stack` by https://github.com/react-navigation/react-navigation/commit/127e030e03cfec9600cca0327edd159a7bb08896

Cheers

**Closed by kacperkapusciak** 2021-09-15 08:28 UTC
