### ISSUE TITLE
How ot draw over a `formSheet` screen ? 

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-screens#587] opened 2020-08-03 02:04 UTC
```jsx
<>
  <NavigationContainer>
    <Stack.Navigator screenOptions={{ stackPresentation: 'formSheet' }} .... >
  </NavigationContainer> 
  <View style={{
   ...Stylesheet.absoluteFillObject,
   zIndex: 1000, 
   backgroundColor: 'rgba(0,0,0,0.4)'
  }}/> /* <<< */
</>
```

the View will always be behind the formSheet screen, 

is there a way to have something render above the formSheet that's not a modal screen ?

**Comment by WoLewicki** [comment] 2020-08-03 10:59
Could you check if it is not duplicate of #525?

**Comment by a-eid** [comment] 2020-08-03 12:13
@WoLewicki yeah, that's possibly duplicated.

**Closed** 2020-08-03 12:13 UTC
