### ISSUE TITLE
Memory leak in iOS

### ISSUE THREAD

**Issue by xutm** [software-mansion/react-native-screens#92] opened 2019-04-29 08:54 UTC
### bug
Used by in iOS will cause  memory leak.

![image](https://user-images.githubusercontent.com/11706751/56885601-68140e80-6a9f-11e9-82dc-2c2e7a81e2d6.png)

![image](https://user-images.githubusercontent.com/11706751/56885575-5a5e8900-6a9f-11e9-8bbe-96f3e24a7452.png)

### env
react-native: 0.59.4
react: 16.8.3
react-navigation: 3.5.1
react-native-screens: 1.0.0-alpha.22

### demo
```js
import React from "react";
import { View, Text } from "react-native";
import { createStackNavigator, createAppContainer } from "react-navigation";
import { useScreens } from 'react-native-screens';
useScreens();

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Home Screen</Text>
      </View>
    );
  }
}

const AppNavigator = createStackNavigator({
  Home: {
    screen: HomeScreen
  }
});

const AppContainer = createAppContainer(AppNavigator)

AppRegistry.registerComponent('AwesomeProject', () => AppContainer)
```

**Comment by ericlewis** [comment] 2019-05-01 02:46
@xutm what was your methodology here?

**Comment by zhigang1992** [comment] 2019-05-03 07:43
From the initial investigation, even though 

https://github.com/kmagiera/react-native-screens/blob/master/ios/RNSScreen.m#L59

That view weak referencing controller,

But with

https://github.com/kmagiera/react-native-screens/blob/master/ios/RNSScreen.m#L103 

It became a strong reference again.

**Comment by kmagiera** [comment] 2019-05-16 12:15
Hey @xutm and @zhigang1992 

One note is that the fact retain cycle exists does not imply there is a memory leak. The retain cycle you've found here is due to the fact RNSScreenView object retains RNSScreen which inherits UIViewController and then loads RNSScreenView as its content. UIViewController require that the loaded view is retained. Note that the cycle only exists while the view is loaded into a controller and we break the cycle here https://github.com/kmagiera/react-native-screens/blob/master/ios/RNSScreen.m#L47 when the view is detached from RN hierarchy. In general we want RNSScreen (which inherits UIViewController) to exists so long RNSScreenView exists. Therefore the way it is currently handled seem correct to me. To be clear the way means that we break the cycle when view is detached from hierarchy.


I could be wrong and maybe the case you are describing actually causes a leak but your app does not seem to reproduce it. In your app you load a single screen, there is nothing that can leak there because the screen needs to be visible, we can't free the memory. Therefore I'm assuming you are only talking about the existence of retain cycle not about memory leak.

**Comment by WoLewicki** [comment] 2020-04-02 10:46
This issue seems outdated. Can I close it @xutm ?

**Comment by WoLewicki** [comment] 2020-05-29 11:22
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Closed by WoLewicki** 2020-05-29 11:22 UTC
