### ISSUE TITLE
I can't install the react native screens and gesturehandler dependencies, it's returning a TASK error - "React-native-screens:compileDebugJavaC 

### ISSUE THREAD

**Issue by pedrinho132** [software-mansion/react-native-screens#1493] opened 2022-06-27 14:32 UTC
<!--
I can't install the react native screens and gesturehandler dependencies, it's returning a TASK error - "react-native-screens:compileDebugJavaC,

I believe it has something to do with the RN0.69 update, I downgraded it but still no success

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |         |
| @react-navigation/native               |    6.0.10     |
| @react-navigation/native-stack         |     6.6.2    |
| react-native-screens                   |    3.10.0     |
| react-native-safe-area-context         |     ^4.3.1    |
| react-native-gesture-handler           |    ^2.3.0     |

**Comment by erikms61** [comment] 2022-06-28 13:05
I have the exact same issue.
reproduction:
npx react-native init rn_screens_issue
cd rn_screens_issue
yarn android
yarn add @react-navigation/native
yarn android
yarn add react-native-safe-area-context
yarn android
yarn add react-native-screens
yarn android
last command fails with a series of "Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0."

editing android/gradle.build as per the github instructions had no effect on this error, and downgrading to kotlin 1.4.0 is impossible with the current version of Android Studio

reproduction in https://github.com/erikms61/rn_screens_issue.git

**Comment by andrewleong** [comment] 2022-06-28 14:26
Please upgrade kotlinVersion to 1.7.0 Cheers

**Comment by nibblesnbits** [comment] 2022-06-29 05:39
Seems duplicate of #1449

**Comment by pedrinho132** [comment] 2022-06-30 00:43
> Please upgrade kotlinVersion to 1.7.0 Cheers

thanks, it´s working now

**Comment by handiandida** [comment] 2022-06-30 04:35
> > Please upgrade kotlinVersion to 1.7.0 Cheers
> 
> Sometimes, feeling a noob can be _very_ rewarding. For future reference, this is the diff android/build.gradle:
> 
> ```diff
> buildscript {
>     ext {
> +        kotlinVersion = "1.7.0"
>         buildToolsVersion = "31.0.0"
>         minSdkVersion = 21
>         compileSdkVersion = 31
>         targetSdkVersion = 31
> ```

It's work to solve the problem

**Comment by isharadilshan** [comment] 2022-06-30 12:38
> > Please upgrade kotlinVersion to 1.7.0 Cheers
> 
> Sometimes, feeling a noob can be _very_ rewarding. For future reference, this is the diff android/build.gradle:
> 
> ```diff
> buildscript {
>     ext {
> +        kotlinVersion = "1.7.0"
>         buildToolsVersion = "31.0.0"
>         minSdkVersion = 21
>         compileSdkVersion = 31
>         targetSdkVersion = 31
> ```

This fix gives `Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.` any idea why I'm having this ?

**Comment by kkafar** [comment] 2022-06-30 14:05
Hi @pedrinho132!
We've just released version 3.14 with https://github.com/software-mansion/react-native-screens/pull/1484 which should resolve your issues. Could you try to upgrade and let us know whether it works for you now?

**Comment by kkafar** [comment] 2022-07-01 10:03
Closing this issue, as discussion can be moved here: https://github.com/software-mansion/react-native-screens/issues/1449

**Closed by kkafar** 2022-07-01 10:03 UTC
Labels: needs-more-info, 🧰needs-repro, needs-review

**Comment by isharadilshan** [comment] 2022-07-03 16:50
> Hi @pedrinho132! We've just released version 3.14 with #1484 which should resolve your issues. Could you try to upgrade and let us know whether it works for you now?

Yes, upgrading to v3.14 resolved the issue.
