### ISSUE TITLE
swiping back with fullScreenSwipeEnabled on iOS 17 will make your keyboard go crazy bananas

### ISSUE THREAD

**Issue by adgarcia** [software-mansion/react-native-screens#1918] opened 2023-10-11 21:59 UTC
### Description

If you use the `fullScreenSwipeEnabled` screen option on a device/simulator running iOS 17 and then swipe 'back' while the keyboard is up, then your keyboard will be translated vertically in an unexpected (if also funny) way.

Although the provided reproduction is on a simulator running the example project on iOS 17, I can also reproduced this in a production app running on a device with iOS 17.

https://github.com/software-mansion/react-native-screens/assets/1191944/3b84c7a3-6609-4809-a284-ecb75cb0413f

### Steps to reproduce

1. have some way to build to an iOS simulator or device running iOS 17
2. run the react-native-screens Examples project
3. navigate to 'Gestures' -> 'Details'
4. make sure full screen swipe is enabled: 
<img width="392" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/1191944/da2182d7-7889-4223-a767-3b418453f092"> 

5. adjust 'top' until the little full screen tomato colored swipe box is visible above the keyboard
<img width="425" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/1191944/1b1b7703-b6ef-415f-b7e1-8330f12a7a06"> 

6. swipe back within that box while the keyboard is visible.

observe the keyboard become vertically translated by an amount that looks kind of like 'height of the keyboard' * 'normalized horizontal swipe distance'  

### Snack or a link to a repository

https://github.com/adgarcia/react-native-screens

### Screens version

3.25.0

### React Native version

0.72.4

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

None

### Device model

Any iPhone running iOS 17

### Acknowledgements

Yes

**Comment by adgarcia** [comment] 2023-10-11 22:40
I am using the screens example

> Hey! 👋
> 
> The issue doesn't seem to contain a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
> 
> Could you provide a [snack](https://snack.expo.dev/) or a link to a GitHub repository under your username that reproduces the problem?

hello robot you are mistaken. I have provided a reproduction using the react native screens example repo. You cannot reply to me but maybe I should just clone the repo and link that. let us see

**Comment by adgarcia** [comment] 2023-10-11 22:43
thank you robot

**Comment by kkafar** [comment] 2023-10-12 07:00
Absolutely love the issue title. I've managed to reproduce the issue and confirmed that it does not occur on older iOS versions (is it the same for you?).

**Comment by adgarcia** [comment] 2023-10-12 21:36
> Absolutely love the issue title. I've managed to reproduce the issue and confirmed that it does not occur on older iOS versions (is it the same for you?).

Hey! Thank you for the response! Yeah that is the same for me. All is well on ios 16 and earlier. 

So I did some more investigating and it seems like it's actually happening anywhere one uses a `UIPercentDrivenInteractiveTransition` to drive a navigation transition animation. In my project I am working around this by patching RNScreenStack.mm to dismiss the keyboard as soon as the swipe is detected.

It would be more ideal to do the dismissal in one of the UINavigationControllerDelegate methods (specifically `animationControllerForOperation`  as that's when you know *for sure* that an animated transition is going to be used), but doing that results in the keyboard not animating away nicely =(

I haven't tried using something custom that conforms to `UIViewControllerInteractiveTransitioning` to replace the `UIPercentDrivenInteractiveTransition` yet.

Anyway! I think software mansion is really cool and every time I poke around in your code I come away impressed. Really appreciate the work you all do.

**Comment by kkafar** [comment] 2023-10-19 12:45
This issue is reproducible on native iOS application. I got some intel that it will be most likely fixed with next patch release for iOS. Closing the issue here, as it seems that it is not caused by `react-native-screens`.

**Closed by kkafar** 2023-10-19 12:45 UTC
Labels: Platform: iOS, Repro provided
