### ISSUE TITLE
type: TransformError, Unexpected token

### ISSUE THREAD

**Issue by prahelixtech** [software-mansion/react-native-screens#1021] opened 2021-07-21 05:48 UTC
## Description

> Unable to run React Native project

### Screenshots

![Screenshot_1626845826](https://user-images.githubusercontent.com/86789101/126436955-4a7c118c-504d-434c-af6a-159368246604.png)
![Screenshot_1626846100](https://user-images.githubusercontent.com/86789101/126437378-c21f0568-d75f-4cc0-9b5f-ee5b8a054d96.png)

## Steps To Reproduce

1.

## Package versions

```json
{
  "name": "Sample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "npx react-native-jetifier",
    "run-android": "react-native run-android",
    "run-android:release": "react-native run-android --configuration Release",
    "run-ios": "react-native run-ios",
    "run-ios:release": "react-native run-ios --configuration Release",
    "build:ios": "react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios",
    "build:android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/"
  },
  "dependencies": {
    "@jumpn/react-native-jetifier": "^0.1.4",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/netinfo": "^4.6.1",
    "@types/react": "^16.9.5",
    "accordion-collapse-react-native": "^0.1.11",
    "axios": "^0.19.0",
    "firebase": "^7.14.4",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "native-base": "^2.13.8",
    "node": "^10.17.0",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-btr": "^1.1.4",
    "react-native-calendars": "^1.212.0",
    "react-native-check-box": "^2.1.7",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^5.2.1",
    "react-native-elements": "^1.2.6",
    "react-native-exception-handler": "^2.10.8",
    "react-native-exit-app": "^1.1.0",
    "react-native-firebase": "5.6.0",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-get-random-values": "^1.3.1",
    "react-native-image-picker": "^2.3.3",
    "react-native-image-progress": "^1.1.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-loader": "^1.3.1",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-mail": "^5.0.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal": "^11.4.0",
    "react-native-multiple-select-list": "^1.0.4",
    "react-native-picker-select": "^6.3.3",
    "react-native-progress": "^4.1.2",
    "react-native-progress-circle": "^2.0.1",
    "react-native-push-notification": "^5.1.0",
    "react-native-rename": "^2.4.1",
    "react-native-render-html": "^4.2.0",
    "react-native-screens": "^2.10.1",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-swiper": "^1.5.14",
    "react-native-user-agent": "^2.1.0",
    "react-native-version-check": "^3.4.1",
    "react-native-webview": "^10.9.0",
    "react-navigation": "^4.0.2",
    "react-navigation-stack": "^1.7.3",
    "react-redux": "^7.1.1",
    "realm": "^3.0.0",
    "redux": "^4.0.4",
    "redux-form": "^8.2.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "tinyurl": "^1.1.7",
    "toggle-switch-react-native": "^2.1.0"
  },
  "devDependencies": {
    "@babel/core": "7.6.0",
    "@babel/runtime": "7.6.0",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.9.0",
    "eslint": "6.3.0",
    "jest": "24.9.0",
    "jetifier": "^1.6.6",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.6",
    "reactotron-react-native": "^3.6.5"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

- React:
- React Native:
- React Native Screens:

**Comment by WoLewicki** [comment] 2021-07-21 08:10
I'm closing this issue due to not following the contributing guidelines for `react-native-screens`. Please provide the reproduction so we can work on the issue.

For more information see [contributing guide](https://github.com/software-mansion/react-native-screens/blob/master/guides/CONTRIBUTING.md).

**Closed by WoLewicki** 2021-07-21 08:10 UTC
