### ISSUE TITLE
FullWindowOverlay demo not working

### ISSUE THREAD

**Issue by maianhvu** [software-mansion/react-native-screens#1815] opened 2023-07-10 09:59 UTC
### Description

`FullWindowOverlay` component was supposed to put its children on top of everything else, but that's not the case when any modal component (RN's `<Modal />` or React Navigation screen whose stack presentation mode is `modal`).

https://github.com/software-mansion/react-native-screens/assets/66685443/e31b3f5b-f483-4b6f-bb13-bd7e0178e449

### Steps to reproduce

1. Create a fresh Expo project
2. Copy code from [Test1096.tsx](https://github.com/software-mansion/react-native-screens/blob/main/TestsExample/src/Test1096.tsx) and install necessary dependencies
3. Expected elements in `<FullWindowOverlay />` to be on top of modals, but instead it's obscured whenever a modal component is displayed

### Snack or a link to a repository

https://snack.expo.dev/@maianhvu/fullwindowoverlay-not-working?platform=ios

### Screens version

3.20.0

### React Native version

0.71.8

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2023-08-21 12:16
Hey, I've just played around with clean RN (no Expo) application and the `FullWindowOverlay` seems to be working fine, thus my first conclusion is that the `react-native-screens` is not directly responsible for this issue and it is Expo who is causing it. 

I'll dig around, however it might be worth bringing this issue to attention of the Expo team.

**Comment by kkafar** [comment] 2023-08-21 12:59
Hey, I've just tested `Test1096` on both managed & bare Expo workflows & it seems to be working fine. I've done the same with the code you provided in a snack:


https://github.com/software-mansion/react-native-screens/assets/50801299/2e157809-c213-42a3-b4ef-a873afe9e714

Works fine. I'm closing the issue, because it is possible that the problem was resolved in most recent Expo SDK / screens version. 

Let me know (tag me) if you still see the issue on most recent package version (if so, please provide me with valid reproduction).

**Closed by kkafar** 2023-08-21 12:59 UTC
Labels: Platform: iOS, Repro provided

**Comment by tonkatsu-wallwisher** [comment] 2023-09-19 04:39
> Hey, I've just tested `Test1096` on both managed & bare Expo workflows & it seems to be working fine. I've done the same with the code you provided in a snack:
> 
>  Simulator.Screen.Recording.-.iPhone.14.-.2023-08-21.at.14.57.27.mp4 
> Works fine. I'm closing the issue, because it is possible that the problem was resolved in most recent Expo SDK / screens version.
> 
> Let me know (tag me) if you still see the issue on most recent package version (if so, please provide me with valid reproduction).

Sorry for the late reply. Turns out it's a bug within Expo Go, and yes, the moment I ejected the app via `npx expo run:ios`, it works just like the screencap you posted.

Thanks for helping to look into it!

**Comment by maianhvu** [comment] 2023-09-19 04:41
> Hey, I've just tested `Test1096` on both managed & bare Expo workflows & it seems to be working fine. I've done the same with the code you provided in a snack:
> 
>  Simulator.Screen.Recording.-.iPhone.14.-.2023-08-21.at.14.57.27.mp4 
> Works fine. I'm closing the issue, because it is possible that the problem was resolved in most recent Expo SDK / screens version.
> 
> Let me know (tag me) if you still see the issue on most recent package version (if so, please provide me with valid reproduction).

Sorry for the late reply! Turns out it's a bug with Expo Go&emdash;the moment I ejected the app via `npx expo run:ios` and ran it as a standalone app, it works well just like in your screen cap.

Thanks for looking into it!
