### ISSUE TITLE
Getting this crash in production android build - Fatal Exception: java.lang.IllegalArgumentException No view found for id 0x5e9 (unknown) for fragment g{5f69ea9} (48fffc1a-4692-4b67-897b-b59d9ee691b1) id=0x5e9} com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow

### ISSUE THREAD

**Issue by ANIBIT14** [software-mansion/react-native-screens#616] opened 2020-08-27 14:38 UTC
Hi, I am getting this error in production build of our app,:
react-native screens version is "2.10.1",
can anybody tell me why this could be  happening
Fatal Exception: java.lang.IllegalArgumentException: No view found for id 0x5e9 (unknown) for fragment g{5f69ea9} (48fffc1a-4692-4b67-897b-b59d9ee691b1) id=0x5e9}
       at androidx.fragment.app.FragmentStateManager.a(FragmentStateManager.java:131)
       at androidx.fragment.app.FragmentManager.a(FragmentManager.java:237)
       at androidx.fragment.app.FragmentManager.a(FragmentManager.java:37)
       at androidx.fragment.app.FragmentManager.b(FragmentManager.java:130)
       at androidx.fragment.app.FragmentManager.c(FragmentManager.java:94)
       at androidx.fragment.app.FragmentManager.c(FragmentManager.java:21)
       at androidx.fragment.app.FragmentManager.n(FragmentManager.java:1)
       at com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow(ScreenContainer.java:15)
       at android.view.View.dispatchDetachedFromWindow(View.java:17612)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3733)
       at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5618)
       at android.view.ViewGroup.removeAllViews(ViewGroup.java:5564)
       at com.facebook.react.views.view.ReactClippingViewManager.removeAllViews(ReactClippingViewManager.java:13)
       at com.facebook.react.views.view.ReactClippingViewManager.removeAllViews(ReactClippingViewManager.java:2)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.a(NativeViewHierarchyManager.java:121)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.a(NativeViewHierarchyManager.java:115)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.a(NativeViewHierarchyManager.java:115)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.a(NativeViewHierarchyManager.java:307)
       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:16)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:72)
       at com.facebook.react.uimanager.UIViewOperationQueue.i(UIViewOperationQueue.java:53)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:46)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:984)
       at android.view.Choreographer.doCallbacks(Choreographer.java:798)
       at android.view.Choreographer.doFrame(Choreographer.java:727)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:972)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6754)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)

**Comment by WoLewicki** [comment] 2020-08-28 07:31
It looks like a duplicate of #463, so I will close this one. Please post this log in #463. Also, can you provide a repo that can be used to reproduce the behavior? It would greatly help us investigate it.

**Closed by WoLewicki** 2020-08-28 07:31 UTC
