### ISSUE TITLE
Craslytics: Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by kperreau** [software-mansion/react-native-screens#408] opened 2020-03-07 20:01 UTC
Some of my users crash and i got this error on crashlytics.
It's random and not all the time.
It look like an internal error so if it can help i post the screen here.
Thank you.

> Unable to start activity ComponentInfo{com.bereal.ft/com.bereal.ft.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: could not find Fragment constructor

![hht](https://user-images.githubusercontent.com/9469797/76151560-a9f5e400-60b6-11ea-8809-843f20a6300c.png)

**Comment by lucasluca** [comment] 2020-03-09 13:56
Same issue here

**Comment by kperreau** [comment] 2020-03-09 14:17
And some times my users got a black screen and get stuck, they only can kill app and restart.

Hope it can help to solve it.

**Comment by lucasluca** [comment] 2020-03-12 01:34
I removed react native screens from my app, because when this error happens, even the AsyncStorage database is cleaned

**Comment by Jekiwijaya** [comment] 2020-03-14 07:50
I think this related to https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067

**Comment by kperreau** [comment] 2020-03-14 13:03
Not really a fix.
I tried this 2 weeks long, my users got a lot of crash when i put `null` in `super.onCreate();`.

**Comment by Jekiwijaya** [comment] 2020-03-15 08:27
I also face the same issue, I just tried to publish the `onCreate(null)` solution.  Anyway,  do you know how to repro the crash?

It's would be sad if must comment `enableScreen()` again, it improves a lot in android performances

**Comment by kperreau** [comment] 2020-03-18 18:45
>  Anyway, do you know how to repro the crash?

No idea.
When the app is killed, then receive a notification and open application from notification. But not sure at 100%.
Plus, it look like the app got a lot of crash with the Google TestLab (without notification, first install).

**Comment by WoLewicki** [comment] 2020-07-07 13:11
@kperreau is the crash the same as the one with not putting `null` in `super.onCreate();`?

**Comment by kperreau** [comment] 2020-07-07 14:28
> @kperreau is the crash the same as the one with not putting `null` in `super.onCreate();`?

Yes i'm not putting putting `null` in `super.onCreate();`, it's worst if i put `null`, maybe cause i use `react-native-splash-screen`, i don't know.

**Comment by WoLewicki** [comment] 2020-07-07 14:34
I need it to be clear, if you put `null` in `super.onCreate();`, then the exception with `Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: could not find Fragment constructor` still exist? Or does a different exception happen then? I am asking since I cannot recreate this exception when putting `null` in `super.onCreate();`.

**Comment by docnbs** [comment] 2020-08-07 15:01
Having the same issue. Please share if there is a proper fix. Sharing details if it helps.

1. Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.appname/com.appname.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appname/com.appname.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)


2. Caused by androidx.fragment.app.Fragment$InstantiationException
Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
androidx.fragment.app.Fragment.instantiate

aused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
       at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
       at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:51)
       at com.appname.MainActivity.onCreate(MainActivity.java:16)
       at android.app.Activity.performCreate(Activity.java:7088)
       at android.app.Activity.performCreate(Activity.java:7079)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by WoLewicki** [comment] 2020-08-10 07:42
@docnbs does this fix the issue: https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067?

**Comment by docnbs** [comment] 2020-08-10 19:51
@WoLewicki Thanks for sharing. Will check and revert.

**Comment by WoLewicki** [comment] 2020-09-08 09:47
From the stack trace, I see that all reported crashes are due to not applying `null` to the `onCreate` method. It is obligatory for the `react-native-screens` to work correctly. You can get more info here: https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-425027574. I am closing this issue then. Feel free to comment if something is wrong.

**Closed by WoLewicki** 2020-09-08 09:47 UTC
Labels: bug

**Comment by mi-mazouz** [comment] 2022-07-05 15:52
This issue still happen to my app even after passing null to onCreate function

**Comment by camboYY** [comment] 2022-07-07 04:09
This issue still happen to my app even after passing null to onCreate function

**Comment by jamninetyfive** [comment] 2022-07-19 09:31
This issue still happen to my app even after passing null to onCreate function

**Comment by beqramo** [comment] 2022-08-05 13:09
me too, with null I have errors on different users, without null on different

**Comment by subhadeepquantiantech** [comment] 2022-10-03 06:49
+1

**Comment by QSuraj** [comment] 2022-10-06 05:20
+1

**Comment by subhadeepquantiantech** [comment] 2022-10-06 06:01
For those who are facing issue while taking image from default camera. use react native camera vision instead.

**Comment by webdiego** [comment] 2022-10-07 06:58
Same
