### ISSUE TITLE
FullWindowOverlay not fitting the window

### ISSUE THREAD

**Issue by nazrdogan** [software-mansion/react-native-screens#1247] opened 2021-12-25 21:22 UTC
I m trying to use  `FullWindowOverlay`  to show a custom action sheet in the modal screen. but FullWindowOverlay has some spaces at the bottom.
In our app, I edited react-native-screens/ios/RNSFullWindowOverlay.m  ( version: 3.10.1) like this way. it seems working for me. but I m not sure this is the right way to do 
```
- (void)reactSetFrame:(CGRect)frame
{
  _reactFrame = frame;
  CGRect rect = [[UIScreen mainScreen] bounds];
  [_container setFrame:rect];
}
```
https://snack.expo.dev/@nazrdogan/suspicious-coffee

![Image from iOS](https://user-images.githubusercontent.com/1672303/147393731-20f9e174-ce7b-496d-b14f-f07f82a5c13d.png)

**Comment by WoLewicki** [comment] 2022-01-03 13:51
I believe it is a duplicate of #1202 (check if https://github.com/software-mansion/react-native-screens/issues/1202#issuecomment-981755351 resolves the issue). As for adding such code, it may be a good point to just make it fullscreen by default, could you make a PR with this change and this reproduction in `TestsExample` app ?

**Comment by lexi-stein** [comment] 2023-07-25 18:03
Hi! Having the same issue but I can't use the solution indicated in that PR because FullWindowOverlay no longer seems to accept a style prop

**Comment by erickreutz** [comment] 2023-11-19 18:24
This is still an issue.

**Comment by erickreutz** [comment] 2023-11-19 19:40
The change op mentions did not work for me.

**Comment by GLSinthu** [comment] 2024-03-01 15:24
Having a child view with the styles mentioned in the workaround fixed the issue for me.
```
      <FullWindowOverlay>
        <View style={tw`absolute inset-0 w-100vw h-100vh`}>{children}</View>
      </FullWindowOverlay>
```

**Closed** 2024-10-22 12:17 UTC
Labels: Bug, Repro provided
