### ISSUE TITLE
Sticky header doesn't work with largeTitle

### ISSUE THREAD

**Issue by ArekChr** [software-mansion/react-native-screens#542] opened 2020-06-13 10:48 UTC
Sticky header in FlatList and ScrollView doesn't work with largeTitle

```
- @react-navigation/native: 5.2.6
- @react-navigation/stack: 5.3.1
- react-native-screens: 2.780

platform: iOS
mode: Debug
Device: iPhone XS
OS version: 13.4.5
```

**Comment by WoLewicki** [comment] 2020-06-15 15:31
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by ArekChr** [comment] 2020-06-15 22:06
please note that `headerTranslucent: true` makes this broken, not largeTitle at all

please follow this repo https://github.com/ArekChr/ReactNativeScreensExamples/blob/master/ReactNativeScreensBugs.tsx

or code here: 


```
import {NavigationContainer} from '@react-navigation/native';
import React, {useRef} from 'react';
import {ScrollView, StyleSheet, Text, View, Button} from 'react-native';
import {TouchableOpacity} from 'react-native-gesture-handler';
import {createNativeStackNavigator} from 'react-native-screens/native-stack';

export const NativeStack = createNativeStackNavigator();

export function StickyHeaderBugScreen() {
  const someContent = Array.from({length: 50}, (v, i) => i);

  return (
    <ScrollView
      contentInsetAdjustmentBehavior="automatic"
      stickyHeaderIndices={[0]}>
      <View style={styles.button}>
        <Text>Sticky Header</Text>
      </View>
      {someContent.map((x) => (
        <TouchableOpacity key={x} style={styles.button}>
          <Text>Scroll to 0</Text>
        </TouchableOpacity>
      ))}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  button: {
    padding: 5,
    borderBottomColor: 'gray',
    borderBottomWidth: 0.5,
    backgroundColor: 'lightblue',
    flex: 1,
  },
});

export function ReactNativeScreensBugs() {
  return (
    <NavigationContainer>
      <NativeStack.Navigator
        screenOptions={{
          headerTranslucent: true,
          headerStyle: {backgroundColor: 'rgba(255,255,255, 0.1)'},
          headerTitleStyle: {color: 'white'},
        }}>
        <NativeStack.Screen
          options={{headerLargeTitle: true}}
          name="StickyHeader"
          component={StickyHeaderBugScreen}
        />
      </NativeStack.Navigator>
    </NavigationContainer>
  );
}

```

**Comment by WoLewicki** [comment] 2020-06-16 13:47
What is the behavior you would expect regarding those issues? Setting a translucent header makes the content of the Screen go under the navigation bar to be able to draw under it, so the sticky header gets attached to the top of the `Screen`, which is not visible in this configuration, but you can spot it with transparent `backgroundColor`. The `contentInsetAdjustmentBehavior="automatic"` makes the ScrollView respect the header's height at the beginning and makes the ScrollView render first item below the header by setting the `contentOffset`.

**Comment by ArekChr** [comment] 2020-06-16 14:48
IMO it should automatically change position of sticked header when I set headerTransculent, I tried to change that manually I mean move position of stick but seems to be impossible

**Comment by WoLewicki** [comment] 2020-08-11 09:23
The problem with sticky header is the problem with how `react-native`'s `ScrollView` component works. You can submit an issue in the repo regarding the implementation of https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollViewStickyHeader.js and suggest to be able to take into account the offset of the iOS translucent header when calculating the start of the "stickiness".
I am closing this issue then. Feel free to comment if you have any questions.

**Closed by WoLewicki** 2020-08-11 09:23 UTC
Labels: bug, iOS, native-stack, scrollView

**Comment by sintylapse** [comment] 2020-08-25 17:17
@ArekChr any luck on fixing this?

**Comment by ArekChr** [comment] 2020-08-25 17:18
Unfortunately no

**Comment by pouyarezvani** [comment] 2021-07-19 18:40
@ArekChr I'm facing the same issue where the sticky section headers go below the `TranslucentHeader`. I've tried to programmatically give margin-top to the sticky headers but it has a jumping behavior. 

this is already implemented in the iOS contacts app. if you take a look, you'll see that contacts are sectioned alphabetically and the header is translucent. 

Have you had any more luck on this?

**Comment by ArekChr** [comment] 2021-07-19 21:53
> @ArekChr I'm facing the same issue where the sticky section headers go below the `TranslucentHeader`. I've tried to programmatically give margin-top to the sticky headers but it has a jumping behavior. 
> 
> 
> 
> this is already implemented in the iOS contacts app. if you take a look, you'll see that contacts are sectioned alphabetically and the header is translucent. 
> 
> 
> 
> Have you had any more luck on this? 

I tried to fix it in the same way but got the same behaviour. I didn't found another solution.

I have no translucent headers in some places in the app for now.

**Comment by ArekChr** [comment] 2021-07-19 21:54
@WoLewicki why this issue is closed?

**Comment by pouyarezvani** [comment] 2021-08-22 20:22
@WoLewicki and @ArekChr I opened an issue on the react-native GitHub regarding the sectionList sticky headers not taking the iOS translucent header into account
[here is a  link to it](https://github.com/facebook/react-native/issues/32063#issue-976462169)

**Comment by okarakose** [comment] 2023-01-05 14:30
> @ArekChr did you ever solve this?

Did you find a solution about this one? your react-native issue is closed for no activity

**Comment by ArekChr** [comment] 2023-01-05 15:56
> 

Still didn't found a solution for translucent headers

**Comment by metehandemir** [comment] 2024-08-15 21:46
Facing same issue..

**Comment by schriker** [comment] 2024-11-06 14:20
Yeah, the issue is still there also for section list sticky headers going under the app header. Has anyone had any luck or workaround for it?
