### ISSUE TITLE
IOS, app hang and crash when swiping back after move to background

### ISSUE THREAD

**Issue by hunterbmt** [software-mansion/react-native-screens#786] opened 2021-01-24 10:28 UTC
## Description

After upgrade to 2.15.2 (using Expo SDK 40), on IOS, app will hang and crash when swiping back after moving to background.
This only happy when move from screen inside a tab view to a screen outside tab view.

## Steps To Reproduce

1. Create a standard structure
    ---Product Detail
    ---Something
    ---Home (Bottom Tab)
    -------Hot Product (Material Top Tab) 
2. Navigate to Hot Product
3. From Hot Product navigate to Product Detail
4. Move app to background
5. Get back and swipe back

App won't crash if
- Using navigate.goBack() instead of swipe
- Not using enableScreens()
- Move from ProductDetail to Something after move app to background then swipe back (still crash if swipe back from ProductDetail)

### Expected behavior

Move back and don't hang/crash

### Actual behavior

Hang and crash

## Package versions

- React Native Screens: 2.15.2
- React Native: Expo SDK 40

**Comment by WoLewicki** [comment] 2021-01-27 14:51
Can you provide a test example in TestsExample project (https://github.com/software-mansion/react-native-screens/tree/master/TestsExample) or a snack with minimal configuration needed to reproduce the issue?

**Comment by hunterbmt** [comment] 2021-01-27 15:52
@WoLewicki tried to reproduce by a snack but cannot reproduce.
The structure is our app is something like this (https://snack.expo.io/SNMFYkUyN)
I can confirm that the issue only happen when enableScreens and with 2.15.0 (with Expo 40). I don't know if it has anything to do with the level of complexity of the stack and cannot test again 2.17.1 since we are using Expo managed workflow

**Comment by WoLewicki** [comment] 2021-01-28 12:52
I couldn't repro the problem when applying your snack my example with `2.17.1` so I am not sure if there is much I can do about it unfortunately.

**Comment by WoLewicki** [comment] 2021-03-01 10:12
I will close it since I believe there is nothing on the side of `react-native-screens` to be done with it. Expo SDK 41 should be out soon, please test it there, and if the issue persists, comment here and we can reopen it then.

**Closed by WoLewicki** 2021-03-01 10:12 UTC
Labels: iOS, needs more info, needs repro

**Comment by trizerr** [comment] 2021-12-06 03:43
@WoLewicki I believe that is related to this issue https://github.com/facebook/react-native/issues/29472. And this is an issue of react-native-screens because if you disable it crash isn't happening. Could you please look into that?

**Comment by trizerr** [comment] 2021-12-06 03:50
I get this error on react-native-screens version 3.9.0

**Comment by WoLewicki** [comment] 2021-12-07 09:36
Please provide a minimal reproduction of the crash (a snack or simple repo) so we can work on it and we can reopen this then.

**Comment by trizerr** [comment] 2021-12-07 10:12
the problem here is that it's not reproducing constantly, it happens very randomly. We tried to reproduce it for 3 hours but didn't get this error (We only have crash reports from our users). Steps to reproduce in this issue are correct because our breadcrumbs state the same. So the only thing I can send you is crash reports:( https://github.com/trizerr/react-native-screens-crash

**Comment by WoLewicki** [comment] 2021-12-07 15:04
In these logs, I cannot see any methods invoked by `react-native-screens` so it is almost impossible to withdraw any conclusions regarding our library. The logs suggest that there is a deadlock since there are multiple mutexes awaiting, but I cannot say much more.
