### ISSUE TITLE
[native-stack] Swipe back is not working

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-screens#358] opened 2020-02-22 18:12 UTC
_Moved from [react-navigation/react-navigation#6809](https://github.com/react-navigation/react-navigation/issues/6809). Originally opened by @berkaey_
___

**Current Behavior**

with 

```
"@react-navigation/native-stack": "^5.0.0",
"react-native-screens": "^2.0.0-beta.2",
```
swipe back is not work on iOS 13.

**Expected Behavior**

It should work line in stack navigator.

**How to reproduce**

just create a simple 2 view app and swipe back.

https://snack.expo.io/@berkaey/routing-test << some how working in this demo

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13.3
| @react-navigation/native       |
| @react-navigation/native-stack | 5
| react-native-screens           | 2.0.0-beta.2
| react-native                   | 0.61.5
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by alexichristakis** [comment] 2020-02-26 03:54
Confirm swipe back stops working with react-native-screens version 2.0.0 beta 11

**Comment by WoLewicki** [comment] 2020-03-31 09:23
@berkaey @alexichristakis can you repro the bug on the newest master branch?

**Comment by WoLewicki** [comment] 2020-04-16 08:40
I used the snack provided and couldn't repro the issue on the newest branch. Looks like it has been fixed in one of the newer versions. I am closing it then. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2020-04-16 08:40 UTC
Labels: bug, native-stack

**Comment by denispixi** [comment] 2020-06-08 02:40
I am in v2.0.7 and I have this problem. I have a NativeStack.Navigator inside a React Navigation's Tab.Navigator and I can't swipe back.

Help me pls! 😭

**Comment by WoLewicki** [comment] 2020-06-08 09:10
@denispixi can you provide a repo/smack with minimal configuration needed to reproduce the issue?

**Comment by smancebo** [comment] 2021-05-02 04:53
Any updae on this issue, is still happening on v3.1.1

**Comment by smancebo** [comment] 2021-05-02 05:10
Here you can check the issue
https://snack.expo.io/Sfys2hq_3

**Comment by WoLewicki** [comment] 2021-05-04 09:43
@smancebo I opened your snack and this is the result, so I am not sure if I am doing something wrong or maybe there is a problem with configuration on your side.

![Simulator Screen Recording - iPhone SE (2nd generation) - 2021-05-04 at 11 42 05](https://user-images.githubusercontent.com/32481228/116986249-d4006180-accd-11eb-8c3c-57a7f726b251.gif)

**Comment by smancebo** [comment] 2021-05-05 11:26
Thanks @WoLewicki, running same code on physical device (iOS 14.4) works just fine, but running on actual simulator does not (iOS 14.5, xcode 12.5). i will update the phone to iOS 14.5 and will test again just to confirm if it is something related to iOS 14.5 version

**Comment by WoLewicki** [comment] 2021-05-05 16:27
I tested it on the simulator with Xcode 12.5 and newest iOS.
