### ISSUE TITLE
headerTranslucent:True Removes the Sticky Section Headers from SectionList

### ISSUE THREAD

**Issue by pouyarezvani** [software-mansion/react-native-screens#927] opened 2021-05-10 18:02 UTC
## Description

headerTranslucent = true, removes the sticky section Headers from SectionList. 

Here is a [snack](https://snack.expo.io/@invoiss_corp/native-navigation-boilerplate) that can reproduce the problem. Just navigate to SectionList Tab from the bottomTabNavigator. And you can see that the SectionList's Sticky headers don't stick to the top when HeaderTranslucent is set to True. 

Is there any way to fix this Issue?

Thanks.

https://user-images.githubusercontent.com/32917154/117703965-21be1380-b17f-11eb-81ec-1e21e96d2730.mov

**Comment by WoLewicki** [comment] 2021-05-11 07:40
I believe it is a duplicate of #542, so I will close it to keep the discussion in one place. Feel free to comment here if something is wrong.

**Closed by WoLewicki** 2021-05-11 07:40 UTC

**Comment by pouyarezvani** [comment] 2021-05-12 16:35
This is not the same issue as the one in [#542](https://github.com/software-mansion/react-native-screens/issues/542)
For me, the sticky header works with FlatList. 
This issue I'm having now only happens in SectionList. 
SectionList has a prop for sticky Header called `renderSectionHeader` which every section's individual header becomes sticky as you scroll. 
Now if I keep the header Translucent, this behavior is removed.

**Comment by WoLewicki** [comment] 2021-05-13 08:00
I tested your snack and it works the same for sticky indices in `FlatList` and sticky section headers for `SectionList`. If you remove the blur effect, you will see that the headers stick to the top edge of the screen, which is the correct behavior since translucent header means the content can go below the header. I am not sure what behavior exactly are you trying to achieve. Could you elaborate more on it and what do you mean by working on `Flatlist`?
![image](https://user-images.githubusercontent.com/32481228/118096646-ec5d3400-b3d1-11eb-8920-3f7e1ef701bb.png)

**Comment by pouyarezvani** [comment] 2021-05-18 03:31
@WoLewicki Looks like you are correct sir. The translucent header actually removed any sticky component no matter its `SectionList `or `FlatList`.
Looks like there is no luck with it sadly.

**Comment by WoLewicki** [comment] 2021-05-18 08:56
I think it is a correct behavior since it would be weird to have a sticky header below the translucent header and the content visible when scrolling above it.

**Comment by pouyarezvani** [comment] 2021-07-19 18:36
@WoLewicki It's not a weird behavior, as the iOS contacts app is already doing that. Look at this video below. 

https://user-images.githubusercontent.com/32917154/126209864-72423647-c49d-46f0-90d2-def668f46ca0.mov


I have been trying to achieve this behavior but I've been unsuccessful. Is there any way to `offset` the first section header of `SectionList` so It can fall right under the `TranslucentHeader`?

I've even tried to give a margin-top to section headers if the user starts scrolling but this applies to all the sections and it has a jumping behavior. 

Any help/code example would be appreciated.

**Comment by WoLewicki** [comment] 2021-07-20 07:54
I don't know how to resolve this, but I think it is the problem with sticky header implementation, as mentioned here: https://github.com/software-mansion/react-native-screens/issues/542#issuecomment-671835098. You can try and change the code in that file to properly fit your cases, I cannot think of other solution. The contacts app does not use `react-native` `ScrollView` implementation, that's probably why it works correctly. Please inform me if you had any luck fixing this.
