### ISSUE TITLE
reactNative crashes indeterminately in Android 13 production

### ISSUE THREAD

**Issue by maxfrees** [software-mansion/react-native-screens#2401] opened 2024-10-14 08:33 UTC
### Description

![1728894785227](https://github.com/user-attachments/assets/5ea5d5c9-eeeb-4d88-b19c-aea7804d2e85)

```
{
  "name": "atms",
  "version": "1.7.5",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "build": "cd android && ./gradlew assembleRelease",
    "build-win": "cd android && gradlew assembleRelease",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "prettier": "prettier . --ext --write .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@ant-design/icons-react-native": "^2.3.1",
    "@react-native-async-storage/async-storage": "^1.15.5",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "axios": "0.26.1",
    "jotai": "^2.2.1",
    "native-base": "^3.3.0",
    "react": "^17.0.1",
    "react-hook-form": "^7.11.1",
    "react-native": "^0.64.4",
    "react-native-device-info": "^8.1.7",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-mmkv": "2.5.1",
    "react-native-pager-view": "^5.2.1",
    "react-native-reanimated": "^2.2.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.4.0",
    "react-native-svg": "^12.1.1",
    "react-native-tab-view": "^3.0.1",
    "react-native-webview": "^11.14.2",
    "react-qr-code": "^2.0.3",
    "styled-components": "^5.3.0",
    "styled-system": "^5.1.5",
    "swr": "1.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.64.5",
    "@types/react-test-renderer": "^16.9.2",
    "babel-jest": "^26.6.3",
    "babel-plugin-module-resolver": "^5.0.0",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-native-bundle-visualizer": "^2.2.1",
    "react-test-renderer": "17.0.1",
    "typescript": "^3.8.3"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

### Steps to reproduce

![image](https://github.com/user-attachments/assets/8e0e777d-c65c-4f54-bce1-d7f54d9955d2)

### Snack or a link to a repository

*

### Screens version

3.4

### React Native version

0.64

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2024-10-14 10:59
Hello @maxfrees, let me leave few remarks on the issue:

1. The "stacktraces" you provided us with indicate that you haven't performed [library installation steps](https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#android), please try these out.
2. We do not support version 0.64 of react-native since a long time ago. We need confirmation that this happens of recent version of screens (paired with recent version of react-native, see the [compatibility tables](https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#supported-react-native-version).
3. Most likely we won't be able to help much w/o proper reproduction of the issue (see the messages from our bot above)
4. You might find interesting issue no. #17, together with all issues linked to it.

I'll close the issue, as in current shape we won't be able to proceed with it. Please fill the missing information and notify us when its ready - I'll reopen. 

> [!tip]
> Try to avoid posting information in form of screenshots - this makes it hard to read, copy & process. Text format is much more user friendly.

**Closed by kkafar** 2024-10-14 10:59 UTC
Labels: Missing info, Platform: Android, Missing repro

**Comment by maxfrees** [comment] 2024-10-15 08:24
```
package com.atms;

import com.facebook.react.ReactActivity;
import android.os.Bundle;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "ATMS";
  }

  @Override
  protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(null);
  }
}
```

@kkafar  Still can't
