### ISSUE TITLE
[native-stack] modals are only dismissible on iOS 13

### ISSUE THREAD

**Issue by alexichristakis** [software-mansion/react-native-screens#436] opened 2020-03-22 19:31 UTC
In a barebones project I can't get a modal to dismiss on iOS 11 or 12.

```
import React from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from 'react-native-screens/native-stack';
import {enableScreens} from 'react-native-screens';

enableScreens();

import Root from './Root';
import Modal from './Modal';

const Stack = createNativeStackNavigator();

const App = () => (
  <NavigationContainer>
    <Stack.Navigator screenOptions={{stackPresentation: 'modal'}}>
      <Stack.Screen name="ROOT" component={Root} />
      <Stack.Screen name="MODAL" component={Modal} />
    </Stack.Navigator>
  </NavigationContainer>
);

export default App;
```

When an action is fired from Modal to dismiss or navigate back to Root the screen seems to be unmounted based on the performance monitor.

before `navigation.goBack()` or `navigation.navigate('ROOT')` is called:
![Simulator Screen Shot - iPhone X - 2020-03-22 at 12 22 24](https://user-images.githubusercontent.com/21017729/77258443-dd4c7d00-6c37-11ea-8063-edf7a53dea89.png)

after `navigation.goBack()` or `navigation.navigate('ROOT')` is called:
![Simulator Screen Shot - iPhone X - 2020-03-22 at 12 22 29](https://user-images.githubusercontent.com/21017729/77258445-df164080-6c37-11ea-8a7e-9f6c26c27fd7.png)

It doesn't animate away and loses all responsiveness.

Everything works fine in iOS 13. Any thoughts?

**Comment by WoLewicki** [comment] 2020-03-23 15:03
The problem seems to be here: https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreen.m#L85, the `UIModalPresentationFullScreen` causes the block. You can check it if you set `stackPresentation="fullScreenModal"`, then it will resolve to `UIModalPresentationFullScreen` as well and block the application. Am I right @alexichristakis?

**Comment by alexichristakis** [comment] 2020-03-23 16:43
yep, you're correct. any ideas on how we can fix this?

**Comment by WoLewicki** [comment] 2020-03-24 17:01
You can wait for #438 to be merged or change the presentation to `containedModal`. It should look the same on iOS < 13. Does it fix your issue?

**Comment by alexichristakis** [comment] 2020-03-24 18:02
containedModal does fix the issue, but #438 does not fix fullScreenModal. is it working for you?

**Comment by WoLewicki** [comment] 2020-03-25 08:36
It worked for me, can you make a quick repro where it is not working? And is it failing on iOS < 13?

**Comment by WoLewicki** [comment] 2020-03-27 11:30
It looks like I made a mistake by adding the check in the wrong method. Try #441 and please tell if it fixes your issue.

**Comment by SmirnovM91** [comment] 2020-04-06 13:58
Hi, When update is going to be released?

**Comment by limaAniceto** [comment] 2020-04-06 16:37
Hi @WoLewicki,
Really appreciate all the work you've done on this project

I'm afraid I tried #441 and it still happens on fullScreenModal 😞 

@alexichristakis do you mind testing #441 to confirm?

**Comment by WoLewicki** [comment] 2020-04-07 09:06
@limaAniceto can you provide a repo with minimal configuration needed to reproduce the issue?

**Comment by limaAniceto** [comment] 2020-04-09 14:10
Hi @WoLewicki,
I've managed to identify that the issue is on the usage of the prop `transparentCard` from `react-navigation` and that removing it addresses the issue 🎉 

```
transparentCard - Experimental - Prop to keep all cards in the stack visible and add a transparent background instead of a white one. This is useful to implement things like modal dialogs where the previous scene should still be visible underneath the current one.
```
https://reactnavigation.org/docs/4.x/stack-navigator-1.0/#specifying-the-transition-mode-for-a-stacks-screens-explicitly

You can see the issue on this GIF (iOS 13.3 - iphone 11)
![2020-04-09 15 10 05](https://user-images.githubusercontent.com/2905749/78904308-3740a580-7a74-11ea-90ce-63eaa38917ac.gif)


**Reproducible repo**: https://github.com/limaAniceto/RN-Screens-Bug

**Comment by tdoran** [comment] 2020-04-15 16:39
I think there may be two issues being discussed here:

1. When using react-screens' `createNativeStackNavigator`, on iOS devices below iOS13, modals are not dismissable. I believe this is what is being references in the first post in this issue.

2. When using react-native-screens 2.4.0 and the `transparentCard` option on a `createStackNavigator` from react-navigation: after dismissing a modal, it immediately reappears and is not dismissable.

No. 2 is solvable by using `createNativeStackNavigator`. 

I believe 1 should be fixed by https://github.com/software-mansion/react-native-screens/pull/441 , but I've tested it and this hasn't fixed it for me.

I don't suppose you've had any recent luck with this @alexichristakis ?

**Comment by WoLewicki** [comment] 2020-04-16 07:16
@tdoran so can you provide a repo with a minimal configuration that shows the bug so I can work on it?

**Comment by WoLewicki** [comment] 2020-06-08 18:13
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Closed by WoLewicki** 2020-06-08 18:13 UTC
Labels: bug, native-stack

**Comment by EhsanSarshar** [comment] 2020-09-26 12:43
@WoLewicki I am using the `modal` stackTransition. it work find in Iphone X (with safeArea). but in iphone 7 and 8 it's not dismissable. it seems that it goes behind the status bar, far away.

**Comment by EhsanSarshar** [comment] 2020-09-27 07:41
@WoLewicki the issue still exist in latest release.

**Comment by WoLewicki** [comment] 2020-09-30 08:01
@EhsanSarshar can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by henninghall** [comment] 2020-10-13 13:57
Having the same problem, the app becomes unresponsive when trying to close a modal on iOS 12, reproduced with iPhone 6, iOS 12.4.5. The problem occurs when stackPresentation is set to `modal` but not when set to `transparentModal`.

**Comment by WoLewicki** [comment] 2020-10-14 11:08
Can you apply https://github.com/software-mansion/react-native-screens/pull/643 and check if it fixes your issue @henninghall @EhsanSarshar ?

**Comment by DanielMarkiel** [comment] 2020-10-27 10:33
@WoLewicki I can confirm that #643 fixes the issue described above.

**Comment by ajsmth** [comment] 2020-11-16 17:59
just tested this on iPhone 8 and iPhone X (iOS 12) - the modals are not dismissable with #643

**Comment by WoLewicki** [comment] 2020-11-17 14:42
@ajsmth please provide a repo that shows the issue so it can be reproduced.
