### ISSUE TITLE
Navigate from StackPresentation in modal

### ISSUE THREAD

**Issue by Razorholt** [software-mansion/react-native-screens#826] opened 2021-02-22 00:53 UTC
Issue: no way to navigate away from a screen in modal (Presentation is iOS). Tried goBack(), pop() and push.

I'm on Expo SDK 40, which means that the most recent version I can install is 2.15.2. I can't even go back to 2.11 as suggested in this forum somewhere because it won't work at all.

Is this a bug that will get fixed soon for Expo users? Thank you so much!

**Comment by WoLewicki** [comment] 2021-02-22 10:01
Can you provide a snack with minimal configuration needed to reproduce the issue?

**Comment by Razorholt** [comment] 2021-02-22 19:48
I put together a snack BUT it does work fine both on the simulator as well as on my real device (iPhone 11):
https://snack.expo.io/@mobshed/react-native-screens-presentation

However, when I include the exact components within my current project, the screen just freezes anytime I hit the navigation link.

Here are my dependencies:
```
 "dependencies": {
    "@react-native-async-storage/async-storage": "1.13.4",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "5.9.7",
    "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/material-top-tabs": "^5.2.19",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "expo": "^40.0.0",
    "expo-asset": "~8.2.1",
    "expo-av": "~8.7.0",
    "expo-blur": "~8.2.2",
    "expo-constants": "~9.3.3",
    "expo-contacts": "~8.6.0",
    "expo-file-system": "~9.3.0",
    "expo-font": "~8.4.0",
    "expo-haptics": "~8.4.0",
    "expo-image-picker": "~9.2.0",
    "expo-linear-gradient": "~8.4.0",
    "expo-localization": "~9.1.0",
    "expo-location": "~10.0.0",
    "expo-notifications": "~0.8.2",
    "expo-permissions": "~10.0.0",
    "expo-screen-orientation": "~2.1.0",
    "expo-speech": "~8.5.0",
    "expo-splash-screen": "~0.8.1",
    "expo-status-bar": "~1.0.3",
    "expo-video-thumbnails": "~4.4.0",
    "md5": "^2.3.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-animatable": "^1.3.3",
    "react-native-autoheight-webview": "^1.5.4",
    "react-native-button": "^3.0.1",
    "react-native-easy-view-transformer": "^1.2.0",
    "react-native-floating-label-input": "^1.3.4",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-htmlview": "^0.16.0",
    "react-native-image-lightbox-zoom-pan": "^1.0.1",
    "react-native-image-modal": "^1.0.16",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-transformer": "^1.5.1",
    "react-native-indicators": "^0.17.0",
    "react-native-modal": "11.6.1",
    "react-native-modals": "^0.22.3",
    "react-native-safe-area-context": "3.1.9",
    "react-native-scalable-image": "^1.0.0",
    "react-native-screens": "~2.15.2",
    "react-native-tab-view": "^2.15.1",
    "react-native-web": "^0.15.0",
    "react-native-webview": "11.0.0"
  },
```

**Comment by Razorholt** [comment] 2021-02-22 23:07
OK, I was finally able to reproduce the bug:
https://snack.expo.io/@mobshed/react-native-screens-presentation

Apparently, you can't go from 'containedModal' to 'modal'?

**Comment by WoLewicki** [comment] 2021-02-23 11:19
Yes, it is forbidden to include both `containedModals` and "normal" `modals` in one flow since it messes with the implementation of setting the native view hierarchy. It should be documented for sure. Are you willing to submit a PR with this information? It would be required to put it in the main README and in READMEs of `native-stack` and `createNativeStackNavigator`.

**Comment by kacperkapusciak** [comment] 2021-02-25 12:24
I've added to READMEs using `containedModal ` and `containedTransparentModal ` in one native stack navigator is unadvised and leads to crashes in https://github.com/software-mansion/react-native-screens/pull/835

I'll close this issue now

**Closed by kacperkapusciak** 2021-02-25 12:24 UTC
Labels: iOS, needs repro

**Comment by Razorholt** [comment] 2021-03-11 02:54
Actually, after several tests I came to the conclusion that you can't transition from one stackPresentation to another (within the same container) without experiencing a weird behavior or a freeze.
i.e. from stackPresentation:'fullScreenModal' to stackPresentation: 'modal', the next screen moves up fine but the previous screen doesn't "move down" behind it and no shadow.
I tried several combinations. Can you guys please confirm?

**Comment by WoLewicki** [comment] 2021-03-15 17:01
I believe the `fullScreenModal` option is natively designed in such a way that it stays below even other modals after the transition. You can check if there are any inconsistencies between the `react-native-screens` and the native behavior by making a simple native iOS app and checking the transitions/view hierarchies there. We can then work on it if there are any.
