### ISSUE TITLE
[tvos]: Compilation issue: 'searchTextField' is unavailable: not available on tvOS

### ISSUE THREAD

**Issue by Budaa** [software-mansion/react-native-screens#993] opened 2021-06-22 13:25 UTC
## Description
The App is failing to compile because the native module `RNSSearchBar` is trying to use the features not available on tvos. 

`'searchTextField' is unavailable: not available on tvOS`
`'setShowsCancelButton:animated:' is unavailable: not available on tvOS`

### Screenshots
![Screenshot 2021-06-22 at 2 20 59 pm](https://user-images.githubusercontent.com/6993121/122931735-11e04480-d365-11eb-8c5b-7620668547f7.png)

## Steps To Reproduce

1. Add `react-native-screens@^3.4.0:` to tvos app
2. Link dependencies in podfile: `pod 'RNScreens', :path => './node_modules/react-native-screens'`
3. pod update
4. try to compile

### Expected behavior
App compiles

### Actual behavior
App fails to compile

## Package versions

- React: 16.11.0
- React Native: npm:react-native-tvos@0.62.2-0
- React Native Screens: 3.4.0

**Comment by Budaa** [comment] 2021-06-22 17:04
Looks like this PR is fixing above issue.
https://github.com/software-mansion/react-native-screens/pull/988

**Comment by WoLewicki** [comment] 2021-06-23 08:58
I think it is duplicate of #950 so I will close it. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2021-06-23 08:58 UTC

**Comment by Budaa** [comment] 2021-06-23 10:09
@WoLewicki Yes it is indeed, just there are bit more details on mine so it will be easier to find if someone googles the error. :+1:
