### ISSUE TITLE
[3.0.0] = Header's background color + Warning

### ISSUE THREAD

**Issue by Razorholt** [software-mansion/react-native-screens#888] opened 2021-04-15 02:10 UTC
Expo SDK 41
Screens 3.0.0
React-Navigation v5
---

After upgrading to Expo SDK 41 with Screens v3.0.0 I have the following issues:

1.-  Header's background color (not showing)
2.- "Can't perform a React state update on an unmounted component" warning on navigation.pop()

Disabling screens fixes both issues, but I'd prefer using it. Thanks for your help!

**Comment by WoLewicki** [comment] 2021-04-15 09:16
Can you provide a repo with minimal configuration needed to reproduce the issue?

**Comment by hugo-chq** [comment] 2021-04-21 05:07
I could reliably get the header color to not get set with this example screen (posted in other issue) 
https://github.com/software-mansion/react-native-screens/issues/862#issuecomment-805467360

it appears related to screen render time, 

quick render time = header background works
slow render time = header background doesn't change

**Comment by kacperkapusciak** [comment] 2021-04-21 09:18
This issue should no longer persist in `react-native-screens` v3.1.0+. If you are using Expo managed workflow you're kind of out of luck here 😞 . Sadly, one of the disadvantages of Expo managed workflow is that you can't upgrade native dependencies by hand because they compiled for a specific SDK. The newest version of our lib will be included in the next (hopefully patch) release of Expo SDK. If you want to know more check [this part of Expo docs](https://docs.expo.io/introduction/managed-vs-bare/#workflow-comparison).

**Comment by Razorholt** [comment] 2021-04-21 15:48
Thanks a lot guys for your replies. That's what I was afraid of. Until Expo updates screens to 3.1 I'll have to eject... That sucks, really.

**Comment by Razorholt** [comment] 2021-04-21 16:24
There is hope... https://forums.expo.io/t/react-native-screens-v3-1-1/51483

**Closed** 2021-04-22 07:17 UTC
Labels: needs repro
