### ISSUE TITLE
Accidental click event on swipe back gesture

### ISSUE THREAD

**Issue by rinpatva14** [software-mansion/react-native-screens#417] opened 2020-03-12 06:56 UTC
I have create multiple Stack.Navigator.

Present one controller(Present screen - screen A) then navigate to second screen(Right to left transition - Screen B). 
-> Swipe to back (Execute click event in second B). I have using flat list in screen B. When I back screen B to screen with swipe event then execute click event on screen B. 

= Generaly no view event execute while swipe to back but multiple stack.Navigator facing issue.

Example
======
```
 <Stack.Navigator
            screenOptions={{
                headerShown: false
            }}>
            <Stack.Screen name="mainscreen" options={{stackAnimation: 'none'}} component={Mainscreen}/>
            <Stack.Screen name="mainscreen" options={{stackAnimation: 'transparentModal'}} component={TeamSettings}/>
<Stack.Navigator>


export const TeamSettings =() => {
    return (
        <Stack.Navigator
            initialRouteName="screenA"
            screenOptions={{
                headerShown: false
            }}
        >
            <Stack.Screen name="screenA" options={{stackPresentation: 'transparentModal'}} component={changeTeam}/>
            <Stack.Screen name="screenB" options={{stackPresentation: 'push'}} component={createPrivateTeam}/>
</Stack.Navigator>
```

**Comment by WoLewicki** [comment] 2020-03-16 16:21
Looks like a duplicate of #416, I'm closing it then. If it is not the same, please inform me.

**Closed by WoLewicki** 2020-03-16 16:21 UTC
