### ISSUE TITLE
Navigation header looks different in ios 16 beta.

### ISSUE THREAD

**Issue by dlehddnjs** [software-mansion/react-native-screens#1570] opened 2022-08-23 06:31 UTC
### Description

<img width="445" alt="Screen Shot 2022-08-23 at 10 52 25 AM" src="https://user-images.githubusercontent.com/7699765/186051598-c503a352-13e3-4d0a-bbe5-40866d033677.png">

Navigation header looks different in iOS 16 Beta.
It happens in iPhone 11 Pro (16.0, 20A5349b)
I just updated iOS to 16.0 and other don't.
Is there any changes on iOS 16.0 affects to native-stack?

Expected behavior below.

![Screen Shot 2022-08-23 at 10 51 51 AM](https://user-images.githubusercontent.com/7699765/186051827-4e7d6aea-9054-4fd0-a0d1-b6ac3d97d2df.png)

### Steps to reproduce

Navigation header in all screens are looks different in iOS 15.

### Snack or a link to a repository

https://snack.expo.dev/NmQgCtSUU?platform=ios

### Screens version

3.5.0

### React Native version

0.67.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

iPhone 12 mini (But iOS version is important - 16.0 Beta)

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2022-08-26 10:36
Hi @dlehddnjs, 

would you mind describing the differences between iOS 15 & 16 in more verbose way? Is this only `headerTitle` offset, or are there more visual quirks? 

![image](https://user-images.githubusercontent.com/50801299/186885501-80b49c58-ed10-4d02-be60-91deb1d05fd9.png)

**Comment by dlehddnjs** [comment] 2022-08-29 06:39
Hi, @kkafar, 
Test results so far have not found anything other than `headerTitle` offset.

**Comment by notjosh** [comment] 2022-09-01 11:21
I'm unable to reproduce the button on the right drifting off to the bottom. From screenshots, it seems to only occur on device, is that correct? I'm running the latest iOS 16 beta (beta8, 20A5358a).

@dlehddnjs can you confirm this is still an issue for you, and that the Snack is correct (your screenshot is a different icon, so maybe the icon(/subviews) matter).

Thanks!

**Comment by dlehddnjs** [comment] 2022-09-05 06:06
@notjosh,

Yes, I've been tested it only on device.
(Worrying about the stableness for Xcode, I did not update to Xcode beta version.)

Your solution is worked perfectly on title text, but not on Icon.
(Title is aligned perfect.)

I think size of the Icon is same, I'll figure it out whether there is un difference on icons or not.

**Comment by notjosh** [comment] 2022-09-05 09:39
@dlehddnjs I was (finally) able to consistently reproduce problem with the icon in our app (with a semi-complicated set up), but not with the reproduction code you provided. Do you have a smaller repro that consistently causes the problem? I'm happy to look into it if you can put up a Snack that consistently triggers the issue for you!

Key points:

- build app with Xcode 13, run app on iOS 16 (both simulator or device have the problem)
- dynamically toggle the icon (i.e. reacting to scroll, or timer), where the initial state is hidden (i.e. `headerRight: undefined`)
- `title` (and some other styles?) needs to be set

If all of these conditions are met, then I can get icon misalignment.

I haven't got a small repro for a Snack, as the current situation is occurring deep within in our app, and I can't easily extract it to examine/share the bug :( I also don't have a good workaround right now, but it doesn't seem to occur when building via Xcode 14...so we're hoping the bug will mostly disappear when Xcode 14/iOS 16 is released

**Comment by dlehddnjs** [comment] 2022-09-06 00:51
@notjosh,

Thank you for you help, I found where this problem occurs.
It occurs from ```headerRight: () => <></>```
We kept reproduced this issue but other option is not affect on it.

We define NativeStackNavigationOptions and using like below.

```
type HeaderOption = 'default';

const DefaultNavigatorHeaderOption: NativeStackNavigationOptions = {
  // it is default header design, can override option in each screen
  headerStyle: {backgroundColor: palette.white},
  headerShadowVisible: false,
  headerBackTitleVisible: false,
  headerBackVisible: false,
  headerTintColor: palette.primaryBlack,
  headerTitleAlign: 'center',
  headerTitle: ({children}) => <SubTitle size={1}>{children}</SubTitle>,
  headerLeft: () => <></>,

  // Where problem occurs
  headerRight: () => <></>,
};

const NavigationHeaderOptions: {[key in HeaderOption]: NativeStackNavigationOptions} = {
  default: DefaultNavigatorHeaderOption,
};

export {NavigationHeaderOptions};
```

I think it can be occurred in headerLeft also. Is it possible?
Is there any patch about this on next version?
Or should I avoid using in code like ```headerRight: () => <></>``` ?

**Comment by hugo-chq** [comment] 2022-09-08 01:21
We had a similar issue on iOs 16, multiple buttons were mapped inside a fragment
```
headerRight: () => (
          <>
            {rightButtons?.map((item, index) => (<RightButton  />)
          </>
        )
```
moving them to a view (with a flex style) fixed it here, atleast in the simulator
```
headerRight: () => (
         <View style={styles.rightButtonsHolder}>
            {rightButtons?.map((item, index) => (<RightButton  />)
         <View/>
        )
```

**Comment by bradzickafoose** [comment] 2022-09-09 16:18
I'm also experiencing this issue where the header title is not displaying properly on iOS 16. 

I thought the issue might resolve itself in the latest iOS 16/Xcode 14 Release Candidates but it still exists.

My issue is only with the header title (and not the header right/left areas). I haven't tried @notjosh's fix yet, but I will try it now, and see if it resolves the issue. 

What's weird is the issue seems like some sort of race condition because if I kill the app, and then restart it, the issue with the header title will sometimes go away on one screen, but then appear on a different screen.

**Comment by hirbod** [comment] 2022-09-10 11:58
iOS 16 is out in two days, can we quickly land a fix for this @kkafar ?

**Comment by kkafar** [comment] 2022-09-10 12:07
@hirbod 
I've tested this fix with header: https://github.com/software-mansion/react-native-screens/pull/1579 (just swapping the lines around) but I had report from other @software-mansion team that it did not resolve the issue. I guess I can have it landed, as this change should not mess with any other behaviour, but it is not 100% reliant.

**Comment by hirbod** [comment] 2022-09-10 12:32
Ok, thanks for the insights. I'll pull them patch in and give it a try, but since you already have reports that's not reliant I'm not having high hopes :).

Hmu when you need testing!

**Comment by Gregoirevda** [comment] 2022-09-13 12:31
I'm having a similar issue on iOS 16 device (not emulator). When Screen options have
```jsx
<Stack.Screen options={{headerShown: false}}>
```

And the screen has 
```jsx
function onMount() {
  navigation.setOptions({headerShown: true, title: '', headerRight: <Icon name="bookmark" />})
}
```
The default back button misses margin left and the headerRight icon is out of the header: pushed down and right.

**Comment by hirbod** [comment] 2022-09-13 13:41
@Gregoirevda when is onMount triggered? `useEffect`? If yes, try useLayoutEffect instead. I also had this issue with iOS 15 and using useLayoutEffect was the way to fix it.

**Comment by Gregoirevda** [comment] 2022-09-13 16:32
@hirbod It's an `onCompleted` of a network query. So I can't use `useLayoutEffect` as I need network data to set the `headerRight` or not

I've seen the same issue on Instagram on iOS 16: if you navigate to a user profile screen the header will look fine, but if you (close the app) and open the profile screen from an universal link (opening the link from Notes for example), they need to do a network request before knowing the person name (and adding a bell icon or not). This seem to change the order in which the header is created and the title is moved down, not aligned anymore with other icons.

I'm going to try compiling with XCode 14

**Comment by fobin** [comment] 2022-09-14 06:32
I have the same issue. 
![image](https://user-images.githubusercontent.com/1096951/190076605-2e90067d-e919-4a96-93b7-98a4f5f91f0f.png)

I'm using it like: 
```js
useLayoutEffect(() => {
    navigation.setOptions({
      headerRight: () => (
        <Icon name="ios-attach" size={30} color="white" onPress={() => {}} />
      ),
    });
  });
`

**Comment by hirbod** [comment] 2022-09-14 08:25
Ok, so the bug is back. @WoLewicki once implemented a fix for it

**Comment by howg0924** [comment] 2022-09-15 07:25
Maybe related:

https://developer.apple.com/forums/thread/713676

**Comment by klandell** [comment] 2022-09-15 13:39
Related to this issue in native-navigation:
https://github.com/react-navigation/react-navigation/issues/10840

**Comment by dlehddnjs** [comment] 2022-09-15 14:10
> Related to this issue in react-navigation: [react-navigation/react-navigation#10840](https://github.com/react-navigation/react-navigation/issues/10840)

Following @hirbod 's answer from @klandell 's link, maybe it has fixed in later version of iOS 16.

https://github.com/react-navigation/react-navigation/issues/10840#issuecomment-1248117850

**Closed** 2022-09-23 09:29 UTC
Labels: Platform: iOS, Repro provided

**Comment by TheDexire** [comment] 2022-10-20 10:59
This problem still actual
How to resolve this issue?

**Comment by stachu2k** [comment] 2022-10-25 12:17
I have just updated to iOS 16.1 and it looks fixed :)

**Comment by arthuralee** [comment] 2022-11-08 19:34
This issue seems to have re-emerged after ios 16.1 came out of beta. Can anyone else in here confirm this?

**Comment by chinieer** [comment] 2022-11-16 03:46
This issue still in ios 16.1 official version

**Comment by Watersdr** [comment] 2022-12-19 16:51
Still seeing this behavior on Xcode 14.2 iOS 16.2 iPhone 14 simulator

**Comment by fobin** [comment] 2022-12-22 12:00
@kkafar I think this should be kept open. Still seeing this with 16.2.

**Comment by fobin** [comment] 2022-12-22 12:01
I've managed to narrow it down a bit. I was using it actually like this. useLayoutEffect(() => {
    navigation.setOptions({
      headerRight: () => (
        <Icon name="ios-attach" size={30} color="white" onPress={() => {}} />
      ),
    });
  });
`

**Comment by fobin** [comment] 2022-12-22 12:43
I managed to find a workaround. Think issue comes from the fact I was clearing the headerTitle set in previous screen at the same time as I was bringing the headerRight element. What worked for me was to first clear the headerTitle and then in setTimeout call again navigation.setOptions and set the headerRight there separately.

**Comment by Entireno** [comment] 2023-11-10 12:06
I am experiencing the same problem in iOS 17, both in the simulator and on the real device. Can you help to solve the problem?
