### ISSUE TITLE
Multiple push have webview page stack navigation  will be crashed

### ISSUE THREAD

**Issue by tentechgroup** [software-mansion/react-native-screens#135] opened 2019-08-12 13:04 UTC
When i enter twice with the view have webview stack navigation, it will be crashed.
![image](https://user-images.githubusercontent.com/46642361/62866854-7cc19d00-bd44-11e9-9eb0-32f171176de5.png)

**Comment by tentechgroup** [comment] 2019-08-12 13:05
in App.js 
![image](https://user-images.githubusercontent.com/46642361/62867026-daee8000-bd44-11e9-96c2-ae0611a6bcbf.png)
when i remove useScreens() it do not crash again.

**Comment by xtroncode** [comment] 2020-03-13 04:45
@tentechgroup  were you able to solve this ? I am facing a similar issue (same error stack ) . In my case when I remove useScreens() the app does not crash but becomes very slow after navigating a few screens

**Comment by xtroncode** [comment] 2020-03-13 04:48
@kmagiera Can I help resolve this issue ? It is blocking the release of react-native version of our app. It would be great if you could point to where I should be looking at as to why this is occurring. Thanks.

**Comment by kmagiera** [comment] 2020-03-13 07:44
Thanks for offering your help. The  first step as with all the issues reported would be to prepare a small reproduction app for example in a form of snack or small repo on GitHub

**Comment by WoLewicki** [comment] 2020-05-19 07:44
@xtroncode any update on that? Can you say if it is the same issue as #214?

**Comment by xtroncode** [comment] 2020-05-19 08:24
@WoLewicki  I am not working on that project now but I think we got around the issue by adding the `androidHardwareAccelerationDisabled={true}` prop to WebView component.

**Comment by WoLewicki** [comment] 2020-05-19 09:38
Ok, it looks similar to the workaround of #214 so the origin of the bug seems to be the same. I am closing it then. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2020-05-19 09:38 UTC
Labels: Android, bug, needs more info
