### ISSUE TITLE
enableScreens() with react navigation make component inside ScrollView unable to receive touch event

### ISSUE THREAD

**Issue by OscarYuen** [software-mansion/react-native-screens#373] opened 2020-02-23 08:48 UTC
In the app , create a bottom tab bar with createBottomTabNavigator in react-navigation
There are two screens located at two bottom tabs respectively, the first one with ScrollView and the another one has normal flat list

-Opening the 1st tab for the first time, scrollView works fine.
-Switch to 2nd tab and back to 1st tab the scrollView still works
-Fast scroll the scrollview and switch to the 2nd tab when momentum of the scrollview is still running
-Switch back the 1st tab, the component inside the scrollview cannot trigger onPress callback

Solution:
Remove enableScreens() in app.js

Using:
iOS 13(seem this bugs only happen in iOS)
Expo SDK 36
"react-native-reanimated": "~1.4.0"
"react-native-screens": "2.0.0-alpha.12"
"react-navigation": "^4.1.1"
"react-navigation-stack": "^2.1.1"
"react-navigation-tabs": "^2.7.0"

**Comment by OscarYuen** [comment] 2020-02-26 14:06
Confirmed that this issue also happens in 2.0.0-beta.12

**Comment by WoLewicki** [comment] 2020-03-26 15:15
Can you provide a repo with minimal configuration needed that shows the bug?

**Comment by WoLewicki** [comment] 2020-04-03 11:55
It looks like a duplicate of #102 so I am closing it. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2020-04-03 11:55 UTC
Labels: bug, iOS
