### ISSUE TITLE
transparentModal with react-navigation does not allow for navigations outside the stack

### ISSUE THREAD

**Issue by Aryk** [software-mansion/react-native-screens#597] opened 2020-08-09 21:42 UTC
Once I open either a navigator or a screen using "transparentModal", I cannot navigate to anything that is not contained within the transparentModal without navigating "back" and closing the modal first.

The issue with this is if a user clicks on a notification and is in a transparentModal, nothing will happen.

I'm using react-navigation v5, expo managed workflow SDK 38.0.  My yarn.lock reports "2.9.0" for react-native-screens.

The only solution it seems for now is that I have to keep track via global state if I'm in a transparentModal or not. If I am, then I have to completely navigate back out of the transparent modal and only then I can navigate to another screen or tab.

Or am I missing something?

**Comment by Aryk** [comment] 2020-08-12 08:54
I tried making the snack and it was working there...I was able to get it working in my code, by running two navigate commands. Is it bad practice to run two navigate commands back-to-back?

**Comment by WoLewicki** [comment] 2020-08-12 08:56
Navigation events bubble up IIRC, so if it gets things done, I think it is OK. Can I close this issue then?

**Comment by WoLewicki** [comment] 2020-08-27 07:34
Closing this issue since I think there is nothing more I can help you with regarding it. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2020-08-27 07:34 UTC

**Comment by Aryk** [comment] 2020-08-30 21:48
Ok...I think I finally got it!

Check this out: https://snack.expo.io/@tennisbum/transparentmodal-navigate

If you remove the `options={{stackPresentation: "transparentModal"}}` from line 80, it will actually navigate.

The current "hack" that I have to do...is readd the screens/navigators **again** in the transparentModal navigator.

**Comment by WoLewicki** [comment] 2020-08-31 14:38
It looks like it is not the case of only `transparentModal`, but of all modal presentation types. You can see that the screen under the modal changes so it is not like the navigation is not happening, rather the modals are not dismissed when the screen in which they were presented is dismissed. You could add something like `[self.presentedViewController dismissViewControllerAnimated:NO completion:nil];` under this line: https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreen.m#L361. Also, what do you mean by re-adding?

**Comment by Aryk** [comment] 2020-08-31 16:04
Well, what I have to do now is if I have:

 * NavigatorA
 * NavigatorB (transparentModal)

I have to put NavigatorA inside NavigatorB for it to actually work. So it is a sibling and a child of NavigatorB.

**Comment by spedroq** [comment] 2025-06-03 13:59
I still see an unexpected behaviour with the `transparentModal` only.

Scenario:
 - StackNavigator A
     - ScreenA
     - ScreenB (modal)
     - ScreenC (transparentModal)
     - ScreenD (transparentModal)

Navigating from ScreenC to ScreenD does not navigate correctly, where other navigations work as expected.

Currently if I want to support navigating from a transparentModal screen to another (through a notification press for example), I have two work arounds:
 - Go back before navigating
 - Do not use `transparentModal`

If you have other ideas or news let me know 😄
