### ISSUE TITLE
image picker break "modal" | "formsheet" presentation in native-stack.

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-screens#1266] opened 2022-01-11 08:56 UTC
## Description

![Jan-11-2022 10-55-18](https://user-images.githubusercontent.com/19273413/148911398-0098b462-aaf3-457a-8753-f3157a902466.gif)

## Reproduction

https://snack.expo.dev/@aeid/thrilled-strawberries

## Steps To Reproduce

just try to open the image picker with `expo-image-picker` or the community package, while being inside a formSheet ios modal.

## Platform

-  [x] iOS

## Workflow

- [ x ] Managed workflow
- [ x ] Bare workflow

## Package versions

    "react-dom": "17.0.1"
    "react-native": "0.64.3"
    "@react-navigation/native": "^6.0.6"   
    "react-native-screens": "~3.10.1",

**Comment by Hirbod** [comment] 2022-01-18 09:41
I can confirm this. Only "containedModal" is not affected by this. 
I also had issues with this library: https://github.com/baronha/react-native-multiple-image-picker/issues/59

As soon as the picker modal closed, my open modal closed as well.

**Comment by kkafar** [comment] 2022-08-16 07:01
Looks like fixed by [expo#15960](https://github.com/expo/expo/pull/15960). If it is not the case, please let me know & will reopen and look into this.

**Closed by kkafar** 2022-08-16 07:01 UTC
Labels: Repro provided
