### ISSUE TITLE
[Android] App crash on start (NullPointerException)

### ISSUE THREAD

**Issue by maitrungduc1410** [software-mansion/react-native-screens#279] opened 2020-01-11 10:02 UTC
Hi All,

I'm using this library with `react-navigation`

when enable this library using:
```js
// enable in App.js
import { enableScreens } from 'react-native-screens'
enableScreens() // OK on iOS but crash on Android
```
Then when I start my app in Android it crashes right at the beginning

Here the error:
```js
 --------- beginning of crash
2020-01-11 17:56:41.155 25469-25469/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.meadow9, PID: 25469
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.swmansion.rnscreens.ScreenContainer.isTransitioning()' on a null object reference
        at com.swmansion.rnscreens.ScreenFragment.onCreate(ScreenFragment.java:51)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

My environment:
- react-native: 0.61.5
- react-navigation: 4.0.10
- react-native-screens: 2.0.0-alpha.22
(Other setups I already follow documents)

Can any help this,

Many thanks

**Comment by iohin** [comment] 2020-01-13 07:57
Hi. I have the same issue. This crash may be fixed by replacing in com.swmansion.rnscreens.ScreenFragment
public void onCreate (@Nullable Bundle savedInstanceState)
on
public void onViewCreated (@NonNull View view, @Nullable Bundle savedInstanceState)

But this leads to another issue with react-navigation-tabs. If push to some screen from tab navigator and return back then tab navigation no more switched between tabs

**Comment by gavinangym** [comment] 2020-01-15 06:53
Same issue:     
Process: sg.xxx.dbg, PID: 9824
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.swmansion.rnscreens.ScreenContainer.isTransitioning()' on a null object reference
        at com.swmansion.rnscreens.ScreenFragment.onCreate(ScreenFragment.java:51)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

OK on iOS. I hope this can be fixed. Seems like quite a number of issues related to onCreate in the issues list that are not closed for a very long time.

**Comment by DGCarramona** [comment] 2020-01-15 23:00
Same here, error thrown when navigating in a switch navigator

**Comment by SystemBlad** [comment] 2020-01-22 21:41
Same error here.

**Comment by ChrisEelmaa** [comment] 2020-01-28 11:26
same

**Comment by ilibilibom** [comment] 2020-01-30 12:00
same here

**Comment by neoswallow** [comment] 2020-01-30 15:47
Having same issue with exact same versions.

react-native: 0.61.5
react-navigation: 4.0.10
react-native-screens: 2.0.0-alpha.22

**Comment by maitrungduc1410** [comment] 2020-02-05 03:32
@kmagiera Do you have any plan to look at this issue, thank you

**Comment by kmagiera** [comment] 2020-02-05 08:55
I can take a look but before I do I'd need to get a minimal repro app where I can see the crash happening. Apparently in this case the stacktrace that's provided in the issue description does not say much about what could be causing the issue (I see that there one object is null but I wouldn't expect it to be null at this moment and adding nullability check won't resolve this problem)

**Comment by luutruong** [comment] 2020-02-06 13:43
Hi @kmagiera I have this error when running app (android, app crash at begin)

```
Process: XXX, PID: 12531
    java.lang.IllegalStateException: Fragment already added: ScreenFragment{a7a1462 (c161878b-e815-41df-a526-5cdbf51b95d1) id=0x19f}
        at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:1379)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:399)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

My `package.json`

```
"@merryjs/photo-viewer": "^3.1.2",
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/masked-view": "^0.1.6",
    "@react-native-community/viewpager": "^3.3.0",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/material-top-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "buffer": "^5.4.3",
    "crypto-js": "^3.1.9-1",
    "events": "^3.1.0",
    "htmlparser2": "^4.0.0",
    "i18n-js": "^3.5.1",
    "lodash": "^4.17.15",
    "lodash.memoize": "^4.1.2",
    "moment": "^2.24.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-admob": "^2.0.0-beta.6",
    "react-native-device-info": "^5.5.1",
    "react-native-fast-image": "^7.0.2",
    "react-native-gesture-handler": "^1.5.6",
    "react-native-google-analytics": "^1.3.2",
    "react-native-image-crop-picker": "^0.26.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-onesignal": "^3.6.4",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.6.4",
    "react-native-screens": "^2.0.0-beta.2",
    "react-native-tab-view": "^2.13.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^8.0.6",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0"
```

**Comment by tapz** [comment] 2020-02-12 18:09
Just added react-native-screen as react-navigation-native-stack requires it. And what it does it crash. Shouldn't be too hard to reproduce.

**Comment by MostafaMAbdellateif** [comment] 2020-02-17 23:02
Same here, i also tried downgrade them as @neoswallow said but didn't work

**Comment by kmagiera** [comment] 2020-02-18 14:45
Hi @tapz – looks like you don't have any problems reproducing the crash. Do you mind pushing a sample project where the crash happens on github so that I can pull the code and reproduce for myself?

**Comment by ChrisEelmaa** [comment] 2020-03-01 10:51
I just noticed there is no `isTransitioning` property in the latest version (2.2.0). I've rolled out that version to production to see how everything holds up, worth a try if anyone has still problems.

**Comment by WoLewicki** [comment] 2020-04-01 09:15
Does the issue still persist in the newer version @maitrungduc1410 @ChrisEelmaa or can I close this issue?

**Comment by ChrisEelmaa** [comment] 2020-04-01 09:26
No problems from me with 2.2.0, looks like everything is ok

**Comment by WoLewicki** [comment] 2020-04-01 12:38
Ok, so I am closing it. Feel free to comment if something still does not work as it should.

**Closed by WoLewicki** 2020-04-01 12:38 UTC
Labels: Android, bug
