### ISSUE TITLE
enableFreeze can not prevent re-render caused by useIsFocused hook

### ISSUE THREAD

**Issue by sunhx-shx** [software-mansion/react-native-screens#2005] opened 2024-01-08 08:23 UTC
### Description

there have two screen in my application, I press one item navigate to detail screen, when I get into detail screen, the last search screen re-rendered, I used the useIsFocused hook in search.jsx,
the react navigation doc show that using useIsFocused hook triggers a re-render for the screen when it changes focus,  Is this the reason?   This can show the enableFreeze can not freeze screen which called useIsFocused?

<img width="929" alt="one" src="https://github.com/software-mansion/react-native-screens/assets/77148584/18c172a1-82c9-4c96-af3e-356986c75020">
<img width="929" alt="two" src="https://github.com/software-mansion/react-native-screens/assets/77148584/b0b62049-182b-4963-bb6d-6e841dfbfc67">

### Steps to reproduce

1. set enableFreeze(true) in app.js
2.Navigate to search screen.
3.tap item to detail screen
4.when get into detail screen, search screen re-render 

### Snack or a link to a repository

https://snack.expo.dev/hz-a9zzR7

### Screens version

~3.20.0

### React Native version

0.71.14

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 pro max

### Acknowledgements

Yes

**Comment by tboba** [comment] 2024-01-08 09:46
Hi @sunhx-shx, thank you for creating this issue!
Do you know if this issue still exists on the newest version of react-native-screens? Have you tried to install `3.29.0` version and create a custom development bundle (with `npx expo prebuild`)?

Also, could you create a repro with similar hierarchy of screens that you have (currently I cannot reproduce this issue, nothing re-renders for me 😕)

**Comment by sunhx-shx** [comment] 2024-01-08 13:20
> Hi @sunhx-shx, thank you for creating this issue! Do you know if this issue still exists on the newest version of react-native-screens? Have you tried to install `3.29.0` version and create a custom development bundle (with `npx expo prebuild`)?
> 
> Also, could you create a repro with similar hierarchy of screens that you have (currently I cannot reproduce this issue, nothing re-renders for me 😕)

@tboba   hi  thanks for the reply!
I've reproduced the issue here:    https://github.com/sunhx-shx/furniture_mall
Thanks♪(･ω･)ﾉ

**Comment by sunhx-shx** [comment] 2024-01-15 08:50
@tboba   Can you reproduce the issue?

**Comment by kkafar** [comment] 2024-06-08 09:28
Hey, that behaviour is known and I believe this behaviour to be expected. Navigating to new destination causes reaction to 'blur' event on the side of navigating-from screen, thus most likely causing a re-render. Moreover, enableFreeze just uses react suspense mechanism underneath so I guess this is how the interaction looks like. 

I'll close the issue as we do not plan to work on this, however I'm leaving the discussion open. Don't hesitate to ping me if any new facts emerge.

**Closed by kkafar** 2024-06-08 09:28 UTC
Labels: Platform: iOS, Repro provided
