### ISSUE TITLE
Using `headerTitleAlign` or `headerLeft` or `headerRight` ignores `headerTitleStyle`

### ISSUE THREAD

**Issue by arcollector** [software-mansion/react-native-screens#1105] opened 2021-09-06 01:01 UTC
## Description

Using `@react-navigation/native-stack` and applying some of these props:
1. `headerTitleAlign`
2. `headerLeft`
3. `headerRight`

makes `headerTitleStyle` prop to be ignored completly

## Steps To Reproduce

1. The following header configuration makes `headerTitleStyle` ignored

```js
    <Stack.Navigator
      initialRouteName="Home"
      screenOptions={{
        headerTintColor: 'white',
        headerStyle: { backgroundColor: 'tomato' },
        headerTitleStyle: {
          fontSize: 10,
        },
        // un-comment this line to reproduce bug
        //headerTitleAlign: 'center',
      }}
    >
```

### Expected behavior

`headerTitleStyle` should still persist whatever value  `headerTitleAlign` or `headerLeft` or `headerRight` contains

### Actual behavior

Without `headerTitleAlign`

![image](https://user-images.githubusercontent.com/1631140/132146957-9f30e2da-fe4b-40c3-a6eb-ae163153820a.png)

Setting to  `headerTitleAlign: 'center'`

![image](https://user-images.githubusercontent.com/1631140/132146914-54e8d1bb-4762-493a-8cd2-ec51771bec89.png)

## Snack or minimal code example

```jsx
import React from 'react';
import {
  Text,
  View,
} from 'react-native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { NavigationContainer } from '@react-navigation/native';

const Home = () =>
  <View style={{flex:1}}><Text>Home</Text></View>

const Stack = createNativeStackNavigator();
function MyStack() {
  return (
    <Stack.Navigator
      initialRouteName="Home"
      screenOptions={{
        headerTintColor: 'white',
        headerStyle: { backgroundColor: 'tomato' },
        headerTitleStyle: {
          fontSize: 10,
        },
        headerTitleAlign: 'center',
      }}
    >
      <Stack.Screen
        name="Home"
        component={Home}
        options={{
          title: 'Awesome app',
        }}
      />
    </Stack.Navigator>
  );
}

function App() {
  return (
    <NavigationContainer>
      <MyStack />
    </NavigationContainer>
  )
}

export default App;
```

## Package versions

- React: 17.0.2
- React Native: 0.65.1
- React Native Screens: 3.6.0

**Comment by kacperkapusciak** [comment] 2021-09-06 09:32
Duplicate of https://github.com/react-navigation/react-navigation/issues/9885
Issue should be fixed in the next release of `react-navigation/native-stack` by https://github.com/react-navigation/react-navigation/commit/127e030e03cfec9600cca0327edd159a7bb08896

Cheers

**Closed by kacperkapusciak** 2021-09-06 09:32 UTC
