### ISSUE TITLE
`navigation.goBack` crashes the app on Android

### ISSUE THREAD

**Issue by Miraj98** [software-mansion/react-native-screens#1300] opened 2022-02-02 17:56 UTC
## Description

When calling `navigation.goBack` on Android, the app crashes. Works perfectly fine on iOS. The issue does not occur for all screens but specifically when navigating back to the `Tab.Navigator`. My navigation is setup as follows
```
<Stack.Navigator>
  <Stack.Screen name="MainTabs" component={MainTabs} /> // <- This is a bottom tab navigator
  <Stack.Screen name="Screen1" component={Screen1} /> 
  <Stack.Screen name="Screen2" component={Screen2} /> 
  {/*
   * Other screens...
   * /}
</Stack.Navigator>
```

Some where I saw that I should try `detachInactiveScreens={false}`. I tried this and it still does not work. Here is an error log as well - 
```
java.lang.IllegalStateException: com.facebook.react.uimanager.IllegalViewOperationException: StackOverflowException
	at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:387)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:755)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4313)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4138)
	at android.view.View.draw(View.java:20237)
	at android.widget.ScrollView.draw(ScrollView.java:1739)
	at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:488)
	at android.view.View.updateDisplayListIfDirty(View.java:19109)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4138)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:710)
	at android.view.View.draw(View.java:20237)
	at android.view.View.updateDisplayListIfDirty(View.java:19109)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4138)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:710)
	at android.view.View.draw(View.java:20237)
	at android.view.View.updateDisplayListIfDirty(View.java:19109)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4138)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.View.draw(View.java:19962)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at com.swmansion.rnscreens.ScreenStack.performDraw(ScreenStack.kt:295)
	at com.swmansion.rnscreens.ScreenStack.access$performDraw(ScreenStack.kt:15)
	at com.swmansion.rnscreens.ScreenStack$DrawingOp.draw(ScreenStack.kt:316)
	at com.swmansion.rnscreens.ScreenStack.drawAndRelease(ScreenStack.kt:269)
	at com.swmansion.rnscreens.ScreenStack.dispatchDraw(ScreenStack.kt:286)
	at android.view.View.updateDisplayListIfDirty(View.java:19100)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3406)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3190)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2559)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1529)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7409)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1036)
	at android.view.Choreographer.doCallbacks(Choreographer.java:832)
	at android.view.Choreographer.doFrame(Choreographer.java:767)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: com.facebook.react.uimanager.IllegalViewOperationException: StackOverflowException
	... 84 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at org.reactnative.maskedview.RNCMaskedView.updateBitmapMask(RNCMaskedView.java:58)
	at org.reactnative.maskedview.RNCMaskedView.dispatchDraw(RNCMaskedView.java:33)
	at android.view.View.buildDrawingCacheImpl(View.java:19499)
	at android.view.View.buildDrawingCache(View.java:19365)
	at android.view.View.draw(View.java:19954)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4138)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:710)
	... 83 more
```

## Steps To Reproduce

1. Create a stack navigator
2. Embed a tab navigator is its initial screen
3. Add other screens to the stack navigator
4. Navigate to one of these screens from any of the tab navigator tabs
5. call navigation.goBack and the app crashes on android

### Expected behavior
App should not crash

### Actual behavior
App crashes

## Platform

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |    0.64.0     |
| @react-navigation/native               |     6.0.6    |
| @react-navigation/native-stack         |     6.2.5    |
| react-native-screens                   |    3.9.0     |
| react-native-safe-area-context         |   3.3.2      |
| react-native-gesture-handler           |      2.1.0   |
| react-native-reanimated                |    2.2.4     |

**Comment by maticzav** [comment] 2022-02-05 12:15
Did you have any luck resolving this issue or at least finding the source of error?

**Comment by kacperkapusciak** [comment] 2022-02-10 10:45
Hi @Miraj98,
Thank you for submitting an issue!

From the provided steps I was unable to reproduce the crash. Could you provide a minimal reproduction eg. a snack, snippet of code, or GitHub repo that reproduces the problem?

Cheers

**Closed** 2022-03-13 22:45 UTC
Labels: needs-more-info, 🤖android, 🧰needs-repro, needs-review

**Comment by Chandranshu5** [comment] 2023-06-04 04:24
Hey @Miraj98! were you able to resolve the issue, I am facing the same issue and unable to get the solution. Kindly help me.

**Comment by Miraj98** [comment] 2023-06-04 07:20
@Chandranshu5 The issue was actually with a masking library that I was using at the time. The masking library worked on iOS but not on Android.

**Comment by bhc777** [comment] 2024-11-06 01:04
@Miraj98 
me too ,use Material Top Tabs Navigator  page , goback crashes the app on Android .
RN 0.76, 
Material Top Tabs Navigator:6.6.14
react-native-tab-view:3.5.2

Have you found a solution? Please reply to me with help thanks . 
lemonwater@mi.com.tw
