### ISSUE TITLE
[Android] java.lang.IllegalStateException: FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by milkmouth** [software-mansion/react-native-screens#1672] opened 2022-12-29 13:52 UTC
### Description

Can't reproduce locally, only happens in prod, ios work well

android setting
<img width="416" alt="截圖 2022-12-29 下午9 45 13" src="https://user-images.githubusercontent.com/17698980/209962402-f7aacb9b-0e44-4e0a-88ec-b5e8d4408191.png">

enableScreens(false) not work
<img width="384" alt="截圖 2022-12-29 下午9 46 23" src="https://user-images.githubusercontent.com/17698980/209962489-a395ceb2-ba54-4255-ad22-1631bab0935a.png">

Libraries:

"react-native-screens": "^3.18.2",
"react-native": "0.67.1",
"@react-navigation/native": "^6.0.6",

Happens mostly on Samsung phones
<img width="332" alt="截圖 2022-12-30 上午9 33 10" src="https://user-images.githubusercontent.com/17698980/210025980-6b15085e-64ce-4857-9e90-26b2bf7f6f44.png">

Only firebase error tracking

Fatal Exception: java.lang.RuntimeException: java.lang.IllegalStateException: FragmentManager is already executing transactions
       at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:55)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:46)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
       at android.view.Choreographer.doCallbacks(Choreographer.java:899)
       at android.view.Choreographer.doFrame(Choreographer.java:827)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
       
Caused by java.lang.IllegalStateException: FragmentManager is already executing transactions
       at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:94)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:11)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:6)
       at com.swmansion.rnscreens.ScreenContainer.onUpdate(ScreenContainer.java:206)
       at com.swmansion.rnscreens.ScreenContainer.performUpdates(ScreenContainer.java:29)
       at com.swmansion.rnscreens.ScreenContainer.performUpdatesNow(ScreenContainer.java:3)
       at com.swmansion.rnscreens.ScreenContainer.notifyChildUpdate(ScreenContainer.java)
       at com.swmansion.rnscreens.Screen.setActivityState(Screen.java:16)
       at com.swmansion.rnscreens.ScreenViewManager.setActivityState(ScreenViewManager.java:26)
       at com.swmansion.rnscreens.ScreenViewManager.setActivityState(ScreenViewManager.java:6)
       at com.swmansion.rnscreens.ScreenViewManager.setActivityState(ScreenViewManager.java:2)
       at com.facebook.react.viewmanagers.RNSScreenManagerDelegate.setProperty(RNSScreenManagerDelegate.java:555)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:28)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:6)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:14)
       at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:9)
       at com.facebook.react.uimanager.UIManagerModule.synchronouslyUpdateViewOnUIThread(UIManagerModule.java:7)
       at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:143)
       at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:172)
       at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent(NativeAnimatedNodesManager.java:99)
       at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:6)
       at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:27)
       at com.reactnativecommunity.viewpager.ReactViewPagerManager$1.onPageScrolled(ReactViewPagerManager.java:20)
       at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageScrolled(CompositeOnPageChangeCallback.java:18)
       at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageScrolled(CompositeOnPageChangeCallback.java:18)
       at androidx.viewpager2.widget.ScrollEventAdapter.dispatchScrolled(ScrollEventAdapter.java:4)
       at androidx.viewpager2.widget.ScrollEventAdapter.onScrollStateChanged(ScrollEventAdapter.java:58)
       at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:37)
       at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:13)
       at androidx.recyclerview.widget.RecyclerView.cancelScroll(RecyclerView.java:4)
       at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:135)
       at androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl.onTouchEvent(ViewPager2.java:8)
       at android.view.View.dispatchTouchEvent(View.java:15010)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3089)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.cancelTouchTarget(ViewGroup.java:3011)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5566)
       at android.view.ViewGroup.removeViewAt(ViewGroup.java:5520)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:89)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:47)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:171)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:94)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:31)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:6)
       at com.swmansion.rnscreens.ScreenContainer.onUpdate(ScreenContainer.java:206)
       at com.swmansion.rnscreens.ScreenContainer.performUpdates(ScreenContainer.java:29)
       at com.swmansion.rnscreens.ScreenContainer.performUpdatesNow(ScreenContainer.java:3)
       at com.swmansion.rnscreens.ScreenContainer.notifyChildUpdate(ScreenContainer.java)
       at com.swmansion.rnscreens.Screen.setActivityState(Screen.java:16)
       at com.swmansion.rnscreens.ScreenViewManager.setActivityState(ScreenViewManager.java:26)
       at com.swmansion.rnscreens.ScreenViewManager.setActivityState(ScreenViewManager.java:6)
       at com.swmansion.rnscreens.ScreenViewManager.setActivityState(ScreenViewManager.java:2)
       at com.facebook.react.viewmanagers.RNSScreenManagerDelegate.setProperty(RNSScreenManagerDelegate.java:555)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:28)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:6)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:14)
       at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:9)
       at com.facebook.react.uimanager.UIManagerModule.synchronouslyUpdateViewOnUIThread(UIManagerModule.java:7)
       at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:143)
       at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:172)
       at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:73)
       at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:14)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:46)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
       at android.view.Choreographer.doCallbacks(Choreographer.java:899)
       at android.view.Choreographer.doFrame(Choreographer.java:827)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

### Steps to reproduce

Can't reproduce locally, only happens in prod, ios work well

### Snack or a link to a repository

will try to repro

### Screens version

3.18.2

### React Native version

0.67.1

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Release mode

### Device

Real device

### Acknowledgements

Yes

**Comment by awojciak** [comment] 2023-01-17 13:22
I have the same issue on react-native-screens 3.18.2 and react native 0.70.6. Happens only on prod, can't reproduce.

**Comment by kkafar** [comment] 2023-01-17 23:05
Hi, thanks for reporting!

I'll close this issue as a duplicate of https://github.com/software-mansion/react-native-screens/issues/1506 (please move discussion there) and I'll consider reopening #1506, however w/o reliable reproduction it will be hard to tackle this issue.

**Closed by kkafar** 2023-01-17 23:05 UTC
Labels: Platform: Android, MIssing repro
