### ISSUE TITLE
iOS: react-native-screens crashing on React Native 0.68.1 with new architecture enabled

### ISSUE THREAD

**Issue by joaotmachado** [software-mansion/react-native-screens#1420] opened 2022-04-23 17:26 UTC
## Description

Trying to enable the new architecture true on React Native 0.68.1 + Running react-native-screes 3.13.1 and can't finish the build process on Xcode.

## Steps To Reproduce

- Upgrade to RN 0.68.1.
- Upgrade to react-native-screes 3.13.1.
- Run build on Xcode.

### Expected behavior

App to build and launch with the new architecture enabled.

### Actual behavior

Build doesn't finish.

## Reproduction

```
- Combine ShadowNodes.cpp (arm64)
-- 'react/renderer/components/view/ViewProps.h' file not found
--- app/ios/build/generated/ios/react/renderer/components/rnscreens/ShadowNodes.cpp:11
--- app/ios/build/generated/ios/react/renderer/components/rnscreens/ShadowNodes.cpp:13
```

## Platform

- [x] iOS

## Package versions

```
"version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "backgroundTests": "jest --verbose ./src/services/background",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@apollo/client": "^3.5.10",
    "@app/react-native-selectable-text": "^0.0.14",
    "@react-native-async-storage/async-storage": "^1.16.1",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-firebase/analytics": "^14.7.0",
    "@react-native-firebase/app": "^14.7.0",
    "@react-native-firebase/crashlytics": "^14.7.0",
    "@react-native-firebase/in-app-messaging": "^14.7.0",
    "@react-native-firebase/messaging": "^14.7.0",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.1",
    "@react-navigation/stack": "^6.2.1",
    "@sentry/react-native": "^3.4.1",
    "@types/react-native-vector-icons": "^6.4.10",
    "@types/react-navigation": "^3.4.0",
    "add": "^2.0.6",
    "formik": "^2.2.6",
    "graphql": "^16.3.0",
    "graphql-tag": "^2.11.0",
    "hermes-engine": "^0.11.0",
    "lottie-ios": "^3.2.3",
    "lottie-react-native": "^5.0.1",
    "npm-check-updates": "^11.3.0",
    "ramda": "^0.27.1",
    "react": "17.0.2",
    "react-native": "0.68.1",
    "react-native-animatable": "^1.3.3",
    "react-native-background-downloader": "^2.3.4",
    "react-native-background-fetch": "^4.0.4",
    "react-native-background-timer": "^2.4.1",
    "react-native-branch": "^5.0.1",
    "react-native-code-push": "^7.0.4",
    "react-native-collapsible": "^1.5.3",
    "react-native-device-info": "^8.0.5",
    "react-native-flash-message": "^0.1.23",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-hyperlink": "0.0.19",
    "react-native-iap": "^8.0.4",
    "react-native-in-app-review": "^4.1.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-open-notification": "^0.1.4",
    "react-native-progress": "^4.1.2",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^4.2.4",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "^3.13.1",
    "react-native-share": "^5.1.4",
    "react-native-size-matters": "^0.4.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-sound": "^0.11.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-super-grid": "^4.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-system-setting": "^1.7.6",
    "react-native-tts": "^4.1.0",
    "react-native-vector-icons": "^8.1.0",
    "react-native-webview": "11.3.1",
    "realm": "10.20.0-beta.5",
    "rn-fetch-blob": "^0.12.0",
    "styled-components": "^5.2.1",
    "text-encoding": "^0.7.0",
    "use-http": "^1.0.18",
    "yarn": "^1.22.10",
    "yup": "^0.32.9",
    "zustand": "^3.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.13.10",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/plugin-transform-flow-strip-types": "^7.13.0",
    "@babel/runtime": "^7.13.10",
    "@react-native-community/cli-debugger-ui": "^5.0.1",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.20",
    "@types/ramda": "^0.27.39",
    "@types/react": "^17.0.17",
    "@types/react-native": "^0.63.52",
    "@types/react-native-background-downloader": "^2.3.3",
    "@types/react-native-background-timer": "^2.0.0",
    "@types/react-native-dotenv": "^0.2.0",
    "@types/react-native-share": "^3.3.1",
    "@types/react-native-snap-carousel": "^3.8.2",
    "@types/react-test-renderer": "17.0.1",
    "@types/styled-components": "^5.1.15",
    "@types/styled-components-react-native": "^5.1.1",
    "@types/text-encoding": "^0.0.35",
    "@types/yup": "^0.29.11",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "babel-jest": "^26.6.3",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "^7.32.0",
    "eslint-plugin-prettier": "^3.3.1",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "patch-package": "^6.4.7",
    "postinstall-postinstall": "^2.1.0",
    "prettier": "^2.2.1",
    "react-native-dotenv": "^2.5.3",
    "react-native-flipper": "^0.124.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.2.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleNameMapper": {
      "^services(.*)$": "<rootDir>/src/services$1"
    },
    "transform": {
      "^.+\\.(js|jsx|ts|tsx)$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "testPathIgnorePatterns": [
      "/node_modules/",
      "./dist"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
 ```

**Comment by WoLewicki** [comment] 2022-04-25 10:38
Could you provide a minimal reproducible code example in a form of simple repository?  It would be very helpful.

**Comment by vic2tee4u** [comment] 2022-05-13 18:04
Did you find a solution to this? I'm facing the same issue right after turning on the new architecture.

**Comment by jai-adapptor** [comment] 2022-06-01 08:11
Same issue except mine says `react/renderer/components/rnscreens/Props.h>` file not found

**Comment by jai-adapptor** [comment] 2022-06-03 05:06
@WoLewicki 
See this repo and try building from Xcode
https://github.com/jai-adapptor/rnscreens-issue

**Comment by maxperry** [comment] 2022-06-08 20:01
Same issue here too.

<img width="903" alt="Screen Shot 2022-06-08 at 4 00 16 PM" src="https://user-images.githubusercontent.com/6955822/172706336-a9946363-997a-4a52-981c-ade6c4e9a32e.png">

**Comment by chazzaoui** [comment] 2022-06-15 08:36
For anyone else that has seen this issue, for me it also pointed towards rnscreens. But upon further inspection, Looked like this issue was codegen related. I forgot to remove codegen from my package.json. Turns out you don't need it in 0.68 and above. Hope this helps someone!

**Comment by WoLewicki** [comment] 2022-06-15 13:27
I'll close this issue since it seems like the original problem has been solved. Feel free to comment here if I am wrong and we can always reopen it then.

**Closed by WoLewicki** 2022-06-15 13:27 UTC
Labels: 🍎iOS, 🧰needs-repro, needs-review

**Comment by rarenatoe** [comment] 2023-02-27 23:57
I am getting
`'react/renderer/components/rnscreens/ComponentDescriptors.h' file not found`

**Comment by Arvinwolf91** [comment] 2023-03-14 23:59
> error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65.
> 
> 'react/renderer/components/safeareacontext/Props.h' file not found

Found the fix for this?

**Comment by Yuniac** [comment] 2024-01-23 12:04
> react/renderer/components/safeareacontext/Props.h

Same issue here, any fix?

**Comment by Yuniac** [comment] 2024-01-23 12:05
> error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65.
> 
> 'react/renderer/components/safeareacontext/Props.h' file not found

Same issue here, found any fix?

**Comment by wulaizi** [comment] 2025-03-19 06:24
Still, no one has been able to solve this? I'm now using 0.78.0, but as soon as I install this library, the error occurs.
