### ISSUE TITLE
iOS Crash When use_frameworks! and  use ENV['RCT_NEW_ARCH_ENABLED'] = '1'

### ISSUE THREAD

**Issue by Yck-Dakucha** [software-mansion/react-native-screens#2228] opened 2024-07-03 07:48 UTC
### Description

iOS Crash When use_frameworks! and  use ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# CrashInfo
```
Running "TestRNScreen" with {"rootTag":1,"initialProps":{"concurrentRoot":true},"fabric":true}
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RNSScreenStackHeaderConfig setHide:]: unrecognized selector sent to instance 0x10692df90'
```
# Env
```
System:
  OS: macOS 14.5
  CPU: (12) arm64 Apple M2 Max
  Memory: 99.48 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v18.18.2/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "31"
      - "34"
    Build Tools:
      - 33.0.1
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.2.1
    path: /usr/bin/javac
  Ruby:
    version: 3.1.2
    path: /Users/yangcankun/.rvm/rubies/ruby-3.1.2/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: true
```
# Reason i guess
fabric doesn’t support use_frameworks! ，when use_frameworks!  fabric will set RCT_DYNAMIC_FRAMEWORKS=1 to backward compatibility.

![image](https://github.com/software-mansion/react-native-screens/assets/12741176/5e69915c-4849-4b8f-9b4c-60c385270a27)

You can use my demo to reproduce the crash

> https://github.com/Yck-Dakucha/TestRNScreenCrash

### Steps to reproduce

1. use_frameworks! 
2. ENV['RCT_NEW_ARCH_ENABLED'] = '1'
3. pod install
4. run

### Snack or a link to a repository

https://github.com/Yck-Dakucha/TestRNScreenCrash

### Screens version

3.32.0

### React Native version

0.74.3

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 15 Pro (17.5)

### Acknowledgements

Yes

**Comment by FacuBenito** [comment] 2024-07-08 19:57
Same here! I'm trying to build the app with Expo on an iOS simulator of an iPad Pro

**Comment by RicoCallirgos** [comment] 2024-07-11 19:30
Same issue here - I don't even get an error message. The app just crashes immediately.

**Comment by FacuBenito** [comment] 2024-07-11 20:17
> Same issue here - I don't even get an error message. The app just crashes immediately.

Same for me. I could only access the error message by building from Xcode and opening the logs. But other than that, the app crashes and throws no information at all

**Comment by RicoCallirgos** [comment] 2024-07-11 22:05
I just got this working on my project without it crashing.
Updating `use_frameworks!` to `use_frameworks! :linkage => :static` in the podfile resolves the issue for me.

**Comment by Yck-Dakucha** [comment] 2024-07-12 02:17
> I just got this working on my project without it crashing. Updating `use_frameworks!` to `use_frameworks! :linkage => :static` in the podfile resolves the issue for me.

Yes, there is no problem with the static library. The problem is that when using the dynamic library, fabric will use the old architecture to call native-components for backward compatibility. This is the direct cause of the crash, because RNScreens makes different View attributes in the new and old architectures, but only uses the judgment of whether it is the new architecture, and is not compatible with fabric backward compatibility.

**Comment by FacuBenito** [comment] 2024-07-15 12:42
> I just got this working on my project without it crashing. Updating `use_frameworks!` to `use_frameworks! :linkage => :static` in the podfile resolves the issue for me.

This worked wonders! Thanks, you're my savior!

**Comment by kkafar** [comment] 2024-07-24 11:06
> Yes, there is no problem with the static library. The problem is that when using the dynamic library, fabric will use the old architecture to call native-components for backward compatibility. This is the direct cause of the crash, because RNScreens makes different View attributes in the new and old architectures, but only uses the judgment of whether it is the new architecture, and is not compatible with fabric backward compatibility.

This is exactly the issue here. 

I wonder what's the application of using the new architecture & `use_frameworks` with dynamic linkage at the same time? As you pointed out RN will use Paper components any way. Do you do this for the sake of turbomodules?

**Comment by Yck-Dakucha** [comment] 2024-07-25 03:27
> > Yes, there is no problem with the static library. The problem is that when using the dynamic library, fabric will use the old architecture to call native-components for backward compatibility. This is the direct cause of the crash, because RNScreens makes different View attributes in the new and old architectures, but only uses the judgment of whether it is the new architecture, and is not compatible with fabric backward compatibility.
> 
> This is exactly the issue here.
> 
> I wonder what's the application of using the new architecture & `use_frameworks` with dynamic linkage at the same time? As you pointed out RN will use Paper components any way. Do you do this for the sake of turbomodules? What's the incentive here?

The first question: Our app uses  RN as a module and is not a pure RN project. We rely on numerous SDK dependencies, including some written in Swift. Using static libraries causes symbol conflicts, so we are currently limited to using dynamic libraries.

The second question: yes,, we only want to use TurboModules because Fabric currently does not support dynamic libraries., but the current version of RN employs Fabric when using the new architecture. I found a link that seems RN is dealing with the problem of dynamic libraries.

[Bringing use_frameworks! to the New Architecture](https://github.com/reactwg/react-native-new-architecture/discussions/115)
![image](https://github.com/user-attachments/assets/7e3f5f44-fafc-4302-a746-c780d3924a50)

**Comment by kkafar** [comment] 2024-07-25 07:35
Thanks for answer, I see, makes sense now. 
So we are considering two approaches: 

1. Refactor whole codebase, split Paper & Fabric implementations, duplicate much of the code and compile both Paper & Fabric with `RCT_NEW_ARCH_ENABLED=1`, so that on Fabric Paper components can be safely used. 
2. Hack it in some way with preprocessor macros, so that we effectively compile only Paper code when `RCT_NEW_ARCH_ENABLED=1` is enabled and `RCT_DYNAMIC_FRAMEWORKS=1`, since Fabric components aren't used anyway. 

Since this is supposed to be only temporary solution before RN adds full support for dynamic frameworks we're favouring second solution at the moment. @maksg will try to hack this up. 

While the first one would be more comprehensive, and we might eventually lean towards it if the (2) is not effective, however in the first pass we want to go with low effort solution.

**Comment by Yck-Dakucha** [comment] 2024-07-25 07:58
> Thanks for answer, I see, makes sense now. So we are considering two approaches:
> 
> 1. Refactor whole codebase, split Paper & Fabric implementations, duplicate much of the code and compile both Paper & Fabric with `RCT_NEW_ARCH_ENABLED=1`, so that on Fabric Paper components can be safely used.
> 2. Hack it in some way with preprocessor macros, so that we effectively compile only Paper code when `RCT_NEW_ARCH_ENABLED=1` is enabled and `RCT_DYNAMIC_FRAMEWORKS=1`, since Fabric components aren't used anyway.
> 
> Since this is supposed to be only temporary solution before RN adds full support for dynamic frameworks we're favouring second solution at the moment. @maksg will try to hack this up.
> 
> While the first one would be more comprehensive, and we might eventually lean towards it if the (2) is not effective, however in the first pass we want to go with low effort solution.

Thank you for your response. Given the current progress of React Native, I agree that the second approach is both preferable and easier to understand.

**Comment by kkafar** [comment] 2024-07-29 10:09
Updating here: we put this issue on a hang for a while, because we could not get to work the "hacky" solution unfortunately. If you feel like you have capacity a PR would be very very welcome, otherwise someone from the team will be able to come back to this after task with higher priority are done with first. 🙇🏻

**Comment by maksg** [comment] 2024-07-29 10:50
Just a small addition from me: the "hacky" solution is available on the branch https://github.com/software-mansion/react-native-screens/tree/%40maksg/fix-dynamic-frameworks-crash.

Basically React Native forces packages to use Paper with dynamic frameworks turned on so we had to force Screens to compile for Paper in this case. And while this solution works at the first glance, there are issues with disappearing buttons, modal not showing, touches not responding and probably more.

So if you have any ideas on how to fix that for the "hacky" solution than your help would also be very much appreciated!

**Comment by denysoleksiienko** [comment] 2024-08-03 11:44
It seems I have the same problem when I try to wrap react native Modal with `Gesture` and use `RCT_NEW_ARCH_ENABLED=1`.
Could someone take a look at this?
https://stackoverflow.com/questions/78813091/rn-modal-with-gesture-stuck-on-ios-with-new-architecture

**Comment by maksg** [comment] 2024-08-27 11:57
@Yck-Dakucha @FacuBenito @RicoCallirgos It seems to be fixed by this PR https://github.com/software-mansion/react-native-screens/pull/2315.

You can test screens directly from GitHub by putting the following in your package.json:
`"react-native-screens": "software-mansion/react-native-screens#29c98e222d1b25106b2e5c7edf3a1aa3c543b478"`

**Comment by Yck-Dakucha** [comment] 2024-09-05 09:30
> @Yck-Dakucha @FacuBenito @RicoCallirgos It seems to be fixed by this PR #2315.
> 
> You can test screens directly from GitHub by putting the following in your package.json: `"react-native-screens": "software-mansion/react-native-screens#29c98e222d1b25106b2e5c7edf3a1aa3c543b478"`

it works!!!!!!! I tested it on both a physical device and an emulator with RN 0.75.2, using both JSCore and Hermes. Everything ran smoothly without any crashes!

but, there's a reference issue that prevents me from compiling.

I change the line in RNSScreenComponentDescriptor.h:
`#include "utils/RectUtil.h"`
to
`#include <react/renderer/components/rnscreens/utils/RectUtil.h>`

**Comment by maksg** [comment] 2024-09-05 10:59
@Yck-Dakucha Glad to hear that it works!
The referencing issue was also fixed last week (https://github.com/software-mansion/react-native-screens/pull/2319) so it should work in the next release.

**Comment by kkafar** [comment] 2024-09-12 08:04
Basing on confirmation above, I'll proceed with closing the issue. We'll release the fix for this one with next minor (that should be 3.35.0 stable). If something will be still off - let us know.

**Closed by kkafar** 2024-09-12 08:04 UTC
Labels: Platform: iOS, Platform: Android, Platform: tvOS, Repro provided

**Comment by griffinshuth** [comment] 2024-10-04 17:03
So it looks like this fix has not been pushed still any news on when we can get this fix released?  I see it is in the 4.0.0 beta are you not going to do any more releases until you test 4.0.0 betas?

**Comment by kkafar** [comment] 2024-10-05 12:02
My plan is to release stable 3.35.0 *after* I'm done with release of 4.0. Due to various reasons I'm not really eager to swap the order.

If that would work for you, I might release 3.35.0-rc.2, but not a stable. Let me know.

**Comment by griffinshuth** [comment] 2024-10-23 19:54
well react-native 0.76.0 was just released today so anyone who creates a new react native app wont be able to use this library because of this crash because the new arch is turned on by default

**Comment by ecroce** [comment] 2025-01-07 22:46
Ran into this and glad I searched the "closed" issues. Upgraded to 0.76 and was crashing immediately with this same error. I would recommend maybe reopening to make this more searchable in the issues since it defaults to "isOpen." This is blocking us from using new arch for our app.

**Comment by kkafar** [comment] 2025-01-08 13:49
@ecroce this issue should be solved. If you encounter some error please consider opening a new issue together with providing an error reproduction. In case it is really the same issue please provide the details of your case (all the info we ask for in issue template), so that we might try to locate the problem. Thanks!
