### ISSUE TITLE
Android: Navigation resets to first tab in nested navigations

### ISSUE THREAD

**Issue by Hirbod** [software-mansion/react-native-screens#402] opened 2020-03-01 15:06 UTC
I have a TabBar. 3 Tabs. Each Tab has its own stack. On iOS, being in Tab 3 and navigating inside that tab and switching tabs and returning back to tab 3: everything works as expected. I am still on the same screen.

When I do the same on android, I get back to the first screen of that Tab, while I should remain on the same inside stack screen. So the navigation state gets lost. Assume I have an open form and just clicked on a chat notification, returning back and everything is gone and I have to go over again.

React-native-screens 2.2.0.
react-native-screens/native-stack 
react-navigation 5

**Comment by WoLewicki** [comment] 2020-03-26 14:15
Try setting https://reactnavigation.org/docs/bottom-tab-navigator#unmountonblur to `false`. Does the stack still reset after this?

**Comment by Hirbod** [comment] 2020-03-26 18:32
It’s false by default. And it does not occur on iOS, only on Android.

**Comment by WoLewicki** [comment] 2020-03-27 08:41
> It’s false by default. And it does not occur on iOS, only on Android.

True. Can you make a quick snack or repo with the minimal configuration that will show the issue?

**Comment by enheit** [comment] 2020-04-02 21:52
I have absolutely the same issue on my Android (v9).

**Comment by WoLewicki** [comment] 2020-04-03 10:30
I cannot repro this issue on Android (v9), but I am not testing on a physical device. Can someone provide a repo or snack with the configuration needed to recreate the issue?

**Comment by Hirbod** [comment] 2020-04-03 10:32
Neither am I. It's reproducible on emulator and physical device. Tested with Expo 37 and 2.4.0 directly with RN

**Comment by WoLewicki** [comment] 2020-04-03 11:06
I have 3 tabs and each one has a native-stack with two screens. Going to the second screen in any of the stack navigators and next switching between tabs does not reset the stack navigator both on Android 9 and X. I use bare RN project with the newest RNScreens. Remember that using ExpoClient v. 37 will give you native code from RNScreens in v. 2.2.0.

**Comment by enheit** [comment] 2020-04-03 11:09
@WoLewicki  Didn't understand that sentence 
> Remember that using ExpoClient v. 37 will give you native code from RNScreens in v. 2.2.0.

I use Expo v36.0.0, you want to say that issue can disappear after switching to the latest version?

**Comment by WoLewicki** [comment] 2020-04-03 11:14
When using Expo Client, it comes with the native code inside it that can't be changed by giving higher version of package in package.json. So if you use Expo Client v. 36, RNScreens will have native code of version "2.0.0-alpha.12" which you can see here: https://unpkg.com/browse/expo@36.0.0/bundledNativeModules.json

**Comment by enheit** [comment] 2020-04-03 11:16
I've updated to the latest version of expo (at the moment it 37.0.0) and issue still reproducible

P.S. I also have updated expo app on my android which running my app.

**Comment by WoLewicki** [comment] 2020-04-03 11:17
What I'm saying is you should try to make a bare RN project with the latest version of RNScreens and check if the issue exists there as well. If it doesn't, then it was probably fixed in the newer version of RNScreens and then it means that it will not work in Expo Client until they release the version with fixed native code of RNScreens so probably ~second half of June.

**Comment by enheit** [comment] 2020-04-03 11:19
Ah, I understand. I have no time to create bare RN project, so I can't be useful here :(

**Comment by Hirbod** [comment] 2020-04-03 11:26
Issues exists with v2.2.0 + 2.4.0

**Comment by WoLewicki** [comment] 2020-04-03 13:28
Maybe it has something to do with react-redux? Can you check if disabling it makes the bug disappear?

**Comment by Hirbod** [comment] 2020-04-03 13:42
I'll try that but I doubt that connecting a store has anything to do with that.

**Comment by Hirbod** [comment] 2020-04-21 16:55
@WoLewicki as I thought, react-redux isnt the issue. The tabs get resetted on android while they work perfectly fine on iOS

**Comment by WoLewicki** [comment] 2020-04-22 06:50
Hmm ok, so can you provide a repo/snack with minimal code needed to spot the issue? I cannot work on the code you provided higher since it's too big and has too many dependencies.

**Comment by Hirbod** [comment] 2020-04-22 08:27
@WoLewicki I've finally found out the reason. It ONLY happens on 

`import { createMaterialBottomTabNavigator } from "@react-navigation/material-bottom-tabs";`
and not on 
`import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";`

Now I have to find out why and prob. report this to react-navigation.

**Comment by WoLewicki** [comment] 2020-04-22 08:32
Can you check if the problem exists with `stack`, not `native-stack` navigator?

**Comment by Hirbod** [comment] 2020-04-22 08:35
@WoLewicki good catch. createMaterialBottomTabNavigator with STACK works perfect (no resets on android), but breaks with native-stack.

**Comment by WoLewicki** [comment] 2020-04-22 08:38
It may be the same issue as the one fixed in #471. Could you try and check if applying this change fixes the issue?

**Comment by Hirbod** [comment] 2020-04-22 13:11
My specific app is on Expo RN, I can't test your fix currently :/

**Comment by Hirbod** [comment] 2020-04-22 15:03
But since you've already tested this and have an test-example you might want to run it against?

**Comment by WoLewicki** [comment] 2020-04-22 15:23
```js
import * as React from 'react';
import {View, Button} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createMaterialBottomTabNavigator} from '@react-navigation/material-bottom-tabs';
import {enableScreens} from 'react-native-screens';
import {createNativeStackNavigator} from 'react-native-screens/native-stack';

enableScreens();
function HomeScreen({navigation, route}) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Button title="Edit" onPress={() => navigation.navigate('Edit')} />
    </View>
  );
}

function EditScreen({navigation, route}) {
  return (
    <Button
      title="+1"
      onPress={() => {
        navigation.navigate('Home');
      }}
    />
  );
}

const Tab = createMaterialBottomTabNavigator();

function HomeStack() {
  const Stack = createNativeStackNavigator();
  return (
    <Stack.Navigator>
      <Stack.Screen name="Home" component={HomeScreen} />
      <Stack.Screen name="Edit" component={EditScreen} />
    </Stack.Navigator>
  );
}

function EditStack() {
  const Stack1 = createNativeStackNavigator();
  return (
    <Stack1.Navigator>
      <Stack1.Screen name="Home" component={HomeScreen} />
      <Stack1.Screen name="Edit" component={EditScreen} />
    </Stack1.Navigator>
  );
}

export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="HomeStack" component={HomeStack} />
        <Tab.Screen name="Edit" component={EditStack} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}

```

This works ok with the latest changes. Can you confirm that the issue exists with your configuration and such setup?

**Comment by Hirbod** [comment] 2020-04-22 15:26
As I told you, I am on Expo SDK 37 (react-native-screens v.2.2.0) - so I can't confirm if your fix works on my setup. I need to eject, grab the update and confirm it.

Asking the other way around: does the bug occur also for you with 2.2.0 and material bar + native-stack and is it fixed with you with the master?

**Comment by WoLewicki** [comment] 2020-04-22 15:35
Ok I managed to recreate the issue. Will work on it.

**Comment by Hirbod** [comment] 2020-04-22 22:17
Awesome! Thank you

**Comment by Hirbod** [comment] 2020-04-24 11:10
@WoLewicki following the official specs at https://material.io/components/bottom-navigation#behavior, this looks like it is intended. 

If so (which I am not sure about), it might have to be configurable. I still think that this "intention" is caused by a bug as it only happens on the native-stack with material-bottom-tabs. 

Just posted this as an informative article.

**Comment by WoLewicki** [comment] 2020-04-24 13:47
It is a bug caused by tabs of material-bottom-tabs not being `Screen` components since react-native-screens is not used in that package. It causes `ScreenStack` of each native-stack navigator to have the same FragmentManager, which pops one Screen at each change of the tab in https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStack.java#L34. I am trying to fix it now. The workaround, for now, is to set `gestureEnabled` to `false` on Android on each native-stack.

**Comment by Hirbod** [comment] 2020-04-24 16:20
Oh I didn’t know about that. But I think none of the tabs are using Screen, right? Actually a loss of performance :-

**Comment by Hirbod** [comment] 2020-04-24 18:19
Your suggested workaround works, which is pretty weird, since android don' have any gestures support anyway :D (at least they removed it on navigation v5 and native-stack never supported it for me on android anyway)

<img width="529" alt="Bildschirmfoto 2020-04-24 um 20 16 29" src="https://user-images.githubusercontent.com/504909/80244051-9a335e80-8668-11ea-93cc-7a2cad9700f1.png">

So I've added 
```
        gestureEnabled: Platform.OS === "android" ? false : true,
```
which fixed it for me and is sufficient enough. Thanks for your help here!

**Comment by enheit** [comment] 2020-05-05 17:35
I have updated to the latest version of the expo (Expo SDK 37) and issue disappeared on Android (v10)

**Closed** 2020-05-12 11:54 UTC
Labels: Android, bug, native-stack

**Comment by kamote** [comment] 2020-09-28 17:23
The issue started to appear on Expo SDK 38, the issue also exists in expo SDK39. Only happens on Android. Disabling `enableScreens` for now

**Comment by WoLewicki** [comment] 2020-09-29 11:49
@kamote could you please provide a snack/repo that shows the bug?

**Comment by kamote** [comment] 2020-10-22 17:17
@WoLewicki here's the repo https://github.com/kamote/navigation-v5-screens-bug/blob/master/App.js#L124-L129
The issue kind of weird on my side and the issue only happening on expo standalone android and when `enableScreens`

I got it working by removing the `View` wrapper of style of `flex:1`
so from 
```
<View 
      style={{
        flex: 1,
        backgroundColor: 'yellow'
      }}
    >
      <PaperProvider theme={theme}>
        {Platform.OS === 'ios' && (
          <StatusBar barStyle={theme.dark ? 'light-content' : 'dark-content'} />
        )}
        <NavigationContainer>
          <MainApp></MainApp>
        </NavigationContainer>
      </PaperProvider>
    </View>
```
to
```
<PaperProvider theme={theme}>
  {Platform.OS === 'ios' && (
    <StatusBar barStyle={theme.dark ? 'light-content' : 'dark-content'} />
  )}
  <NavigationContainer>
    <MainApp></MainApp>
  </NavigationContainer>
</PaperProvider>
```

**Comment by WoLewicki** [comment] 2020-10-28 15:15
I opened your repo but I don't know how to check that resetting behavior? What are the steps to reproduce the issue and what is the issue exactly?
