### ISSUE TITLE
NSInvalidArgumentException: Application tried to present modally an active controller <RNSScreen: 0x105075810>

### ISSUE THREAD

**Issue by nomi9995** [software-mansion/react-native-screens#1284] opened 2022-01-26 07:57 UTC
## Description
I don't know, how to reproduce, but I am getting this issue on the sentry log
here are the logs, which I am getting on sentry
```
NSInvalidArgumentException: Application tried to present modally an active controller <RNSScreen: 0x105075810>.
  CoreFoundation      0x203b1a98c  __exceptionPreprocess
  libobjc.A           0x202cf39f4  objc_exception_throw
  UIKitCore           0x22fed1ec4  -[UIViewController _presentViewController:withAnimationController:completion:]
  UIKitCore           0x22fed44ac  __63-[UIViewController _presentViewController:animated:completion:]_block_invoke_2
  UIKitCore           0x2308f38ec  +[UIView(Animation) performWithoutAnimation:]
  UIKitCore           0x22fed440c  __63-[UIViewController _presentViewController:animated:completion:]_block_invoke
  UIKitCore           0x22fed48a0  -[UIViewController _performCoordinatedPresentOrDismiss:animated:]
  UIKitCore           0x22fed42fc  -[UIViewController _presentViewController:animated:completion:]
  UIKitCore           0x22fed455c  -[UIViewController presentViewController:animated:completion:]
  OnShobbak           0x10121e2b0  facebook::react::JSIExecutor::defaultTimeoutInvoker
  OnShobbak           0x10121d65c  facebook::react::JSIExecutor::defaultTimeoutInvoker
  OnShobbak           0x10121d280  facebook::react::JSIExecutor::defaultTimeoutInvoker
  UIKitCore           0x2308f875c  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x23088735c  -[UIScrollView _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308f83b0  -[UIView(Internal) _didMoveFromWindow:toWindow:]
  UIKitCore           0x2308ebdc0  __45-[UIView _postMovedFromSuperview:]_block_invoke
  UIKitCore           0x2308ebc88  -[UIView(Hierarchy) _postMovedFromSuperview:]
  UIKitCore           0x2308fb0f4  -[UIView(Internal) _addSubview:positioned:relativeTo:]
  UIKitCore           0x22fee7228  __67-[UIViewControllerBuiltinTransitionViewAnimator animateTransition:]_block_invoke_2
  UIKitCore           0x2308f38ec  +[UIView(Animation) performWithoutAnimation:]
  UIKitCore           0x22fee71a8  __67-[UIViewControllerBuiltinTransitionViewAnimator animateTransition:]_block_invoke
  UIKitCore           0x2308f5258  +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:]
  UIKitCore           0x2308f5798  +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:]
  UIKitCore           0x22fee685c  -[UIViewControllerBuiltinTransitionViewAnimator animateTransition:]
  UIKitCore           0x22fdf0704  __56-[UIPresentationController runTransitionForCurrentState]_block_invoke
  UIKitCore           0x2304750a8  _runAfterCACommitDeferredBlocks
  UIKitCore           0x230463bf8  _cleanUpAfterCAFlushAndRunDeferredBlocks
  UIKitCore           0x230490a68  _afterCACommitHandler
  CoreFoundation      0x203aabd04  __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
  CoreFoundation      0x203aa6a2c  __CFRunLoopDoObservers
  CoreFoundation      0x203aa6fa8  __CFRunLoopRun
  CoreFoundation      0x203aa67bc  CFRunLoopRunSpecific
  GraphicsServices    0x205ca7798  GSEventRunModal
  UIKitCore           0x230469c34  UIApplicationMain
  OnShobbak           0x100fb1f74  <redacted>
  libdyld             0x20356a8dc  start
```

### Screenshots
![image](https://user-images.githubusercontent.com/36044436/151124099-3eaa577c-61b0-4039-928a-52f5f684d8d2.png)

## Steps To Reproduce

dont know

### Expected behavior

this error should not be occur

### Actual behavior
n/a

## Reproduction
n/a

## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |    0.66.4     |
| @react-navigation/native               |     6.0.6    |
| @react-navigation/native-stack         |    6.2.5     |
| react-native-screens                   |    3.10.1     |
| react-native-safe-area-context         |    3.3.2     |
| react-native-gesture-handler           |    2.1.0     |
| react-native-reanimated                |    2.3.1     |
| expo                                   |   n/a      |

**Comment by WoLewicki** [comment] 2022-01-27 11:11
I am afraid we cannot help much without a reproduction. From the log, it seems like you try to present an already active screen as a modal, aren't you changing the `stackPresentation` from `push` to some other on an already active screen?

**Comment by nomi9995** [comment] 2022-01-27 11:35
@WoLewicki I think, I am not changing the `stackPresentation` from `push` to some other on an already active screen. i will investigate. thanks for you response.

**Comment by maximewim** [comment] 2022-03-02 10:22
I think I have the same problem. I managed to replicate what happens to my users.
I'm using react-navigation 6 with the native stack.
For me, the error occurs when I get a notification (background or foreground).
When I get a notification, I replace the current navigation stack to navigate to a specific screen. If I was on a normal screen, everything works fine. But if a fullscreen modal was opened, the app will crash with the error below.

Did you manage to solve this problem, or do you have a temporary solution? Thanks

**Comment by WoLewicki** [comment] 2022-03-02 11:44
@maximewim can you provide a simple reproduction of this issue with some mocked screens so we can debug it ?

**Comment by maximewim** [comment] 2022-03-02 13:10
I'll try later to provide a reproduction. Just to help, I solve the problem using 'navigate' instead of 'replace'. 
So seems link to replace directly.

**Comment by WoLewicki** [comment] 2022-04-26 11:28
I will close this issue due to no reproduction provided in 30 days. If you manage to make one, please comment here and we will reopen the issue then.

**Closed by WoLewicki** 2022-04-26 11:28 UTC
Labels: needs-more-info, 🍎iOS, 🧰needs-repro

**Comment by mazenchami** [comment] 2022-07-05 20:32
@nomi9995 were you able to solve this issue?
