### ISSUE TITLE
Missing header bottom border on physical devices

### ISSUE THREAD

**Issue by Jobeso** [software-mansion/react-native-screens#766] opened 2021-01-05 11:33 UTC
## Description
When using react-native-stacks with react-navigation v4 the bottom border of the header is not visible on larger iOS devices like an iPhone Xs & Xr. The border is visible on Simulators and is also visible as a component in the hierarchy view on the physical devices but not visible.

### Screenshots
<details>
  <summary>Device & simulator screenshots</summary>
  
  iPhone Xs physical, iPhone Xs simulator, iPhone 8 simulator
  
  <img src="https://user-images.githubusercontent.com/22718514/103640024-96720e80-4f4f-11eb-9232-795b93490f97.PNG" width="200" height="433" /> <img src="https://user-images.githubusercontent.com/22718514/103640040-9d008600-4f4f-11eb-9235-1c2602a9d6b3.png" width="200" height="433" /> <img src="https://user-images.githubusercontent.com/22718514/103640044-9f62e000-4f4f-11eb-94dc-46c3a59e8eec.png" width="200" height="355" /> 
</details>

<details>
  <summary>Hierarchy view</summary>
  
  ![Screenshot 2021-01-05 at 12 31 04](https://user-images.githubusercontent.com/22718514/103641343-e651d500-4f51-11eb-9f8d-7a06bce670d1.png)
</details>

## Steps To Reproduce

1. Setup react-navigation & react-native-screens
2. Build to physical device like iPhone Xs or iPhone Xr

### Expected behaviour
See header bottom border on all devices.

## Snack or minimal code example
See example repo [here](https://github.com/Jobeso/RNScreensIssue).

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Screens: 2.16.1
- react-navigation: 4.4.3

**Comment by jkadamczyk** [comment] 2021-01-18 15:33
Thanks for the issue and a repro I will try to check it on my device and see what we can do with it 😄

**Comment by jkadamczyk** [comment] 2021-01-18 15:45
So I can confirm that I see the issue and have the same in the view hierarchy. I spoke to @WoLewicki and he thinks it might be a bug in UIKit itself, but we will double check

**Comment by jkadamczyk** [comment] 2021-01-19 09:06
Hi @Jobeso! I found where your problem lies and it is not related to React Native Screens, it's rather an iOS **feature**.

Why a feature though?
So you have a React Native app on iOS with dark mode enabled. Native stack uses native components which follow system-wide appearance setting. Because your app tries to adapt, it has a dark status bar by default. What you were trying to do is to style the navigation bar to have light colors by yourself. Unfortunately, this is not the correct way to do it. If your app does not support dark mode, you can disable it by setting `Appearance` in `Info.plist` in Xcode to `Light`
![image](https://user-images.githubusercontent.com/16062886/105011818-b4ef0400-5a3d-11eb-8f51-6d7717f45270.png)
Having that enabled it works on my iPhone 11 which is almost the same as XR.
![IMG_17E6189FEFCF-1](https://user-images.githubusercontent.com/16062886/105011955-e49e0c00-5a3d-11eb-8242-68884aed2c38.jpeg)
Because of above I'm closing the issue and hope my answer helps you. Have a good day!

**Closed by jkadamczyk** 2021-01-19 09:06 UTC
