### ISSUE TITLE
Type mismatch: inferred type is Canvas? but Canvas was expected

### ISSUE THREAD

**Issue by abdullahIsa** [software-mansion/react-native-screens#1799] opened 2023-06-22 01:10 UTC
### Description

Hello, i updated  my compileSdkVersion to 34 and this issue started happening, i think its related to this https://github.com/software-mansion/react-native-screens/pull/1795

```
> Task :react-native-screens:compileDebugKotlin                                                                                                                                                              
e: C:\Users\Abdullah\Desktop\Programming\company\Chappie\Chappie\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStack.kt: (300, 25): Type mismatch: inferred type is Canvas? but Canvas was expected

> Task :react-native-screens:compileDebugKotlin FAILED
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------                                                                                                                                                                                                  
* What went wrong:
Execution failed for task ':react-native-screens:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 29s
697 actionable tasks: 692 executed, 5 up-to-date
```

### Steps to reproduce

use latest version and try to build ./gradlew build

### Snack or a link to a repository

https://stackoverflow.com/help/mcve

### Screens version

3.21.1

### React Native version

0.70.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Oppo A9 2020

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2023-06-22 07:35
Hey, thanks for reporting. I'm closing this issue, because it is a duplicate of: https://github.com/software-mansion/react-native-screens/issues/1787.

Please see [this answer](https://github.com/software-mansion/react-native-screens/issues/1787#issuecomment-1602152276).
I'll try to make a release soon so that this fix can be downloaded from npm.

**Closed by kkafar** 2023-06-22 07:35 UTC
Labels: Platform: Android, MIssing repro
