### ISSUE TITLE
StatusBar animation like native

### ISSUE THREAD

**Issue by ferrannp** [software-mansion/react-native-screens#781] opened 2021-01-21 14:11 UTC
## Description

Not sure if this is a bug or not but I noticed some difference between a native app and with native stack. See the gifs:

### Screenshots

Native app from Apple (see how StatusBar animates immediately when background behind it changes):

![contacts](https://user-images.githubusercontent.com/774577/105362099-c16c8b80-5bfa-11eb-999b-5adf2c633ad9.gif)

Here is using native stack and `statusBarStyle: 'light'`. Notice that it does not change like native. Only when modal is fully closed and it takes quite a while to do so:

![status-bar-native-stack](https://user-images.githubusercontent.com/774577/105362166-d6491f00-5bfa-11eb-8b19-a3e562d9e026.gif)

### Expected behavior

Try to achieve native behavior.

### Actual behavior

Not exactly as native.

## Snack or minimal code example

Here can be tested: https://github.com/ferrannp/native-stack-playground/

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Screens: 2.16.1

**Comment by WoLewicki** [comment] 2021-02-04 12:35
Closing due to being duplicate of #767. Should be fixed by #798.

**Closed by WoLewicki** 2021-02-04 12:35 UTC
