### ISSUE TITLE
Conditional rendering of screens doesnt update rendered page

### ISSUE THREAD

**Issue by andredewaard** [software-mansion/react-native-screens#690] opened 2020-11-02 15:07 UTC
Conditional rendering screens based on authentication doesnt update screen when condition becomes false.

Implemented conditional rendering like this example: https://reactnavigation.org/docs/auth-flow/#define-our-screens
When loggin in it works great and i automatically shows the Home page, but on logout it stays on the same page and freezes the screen. 

This works when i use the normal https://reactnavigation.org/docs/stack-navigator/
```javascript
import {useAuthState}               from '../context/auth';
import {enableScreens}              from 'react-native-screens';
import {createNativeStackNavigator} from 'react-native-screens/native-stack';

import {AuthRoutes}     from './AuthRoutes';
import {PlatformRoutes} from './PlatformRoutes';

enableScreens();
const Stack = createNativeStackNavigator();

const Routes = () => {
  const {isAuthenticated} = useAuthState();

  return loading ? (
    <SplashScreen/>
  ) : (
    <Stack.Navigator
      screenOptions={{headerShown: false}}
      options={{animationEnabled: true}}>
      {!isAuthenticated ? (
        <Stack.Screen name="Authentication" component={AuthRoutes}/>
      ) : (
        <Stack.Screen name="Platform" component={PlatformRoutes}/>
      )}
    </Stack.Navigator>
  );
};
```

**Comment by WoLewicki** [comment] 2020-11-03 09:02
Can you provide a repo/snack with minimal configuration needed to reproduce the issue? I changed the `stack` to `native-stack` navigator in the https://reactnavigation.org/docs/auth-flow/#implement-the-logic-for-restoring-the-token, where the conditional rendering is used, and it works the same. Also, which platform does the bug appear on?

**Comment by WoLewicki** [comment] 2020-12-11 12:05
Closing due to no reproduction provided in 30 days. Feel free to comment to reopen.

**Closed by WoLewicki** 2020-12-11 12:05 UTC
Labels: needs more info, needs repro

**Comment by karlmarxlopez** [comment] 2022-10-29 07:14
@WoLewicki please reopen this, it's still happening

# How to replicate
OP's code snippet is enough, or follow the official auth flow docs.
https://reactnavigation.org/docs/auth-flow/

# New arch enabled?
Yes

# React native info
```json
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.3",
    "react-native-screens": "^3.18.2",
```

```
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 83.02 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /var/folders/xd/h0fnv84s2vd9sfn4m8ghvmx40000gn/T/yarn--1667027442097-0.8099531023958277/node
    Yarn: 1.22.19 - /var/folders/xd/h0fnv84s2vd9sfn4m8ghvmx40000gn/T/yarn--1667027442097-0.8099531023958277/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 26, 30, 31, 32
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-32 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
 ```

**Comment by karlmarxlopez** [comment] 2022-10-29 07:16
It's showing a blank screen.

https://user-images.githubusercontent.com/7194216/198819079-ec03ab73-5ad2-475d-b29f-32d5f10d3629.mp4

**Comment by WoLewicki** [comment] 2022-11-02 14:43
@karlmarxlopez so you are using new architecture? If so, could you submit another issue with a simple reproduction in a form of a repo attached?

**Comment by karlmarxlopez** [comment] 2022-11-02 15:01
@WoLewicki , sure! I'll tag you on the new issue.
