### ISSUE TITLE
Does not play well with Expo Camera

### ISSUE THREAD

**Issue by slorber** [software-mansion/react-native-screens#46] opened 2018-12-10 18:32 UTC
I'm using the Camera module from Expo SDK31 with react-navigation v3.x

I have a navigation screen that opens on top of the camera view screen (stacknav). When going back to the camera screen, the camera view does not work anymore and is black.

Not sure what is happening exactly, but it looks like the camera view does not reinitialize properly when the screen gets focused again. I don't know if this is an Expo problem or this lib.

These workaround works:
- Remove `useScreens()` call
- Unmount the camera view when the screen is unfocused and remount on focus (using [withNavigationFocus](https://reactnavigation.org/docs/en/with-navigation-focus.html)

**Comment by kmagiera** [comment] 2018-12-20 13:03
Is this android or iOS?

**Comment by slorber** [comment] 2018-12-20 14:07
This is on Android, didn't test on iOS

**Comment by kmagiera** [comment] 2019-01-10 12:08
Would be great if you could prepare a sample app or expo snack that I could juts run to reproduce the problem. That would save me quite a bit of time

**Comment by compojoom** [comment] 2019-01-16 14:56
@kmagiera - I just spent an hour creating a demo of the issue, but the problem is that with a simple app I can no longer reproduce that issue... 

In the app where the issue happens we have 2 separate navigators - maybe it's related to that. I'll have to debug further to figure out what's going on.

**Comment by sibelius** [comment] 2019-03-12 20:43
it is working fine with https://github.com/react-native-community/react-native-camera

**Comment by WoLewicki** [comment] 2020-05-29 11:23
Does this issue still exist or can I close it?

**Comment by slorber** [comment] 2020-05-29 13:23
I don't know sorry ;) we can close it and if I see it again I may reopen

**Closed** 2020-06-01 07:01 UTC
Labels: needs repro
