### ISSUE TITLE
popToTop in nested StackNavigator of react-navigation BottomTabNavigator blocks main UI thread causing jank

### ISSUE THREAD

**Issue by bonesyblue** [software-mansion/react-native-screens#78] opened 2019-03-05 15:33 UTC
## Current Behaviour
UI thread is blocked after double tapping on a BottomTabNavigator icon (calling popToTop of the nested StackNavigator) when reseting the nested StackNavigator state.

[![iOS with screens](https://img.youtube.com/vi/0EihSu5pwtQ/hqdefault.jpg)](https://youtu.be/0EihSu5pwtQ?t=48) 

Reproducible project: [https://github.com/bonesyblue/tab-stack-rn-screens](https://github.com/bonesyblue/tab-stack-rn-screens)

## Expected Behaviour
popToTop of nested stack navigator (within a BottomTabNavigator) should not block the UI thread or cause visible UI lag / jank.

## Environment
package | version
-- | --
react | 16.6.3
react-native | 0.58.6
react-navigation | 3.3.2
react-native-screens | 1.0.0-alpha.22

Any help or feedback on this issue would be greatly appreciated 👍

**Comment by brentvatne** [comment] 2019-03-08 19:36
confirmed this does occur. @kmagiera is away at the moment, when he's back and has some time i'm sure he will investigate

**Comment by WoLewicki** [comment] 2020-04-02 11:29
Does the issue still exists or can I close it @bonesyblue @brentvatne ?

**Comment by brentvatne** [comment] 2020-04-17 16:57
probably not but i'm not familiar with the current state of it. would be necessary to clone the repo provided in the original post and update screens to latest

**Comment by WoLewicki** [comment] 2020-04-20 17:40
I opened the project with updated packages and it looks like the issue is not there. I am closing it then. Feel free to comment if I am wrong.

**Closed by WoLewicki** 2020-04-20 17:40 UTC
