### ISSUE TITLE
Recording currently in progress - missing #endRecording() call

### ISSUE THREAD

**Issue by invyctus92** [software-mansion/react-native-screens#1287] opened 2022-01-26 13:22 UTC
Recording currently in progress - missing #endRecording() call

## Description

App crashes during navigation in Android

## Steps To Reproduce

1. in the home in my app with a tab menu and a drawer
2. I open a page continuing in the stack of the first element of the tab
3. I open another consecutive page in the stack
4. when I quickly go back, pressing the back button twice, the app crashes

## Screenshots 

https://user-images.githubusercontent.com/13299821/151399958-752819ed-9233-4074-97e3-90073876954b.mp4

## Platform

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Log

java.lang.IllegalStateException: Recording currently in progress - missing #endRecording() call?
        at android.graphics.RenderNode.beginRecording(RenderNode.java:372)
        at android.view.View.updateDisplayListIfDirty(View.java:21199)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.swmansion.rnscreens.ScreenStack.performDraw(ScreenStack.kt:322)
        at com.swmansion.rnscreens.ScreenStack.access$performDraw(ScreenStack.kt:15)
        at com.swmansion.rnscreens.ScreenStack$DrawingOp.draw(ScreenStack.kt:343)
        at com.swmansion.rnscreens.ScreenStack.drawAndRelease(ScreenStack.kt:296)
        at com.swmansion.rnscreens.ScreenStack.dispatchDraw(ScreenStack.kt:313)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22353)
        at android.view.View.draw(View.java:22223)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22353)
        at android.view.View.draw(View.java:22223)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22353)
        at android.view.View.draw(View.java:22223)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.swmansion.rnscreens.ScreenStack.performDraw(ScreenStack.kt:322)
        at com.swmansion.rnscreens.ScreenStack.access$performDraw(ScreenStack.kt:15)
        at com.swmansion.rnscreens.ScreenStack$DrawingOp.draw(ScreenStack.kt:343)
        at com.swmansion.rnscreens.ScreenStack.drawAndRelease(ScreenStack.kt:296)
        at com.swmansion.rnscreens.ScreenStack.dispatchDraw(ScreenStack.kt:313)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:225)
        at android.view.View.draw(View.java:22221)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22353)
        at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:122)
        at eightbitlab.com.blurview.BlockingBlurController.draw(BlockingBlurController.java:164)
        at eightbitlab.com.blurview.BlurView.draw(BlurView.java:51)
        at android.view.View.updateDisplayListIfDirty(View.java:21226)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22353)
        at android.view.View.updateDisplayListIfDirty(View.java:21226)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22353)
        at android.view.View.updateDisplayListIfDirty(View.java:21226)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.swmansion.rnscreens.ScreenStack.performDraw(ScreenStack.kt:322)
        at com.swmansion.rnscreens.ScreenStack.access$performDraw(ScreenStack.kt:15)
        at com.swmansion.rnscreens.ScreenStack$DrawingOp.draw(ScreenStack.kt:343)
        at com.swmansion.rnscreens.ScreenStack.drawAndRelease(ScreenStack.kt:296)
        at com.swmansion.rnscreens.ScreenStack.dispatchDraw(ScreenStack.kt:313)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22353)
        at android.view.View.updateDisplayListIfDirty(View.java:21226)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
        at android.view.View.updateDisplayListIfDirty(View.java:21186)

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
 "react-native": "0.67.1",
"@react-navigation/bottom-tabs": "^6.0.9",
"@react-navigation/compat": "^5.3.20",
"@react-navigation/drawer": "^6.1.8",
"@react-navigation/native": "^6.0.6",
"@react-navigation/native-stack": "^6.2.5",
"@react-navigation/stack": "^6.0.11",
"react-native-gesture-handler": "2.2.0",
"react-native-screens": "^3.10.2",
"react-native-reanimated": "^2.3.1",
"react-native-safe-area-context": "^3.3.2",

**Comment by invyctus92** [comment] 2022-01-31 09:57
I found the reason why it happens, on the main page I have a blur effect on, and when I go back to this page which is the main page, the app crashes. 

`
import { BlurView, VibrancyView } from "@react-native-community/blur"; 
`
`
<BlurView
          style={styles.absolute}
          blurType="light"
          viewRef={this.props.viewRef}
          blurAmount={1}
        />`

**Comment by WoLewicki** [comment] 2022-02-16 11:02
Unfortunately, we cannot say much about this without a reproduction such as a snack or a simple repo.

**Comment by mjm918** [comment] 2022-03-13 01:39
This issue happens due to React Native Blur. Repo issue can be found here:
https://github.com/Kureev/react-native-blur/issues/452

Most of the react-navigation 6 users are facing this issue. The crash log is same for everyone.

For me, the App will crash on android if it has blur view. I tried to mount the blur view after a delay but the crash still happens.

Example 1: In the navigator. Works fine on iOS but crashes on Android
```
<BottomTab.Navigator
screenOptions={{
	unmountOnBlur:true,
	tabBarStyle: { position: "absolute" },
	tabBarBackground: () => (
		// eslint-disable-next-line @typescript-eslint/ban-ts-comment
		// @ts-ignore
		<BlurView blurType={blurType} blurAmount={100} style={StyleSheet.absoluteFill} />
	)
}}
```

Example 2: In Main screen, the app crashes also

```
<ImageBackground
    source={C.ASSETS.DashboardScreen.menu}
    imageStyle={styles.menuImage}
    style={styles.menuImageContainer}>
    <BlurView style={styles.menuBlurView} blurType={theme_type} blurAmount={5}>
	    <RippleIconButton onPress={()=>Haptic(this.goProducts.bind(this))} rippleContainerBorderRadius={40} name={"cards"}>
		    PRODUCTS
	    </RippleIconButton>
	    <RippleIconButton onPress={()=>Haptic(this.onPressSearch.bind(this))} rippleContainerBorderRadius={40} name={"shopping-search"}>
		    SEARCH
	    </RippleIconButton>
	    <RippleIconButton rippleContainerBorderRadius={40} name={"vector-polyline-edit"}>
		    STATEMENTS
	    </RippleIconButton>
    </BlurView>
</ImageBackground>
```

I tried to remove the blur view from Navigator and used in the main screen only but the problem still persist

**Comment by WoLewicki** [comment] 2022-03-14 11:35
@mjm918 can you put the code in a form of a simple repo or a snack? We will be then able to easily reproduce the problem and collaborate.

**Comment by mjm918** [comment] 2022-03-22 08:39
Hi @WoLewicki  sorry for late, I was a bit occupied. I have created a repo here 

https://github.com/mjm918/RNScreensBlurViewCrash-Repro

Hope it will be helpful.

Thank you

**Comment by enlightenedpie** [comment] 2022-03-24 00:02
If you look at Kureev/react-native-blur Readme, there is a section:
`Android
Android uses the [BlurView](https://github.com/Dimezis/BlurView).

If you only need to support iOS, then you can safely ignore these limitations.

In addition to blurType and blurAmount, Android has some extra props that can be used to override the default behavior (or configure Android-specific behavior):

blurRadius (Number - between 0 and 25) - Manually adjust the blur radius. (Default: matches iOS blurAmount)
downsampleFactor (Number - between 0 and 25) - Scales down the image before blurring (Default: matches iOS blurAmount)
overlayColor (Color) - Set a custom overlay color (Default color based on iOS blurType)`

**Comment by mjm918** [comment] 2022-04-01 07:37
> @mjm918 can you put the code in a form of a simple repo or a snack? We will be then able to easily reproduce the problem and collaborate.

Hi @WoLewicki did you manage to check the issue?

**Comment by YunsGeek** [comment] 2022-04-10 16:22
same probleme , any solutions here..?

**Comment by mjm918** [comment] 2022-04-11 08:16
@YunsGeek no solution yet. stuck here for last 1 month. I'm using a transparent view on android instead of blurview. and my android app looks super ugly

**Comment by WoLewicki** [comment] 2022-04-13 10:55
I made a PR trying to solve this behavior with an explanation of what is happening under the hood: https://github.com/software-mansion/react-native-screens/pull/1406. Could you check if it resolves the issue and does not introduce any new ones?

**Comment by mjm918** [comment] 2022-04-14 03:24
Thank you so much @WoLewicki . I tried your commit just now. During the first launch, the app crashed with the following exception:


```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.esselforder, PID: 9890
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3765)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4287)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at com.swmansion.rnscreens.ScreenStack.performDraw(ScreenStack.kt:308)
        at com.swmansion.rnscreens.ScreenStack.access$performDraw(ScreenStack.kt:14)
        at com.swmansion.rnscreens.ScreenStack$DrawingOp.draw(ScreenStack.kt:329)
        at com.swmansion.rnscreens.ScreenStack.drawAndRelease(ScreenStack.kt:283)
        at com.swmansion.rnscreens.ScreenStack.dispatchDraw(ScreenStack.kt:299)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:226)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at android.view.View.draw(View.java:22960)
        at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:149)
        at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.java:61)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3421)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2211)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8938)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1211)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1219)
        at android.view.Choreographer.doCallbacks(Choreographer.java:892)
        at android.view.Choreographer.doFrame(Choreographer.java:825)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1194)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7850)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by mjm918** [comment] 2022-04-14 03:25
Thank you so much @WoLewicki . I tried your commit just now. During the first launch, the app crashed with the following exception:


```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxxxxxxxxx, PID: 9890
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3765)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4287)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at com.swmansion.rnscreens.ScreenStack.performDraw(ScreenStack.kt:308)
        at com.swmansion.rnscreens.ScreenStack.access$performDraw(ScreenStack.kt:14)
        at com.swmansion.rnscreens.ScreenStack$DrawingOp.draw(ScreenStack.kt:329)
        at com.swmansion.rnscreens.ScreenStack.drawAndRelease(ScreenStack.kt:283)
        at com.swmansion.rnscreens.ScreenStack.dispatchDraw(ScreenStack.kt:299)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:226)
        at android.view.View.draw(View.java:22828)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
        at android.view.View.draw(View.java:22960)
        at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:149)
        at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.java:61)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3421)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2211)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8938)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1211)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1219)
        at android.view.Choreographer.doCallbacks(Choreographer.java:892)
        at android.view.Choreographer.doFrame(Choreographer.java:825)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1194)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7850)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by WoLewicki** [comment] 2022-04-14 07:54
@mjm918 does this happen in the repo you provided? I couldn't spot such an issue there. Do you have an easy reproduction of this?

**Comment by WoLewicki** [comment] 2022-04-14 12:19
I was able to reproduce this issue with `android:hardwareAccelerated="false"` flag set in the project's manifest. At the same time, it crashes even without any code modifying the children drawing order in `ScreenStack`. Just above the crash, there is an information about `BlurView` needing the hardware acceleration. Are you sure it is present in your application. Could you double-check if this error does not appear in your logs too?
![image](https://user-images.githubusercontent.com/32481228/163388967-be4c7332-a9c1-45bf-9512-a52fa817352f.png)

**Comment by mjm918** [comment] 2022-04-14 13:12
Hi @WoLewicki thank you for your fast response. 

I think I found the root cause. The app will not crash if there is single blurview. I have updated the reproduction code here:

https://github.com/mjm918/RNScreensBlurViewCrash-Repro
Commit ID: 226a0a86e631cc0844f6fdd97df14c141aabb3d1
<img width="460" alt="Screenshot 2022-04-14 at 9 10 36 PM" src="https://user-images.githubusercontent.com/17846525/163397616-872b9bcf-e564-4173-8aae-e53e523ab547.png">

In the Code, I tried to create blurview with Array map and the app crashed.

**Comment by yincrash** [comment] 2022-04-14 22:28
> I made a PR trying to solve this behavior with an explanation of what is happening under the hood: #1406. Could you check if it resolves the issue and does not introduce any new ones?

This PR fixed the crash for me. I did not attempt with multiple blurviews though.

**Comment by WoLewicki** [comment] 2022-04-19 10:20
Does this changed code work in the simple case though @mjm918 ? I mean if you added it here: https://github.com/mjm918/RNScreensBlurViewCrash-Repro/blob/226a0a86e631cc0844f6fdd97df14c141aabb3d1/App.tsx. Cause it does not work for me due to probably recursive calls for updating blur from the `BlurView`, or am I missing something? 
![image](https://user-images.githubusercontent.com/32481228/163983212-a71f592f-4884-42af-b769-901eea2cf717.png)

**Comment by mjm918** [comment] 2022-04-21 02:06
> Does this changed code work in the simple case though @mjm918 ? I mean if you added it here: https://github.com/mjm918/RNScreensBlurViewCrash-Repro/blob/226a0a86e631cc0844f6fdd97df14c141aabb3d1/App.tsx. Cause it does not work for me due to probably recursive calls for updating blur from the `BlurView`, or am I missing something? ![image](https://user-images.githubusercontent.com/32481228/163983212-a71f592f-4884-42af-b769-901eea2cf717.png)

Hi @WoLewicki in simple case like, 1 BlurView in 1 screen will work. But multiple blurview in a screen causes the crash

**Comment by WoLewicki** [comment] 2022-04-21 08:35
So, if there is a 1 BlurView, #1406 fixes the issue, and if there are multiple BlurViews, the app will crash anyway, doesn't matter if with `react-native-screens` or not. So I think we should merge #1406 and close this issue, since there is no more work to do on the side of the library. Or am I missing something?

**Comment by mjm918** [comment] 2022-04-24 03:47
> So, if there is a 1 BlurView, #1406 fixes the issue, and if there are multiple BlurViews, the app will crash anyway, doesn't matter if with `react-native-screens` or not. So I think we should merge #1406 and close this issue, since there is no more work to do on the side of the library. Or am I missing something?

Sorry for late reply. I haven't tried the blurview without react-native-screens. that's why i cant really agree with this statement "doesn't matter if with react-native-screens or not".

What I found in some [discussion](https://github.com/Kureev/react-native-blur/issues/452#issuecomment-1003717311) is that people started experiencing this crash after upgrading react-navigation to v6.

**Comment by WoLewicki** [comment] 2022-04-25 09:57
> What I found in some [discussion](https://github.com/Kureev/react-native-blur/issues/452#issuecomment-1003717311) is that people started experiencing this crash after upgrading react-navigation to v6.

I looks like an older issue: https://github.com/Kureev/react-native-blur/issues/368.

I think we cannot do anything more in our library than what #1406 does. I will merge it and close this issue then. Feel free to comment here if I am missing something and we can always reopen it.

**Closed** 2022-04-25 09:59 UTC
Labels: needs-more-info, 🤖android, repro-provided, needs-review

**Comment by LautaroNavarro** [comment] 2022-05-12 15:02
@WoLewicki can we have a new release with the fix?

**Comment by WoLewicki** [comment] 2022-06-01 13:21
@LautaroNavarro sorry for late reply. We are planning on releasing new version when we end the Fabric integration of `react-native-screens` which should happen soon, so stay tuned :tada:

**Comment by vladimirevstratov** [comment] 2022-07-06 12:29
thanks, after updating to react-native-screens problem has gone!

**Comment by fukemy** [comment] 2022-08-19 12:23
still got this crash

**Comment by fxricky** [comment] 2022-10-02 09:04
tried with:

"react-native-screens": "^3.17.0",
"@react-native-community/blur": "^4.2.0"

but the issue is still there.

My issue - Android crash when navigating to another screen that have `react-native-blur`.

**Comment by mobinni** [comment] 2025-01-18 18:15
I think I'm seeing the same issue 🤔 but on 4.5.0 and 0.76.6. @fxricky did you ever find a resolution
