### ISSUE TITLE
headerLeft / headerRight / headerCenter disappearing when Android hardware back button functionality is used

### ISSUE THREAD

**Issue by tomtargosz** [software-mansion/react-native-screens#817] opened 2021-02-16 19:47 UTC
## Description

We're currently seeing an issue where if a user uses the hardware back button to pop off a screen the `headerLeft` / `headerRight` / `headerCenter` properties of the screen are being unmounted while the screen is still visible.

### Screenshots
Here's a video of using the software back button to go back a screen (notice how the `headerCenter` component (the Help Center title) stays visible throughout the entire transition)
https://user-images.githubusercontent.com/7979579/108112834-44e39600-705c-11eb-95f9-dc046943a843.mp4

Here's a video of using the hardware back button to go back a screen (notice how the `headerCenter` component (the Help Center title) is removed as the transition begins)
https://user-images.githubusercontent.com/7979579/108112877-59c02980-705c-11eb-9632-2ee189768fdd.mp4

## Steps To Reproduce

1. Use the hardware back button to pop from a screen with  `headerLeft` / `headerRight` / `headerCenter` properties set on it

### Expected behavior
The properties remain visible during the duration of the animation

### Actual behavior
All properties disappear as the transition begins

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Screens: 2.17.1

**Comment by WoLewicki** [comment] 2021-02-17 16:47
I think it is duplicate of #773. I will close the issue then. If I am wrong, please comment here and I will reopen the issue.

**Comment by tomtargosz** [comment] 2021-02-17 17:00
@WoLewicki I don't believe it's a duplicate as we are not using `react-native-svg` within our project, the views that are disappearing are standard `<Text>` components. It seems like the conclusion of that thread was to fix an issue on the `react-native-svg` side which would not solve this issue.

**Comment by WoLewicki** [comment] 2021-02-17 17:10
Oh, I see, I'm sorry. The issue also points that the same happens in `react-native-fast-image` iirc. Can you provide a simple reproduction of the issue then?

**Comment by msvargas** [comment] 2021-02-17 19:49
@wkozyra95 @tomtargosz Hi, I fixed this issue in #773 this is because ScreenHeaderConfig not have override getChild, please check the example, the image in back button is an Image component and no an SVG: https://github.com/software-mansion/react-native-screens/issues/773#issuecomment-769418173

**Comment by tomtargosz** [comment] 2021-02-18 01:08
Hey @msvargas can you link to where the fix is? I see you posted this fix in the issue https://github.com/software-mansion/react-native-screens/issues/773#issuecomment-770043776 but that's a fix for `react-native-svg` whereas this is happening to be without that library.

**Comment by tomtargosz** [comment] 2021-02-18 01:56
@WoLewicki I created a repo with the issue here: https://github.com/tomtargosz/react-navigation-android-back-button

Here's a video of what's happening when pressing the back button on the page vs using the Android back button

https://user-images.githubusercontent.com/7979579/108292991-25329780-715a-11eb-82f9-63e98058582c.mp4

**Comment by WoLewicki** [comment] 2021-02-18 11:41
I tested the code you provided (there is no android folder there so I just copied the code into the `TestsExample` project in our repo), and applying patch from @msvargas (https://github.com/software-mansion/react-native-screens/issues/773#issuecomment-764686684) fixes the issue, as it makes the header subviews "subscribe" to transition of going back from the screen in `native-stack` (see https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStackViewManager.java#L39). Can you confirm these observations?

**Comment by tomtargosz** [comment] 2021-02-18 15:14
@WoLewicki confirmed that fixed the issue! Thank you so much to both you and @msvargas for the fast follow up on this! 😄

**Closed** 2021-02-25 10:41 UTC
