### ISSUE TITLE
White Screen Appearing Issue ,While Navigate from One Screen to Another Screen in Android

### ISSUE THREAD

**Issue by Akilramki** [software-mansion/react-native-screens#1724] opened 2023-02-24 06:05 UTC
### Description

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 294.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    Yarn: Not Found
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
    Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/ramki/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1
      System Images: android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.2 => 0.71.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. While Move from One screen (Create Account ) to another Screen (Login Otp)
      props.navigation.navigate('loginOtp', {
         register: true
      });
      
 2. Screen is not Showing the UI Design 
 3. Then Go to Background State and open the app , Screen is showing in Android
 
 
 Package.json
 
     "react": "18.2.0",
    "react-native": "0.71.2",
     "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
     "react-native-reanimated": "^2.9.1",
     "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.4.0",
    

### Snack or a link to a repository

No

### Screens version

^3.4.0

### React Native version

0.71.2

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Android emulator

### Device model

Vivo 1901  (Android 11)

### Acknowledgements

Yes

**Comment by kkafar** [comment] 2023-02-24 08:15
Hey, I believe this is a duplicate of #1685, please continue discussion there

**Closed by kkafar** 2023-02-24 08:15 UTC
Labels: Missing info, Platform: iOS, Platform: Android, MIssing repro, Platform: tvOS

**Comment by murilogok** [comment] 2023-02-24 20:08
> Hey, I believe this is a duplicate of #1685, please continue discussion there

+1 on iOS

**Comment by murilogok** [comment] 2023-02-24 20:09
+1 on iOS

```
    "react-native": "^0.71.3",
    "@react-navigation/bottom-tabs": "^6.5.6",
    "@react-navigation/native": "^6.1.5",
    "@react-navigation/native-stack": "^6.9.11",
    "react-native-screens": "3.19.0",
    "react-native-safe-area-context": "^4.5.0",
```
