### ISSUE TITLE
App crash on launch in Android - Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: could not find Fragment constructor

### ISSUE THREAD

**Issue by rinpatva14** [software-mansion/react-native-screens#421] opened 2020-03-16 04:17 UTC
Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: could not find Fragment constructor

Latest version - 2.3.0

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.brainbuddy.android/com.brainbuddy.android.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: could not find Fragment constructor

**Comment by itsjgf** [comment] 2020-03-19 06:23
Probably related to #408

**Comment by WoLewicki** [comment] 2020-03-26 13:52
I'm closing it then. If it is not duplicate, feel free to comment here to reopen.

**Closed by WoLewicki** 2020-03-26 13:52 UTC

**Comment by docnbs** [comment] 2020-08-07 14:57
Having the same issue. Sharing the details if it helps.

![image](https://user-images.githubusercontent.com/9844094/89658431-2c940100-d8ec-11ea-95c6-6ae1fd1cc847.png)
Details: Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.edfone/com.edfone.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

![image](https://user-images.githubusercontent.com/9844094/89658577-577e5500-d8ec-11ea-9231-0b9b2005224b.png)

Details:
Caused by androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:566)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
       at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
       at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:51)
       at com.edfone.MainActivity.onCreate(MainActivity.java:16)
       at android.app.Activity.performCreate(Activity.java:7088)
       at android.app.Activity.performCreate(Activity.java:7079)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
