### ISSUE TITLE
Bottom tabs and screen not touchable

### ISSUE THREAD

**Issue by faizanbutt** [software-mansion/react-native-screens#1663] opened 2022-12-10 17:17 UTC
### Description

I have a project that has stack and tab navigation in it. There is a strange problem it in which is: The tabs and screens are not touchable sometimes, although the screen is always scrollable is there is any ScrollView in that screen.

Note: The project was running fine for last 2 years but I recently(last month) migrated from mac intel to mac m1 chip using migration assistant. 
This problem started appearing from the last week.

### Steps to reproduce

The Structure. of the Project:
- The Screen MainScreen is imported and called in app.js
- MainScreen checks for the token and calls MainNavigation, which is another screen
- In MainNavigation I have 4 tabs like <Tab.Screen name="Dashboard" component={DashboardStack}/> 
- Used import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
- Then there are 4 other screens each one for one tab like: DashboardStack
- Used import {createStackNavigator} from '@react-navigation/stack';
- And inside DashboardStack file, I have all the files that will be for Dashboard

### Snack or a link to a repository

https://github.com/wwdrew/react-navigation-tabs-error

### Screens version

2.16.1

### React Native version

0.63.4

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Device model

Redmi Note 10 Pro, Google Pixel 3

### Acknowledgements

Yes

**Comment by oktorakevinarigi** [comment] 2022-12-16 15:41
I got the same problem, but i did a certain gesture on the screen, to activate the touchable. Any solution?

**Comment by faizanbutt** [comment] 2022-12-16 16:01
@oktorakevinarigi My problem resolved after updating libraries..

**Comment by oktorakevinarigi** [comment] 2022-12-16 16:11
I've got the latest update and am still experiencing it. I tried android 10 and 8 it doesn't happen. The problem was found on android 12. have you experienced it on android version 12 @faizanbutt

**Comment by faizanbutt** [comment] 2022-12-16 16:44
@oktorakevinarigi I only tested it on android 12 and it is working fine for me.
Will test on other versions as well.

**Comment by kokuren** [comment] 2022-12-30 16:15
@faizanbutt  What libraries you updated? I am having the same issues with android 12 and all my libraries are up to date.

**Comment by faizanbutt** [comment] 2023-01-05 11:21
@kokuren react-native-screens and @react-navigation libraries.

**Comment by alduzy** [comment] 2024-06-17 13:26
Hi there, I've just checked if the problem persists with screens 3.31.1 and I couldn't reproduce it, thus I am closing the issue. In case you encounter such problem with the latest version please report a new issue and include a working repro.

**Closed by alduzy** 2024-06-17 13:26 UTC
Labels: Platform: iOS, Platform: Android, Missing repro
