### ISSUE TITLE
headerLeft&headerRight goes off screen after orientation change

### ISSUE THREAD

**Issue by burakgormek** [software-mansion/react-native-screens#857] opened 2021-03-17 14:23 UTC
## Description
Custom headerLeft and headerRight components goes off screen after orientation change. Native controls doesn't seems to affected.

### Screenshots
![a5c76ae34fcc](https://user-images.githubusercontent.com/7578884/111477507-3ca47680-8740-11eb-86f2-50798429c5ed.gif)

## Steps To Reproduce

1. Copy Test831 example (https://raw.githubusercontent.com/software-mansion/react-native-screens/master/TestsExample/src/Test831.tsx)
2. Put dummy component in headerLeft or headerRight (ex: <View style={{backgroundColor: 'red', width: 20, height: 20}}></View>)
3. Remove "screenOptions={{direction: 'rtl'}}" to set default direction 'ltr'
(Note that it works correctly when have direction 'rtl' options but I don't want 'rtl' direction. I need ltr like default value)
4. Change device or simulator orientation

### Expected behavior
headerLeft&headerRight components needs to stay in the right position where headerLeft and headerRight needs to be after orientation change.

### Actual behavior
headerLeft&headerRight components goes off screen

## Snack or minimal code example
1. Copy Test831 example (https://raw.githubusercontent.com/software-mansion/react-native-screens/master/TestsExample/src/Test831.tsx)
2. Put component to headerLeft or headerRight.

## Package versions

- React: "17.0.1"
- React Native: "0.64.0"
- React Native Screens: "2.18.1"

**Comment by WoLewicki** [comment] 2021-03-18 09:54
I believe it is a duplicate of #528, so I will close it. You can check if https://github.com/software-mansion/react-native-screens/pull/668 resolves your issue, and if not, comment in #528 about it. Feel free to comment here if I am wrong and I'll reopen it then.

**Closed by WoLewicki** 2021-03-18 09:54 UTC
