### ISSUE TITLE
[native-stack] [iOS] BottomTabNavigator hide/show bug in Native Stack

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-screens#364] opened 2020-02-22 18:21 UTC
_Moved from [react-navigation/react-navigation#6772](https://github.com/react-navigation/react-navigation/issues/6772). Originally opened by @guvenakcoban_
___

### The problem

- When I tried to hide bottom tabs in native stack, tabs going out but the screen's height doesn't update. If I change orientation of device or pull the status bar, it's fixing. See the gif.
- This problem is only appear when using native stack navigator, there's no problem with createStackNavigator.

![ezgif com-resize](https://user-images.githubusercontent.com/30349984/70693950-8b5a9980-1ccf-11ea-9c09-a648b487c386.gif)

### Code

- Basic tab based navigation with native stack

```
import React from 'react';
import { View, Text, TouchableOpacity } from 'react-native';
import { NavigationNativeContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { useScreens } from 'react-native-screens';

useScreens();

const Home = props => {
  return (
    <View
      style={{
        flex: 1,
        backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'center',
      }}>
      <Text>Home Screen</Text>
      <TouchableOpacity onPress={() => props.navigation.navigate('Settings')}>
        <Text>GoToSettings</Text>
      </TouchableOpacity>
    </View>
  );
};

const Profile = props => {
  return (
    <View
      style={{
        flex: 1,
        backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'center',
      }}>
      <Text>Profile Screen</Text>
    </View>
  );
};

const Settings = props => {
  return (
    <View
      style={{
        flex: 1,
        backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'center',
      }}>
      <Text>Settings Screen</Text>
    </View>
  );
};

const Stack = createNativeStackNavigator();
const Tab = createBottomTabNavigator();

function HomeStackScreen() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="Home" component={Home} />
      <Stack.Screen name="Settings" component={Settings} />
    </Stack.Navigator>
  );
}

const App = () => {
  return (
    <NavigationNativeContainer>
      <Tab.Navigator
        screenOptions={({ route }) => {
          const routeName = route.state
            ? route.state.routes[route.state.index].name
            : 'Home';

          return { tabBarVisible: routeName === 'Home' };
        }}
        tabBarOptions={{ inactiveBackgroundColor: 'green' }}>
        <Tab.Screen name="Home" component={HomeStackScreen} />
        <Tab.Screen name="Profile" component={Profile} />
      </Tab.Navigator>
    </NavigationNativeContainer>
  );
};

export default App;

```

### Your Environment

| software         | version
| ---------------- | -------
| @react-navigation/core | ^5.0.0-alpha.27
| @react-navigation/native | ^5.0.0-alpha.18
| @react-navigation/native-stack | ^5.0.0-alpha.16
| react-native-screens | ^2.0.0-alpha.18
| @react-navigation/bottom-tabs | ^5.0.0-alpha.25

**Comment by guvenakcoban** [comment] 2020-02-26 11:01
tested with `"react-native-screens": "^2.0.0-beta.13"` still same.

**Comment by guvenakcoban** [comment] 2020-02-26 11:03
tested with "react-native-screens": "^2.0.0-beta.13" still same.

**Comment by kmagiera** [comment] 2020-02-27 00:22
one thing you can do as a workaround is to place stack above tabs in the hierarchy.

**Comment by kmagiera** [comment] 2020-02-27 08:41
One benefit of the approach of structuring the navigation the other way around (tabs inside stack) is that when you push, the tabs will animate away along the previous screen.

**Comment by Hirbod** [comment] 2020-03-01 15:01
I can confirm this issue, will try the suggestion

**Comment by Gavin97Dmello** [comment] 2020-06-01 06:51
> One benefit of the approach of structuring the navigation the other way around (tabs inside stack) is that when you push, the tabs will animate away along the previous screen.

It didnt work. Any other alternate solution?

**Comment by WoLewicki** [comment] 2020-06-01 09:09
@Gavin97Dmello what do you mean by didn't work? That you can't structurize your project to follow it?

**Comment by WoLewicki** [comment] 2020-07-03 14:51
It is now officially recommended not to use `tabBarVisible` prop, but rather refactor the navigation structure: https://reactnavigation.org/docs/hiding-tabbar-in-screens/
I am closing this issue then, feel free to comment if you have any questions.

**Closed by WoLewicki** 2020-07-03 14:51 UTC
Labels: native-stack

**Comment by watadarkstar** [comment] 2020-07-29 21:40
This is still an issue for me in 2.9.0 using `react-navigation` v4. I'm using `tabBarVisible` because v4 can't do https://reactnavigation.org/docs/hiding-tabbar-in-screens/

**Comment by WoLewicki** [comment] 2020-07-30 08:31
What do you mean by v4 can't do something?

**Comment by watadarkstar** [comment] 2020-07-30 14:11
@WoLewicki v4 has this bug as this page does not exist in the documentation: https://reactnavigation.org/docs/4.x/hiding-tabbar-in-screens/

You can't hide the tab bar without this bug if you are on v4 of React Navigation. At least based on my research you need to be on v5 to be able to do this: https://reactnavigation.org/docs/hiding-tabbar-in-screens/ which doesn't exist in v4.

i.e. this page does not exist https://reactnavigation.org/docs/4.x/hiding-tabbar-in-screens/

> But if we want to show the tab bar only on the Home, Feed and Notifications screens, but not on the Profile and Settings screens, we'll need to change the navigation structure. The easiest way to achieve this is to nest the tab navigator inside the first screen of the stack instead of nesting stack inside tab navigator:

**Comment by satya164** [comment] 2020-07-31 12:50
The page doesn't exist doesn't mean that you can't do it. I'm pretty sure you can nest a tab navigator inside the first screen of the stack in v4.

**Comment by watadarkstar** [comment] 2020-07-31 14:56
@satya164 Haha yeah I realized that after I posted this comment. Long day!

**Comment by VanDu97** [comment] 2020-10-22 10:16
"react-native-screens": "^2.11.0"
 "@react-navigation/native": "^5.7.6"
Same still issues
