### ISSUE TITLE
[native-stack] does not show header with transparentModal

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-screens#365] opened 2020-02-22 18:23 UTC
_Moved from [react-navigation/react-navigation#6768](https://github.com/react-navigation/react-navigation/issues/6768). Originally opened by @Aryk_
___

I was using createNativeStackNavigator to create a new stack. For one of the screens when setting presentation to "transparentModal" or "modal" in my iOS simulator, the overlay comes up but the header is completely gone. Removing {presentation: "transparentModal"} defaults to the push method and it shows the header like its supposed to.

However, with"transparentModal" or "modal" if the screen is another stack, it will show the header in that stack correctly. Is this normal functionality for modals?

**Comment by WoLewicki** [comment] 2020-03-31 08:45
Follow #260 to see any changes in the topic.

**Comment by WoLewicki** [comment] 2020-04-01 14:23
I am closing this issue. Feel free to comment if it is not the duplicate of #260.

**Closed by WoLewicki** 2020-04-01 14:23 UTC
Labels: native-stack
